### ISSUE TITLE
Unable to compile Tensorrt_llm image,error msg is : error adding symbols: file in wrong format

### ISSUE THREAD

**Issue by WangxuP** [NVIDIA/TensorRT-LLM#100]
```
1473.4 /usr/bin/ld: /src/tensorrt_llm/cpp/tensorrt_llm/batch_manager/x86_64-linux-gnu/libtensorrt_llm_batch_manager_static.a(kvCacheManager.cpp.o): Relocations in generic ELF (EM: 183)
1473.4 /usr/bin/ld: /src/tensorrt_llm/cpp/tensorrt_llm/batch_manager/x86_64-linux-gnu/libtensorrt_llm_batch_manager_static.a: error adding symbols: file in wrong format
1473.4 collect2: error: ld returned 1 exit status
1473.4 gmake[3]: *** [tensorrt_llm/CMakeFiles/tensorrt_llm.dir/build.make:714: tensorrt_llm/libtensorrt_llm.so] Error 1
1473.4 gmake[2]: *** [CMakeFiles/Makefile2:677: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/all] Error 2
1473.4 gmake[1]: *** [CMakeFiles/Makefile2:684: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/rule] Error 2
1473.4 gmake: *** [Makefile:179: tensorrt_llm] Error 2
1473.4 Traceback (most recent call last):
1473.4   File "/src/tensorrt_llm/scripts/build_wheel.py", line 248, in <module>
1473.4     main(**vars(args))
1473.4   File "/src/tensorrt_llm/scripts/build_wheel.py", line 152, in main
1473.4     build_run(
1473.4   File "/usr/lib/python3.10/subprocess.py", line 526, in run
1473.4     raise CalledProcessError(retcode, process.args,
1473.4 subprocess.CalledProcessError: Command 'cmake --build . --config Release --parallel 112 --target tensorrt_llm tensorrt_llm_static nvinfer_plugin_tensorrt_llm th_common ' returned non-zero exit status 2.
------
Dockerfile.multi:49
--------------------
  47 |
  48 |     ARG BUILD_WHEEL_ARGS="--clean --trt_root /usr/local/tensorrt"
  49 | >>> RUN python3 scripts/build_wheel.py ${BUILD_WHEEL_ARGS}
  50 |
  51 |     FROM devel as release
--------------------
ERROR: failed to solve: process "/bin/bash -c python3 scripts/build_wheel.py ${BUILD_WHEEL_ARGS}" did not complete successfully: exit code: 1
make: *** [release_build] Error 1

```

**Comment by forrestjgq** [comment]
make sure you've got valid git-lfs and filters configuration in gitconfig and executed `git lfs install` & `git lfs pull`
