### ISSUE TITLE
Benchmarking errors out for GPTJ_6B model on single L4 GPU due to CUDA ERROR: 2

### ISSUE THREAD

**Issue by RajeshThallam** [NVIDIA/TensorRT-LLM#101]
I am running [benchmarking script](https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/benchmarks/python) for GPTJ-6B model on a single NVIDIA L4 GPU and it errors out.

### Error
```
[10/24/2023-13:31:01] [TRT] [I] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 0 MiB, GPU 16385 MiB
[10/24/2023-13:31:01] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in building engine: CPU +0, GPU +11542, now: CPU 0, GPU 11542 (MiB)
[10/24/2023-13:31:01] [TRT] [V] Adding 1 engine(s) to plan file.
[10/24/2023-13:31:10] [TRT] [I] [MemUsageStats] Peak memory usage during Engine building and serialization: CPU: 25877 MiB
[10/24/2023-13:31:10] [TRT-LLM] [I] Total time of building gptj_6b_float16_tp1_rank0.engine: 00:00:45
[10/24/2023-13:31:10] [TRT] [I] Loaded engine size: 11543 MiB
[10/24/2023-13:31:12] [TRT] [V] Local registry did not find Lookup creator. Will try parent registry if enabled.
[10/24/2023-13:31:12] [TRT] [V] Global registry found Lookup creator.
...
...
[10/24/2023-13:31:12] [TRT] [V] Loaded shared library libcublas.so.12
[10/24/2023-13:31:12] [TRT] [V] Using cublas as plugin tactic source
[10/24/2023-13:31:12] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 25256, GPU 12890 (MiB)
[10/24/2023-13:31:12] [TRT] [V] Trying to load shared library libcudnn.so.8
[10/24/2023-13:31:12] [TRT] [V] Loaded shared library libcudnn.so.8
[10/24/2023-13:31:12] [TRT] [V] Using cuDNN as plugin tactic source
[10/24/2023-13:31:12] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 25256, GPU 12898 (MiB)
[10/24/2023-13:31:12] [TRT] [V] Deserialization required 2677906 microseconds.
[10/24/2023-13:31:12] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +11541, now: CPU 0, GPU 11541 (MiB)
Traceback (most recent call last):
  File "/code/tensorrt_llm/benchmarks/python/benchmark.py", line 322, in <module>
    main(args)
  File "/code/tensorrt_llm/benchmarks/python/benchmark.py", line 219, in main
    benchmarker = GPTBenchmark(
  File "/code/tensorrt_llm/benchmarks/python/gpt_benchmark.py", line 173, in __init__
    self.decoder = tensorrt_llm.runtime.GenerationSession(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 306, in __init__
    self.runtime = _Runtime(engine_buffer, mapping)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 143, in __init__
    self.__prepare(mapping, engine_buffer)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 163, in __prepare
    address = CUASSERT(cudart.cudaMalloc(self.engine.device_memory_size))[0]
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 92, in CUASSERT
    raise RuntimeError(
RuntimeError: CUDA ERROR: 2, error code reference: https://nvidia.github.io/cuda-python/module/cudart.html#cuda.cudart.cudaError_t
Exception ignored in: <function _Runtime.__del__ at 0x7fd52269e830>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 232, in __del__
    cudart.cudaFree(self.address)
AttributeError: '_Runtime' object has no attribute 'address'
```

### Command used
```
python benchmark.py \
    -m gptj_6b \
    --mode plugin \
    --batch_size 1 \
    --dtype float16 \
    --input_output_len "128,20" \
    --log_level verbose
```

### Output from nvidia-smi
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA L4           Off  | 00000000:00:03.0 Off |                    0 |
| N/A   68C    P0    34W /  72W |      0MiB / 23034MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by byshiue** [comment]
Same issue as https://github.com/NVIDIA/TensorRT-LLM/issues/85.

**Comment by jdemouth-nvidia** [comment]
Closing as duplicate
