### ISSUE TITLE
RuntimeError: Unsupported model architecture: LlamaForCausalLM

### ISSUE THREAD

**Issue by HoHuiHsieh** [NVIDIA/TensorRT-LLM#1026]
### System Info

- CPU architecture: x86_64
- Host memory size: 64GB
- GPU name: NVIDIA TITAN RTX 24GB
- TensorRT-LLM version: 0.8.0.dev2024012302
- Nvida driver version: 545.23.08
- OS: Ubuntu 22.04.3 LTS

### Who can help?

@Tracin

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Installation
- Here is how dockerfile looklike:
```dockerfile
FROM nvcr.io/nvidia/cuda:12.1.0-devel-ubuntu22.04 AS base-container

# Install dependencies, TensorRT-LLM requires Python 3.10
RUN apt-get update \
    && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev git \
    && apt-get clean

# Install the latest preview version (corresponding to the main branch) of TensorRT-LLM.
RUN pip3 install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com

# Install python dependencies for LLaMA example
WORKDIR /workspace/examples/llama
ADD examples/llama/requirements.txt .
RUN pip3 install -r requirements.txt

ENTRYPOINT ['/bin/bash']
```
- Here is how I start my container:
```bash
#!/bin/bash
VERSION=latest
docker build --target base-container --no-cache \
    -t tensorrt_llm:$VERSION  \
    -f docker/Dockerfile.$VERSION   \
    . \
&& \
docker run -itd --rm --gpus all \
    --shm-size=1g \
    --ulimit memlock=-1 \
    --name tensorrt_llm \
    -v $PWD:/workspace \
    -w /workspace \
    tensorrt_llm:$VERSION

```

2. Build [CodeLlama-7b-Instruct-hf](https://huggingface.co/codellama/CodeLlama-7b-Instruct-hf) model.
```bash
#!/bin/bash
NUM_GPU=1
PRECISION=float16
MODEL_PATH=/workspace/models
MODEL_NAME=CodeLlama-7b-Instruct-hf
python3 convert_checkpoint.py --model_dir $MODEL_PATH/$MODEL_NAME \
                              --output_dir $MODEL_PATH/tllm_checkpoint/$MODEL_NAME/$PRECISION/$NUM_GPU-gpu \
                              --dtype $PRECISION \
                              --rotary_base 1000000 \
                              --vocab_size 32016 \
&& \
trtllm-build --checkpoint_dir $MODEL_PATH/tllm_checkpoint/$MODEL_NAME/$PRECISION/$NUM_GPU-gpu \
             --output_dir $MODEL_PATH/tllm_engines/$MODEL_NAME/$PRECISION/$NUM_GPU-gpu \
             --use_gpt_attention_plugin $PRECISION \
             --use_gemm_plugin $PRECISION
```

### Expected behavior

Build successfully with new files in my `tllm_engines` folder.

### actual behavior

- Here is what I got:
```
[TensorRT-LLM] TensorRT-LLM version: 0.8.0.dev20240123020.8.0.dev2024012302
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████| 2/2 [00:04<00:00,  2.18s/it]
Weights loaded. Total time: 00:00:00
Total time of converting checkpoints: 00:00:45
[TensorRT-LLM] TensorRT-LLM version: 0.8.0.dev2024012302Traceback (most recent call last):
  File "/usr/local/bin/trtllm-build", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 369, in main
    parallel_build(source, build_config, args.output_dir, workers,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 293, in parallel_build
    build_and_save(rank, rank % workers, ckpt_dir, build_config,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 267, in build_and_save
    engine = build(build_config,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 244, in build
    raise RuntimeError(
RuntimeError: Unsupported model architecture: LlamaForCausalLM
```

### additional notes

Got another error in `TensorRT-LLM/examples/llama/convert_checkpoint.py`:
```
[TensorRT-LLM] TensorRT-LLM version: 0.8.0.dev2024012302Traceback (most recent call last):
  File "/workspace/src/convert_checkpoint.py", line 31, in <module>
    from tensorrt_llm.models.llama.weight import (load_from_awq_llama,
ImportError: cannot import name 'load_from_fp8_llama' from 'tensorrt_llm.models.llama.weight' (/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/weight.py)
```
To ignore the error, line 31 was modified in my tests.
```python
...
from tensorrt_llm.models.llama.weight import (load_from_awq_llama,
                                            #   load_from_fp8_llama,
                                              load_from_meta_llama)
...
```

**Comment by QiJune** [comment]
https://github.com/NVIDIA/TensorRT-LLM/blob/3d56a445e8ebf888e78be638faf6beec0a78f3c2/tensorrt_llm/commands/build.py#L232-L236

In the latest main branch, the RuntimeError is in line 234.

@HoHuiHsieh  It seems that trtllm-build you are using is not the latest one, could you please update to the main branch?

**Comment by HoHuiHsieh** [comment]
Thank you for responding. I redid my installation with the following command:
```bash
# Install the latest preview version (corresponding to the main branch) of TensorRT-LLM.
pip3 install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com
```
However, the package version on PyPI has not yet been updated.
```
[TensorRT-LLM] TensorRT-LLM version: 0.8.0.dev2024012302
...
```
Maybe I'll try to build from source.
