### ISSUE TITLE
[Bug] Cannot convert whisper with pip package

### ISSUE THREAD

**Issue by makaveli10** [NVIDIA/TensorRT-LLM#1029]
### System Info

- Architecture: x86_64
- CPU: AMD Ryzen Threadripper 1920X 12-Core Processor
- NVIDIA RTX 3090
- Driver Version: 545.29.06
- Container Tag: cuda12.1-devel-ubuntu22.04

### Who can help?

@byshiue 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Hello, I tried building whisper after installing pip package in the `cuda-12.1-devel-ubuntu22.04` container:
```
docker run --entrypoint /bin/bash -it nvidia/cuda:12.1.0-devel-ubuntu22.04

# Install dependencies, TensorRT-LLM requires Python 3.10
apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev

# Install the latest preview version (corresponding to the main branch) of TensorRT-LLM.
# If you want to install the stable version (corresponding to the release branch), please
# remove the `--pre` option.
pip3 install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com

# Check installation
python3 -c "import tensorrt_llm"
```

All of this works as expected. As soon as I run:
```
python3 build.py --output_dir whisper_large_v3 --use_gpt_attention_plugin --use_gemm_plugin --use_bert_attention_plugin
```

### Expected behavior

To convert whisper to TensorRT Engine

### actual behavior

It fails:
```
[02/01/2024-10:55:05] [TRT-LLM] [I] plugin_arg is None, setting it as float16 automatically.
[02/01/2024-10:55:05] [TRT-LLM] [I] plugin_arg is None, setting it as float16 automatically.
[02/01/2024-10:55:05] [TRT-LLM] [I] plugin_arg is None, setting it as float16 automatically.
[02/01/2024-10:55:07] [TRT] [I] [MemUsageChange] Init CUDA: CPU +13, GPU +0, now: CPU 3065, GPU 11135 (MiB)
[02/01/2024-10:55:11] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1799, GPU +312, now: CPU 5000, GPU 11447 (MiB)
[02/01/2024-10:55:11] [TRT-LLM] [W] Parameter dtype is None, using default dtype: DataType.FLOAT, it is recommended to always specify dtype explicitly
[02/01/2024-10:55:11] [TRT-LLM] [W] Parameter dtype is None, using default dtype: DataType.FLOAT, it is recommended to always specify dtype explicitly
[02/01/2024-10:55:11] [TRT-LLM] [W] Parameter dtype is None, using default dtype: DataType.FLOAT, it is recommended to always specify dtype explicitly
[02/01/2024-10:55:11] [TRT-LLM] [W] Parameter dtype is None, using default dtype: DataType.FLOAT, it is recommended to always specify dtype explicitly
[02/01/2024-10:55:11] [TRT-LLM] [W] Parameter dtype is None, using default dtype: DataType.FLOAT, it is recommended to always specify dtype explicitly
[02/01/2024-10:55:11] [TRT-LLM] [W] Parameter dtype is None, using default dtype: DataType.FLOAT, it is recommended to always specify dtype explicitly
[02/01/2024-10:55:11] [TRT-LLM] [I] Loading encoder weights from PT...
[02/01/2024-10:55:11] [TRT-LLM] [W] Parameter was initialized as DataType.HALF but set to DataType.FLOAT
[02/01/2024-10:55:11] [TRT-LLM] [W] Parameter was initialized as DataType.FLOAT but set to DataType.HALF
[02/01/2024-10:55:11] [TRT-LLM] [W] Parameter was initialized as DataType.FLOAT but set to DataType.HALF
[02/01/2024-10:55:11] [TRT-LLM] [W] Parameter was initialized as DataType.FLOAT but set to DataType.HALF
[02/01/2024-10:55:11] [TRT-LLM] [W] Parameter was initialized as DataType.FLOAT but set to DataType.HALF
[02/01/2024-10:55:15] [TRT-LLM] [W] Parameter was initialized as DataType.FLOAT but set to DataType.HALF
[02/01/2024-10:55:15] [TRT-LLM] [W] Parameter was initialized as DataType.FLOAT but set to DataType.HALF
[TensorRT-LLM] TensorRT-LLM version: 0.8.0.dev2024012302Traceback (most recent call last):
  File "/TensorRT-LLM/examples/whisper/build.py", line 365, in <module>
    run_build(args)
  File "/TensorRT-LLM/examples/whisper/build.py", line 359, in run_build
    build_encoder(model, args)
  File "/TensorRT-LLM/examples/whisper/build.py", line 210, in build_encoder
    network.plugin_config.to_legacy_setting()
AttributeError: 'PluginConfig' object has no attribute 'to_legacy_setting'
```
TensorRT-LLM downloaded from pip has a version tag: `TensorRT-LLM version: 0.8.0.dev2024012302`

### additional notes

NA

**Comment by Shixiaowei02** [comment]
We have fixed this issue, please retry it. Thanks!
