### ISSUE TITLE
AWQ (W4A8 mode) failed for llama-7b model

### ISSUE THREAD

**Issue by littletomatodonkey** [NVIDIA/TensorRT-LLM#1104]
Env:
* trt-llm : 0.9.0.dev2024020600
* nvidia-ammo: 0.7.2
* cuda: 12.2
* device: A100
* TensorRT-llm code: latest main branch.

Hi, i tried to convert llama model using AWQ + W4A8, Errors occured as follows.

```
File "/usr/local/lib/python3.10/site-packages/tensorrt_llm/commands/build.py", line 489, in main
    parallel_build(source, build_config, args.output_dir, workers,
  File "/usr/local/lib/python3.10/site-packages/tensorrt_llm/commands/build.py", line 413, in parallel_build
    passed = build_and_save(rank, rank % workers, ckpt_dir,
  File "/usr/local/lib/python3.10/site-packages/tensorrt_llm/commands/build.py", line 385, in build_and_save
    engine = build(build_config,
  File "/usr/local/lib/python3.10/site-packages/tensorrt_llm/commands/build.py", line 266, in build
    model.load(weights)
  File "/usr/local/lib/python3.10/site-packages/tensorrt_llm/models/modeling_utils.py", line 338, in load
    raise RuntimeError(err_msg)
RuntimeError: Provided tensor names are different from those expected by the engine.
Provided but not expected tensors: {'transformer.layers.15.mlp.proj.activation_scaling_factor', 'transformer.layers.28.mlp.proj.weights_scaling_factor_2', ......
```

Could you please help to have a look? Thanks!

The command is.

```bash
hf_model_dir="/mnt/bn/multimodel/models/llama/llama-7b-hf/"
awq_model_dir="./ouput/w4a8_awq/"
trt_model_dir="./ouput/trt_w4a8_awq/"

# this command is normal
python3 ../quantization/quantize.py \
--model_dir ${hf_model_dir} \
--output_dir ${awq_model_dir} \
--dtype float16 \
--qformat w4a8_awq

# errors occured for trtllm-build
trtllm-build --checkpoint_dir "${awq_model_dir}" \
            --output_dir "${trt_model_dir}" \
            --strongly_typed \
            --gemm_plugin float16
```

**Comment by Tracin** [comment]
@Barry-Delaney Barry could you please help with this?

**Comment by Barry-Delaney** [comment]
@littletomatodonkey The error messages you are encountered with is about checkpoint key names' mismatch, and the related code will be available at next main branch update.
What's more, W4A8-AWQ is aimed at accelerating with FP8 Tensor Cores, hence it is unavailable on pre-Hopper architectures.

**Comment by activezhao** [comment]
Hi @Barry-Delaney , I use `META-CodeLlama-7b-hf ` in A10 for int4_awq, but the human eval test is not good, could u please give me some suggestions about the parameters?

And is the a best practice？

Thanks.

```
python /data/tensorrt_llm/examples/quantization/quantize.py --model_dir /data/META-CodeLlama-7b-hf/ \
                --dtype float16 \
                --qformat int4_awq \
                --batch_size 8 \
                --tp_size 2 \
                --awq_block_size 128 \
                --output_dir /data/trt_llama_7b_quantized_int4-awq-tp2 \
                --calib_size 32

trtllm-build --checkpoint_dir /data/trt_llama_7b_quantized_int4-awq-tp2 \
             --output_dir /data/llama_7B_trt_engines_int4_AWQ/2-gpu/ \
             --workers 2 \
             --max_batch_size 64  \
             --gemm_plugin float16
```

part of the human eval results:
```
{"task_id": "HumanEval/94", "completion": "    # Write your code here\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n", "language": "python"}
{"task_id": "HumanEval/95", "completion": "    if not dict:\n        return False\n\n    if not isinstance(dict, dict)):\n        return False\n\n    if not dict:\n        return False\n\n    if not isinstance(dict, dict)):\n        return False\n\n    if not dict:\n        return False\n\n    if not isinstance(dict, dict)):\n        return False\n\n    if not dict:\n        return False\n\n    if not isinstance(dict, dict)):\n        return False\n\n    if not dict:\n        return False\n\n    if not isinstance(dict, dict)):\n        return False\n\n    if not dict:\n        return False\n\n    if not isinstance(dict, dict)):\n        return False\n\n    if not dict:\n        return False\n\n    if not isinstance(dict, dict)):\n        return False\n\n    if not dict:\n        return False\n\n    if not isinstance(dict, dict)):\n        return False\n\n    if not dict:\n        return False\n\n    if not isinstance(dict, dict)):\n        return False\n\n    if not dict:\n        return False\n\n    if", "language": "python"}
{"task_id": "HumanEval/96", "completion": "    # Your code here\n    # return the array\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n", "language": "python"}
{"task_id": "HumanEval/97", "completion": "    # Your code here\n    return 0\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n", "language": "python"}
{"task_id": "HumanEval/98", "completion": "    # TODO: Implement!\n    return 0\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n", "language": "python"}
{"task_id": "HumanEval/99", "completion": "    return int(round(float(value))))\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n", "language": "python"}

```

**Comment by michaelmandich** [comment]
having similar issue on a 4070ti , i built from llama 7b chat using 

python3.10 convert_checkpoint.py --model_dir ./llmcheckpoints --output_dir ./llm2 --dtype int8 --weight_only_precision int4 --load_by_shard --load-model-on-cpu --convert-model-on-cpu 


trtllm-build --checkpoint_dir ./llm2  --gemm_plugin float16  --output_dir ./llama7b


[02/26/2024-14:46:26] [TRT-LLM] [E] Engine building failed, please check the error log.
[02/26/2024-14:46:26] [TRT-LLM] [I] Serializing engine to ./llama7b/rank0.engine...
Traceback (most recent call last):
  File "/home/mike/.local/bin/trtllm-build", line 8, in <module>
    sys.exit(main())
  File "/home/mike/.local/lib/python3.10/site-packages/tensorrt_llm/commands/build.py", line 514, in main
    parallel_build(source, build_config, args.output_dir, workers,
  File "/home/mike/.local/lib/python3.10/site-packages/tensorrt_llm/commands/build.py", line 436, in parallel_build
    passed = build_and_save(rank, rank % workers, ckpt_dir,
  File "/home/mike/.local/lib/python3.10/site-packages/tensorrt_llm/commands/build.py", line 415, in build_and_save
    engine.save(output_dir)
  File "/home/mike/.local/lib/python3.10/site-packages/tensorrt_llm/runtime/engine.py", line 60, in save
    serialize_engine(
  File "/home/mike/.local/lib/python3.10/site-packages/tensorrt_llm/runtime/engine.py", line 18, in serialize_engine
    f.write(engine)
TypeError: a bytes-like object is required, not 'NoneType'

**Comment by Barry-Delaney** [comment]
@activezhao the usage of `quantize.py` looks good to me, and one possible reason of the degradation is the missing of `rotary_base` in the AMMO exported checkpoint. You can have a manual fix on `config.json` inside the exported checkpoint as a temporary workaround. This is a known issue and is fixed it internally, will get updated later.

**Comment by activezhao** [comment]
> @activezhao the usage of `quantize.py` looks good to me, and one possible reason of the degradation is the missing of `rotary_base` in the AMMO exported checkpoint. You can have a manual fix on `config.json` inside the exported checkpoint as a temporary workaround. This is a known issue and is fixed it internally, will get updated later.

@Barry-Delaney   Thanks for your reply.

These are the files after the usage of `quantize.py`.
```
root@bb4d01d6b166:/data/trt_llama_7b_quantized_int4-awq-tp2# ls
config.json  rank0.safetensors  rank1.safetensors
```

This is the `config.json`, How to change the config? 

Thanks.
```
root@bb4d01d6b166:/data/trt_llama_7b_quantized_int4-awq-tp2# cat config.json 
{
    "producer": {
        "name": "ammo",
        "version": "0.7.3"
    },
    "architecture": "LlamaForCausalLM",
    "dtype": "float16",
    "num_hidden_layers": 32,
    "num_attention_heads": 32,
    "num_key_value_heads": 32,
    "hidden_size": 4096,
    "norm_epsilon": 1e-05,
    "vocab_size": 32064,
    "max_position_embeddings": 16384,
    "hidden_act": "silu",
    "use_parallel_embedding": true,
    "embedding_sharding_dim": 0,
    "quantization": {
        "quant_algo": "W4A16_AWQ",
        "kv_cache_quant_algo": null,
        "group_size": 128,
        "has_zero_point": false,
        "pre_quant_scale": true,
        "exclude_modules": [
            "lm_head"
        ]
    },
    "mapping": {
        "world_size": 2,
        "tp_size": 2,
        "pp_size": 1
    },
    "head_size": 128,
    "intermediate_size": 11008,
    "position_embedding_type": "rope_gpt_neox"
```

**Comment by Barry-Delaney** [comment]
@activezhao you can add a parameter `"rotary_base": 10000.0` (according to your actual `rotary_base` value.

**Comment by Barry-Delaney** [comment]
@michaelmandich It seems like the issue you are running into is not related to W4A8-AWQ. Could you please open another issue on this and provide more detailed error log for help? Thanks!

**Comment by activezhao** [comment]
> @activezhao you can add a parameter `"rotary_base": 10000.0` (according to your actual `rotary_base` value.

@Barry-Delaney Thanks, Barry, it works.

**Comment by yunyaoXYY** [comment]
> @littletomatodonkey The error messages you are encountered with is about checkpoint key names' mismatch, and the related code will be available at next main branch update. What's more, W4A8-AWQ is aimed at accelerating with FP8 Tensor Cores, hence it is unavailable on pre-Hopper architectures.

Hi, do you have fixed this problem in latest 'main' branch ? Thx. :D

**Comment by Barry-Delaney** [comment]
@yunyaoXYY It is fixed.
