### ISSUE TITLE
In  int8_wo and kvcache fp8 mode, assert failed on tensorrt_llm/quantization/quantize.py:301

### ISSUE THREAD

**Issue by Time-Limit** [NVIDIA/TensorRT-LLM#1113]
**The command I execued as follow**
 /app/tensorrt_llm/examples/quantization/quantize.py \
        --model_dir ${model_dir} \
        --dtype float16 \
        --qformat int8_wo \
        --kv_cache_dtype fp8 \
        --output_dir ${quant_dir} \
        --calib_size 512 \
        --batch_size 1 \
        --tp_size 8  \

trtllm-build --checkpoint_dir ${quant_dir} \
        --output_dir ${built_dir} \
        --gpt_attention_plugin float16  \
        --remove_input_padding enable \
        --paged_kv_cache enable \
        --use_custom_all_reduce disable \
        --max_input_len 7168 \
        --max_output_len 1024 \
        --max_batch_size 8 \
        --gemm_plugin float16

**when I run trtllm-build, I got error**

Traceback (most recent call last):
  File "/usr/local/bin/trtllm-build", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 448, in main
    parallel_build(source, build_config, args.output_dir, workers,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 381, in parallel_build
    build_and_save(rank, rank % workers, ckpt_dir, build_config,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 355, in build_and_save
    engine = build(build_config,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 241, in build
    model = model_cls.from_config(rank_config)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/modeling_utils.py", line 298, in from_config
    return cls(config)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/modeling_utils.py", line 278, in __call__
    obj.__post_init__()
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/modeling_utils.py", line 289, in __post_init__
    quantize(self, self.config.quant_mode, **self.config.quant_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/quantization/quantize.py", line 341, in quantize
    default_fp8_quantize(model, quant_mode)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/quantization/quantize.py", line 301, in default_fp8_quantize
    assert use_fp8_qdq

**Some system info**
TensorRT-LLM version: 0.8.0.dev2024013000
GPU: 4090

**Comment by byshiue** [comment]
You cannot combine the int8 weight only and fp8 kv cache. You can try int8-wo + int8-kv-cache or fp8 + fp8-kv-cache.
