### ISSUE TITLE
Dependency Conflict with Latest tensorRT-LLM in Docker Build

### ISSUE THREAD

**Issue by YoctoHan** [NVIDIA/TensorRT-LLM#1130]
I am encountering a dependency conflict when trying to build a Docker container using the provided docker/Dockerfile.multi for tensorRT-LLM. No modifications were made to the Dockerfile's core logic.

Docker version:Docker version 24.0.7, build afdd53b
Host OS: [e.g., Ubuntu 20.04]
TensorRT version: latest

Steps to Reproduce：
Clone the repository: git clone git@github.com:NVIDIA/TensorRT-LLM.git
Move into the repository directory: cd TensorRT-LLM
Build the Docker container: make -C docker release_build CUDA_ARCHS="80-real"

Expected Behavior
The Docker container should build without any dependency conflicts.

Actual Behavior
The build process fails due to a dependency conflict between dask-cuda and pynvml, as well as torch-tensorrt and tensorrt.

Error Messages / Logs

**172.4 ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
172.4 dask-cuda 23.10.0 requires pynvml<11.5,>=11.0.0, but you have pynvml 11.5.0 which is incompatible.
172.4 torch-tensorrt 2.2.0a0 requires tensorrt<8.7,>=8.6, but you have tensorrt 9.2.0.post12.dev5 which is incompatible.**
172.4 Successfully installed accelerate-0.25.0 bandit-1.7.7 build-1.0.3 cfgv-3.4.0 colored-2.2.4 coloredlogs-15.0.1 coverage-7.4.2 datasets-2.17.1 diffusers-0.15.0 dill-0.3.8 distlib-0.3.8 evaluate-0.4.1 flatbuffers-23.5.26 fsspec-2023.10.0 graphviz-0.20.1 huggingface-hub-0.20.3 humanfriendly-10.0 identify-2.5.35 janus-1.0.0 lark-1.1.9 multiprocess-0.70.16 mypy-1.8.0 mypy-extensions-1.0.0 nltk-3.8.1 nodeenv-1.8.0 nvidia-ammo-0.7.3 onnx-graphsurgeon-0.3.27 onnxruntime-1.16.3 optimum-1.17.1 parameterized-0.9.0 pbr-6.0.0 pre-commit-3.6.2 py-1.11.0 pybind11-stubgen-2.4.2 pynvml-11.5.0 pyproject_hooks-1.0.0 pytest-cov-4.1.0 pytest-forked-1.6.0 responses-0.18.0 rouge_score-0.1.2 safetensors-0.4.2 sentencepiece-0.2.0 stevedore-5.1.0 tokenizers-0.15.2 torchprofile-0.0.4 transformers-4.36.1 virtualenv-20.25.1 xxhash-3.4.1
172.4 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
172.4 |DNS-request| pypi.org
172.5 |S-chain|-<>-12.2.20.28:8388-<><>-4.2.2.2:53-<><>-OK
172.7 |DNS-response| pypi.org is 151.101.64.223
172.7 |S-chain|-<>-12.2.20.28:8388-<><>-151.101.64.223:443-<><>-OK
173.3 |DNS-request| pypi.ngc.nvidia.com
173.4 |S-chain|-<>-12.2.20.28:8388-<><>-4.2.2.2:53-<><>-OK
173.6 |DNS-response| pypi.ngc.nvidia.com is 108.157.254.114
173.6 |S-chain|-<>-12.2.20.28:8388-<><>-108.157.254.114:443-<><>-OK
174.0 |DNS-request| developer.download.nvidia.com
174.0 |S-chain|-<>-12.2.20.28:8388-<><>-4.2.2.2:53-<><>-OK
174.3 |DNS-response| developer.download.nvidia.com is 152.199.39.144
174.3 |S-chain|-<>-12.2.20.28:8388-<><>-152.199.39.144:443-<><>-OK
175.5
175.5 [notice] A new release of pip is available: 23.3.1 -> 24.0
175.5 [notice] To update, run: python3 -m pip install --upgrade pip
177.0 -- The CXX compiler identification is GNU 11.4.0
177.1 -- Detecting CXX compiler ABI info
177.4 -- Detecting CXX compiler ABI info - done
177.4 -- Check for working CXX compiler: /usr/bin/c++ - skipped
177.4 -- Detecting CXX compile features
177.4 -- Detecting CXX compile features - done
177.4 -- NVTX is disabled
177.4 -- Importing batch manager
177.4 -- Importing executor
177.4 -- Building PyTorch
177.4 -- Building Google tests
177.4 -- Building benchmarks
177.4 -- Looking for a CUDA compiler
181.7 -- Looking for a CUDA compiler - /usr/local/cuda/bin/nvcc
181.7 -- CUDA compiler: /usr/local/cuda/bin/nvcc
181.8 -- GPU architectures: 80-real
182.0 -- The C compiler identification is GNU 11.4.0
184.0 -- The CUDA compiler identification is NVIDIA 12.3.107
184.1 -- Detecting C compiler ABI info
184.4 -- Detecting C compiler ABI info - done
184.4 -- Check for working C compiler: /usr/bin/cc - skipped
184.4 -- Detecting C compile features
184.4 -- Detecting C compile features - done
184.4 -- Detecting CUDA compiler ABI info
186.2 -- Detecting CUDA compiler ABI info - done
186.4 -- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
186.4 -- Detecting CUDA compile features
186.4 -- Detecting CUDA compile features - done
186.4 -- Found CUDAToolkit: /usr/local/cuda/include (found version "12.3.107")
186.4 -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
186.7 -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
186.7 -- Found Threads: TRUE
186.8 -- CUDA library status:
186.8 --     version: 12.3.107
186.8 --     libraries: /usr/local/cuda/lib64
186.8 --     include path: /usr/local/cuda/targets/x86_64-linux/include
186.8 -- ========================= Importing and creating target nvinfer ==========================
186.8 -- Looking for library nvinfer
186.8 -- Library that was found /usr/local/tensorrt/targets/x86_64-linux-gnu/lib/libnvinfer.so
186.8 -- ==========================================================================================
186.8 -- CUDAToolkit_VERSION 12.3 is greater or equal than 11.0, enable -DENABLE_BF16 flag
186.8 -- CUDAToolkit_VERSION 12.3 is greater or equal than 11.8, enable -DENABLE_FP8 flag
187.2 -- Found MPI_C: /opt/hpcx/ompi/lib/libmpi.so (found version "3.1")
188.1 -- Found MPI_CXX: /opt/hpcx/ompi/lib/libmpi.so (found version "3.1")
188.1 -- Found MPI: TRUE (found version "3.1")
188.1 -- COMMON_HEADER_DIRS: /src/tensorrt_llm/cpp;/usr/local/cuda/include
188.5 -- Found Python3: /usr/bin/python3.10 (found version "3.10.12") found components: Interpreter Development Development.Module Development.Embed
190.2 -- USE_CXX11_ABI is set by python Torch to 1
190.2 -- TORCH_CUDA_ARCH_LIST: 8.0
190.2 CMake Warning at CMakeLists.txt:313 (message):
190.2   Ignoring environment variable TORCH_CUDA_ARCH_LIST=5.2 6.0 6.1 7.0 7.2 7.5
190.2   8.0 8.6 8.7 9.0+PTX
190.2
190.2
190.2 -- Found Python executable at /usr/bin/python3.10
190.2 -- Found Python libraries at /usr/lib/x86_64-linux-gnu
191.8 CMake Error at CMakeLists.txt:333 (message):
191.8   PyTorch >= 1.5.0 is needed for TorchScript mode.
191.8
191.8
191.8 -- Configuring incomplete, errors occurred!
191.9 Traceback (most recent call last):
191.9   File "/src/tensorrt_llm/scripts/build_wheel.py", line 332, in <module>
191.9     main(**vars(args))
191.9   File "/src/tensorrt_llm/scripts/build_wheel.py", line 162, in main
191.9     build_run(
191.9   File "/usr/lib/python3.10/subprocess.py", line 526, in run
191.9     raise CalledProcessError(retcode, process.args,
191.9 subprocess.CalledProcessError: Command 'cmake -DCMAKE_BUILD_TYPE="Release" -DBUILD_PYT="ON" -DBUILD_PYBIND="ON" -DNVTX_DISABLE="ON" "-DCMAKE_CUDA_ARCHITECTURES=80-real" -DTRT_LIB_DIR=/usr/local/tensorrt/targets/x86_64-linux-gnu/lib -DTRT_INCLUDE_DIR=/usr/local/tensorrt/include  -S "/src/tensorrt_llm/cpp"' returned non-zero exit status 1.

**Comment by YoctoHan** [comment]
Fixed, the latest version builds docker normally.
