### ISSUE TITLE
LLaMA + SmoothQuant checkpoint creation does not work in bfloat16

### ISSUE THREAD

**Issue by vnkc1** [NVIDIA/TensorRT-LLM#1153]
### System Info

GPU : NVIDIA A100 80GB

package version
tensorrt 9.2.0.post12.dev5-cp310-none-linux_x86_64
tensorrt-llm 0.9.0.dev2024022000
nvidia-ammo 0.7.3

### Who can help?

@Tracin @byshiue

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Install first with pip install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com
2. git clone https://github.com/NVIDIA/TensorRT-LLM.git
3. python -m pip install ~/TensorRT-LLM/examples/llama/requirements.txt
4. python ~/TensorRT-LLM/examples/llama/convert_checkpoint.py --model_dir ~/Llama-2-13b-chat-hf --output_dir ~/output_dir --dtype bfloat16 --smoothquant 0.5

### Expected behavior

Expect trtllm checkpoint to be generated.

### actual behavior

Traceback (most recent call last):
  File "convert_checkpoint.py", line 1509, in <module>
    main()
  File "convert_checkpoint.py", line 1482, in main
    covert_and_save(rank, convert_args)
  File "convert_checkpoint.py", line 1457, in covert_and_save
    weights = convert_hf_llama(
  File "convert_checkpoint.py", line 942, in convert_hf_llama
    int8_weights = generate_int8(
  File "convert_checkpoint.py", line 297, in generate_int8
    weights = weights.detach().cpu().numpy()
TypeError: Got unsupported ScalarType BFloat16

### additional notes

The closest discussion to a similar error I can find is: https://github.com/NVIDIA/TensorRT-LLM/issues/1039#issuecomment-1953960126

I tried the fix mentioned (torch_to_numpy convertor) and see the following error:
numpy.core._exceptions._UFuncNoLoopError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('V2'), dtype('float32')) -> None

**Comment by Tracin** [comment]
Currently, plugin based SQ can not work with BF16. You can try other precision or using AMMO (no-plugin).
```
python ../quantization/quantize.py --model_dir ~/Llama-2-13b-chat-hf  \
                                   --dtype bfloat16 \
                                   --qformat int8_sq \
                                   --output_dir ~/output_dir
```

**Comment by ghost** [comment]
> Currently, plugin based SQ can not work with BF16. You can try other precision or using AMMO (no-plugin).
> 
> ```
> python ../quantization/quantize.py --model_dir ~/Llama-2-13b-chat-hf  \
>                                    --dtype bfloat16 \
>                                    --qformat int8_sq \
>                                    --output_dir ~/output_dir
> ```

Thank you! However, after quantization, `trtllm-build` fails to build the inference engine.
```
python ./quantization/quantize.py --model_dir ~/Llama-2-13b-chat-hf --dtype bfloat16 --qformat int8_sq --output_dir ~/Llama-2-13b-chat-ammo-tp4-sq-pc-kvcacheint8  --tp_size 4 --kv_cache_dtype int8
```

```
trtllm-build --checkpoint_dir ~/Llama-2-13b-chat-ammo-tp4-sq-pc-kvcacheint8 --output_dir ~/Llama-2-13b-chat/bf16-tp4-sq-ammo-int8kv --gpt_attention_plugin bfloat16 --gemm_plugin bfloat16
```

Error trace:
```
[02/27/2024-10:00:24] [TRT] [W] IElementWiseLayer with inputs LLaMAForCausalLM/transformer/layers/39/ELEMENTWISE_SUM_1_output_0 and LLaMAForCausalLM/transformer/ln_f/SHUFFLE_0_output_0: first input has type BFloat16 but second input has type Float.
[02/27/2024-10:00:24] [TRT] [W] IElementWiseLayer with inputs LLaMAForCausalLM/transformer/ln_f/REDUCE_AVG_0_output_0 and LLaMAForCausalLM/transformer/ln_f/SHUFFLE_1_output_0: first input has type BFloat16 but second input has type Float.
[02/27/2024-10:00:24] [TRT-LLM] [I] Build TensorRT engine Unnamed Network 0
[02/27/2024-10:00:24] [TRT] [W] Unused Input: position_ids
[02/27/2024-10:00:25] [TRT] [W] [RemoveDeadLayers] Input Tensor position_ids is unused or used only at compile-time, but is not being removed.
[02/27/2024-10:00:25] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 2354, GPU 799 (MiB)
[02/27/2024-10:00:25] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +2, GPU +10, now: CPU 2356, GPU 809 (MiB)
[02/27/2024-10:00:25] [TRT] [W] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.2
[02/27/2024-10:00:25] [TRT] [I] Global timing cache in use. Profiling results in this builder pass will be stored.
[02/27/2024-10:05:44] [TRT] [I] [GraphReduction] The approximate region cut reduction algorithm is called.
[02/27/2024-10:06:49] [TRT] [I] Detected 131 inputs and 5 output network tensors.
[02/27/2024-10:08:29] [TRT] [I] Total Host Persistent Memory: 277136
[02/27/2024-10:08:29] [TRT] [I] Total Device Persistent Memory: 0
[02/27/2024-10:08:29] [TRT] [I] Total Scratch Memory: 33558784
[02/27/2024-10:08:29] [TRT] [I] [BlockAssignment] Started assigning block shifts. This will take 774 steps to complete.
[02/27/2024-10:08:29] [TRT] [I] [BlockAssignment] Algorithm ShiftNTopDown took 63.567ms to assign 13 blocks to 774 nodes requiring 75506176 bytes.
[02/27/2024-10:08:29] [TRT] [I] Total Activation Memory: 75506176
[02/27/2024-10:08:29] [TRT] [I] Total Weights Memory: 3339259392
[02/27/2024-10:08:30] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 2770, GPU 4035 (MiB)
[02/27/2024-10:08:30] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +10, now: CPU 2770, GPU 4045 (MiB)
[02/27/2024-10:08:30] [TRT] [W] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.2
[02/27/2024-10:08:30] [TRT] [I] Engine generation completed in 485 seconds.
[02/27/2024-10:08:30] [TRT] [I] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 159 MiB, GPU 3185 MiB
[02/27/2024-10:08:30] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in building engine: CPU +0, GPU +3185, now: CPU 0, GPU 3185 (MiB)
[02/27/2024-10:08:30] [TRT] [E] 1: [serialize.cpp::save::155] Error Code 1: Internal Error (Unsupported type for WeightsPtr serialization.)
[02/27/2024-10:08:30] [TRT-LLM] [I] Serializing engine to bf16-tp4-sq-ammo-int8kv/rank1.engine...
concurrent.futures.process._RemoteTraceback: 
Traceback (most recent call last):
  File "python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "python3.10/site-packages/tensorrt_llm/commands/build.py", line 415, in build_and_save
    engine.save(output_dir)
  File "python3.10/site-packages/tensorrt_llm/runtime/engine.py", line 60, in save
    serialize_engine(
  File "python3.10/site-packages/tensorrt_llm/runtime/engine.py", line 18, in serialize_engine
    f.write(engine)
TypeError: a bytes-like object is required, not 'NoneType'
```

**Comment by Tracin** [comment]
@vnkc1 Please try add `--strongly_typed` option
