### ISSUE TITLE
[BUG] close_ipc_memory Error Exception ignored in: <function IpcMemory.__del__ at 0x7f94b6286a70>

### ISSUE THREAD

**Issue by DefTruth** [NVIDIA/TensorRT-LLM#1190]
### System Info

- CPU: x86_64
- GPU: A30
- Container: nvcr.io/nvidia/tritonserver:24.01-trtllm-python-py3
- PyTorch: 2.2.1
- tensorrt_llm:  0.9.0.dev2024022700
- tensorrt: 9.2.0.post12.dev5
- cuda-python: 12.3.0
- CUDA: 12.3

### Who can help?

@byshiue 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```bash 
# MODEL_NAME=llava-1.5-7b-hf
(triton)(TRT92)➜ multimodal git:(main) ✗ mpirun --allow-run-as-root -n 2 python3 run.py \
    --max_new_tokens 30 \
    --input_text "Question: which city is this? Answer:" \
    --hf_model_dir tmp/hf_models/$MODEL_NAME \
    --visual_engine_dir visual_engines/$MODEL_NAME \
    --llm_engine_dir trt_engines/$MODEL_NAME/fp16/2-gpu \
    --decoder_llm
/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
[TensorRT-LLM] TensorRT-LLM version: 0.9.0.dev2024022700
[TensorRT-LLM] TensorRT-LLM version: 0.9.0.dev2024022700
/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[02/29/2024-05:37:22] [TRT-LLM] [I] Loading engine from visual_engines/llava-1.5-7b-hf/visual_encoder.engine
[02/29/2024-05:37:22] [TRT-LLM] [I] Loading engine from visual_engines/llava-1.5-7b-hf/visual_encoder.engine
[02/29/2024-05:37:22] [TRT-LLM] [I] Creating session from engine visual_engines/llava-1.5-7b-hf/visual_encoder.engine
[02/29/2024-05:37:22] [TRT-LLM] [I] Creating session from engine visual_engines/llava-1.5-7b-hf/visual_encoder.engine
[02/29/2024-05:37:22] [TRT] [I] Loaded engine size: 599 MiB
[02/29/2024-05:37:22] [TRT] [I] Loaded engine size: 599 MiB
[02/29/2024-05:37:22] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +595, now: CPU 0, GPU 595 (MiB)
[02/29/2024-05:37:22] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +595, now: CPU 0, GPU 595 (MiB)
[02/29/2024-05:37:23] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +49, now: CPU 0, GPU 644 (MiB)
[02/29/2024-05:37:23] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +49, now: CPU 0, GPU 644 (MiB)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set bert_attention_plugin to float16.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set gpt_attention_plugin to float16.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set gemm_plugin to float16.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set smooth_quant_gemm_plugin to None.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set identity_plugin to None.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set layernorm_quantization_plugin to None.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set rmsnorm_quantization_plugin to None.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set nccl_plugin to float16.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set lookup_plugin to None.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set lora_plugin to None.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set weight_only_groupwise_quant_matmul_plugin to None.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set weight_only_quant_matmul_plugin to None.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set quantize_per_token_plugin to False.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set quantize_tensor_plugin to False.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set moe_plugin to float16.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set context_fmha to True.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set context_fmha_fp32_acc to False.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set paged_kv_cache to True.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set remove_input_padding to True.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set use_custom_all_reduce to True.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set multi_block_mode to False.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set enable_xqa to True.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set attention_qk_half_accumulation to False.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set tokens_per_block to 128.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set use_paged_context_fmha to False.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set use_context_fmha_for_generation to False.
[02/29/2024-05:37:26] [TRT] [I] Loaded engine size: 6555 MiB
[02/29/2024-05:37:26] [TRT-LLM] [I] Set bert_attention_plugin to float16.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set gpt_attention_plugin to float16.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set gemm_plugin to float16.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set smooth_quant_gemm_plugin to None.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set identity_plugin to None.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set layernorm_quantization_plugin to None.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set rmsnorm_quantization_plugin to None.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set nccl_plugin to float16.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set lookup_plugin to None.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set lora_plugin to None.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set weight_only_groupwise_quant_matmul_plugin to None.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set weight_only_quant_matmul_plugin to None.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set quantize_per_token_plugin to False.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set quantize_tensor_plugin to False.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set moe_plugin to float16.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set context_fmha to True.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set context_fmha_fp32_acc to False.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set paged_kv_cache to True.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set remove_input_padding to True.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set use_custom_all_reduce to True.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set multi_block_mode to False.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set enable_xqa to True.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set attention_qk_half_accumulation to False.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set tokens_per_block to 128.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set use_paged_context_fmha to False.
[02/29/2024-05:37:26] [TRT-LLM] [I] Set use_context_fmha_for_generation to False.
[02/29/2024-05:37:26] [TRT] [I] Loaded engine size: 6555 MiB
[02/29/2024-05:37:27] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 6775, GPU 7479 (MiB)
[02/29/2024-05:37:27] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +1, GPU +10, now: CPU 6776, GPU 7489 (MiB)
[02/29/2024-05:37:28] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 6774, GPU 7479 (MiB)
[02/29/2024-05:37:28] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +2, GPU +10, now: CPU 6776, GPU 7489 (MiB)
[02/29/2024-05:37:29] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +6553, now: CPU 0, GPU 7197 (MiB)
[02/29/2024-05:37:29] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +1, GPU +8, now: CPU 6943, GPU 7861 (MiB)
[02/29/2024-05:37:29] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 6943, GPU 7869 (MiB)
[02/29/2024-05:37:29] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +6553, now: CPU 0, GPU 7197 (MiB)
[02/29/2024-05:37:29] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 6942, GPU 7861 (MiB)
[02/29/2024-05:37:29] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 6942, GPU 7869 (MiB)
[02/29/2024-05:37:29] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 7197 (MiB)
[02/29/2024-05:37:29] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 7197 (MiB)
[02/29/2024-05:37:29] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 6966, GPU 7887 (MiB)
[02/29/2024-05:37:29] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 6966, GPU 7887 (MiB)
[02/29/2024-05:37:29] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +10, now: CPU 6966, GPU 7897 (MiB)
[02/29/2024-05:37:29] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +10, now: CPU 6966, GPU 7897 (MiB)
[02/29/2024-05:37:30] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 7197 (MiB)
[02/29/2024-05:37:30] [TRT-LLM] [W] The paged KV cache in Python runtime is experimental. For performance and correctness, please, use C++ runtime.
[02/29/2024-05:37:30] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 7197 (MiB)
[02/29/2024-05:37:30] [TRT-LLM] [I] Load engine takes: 7.2138988971710205 sec
[02/29/2024-05:37:30] [TRT-LLM] [W] The paged KV cache in Python runtime is experimental. For performance and correctness, please, use C++ runtime.
[02/29/2024-05:37:30] [TRT-LLM] [I] Load engine takes: 7.219012022018433 sec
/usr/local/lib/python3.10/dist-packages/torch/nested/__init__.py:166: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. (Triggered internally at ../aten/src/ATen/NestedTensorImpl.cpp:177.)
  return _nested.nested_tensor(
/usr/local/lib/python3.10/dist-packages/torch/nested/__init__.py:166: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. (Triggered internally at ../aten/src/ATen/NestedTensorImpl.cpp:177.)
  return _nested.nested_tensor(
[02/29/2024-05:37:33] [TRT-LLM] [I] ---------------------------------------------------------
[02/29/2024-05:37:33] [TRT-LLM] [I]
[Q] Question: which city is this? Answer:
[02/29/2024-05:37:33] [TRT-LLM] [I]
[A] [['Singapore']]
[02/29/2024-05:37:33] [TRT-LLM] [I] ---------------------------------------------------------
Exception ignored in: <function IpcMemory.__del__ at 0x7fe64738aa70>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_ipc_utils.py", line 76, in __del__
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_ipc_utils.py", line 128, in close_ipc_memory
TypeError: 'NoneType' object is not callable
Exception ignored in: <function IpcMemory.__del__ at 0x7fe64738aa70>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_ipc_utils.py", line 76, in __del__
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_ipc_utils.py", line 128, in close_ipc_memory
TypeError: 'NoneType' object is not callable
Exception ignored in: <function IpcMemory.__del__ at 0x7fe64738aa70>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_ipc_utils.py", line 76, in __del__
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_ipc_utils.py", line 128, in close_ipc_memory
TypeError: 'NoneType' object is not callable
Exception ignored in: <function IpcMemory.__del__ at 0x7f94b6286a70>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_ipc_utils.py", line 76, in __del__
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_ipc_utils.py", line 126, in close_ipc_memory
TypeError: 'NoneType' object is not callable
Exception ignored in: <function IpcMemory.__del__ at 0x7f94b6286a70>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_ipc_utils.py", line 76, in __del__
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_ipc_utils.py", line 126, in close_ipc_memory
TypeError: 'NoneType' object is not callable
Exception ignored in: <function IpcMemory.__del__ at 0x7f94b6286a70>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_ipc_utils.py", line 76, in __del__
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_ipc_utils.py", line 126, in close_ipc_memory
TypeError: 'NoneType' object is not callable
```

### Expected behavior

no error

### actual behavior

```bash
TypeError: 'NoneType' object is not callable
Exception ignored in: <function IpcMemory.__del__ at 0x7fe64738aa70>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_ipc_utils.py", line 76, in __del__
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_ipc_utils.py", line 128, in close_ipc_memory
TypeError: 'NoneType' object is not callable
Exception ignored in: <function IpcMemory.__del__ at 0x7fe64738aa70>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_ipc_utils.py", line 76, in __del__
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_ipc_utils.py", line 128, in close_ipc_memory
TypeError: 'NoneType' object is not callable
Exception ignored in: <function IpcMemory.__del__ at 0x7f94b6286a70>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_ipc_utils.py", line 76, in __del__
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_ipc_utils.py", line 126, in close_ipc_memory
TypeError: 'NoneType' object is not callable
Exception ignored in: <function IpcMemory.__del__ at 0x7f94b6286a70>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_ipc_utils.py", line 76, in __del__
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_ipc_utils.py", line 126, in close_ipc_memory
TypeError: 'NoneType' object is not callable
Exception ignored in: <function IpcMemory.__del__ at 0x7f94b6286a70>
```

### additional notes

I have build latest dev trtllm with commitid: b7c309d1c9baa9c030680988cb73e461f6253b98 and test LLaVA 7B with tp=2
```bash
##### TP 2  ####
# 1. Download Huggingface model weights. This model has both LLM and visual 
# components unlike BLIP2 example which downloads only LLM components from Huggingface.
export MODEL_NAME="llava-1.5-7b-hf"
git clone https://huggingface.co/llava-hf/$MODEL_NAME tmp/hf_models/$MODEL_NAME

# 2. Generate TRT-LLM engine for LLaMA following example in examples/llama/README.md
# convert checkpoint 7b tp=2
python3 ../llama/convert_checkpoint.py \
    --model_dir tmp/hf_models/$MODEL_NAME \
    --output_dir tmp/trt_models/$MODEL_NAME/fp16/2-gpu \
    --dtype float16 \
    --tp_size 2
# trtllm-build 7b tp=2
trtllm-build \
    --checkpoint_dir tmp/trt_models/$MODEL_NAME/fp16/2-gpu \
    --output_dir trt_engines/$MODEL_NAME/fp16/2-gpu \
    --gemm_plugin float16 \
    --max_batch_size 1 \
    --max_input_len 2048 \
    --max_output_len 512 \
    --max_multimodal_len 576
# 3. Build TensorRT engines for visual components
python3 build_visual_engine.py --model_name $MODEL_NAME --model_path tmp/hf_models/$MODEL_NAME
# 4. Add --decoder-llm argument to inference script, since LLaMA is a decoder-only LLM.
mpirun --allow-run-as-root -n 2 python3 run.py \
    --max_new_tokens 30 \
    --input_text "Question: which city is this? Answer:" \
    --hf_model_dir tmp/hf_models/$MODEL_NAME \
    --visual_engine_dir visual_engines/$MODEL_NAME \
    --llm_engine_dir trt_engines/$MODEL_NAME/fp16/2-gpu \
    --decoder_llm

```

**Comment by DefTruth** [comment]
@byshiue 
I temporarily solved this problem by adding `del model.model` at the end of run.py. Is there any other method? Will this problem affect the normal use of trtllm?

**Comment by amukkara** [comment]
@DefTruth 
This is a memory management error, that does not seem to affect execution. Since you are getting correct output, is the inference speed satisfactory?

**Comment by DefTruth** [comment]
> @byshiue I temporarily solved this problem by adding `del model.model` at the end of run.py. Is there any other method? Will this problem affect the normal use of trtllm?

The result is correct. No impact on performance has been found so far.

**Comment by Hukongtao** [comment]
I got the same error as yours. Although it has no impact on the inference results and performance, it always feels strange.

**Comment by zhangts20** [comment]
Do you have any ideas on how to solve this problem? I encountered the same issue in tag v0.11.0 when tp_size is 2
