### ISSUE TITLE
getPluginCreator could not find plugin: AllReducetensorrt_llm version: 1 (AssertionError)

### ISSUE THREAD

**Issue by faust58** [NVIDIA/TensorRT-LLM#1199]
### System Info

CPU x2 Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz 64 Gb
GPU x2 NVIDIA RTX A5000 24 Gb
OS Windows server 2022 Standart x64
Tags: v.0.7.1
Model: Mistral v0.1

I used the following config:

python build.py --model_dir ./tmp/mistral/7B/ \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --output_dir ./tmp/mistral/7B/trt_engines/fp16/1-gpu/ \
                --max_input_len 4096 \
                --max_batch_size 8 \
                --world_size 2 \
                --tp_size 2 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

python C:\TensorRT-LLM\examples\llama\build.py --model_dir . --dtype=float16 --remove_input_padding --use_gpt_attention_plugin=float16 --enable_context_fmha --use_gemm_plugin=float16 --output_dir ./tmp/llama/7B/trt_engines/fp16/2-gpu/ --max_input_len=4096 --max_batch_size=8 --world_size=2 --tp_size=2

### Expected behavior

The engine is build.

### actual behavior

[02/29/2024-20:27:05] [TRT-LLM] [I] Loading weights from HF LLaMA...
[02/29/2024-20:27:11] [TRT-LLM] [I] Weights loaded. Total time: 00:00:05
[02/29/2024-20:27:11] [TRT-LLM] [I] HF LLaMA loaded. Total time: 00:00:16
[02/29/2024-20:27:11] [TRT-LLM] [I] [MemUsage] Rank 0 model weight loaded. - Allocated Memory: Host 25.6480 (GiB) Device 1.3366 (GiB)
[02/29/2024-20:27:11] [TRT-LLM] [I] Context FMHA Enabled
[02/29/2024-20:27:11] [TRT-LLM] [I] Remove Padding Enabled
[02/29/2024-20:27:11] [TRT] [W] A shape layer can only run in INT32 precision
[02/29/2024-20:27:11] [TRT] [W] IElementWiseLayer with inputs LLaMAForCausalLM/vocab_embedding/GATHER_0_output_0 and LLaMAForCausalLM/layers/0/input_layernorm/SHUFFLE_0_output_0: first input has type Half but second input has type Float.
[02/29/2024-20:27:11] [TRT] [W] A shape layer can only run in INT32 precision
[02/29/2024-20:27:11] [TRT] [W] IElementWiseLayer with inputs LLaMAForCausalLM/layers/0/input_layernorm/REDUCE_AVG_0_output_0 and LLaMAForCausalLM/layers/0/input_layernorm/SHUFFLE_1_output_0: first input has type Half but second input has type Float.
[02/29/2024-20:27:11] [TRT] [E] 3: getPluginCreator could not find plugin: AllReducetensorrt_llm version: 1
Traceback (most recent call last):
  File "C:\TensorRT-LLM\examples\llama\build.py", line 906, in <module>
    build(0, args)
  File "C:\TensorRT-LLM\examples\llama\build.py", line 850, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "C:\TensorRT-LLM\examples\llama\build.py", line 777, in build_rank_engine
    tensorrt_llm_llama(*inputs)
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\module.py", line 40, in __call__
    return self.forward(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\models\llama\model.py", line 398, in forward
    hidden_states = super().forward(input_ids, position_ids, use_cache,
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\models\llama\model.py", line 277, in forward
    hidden_states = layer(
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\module.py", line 40, in __call__
    return self.forward(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\models\llama\model.py", line 130, in forward
    attention_output = self.attention(hidden_states,
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\module.py", line 40, in __call__
    return self.forward(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\layers\attention.py", line 923, in forward
    context = self.dense(context,
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\module.py", line 40, in __call__
    return self.forward(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\layers\linear.py", line 220, in forward
    return self.multiply_reduce(x,
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\layers\linear.py", line 206, in multiply_reduce
    x = allreduce(x, self.tp_group, workspace, self.instance_id)
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\functional.py", line 2854, in allreduce
    assert allreduce_plg_creator is not None
AssertionError
PS F:\openbuddy-mistral-7b-v13-base>

### additional notes

Without the --world_size=2 --tp_size=2 flags, the engine is built, but the built model utilizes only one GPU.

**Comment by byshiue** [comment]
Could you try the latest v0.8? Also, please share the steps you build tensorrt_llm if you still have issue.

**Comment by faust58** [comment]
@byshiue I want to use Llamaindex with TensorRT-LLM in my work, and there is a note "Use this branch only for TRT-LLM v0.7.1 on Windows.", so I can't use v.0.8.0.
After installing all the necessary components, I executed the following commands:
1. & 'C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\Launch-VsDevShell.ps1' -Arch amd64
2. python .\scripts\build_wheel.py -a "89-real" --trt_root C:\TensorRT-LLM\windows\TensorRT-9.2.0.5 --clean
3. pip install "C:\TensorRT-LLM\build\tensorrt_llm-0.7.1-cp310-cp310-win_amd64.whl" after that I installed a few more libraries that did not install automatically.
4. PS C:\WINDOWS\system32> python -c "import tensorrt_llm; print(tensorrt_llm._utils.trt_version())"
9.2.0.post12.dev5
5. pip install -r "C:\TensorRT-LLM\examples\llama\requirements.txt"
6. PS F:\> git lfs install
7. PS F:\> git clone https://huggingface.co/mistralai/Mistral-7B-v0.1
8. PS F:\Mistral-7B-v0.1> python C:\TensorRT-LLM\examples\llama\build.py --model_dir . --dtype=float16 --remove_input_padding --use_gpt_attention_plugin=float16 --enable_context_fmha --use_gemm_plugin=float16 --output_dir ./tmp/llama/7B/trt_engines/fp16/2-gpu/ --max_input_len=4096 --max_batch_size=8 --world_size=2 --tp_size=2 --strongly_typed
You are using a model of type mistral to instantiate a model of type llama. This is not supported for all configurations of models and can yield errors.
[03/05/2024-19:25:13] [TRT-LLM] [I] Serially build TensorRT engines.
[03/05/2024-19:25:13] [TRT] [I] [MemUsageChange] Init CUDA: CPU +75, GPU +0, now: CPU 14201, GPU 1548 (MiB)
[03/05/2024-19:25:19] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +2734, GPU +543, now: CPU 17201, GPU 2091 (MiB)
[03/05/2024-19:25:19] [TRT-LLM] [W] Invalid timing cache, using freshly created one
[03/05/2024-19:25:19] [TRT-LLM] [I] [MemUsage] Rank 0 Engine build starts - Allocated Memory: Host 3.5886 (GiB) Device 19.7156 (GiB)
[03/05/2024-19:25:25] [TRT-LLM] [I] Loading HF LLaMA ... from .
You are using a model of type mistral to instantiate a model of type llama. This is not supported for all configurations of models and can yield errors.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 14.10it/s]
Some weights of LlamaForCausalLM were not initialized from the model checkpoint at . and are newly initialized: ['model.layers.1.self_attn.rotary_emb.inv_freq', 'model.layers.13.self_attn.rotary_emb.inv_freq', 'model.layers.5.self_attn.rotary_emb.inv_freq', 'model.layers.9.self_attn.rotary_emb.inv_freq', 'model.layers.30.self_attn.rotary_emb.inv_freq', 'model.layers.3.self_attn.rotary_emb.inv_freq', 'model.layers.25.self_attn.rotary_emb.inv_freq', 'model.layers.15.self_attn.rotary_emb.inv_freq', 'model.layers.26.self_attn.rotary_emb.inv_freq', 'model.layers.18.self_attn.rotary_emb.inv_freq', 'model.layers.12.self_attn.rotary_emb.inv_freq', 'model.layers.19.self_attn.rotary_emb.inv_freq', 'model.layers.6.self_attn.rotary_emb.inv_freq', 'model.layers.0.self_attn.rotary_emb.inv_freq', 'model.layers.14.self_attn.rotary_emb.inv_freq', 'model.layers.2.self_attn.rotary_emb.inv_freq', 'model.layers.17.self_attn.rotary_emb.inv_freq', 'model.layers.31.self_attn.rotary_emb.inv_freq', 'model.layers.22.self_attn.rotary_emb.inv_freq', 'model.layers.24.self_attn.rotary_emb.inv_freq', 'model.layers.10.self_attn.rotary_emb.inv_freq', 'model.layers.28.self_attn.rotary_emb.inv_freq', 'model.layers.16.self_attn.rotary_emb.inv_freq', 'model.layers.8.self_attn.rotary_emb.inv_freq', 'model.layers.27.self_attn.rotary_emb.inv_freq', 'model.layers.23.self_attn.rotary_emb.inv_freq', 'model.layers.11.self_attn.rotary_emb.inv_freq', 'model.layers.21.self_attn.rotary_emb.inv_freq', 'model.layers.7.self_attn.rotary_emb.inv_freq', 'model.layers.4.self_attn.rotary_emb.inv_freq', 'model.layers.20.self_attn.rotary_emb.inv_freq', 'model.layers.29.self_attn.rotary_emb.inv_freq']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[03/05/2024-19:25:26] [TRT-LLM] [I] Loading weights from HF LLaMA...
[03/05/2024-19:25:38] [TRT-LLM] [I] Weights loaded. Total time: 00:00:11
[03/05/2024-19:25:38] [TRT-LLM] [I] HF LLaMA loaded. Total time: 00:00:12
[03/05/2024-19:25:39] [TRT-LLM] [I] [MemUsage] Rank 0 model weight loaded. - Allocated Memory: Host 25.4682 (GiB) Device 20.2371 (GiB)
[03/05/2024-19:25:39] [TRT-LLM] [I] Context FMHA Enabled
[03/05/2024-19:25:39] [TRT-LLM] [I] Remove Padding Enabled
[03/05/2024-19:25:39] [TRT] [E] 3: getPluginCreator could not find plugin: AllReducetensorrt_llm version: 1
Traceback (most recent call last):
  File "C:\TensorRT-LLM\examples\llama\build.py", line 906, in <module>
    build(0, args)
  File "C:\TensorRT-LLM\examples\llama\build.py", line 850, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "C:\TensorRT-LLM\examples\llama\build.py", line 777, in build_rank_engine
    tensorrt_llm_llama(*inputs)
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\module.py", line 40, in __call__
    return self.forward(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\models\llama\model.py", line 398, in forward
    hidden_states = super().forward(input_ids, position_ids, use_cache,
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\models\llama\model.py", line 277, in forward
    hidden_states = layer(
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\module.py", line 40, in __call__
    return self.forward(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\models\llama\model.py", line 130, in forward
    attention_output = self.attention(hidden_states,
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\module.py", line 40, in __call__
    return self.forward(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\layers\attention.py", line 923, in forward
    context = self.dense(context,
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\module.py", line 40, in __call__
    return self.forward(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\layers\linear.py", line 220, in forward
    return self.multiply_reduce(x,
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\layers\linear.py", line 206, in multiply_reduce
    x = allreduce(x, self.tp_group, workspace, self.instance_id)
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\functional.py", line 2854, in allreduce
    assert allreduce_plg_creator is not None
AssertionError
PS F:\Mistral-7B-v0.1>

**Comment by faust58** [comment]
I tried v 0.8, but I'm getting the same error. Please help me @byshiue 

PS D:\TensorRT-LLM> python D:\TensorRT-LLM\examples\llama\convert_checkpoint.py --model_dir "F:\Llama-2-7b-chat-hf" --output_dir ./tllm_checkpoint_1gpu_mistral --dtype float16 --worker 4 --tp_size=2 --pp_size=2
[TensorRT-LLM] TensorRT-LLM version: 0.8.00.8.0
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:43<00:00, 21.83s/it]
Weights loaded. Total time: 00:00:29
Weights loaded. Total time: 00:00:29
Weights loaded. Total time: 00:01:33
Weights loaded. Total time: 00:01:34
Total time of converting checkpoints: 00:02:49
PS D:\TensorRT-LLM> trtllm-build --checkpoint_dir ./tllm_checkpoint_1gpu_mistral --output_dir ./tmp/mistral/7B/trt_engines/fp16/1-gpu/ --gemm_plugin float16 --strongly_typed --remove_input_padding enable --context_fmha enable --max_num_tokens 32768 --max_input_len=4096 --max_batch_size=8
[TensorRT-LLM] TensorRT-LLM version: 0.8.0[04/04/2024-11:29:13] [TRT-LLM] [I] Set bert_attention_plugin to float16.
[04/04/2024-11:29:13] [TRT-LLM] [I] Set gpt_attention_plugin to float16.
[04/04/2024-11:29:13] [TRT-LLM] [I] Set gemm_plugin to float16.
[04/04/2024-11:29:13] [TRT-LLM] [I] Set lookup_plugin to None.
[04/04/2024-11:29:13] [TRT-LLM] [I] Set lora_plugin to None.
[04/04/2024-11:29:13] [TRT-LLM] [I] Set context_fmha to True.
[04/04/2024-11:29:13] [TRT-LLM] [I] Set context_fmha_fp32_acc to False.
[04/04/2024-11:29:13] [TRT-LLM] [I] Set paged_kv_cache to True.
[04/04/2024-11:29:13] [TRT-LLM] [I] Set remove_input_padding to True.
[04/04/2024-11:29:13] [TRT-LLM] [I] Set use_custom_all_reduce to True.
[04/04/2024-11:29:13] [TRT-LLM] [I] Set multi_block_mode to False.
[04/04/2024-11:29:13] [TRT-LLM] [I] Set enable_xqa to True.
[04/04/2024-11:29:13] [TRT-LLM] [I] Set attention_qk_half_accumulation to False.
[04/04/2024-11:29:13] [TRT-LLM] [I] Set tokens_per_block to 128.
[04/04/2024-11:29:13] [TRT-LLM] [I] Set use_paged_context_fmha to False.
[04/04/2024-11:29:13] [TRT-LLM] [I] Set use_context_fmha_for_generation to False.
[04/04/2024-11:29:14] [TRT] [I] [MemUsageChange] Init CUDA: CPU +90, GPU +0, now: CPU 12694, GPU 1372 (MiB)
[04/04/2024-11:29:51] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +2707, GPU +312, now: CPU 15682, GPU 1684 (MiB)
[04/04/2024-11:29:51] [TRT-LLM] [I] Set nccl_plugin to float16.
[04/04/2024-11:29:51] [TRT-LLM] [I] Set use_custom_all_reduce to True.
[TensorRT-LLM][ERROR] Parameter check failed at: C:\Users\tejaswinp\workspace\tekit\cpp\tensorrt_llm\plugins\common\plugin.cpp::PluginFieldParser::~PluginFieldParser::183, condition: unused plugin field with name: enable_xqa
[TensorRT-LLM][ERROR] Parameter check failed at: C:\Users\tejaswinp\workspace\tekit\cpp\tensorrt_llm\plugins\common\plugin.cpp::PluginFieldParser::~PluginFieldParser::183, condition: unused plugin field with name: unfuse_qkv_gemm
[TensorRT-LLM][ERROR] Parameter check failed at: C:\Users\tejaswinp\workspace\tekit\cpp\tensorrt_llm\plugins\common\plugin.cpp::PluginFieldParser::~PluginFieldParser::183, condition: unused plugin field with name: pos_shift_enabled
[TensorRT-LLM][ERROR] Parameter check failed at: C:\Users\tejaswinp\workspace\tekit\cpp\tensorrt_llm\plugins\common\plugin.cpp::PluginFieldParser::~PluginFieldParser::183, condition: unused plugin field with name: dense_context_fmha
[TensorRT-LLM][ERROR] Parameter check failed at: C:\Users\tejaswinp\workspace\tekit\cpp\tensorrt_llm\plugins\common\plugin.cpp::PluginFieldParser::~PluginFieldParser::183, condition: unused plugin field with name: is_medusa_enabled
[04/04/2024-11:29:51] [TRT] [E] 3: getPluginCreator could not find plugin: AllReducetensorrt_llm version: 1
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\trtllm-build.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\commands\build.py", line 497, in main
    parallel_build(source, build_config, args.output_dir, workers,
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\commands\build.py", line 420, in parallel_build
    passed = build_and_save(rank, rank % workers, ckpt_dir,
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\commands\build.py", line 392, in build_and_save
    engine = build(build_config,
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\commands\build.py", line 282, in build
    return build_model(model, build_config)
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\commands\build.py", line 198, in build_model
    model(**inputs)
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\module.py", line 40, in __call__
    output = self.forward(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\models\modeling_utils.py", line 498, in forward
    hidden_states = self.transformer.forward(**kwargs)
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\models\llama\model.py", line 202, in forward
    hidden_states = self.layers.forward(
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\models\modeling_utils.py", line 255, in forward
    hidden_states = layer(
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\module.py", line 40, in __call__
    output = self.forward(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\models\llama\model.py", line 116, in forward
    attention_output = self.attention(
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\module.py", line 40, in __call__
    output = self.forward(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\layers\attention.py", line 1085, in forward
    context = self.dense(context, lora_runtime_params=dense_lora_params)
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\module.py", line 40, in __call__
    output = self.forward(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\layers\linear.py", line 217, in forward
    return self.multiply_reduce(x,
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\layers\linear.py", line 208, in multiply_reduce
    x = allreduce(x, self.tp_group)
  File "C:\Program Files\Python310\lib\site-packages\tensorrt_llm\functional.py", line 3052, in allreduce
    assert allreduce_plg_creator is not None
AssertionError
PS D:\TensorRT-LLM>

**Comment by faust58** [comment]
" TensorRT-LLM is supported on bare-metal Windows for single-GPU inference. "
