### ISSUE TITLE
LLaMA INT8 KV Cache engine not building (0.8.0 release)

### ISSUE THREAD

**Issue by vnkc1** [NVIDIA/TensorRT-LLM#1268]
### System Info

GPU : NVIDIA A100 40GB

package version
tensorrt-9.2.0.post12.dev5-cp310-none-linux_x86_64.whl
[TensorRT-LLM] TensorRT-LLM version: 0.8.00.8.0

### Who can help?

@Tracin @byshiue 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Installation
`python -m pip install tensorrt_llm==0.8.0 --extra-index-url https://pypi.nvidia.com`

2. Create checkpoint
`python ./llama/convert_checkpoint.py --model_dir ~/Llama-2-13b-chat-hf  --output_dir ~/fp16-tp4-int8kv --dtype float16 --tp_size 4 --workers 4 --int8_kv_cache`

3. Build engine
`trtllm-build --checkpoint_dir ~/fp16-tp4-int8kv  --output_dir ~/engines/fp16-tp4-int8kv --gemm_plugin float16 --remove_input_padding enable --paged_kv_cache enable --context_fmha enable --workers 4 --max_batch_size 32 --max_input_len 4096 --max_output_len 512`

### Expected behavior

Engine successfullly created.

### actual behavior

[03/11/2024-16:45:16] [TRT] [E] 4: [standardEngineBuilder.cpp::initCalibrationParams::1837] Error Code 4: Internal Error (Calibration failure occurred with no scaling factors detected. This could be due to no int8 calibrator or insufficient custom scales for network layers. Please see int8 sample to setup calibration correctly.)
[03/11/2024-16:45:16] [TRT-LLM] [E] Engine building failed, please check the error log.

"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File ".../tensorrt_llm/commands/build.py", line 399, in build_and_save
    engine.save(output_dir)
  File "...tensorrt_llm/runtime/engine.py", line 60, in save
    serialize_engine(
  File ".../tensorrt_llm/runtime/engine.py", line 18, in serialize_engine
    f.write(engine)
TypeError: a bytes-like object is required, not 'NoneType'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ../tensorrt_llm/commands/build.py", line 436, in parallel_build
    future.result()
  File "../python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "../python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
TypeError: a bytes-like object is required, not 'NoneType'
Traceback (most recent call last):
  File "/trtllm-build", line 8, in <module>
    sys.exit(main())
  File ".../tensorrt_llm/commands/build.py", line 497, in main
    parallel_build(source, build_config, args.output_dir, workers,
  File ".../tensorrt_llm/commands/build.py", line 440, in parallel_build
    assert len(exceptions
AssertionError: Engine building failed, please check error log.

### additional notes

No such error on release version 0.7.1

**Comment by byshiue** [comment]
Could you try adding `--strongly_type` when you build engine?

**Comment by ghost** [comment]
`--strongly_typed` works, thank you
