### ISSUE TITLE
`freq_cis` missing from model.state_dict(), causing convert_checkpoint.py to fail for Gemma

### ISSUE THREAD

**Issue by jhirschibar** [NVIDIA/TensorRT-LLM#1271]
Attempting to convert_checkpoint with the latest gemma model from huggingface. It is throwing this error:

```tensorrt-llm-1  | [TensorRT-LLM] TensorRT-LLM version: 0.9.0.dev2024030500
tensorrt-llm-1  | Loading source parameters from /tmp/model/gemma-7b-it
tensorrt-llm-1  | Traceback (most recent call last):
tensorrt-llm-1  |   File "/opt/TensorRT-LLM/examples/gemma/convert_checkpoint.py", line 849, in <module>
tensorrt-llm-1  |     main()
tensorrt-llm-1  |   File "/opt/TensorRT-LLM/examples/gemma/convert_checkpoint.py", line 758, in main
tensorrt-llm-1  |     ckpt_params = ckpt_parser.load_parameters(args.model_dir)
tensorrt-llm-1  |   File "/opt/TensorRT-LLM/examples/gemma/convert_checkpoint.py", line 245, in load_parameters
tensorrt-llm-1  |     model_params.pop('freqs_cis')
tensorrt-llm-1  | KeyError: 'freqs_cis'
```

My checkpoint file is a dictionary like this, where `model` is a torch model downloaded from huggingface:
```{"model_state_dict": model.state_dict()}```

It looks like the script is trying to remove a field that doesn't exist anymore in the model

**Comment by jhirschibar** [comment]
Caused by trying to squash a hf checkpoint into the torch ckpt type. Resolved with the recent addition of `ckpt-type: hf`
