### ISSUE TITLE
convert_checkpoint.py not working - safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization

### ISSUE THREAD

**Issue by saurabhbhagwat** [NVIDIA/TensorRT-LLM#1287]
### System Info

While building TensorRT engines for Mixtral model Mixtral-8x7B-Instruct-v0.1, ran into this error. 

Loading checkpoint shards:  21%|██████████████████████████████████▌                                                                                                                                 | 4/19 [05:30<20:38, 82.58s/it]
Traceback (most recent call last):
  File "/app/tensorrt_llm/examples/llama/convert_checkpoint.py", line 521, in <module>
    main()
  File "/app/tensorrt_llm/examples/llama/convert_checkpoint.py", line 513, in main
    convert_and_save_hf(args)
  File "/app/tensorrt_llm/examples/llama/convert_checkpoint.py", line 433, in convert_and_save_hf
    llama = from_hugging_face(
  File "/app/tensorrt_llm/tensorrt_llm/models/llama/convert.py", line 1179, in from_hugging_face
    model = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3502, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3903, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 505, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization

### Who can help?

@ncomly-nvidia @byshiue

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Follow the steps mentioned in this example. https://github.com/NVIDIA/TensorRT-LLM/tree/5955b8afbad2ddcc3156202b16c567e94c52248f/examples/mixtral

It fails while running the convert_checkpoint.py script. 

### Expected behavior

It should convert the model into checkpoints

### actual behavior

Loading checkpoint shards:  21%|██████████████████████████████████▌                                                                                                                                 | 4/19 [05:30<20:38, 82.58s/it]
Traceback (most recent call last):
  File "/app/tensorrt_llm/examples/llama/convert_checkpoint.py", line 521, in <module>
    main()
  File "/app/tensorrt_llm/examples/llama/convert_checkpoint.py", line 513, in main
    convert_and_save_hf(args)
  File "/app/tensorrt_llm/examples/llama/convert_checkpoint.py", line 433, in convert_and_save_hf
    llama = from_hugging_face(
  File "/app/tensorrt_llm/tensorrt_llm/models/llama/convert.py", line 1179, in from_hugging_face
    model = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3502, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3903, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 505, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization

### additional notes

I tried running this inside the docker built on a server and also inside a k8s pod. Both fail on this error.

**Comment by byshiue** [comment]
@saurabhbhagwat Sorry for delay response. Do you still encounter same issue on latest main branch?

**Comment by FernandoDorado** [comment]
I'm getting also the same error with the latest main branch

**Comment by byshiue** [comment]
Could you share your reproduced steps?

**Comment by FernandoDorado** [comment]
After a cleanup by uninstalling all the libraries and installing everything again with tag v0.10.0 I was able to solve this problem. Apologies for not being able to share the steps to reproduce, I think it was a mismatch between one of the versions of the packages.

**Comment by nv-guomingz** [comment]
Hi @saurabhbhagwat do u still have further issue or question now? If not, we'll close it soon.
