### ISSUE TITLE
Mistral-7B smoothquant failed

### ISSUE THREAD

**Issue by sirodeneko** [NVIDIA/TensorRT-LLM#1333]
### System Info

- CPU: x86_64
- GPU: A800
- CUDA Version: 12.2
- Driver Version: 535.129.03
- TensorRT-LLM version: 0.8.0.dev20240130000.8.0.dev2024013000
- Python: 3.9

### Who can help?

@Tracin

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1.  run
```
python3 /opt/tiger/TensorRT-LLM/examples/llama/convert_checkpoint.py --model_dir /opt/tiger/mixtral/Mistral-7B-Instruct-v0.2 \
--output_dir /opt/tiger/mixtral/tllm_checkpoint_mixtral_1gpu/sq0.5 \
--dtype float16 \
--smoothquant 0.5 \
--per_token \
--per_channel
```

### Expected behavior

Successful conversion model

### actual behavior

output:
```
python3 /opt/tiger/TensorRT-LLM/examples/llama/convert_checkpoint.py --model_dir /opt/tiger/mixtral/Mistral-7B-Instruct-v0.2 --output_dir /opt/tiger/mixtral/tllm_checkpoint_mixtral_1gpu/sq0.5 --dtype float16 --smoothquant 0.5 --per_token --per_channel
--------------------------------------------------------------------------
Open MPI's OFI driver detected multiple equidistant NICs from the current process,
but had insufficient information to ensure MPI processes fairly pick a NIC for use.
This may negatively impact performance. A more modern PMIx server is necessary to
resolve this issue.
--------------------------------------------------------------------------
[TensorRT-LLM] TensorRT-LLM version: 0.8.0.dev20240130000.8.0.dev2024013000
You are using a model of type mistral to instantiate a model of type llama. This is not supported for all configurations of models and can yield errors.
You are using a model of type mistral to instantiate a model of type llama. This is not supported for all configurations of models and can yield errors.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.20s/it]
/usr/local/lib/python3.9/dist-packages/datasets/load.py:1429: FutureWarning: The repository for ccdv/cnn_dailymail contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/ccdv/cnn_dailymail
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
  warnings.warn(
Downloading data: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 159M/159M [00:15<00:00, 10.5MB/s]
Downloading data: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 376M/376M [00:37<00:00, 9.99MB/s]
Downloading data: 2.11MB [00:01, 1.35MB/s]                                                                                                                            
Downloading data: 46.4MB [00:01, 30.4MB/s]                                                                                                                            
Downloading data: 2.43MB [00:00, 3.58MB/s]                                                                                                                            
Generating train split: 287113 examples [00:44, 6470.63 examples/s]
Generating validation split: 13368 examples [00:02, 6472.72 examples/s]
Generating test split: 11490 examples [00:01, 6634.31 examples/s]
calibrating model: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:38<00:00, 13.18it/s]
Traceback (most recent call last):
  File "/opt/tiger/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 1971, in <module>
    main()
  File "/opt/tiger/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 1956, in main
    covert_and_save(rank, convert_args)
  File "/opt/tiger/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 1893, in covert_and_save
    weights = convert_hf_llama(
  File "/opt/tiger/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 1306, in convert_hf_llama
    int8_weights = generate_int8(qkv_weight,
  File "/opt/tiger/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 319, in generate_int8
    weights = weights.detach().cpu().numpy()
TypeError: Got unsupported ScalarType BFloat16
```

### additional notes

I also try to use TensorRT-LLM version: 0.9.0.dev2024031200

output:
```
[TensorRT-LLM] TensorRT-LLM version: 0.9.0.dev2024031200
0.9.0.dev2024031200
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:23<00:00,  7.98s/it]
calibrating model: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [01:28<00:00,  5.82it/s]
Traceback (most recent call last):
  File "/root/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 521, in <module>
    main()
  File "/root/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 513, in main
    convert_and_save_hf(args)
  File "/root/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 415, in convert_and_save_hf
    quantize(args.dtype,
  File "/root/miniconda3/envs/3.10/lib/python3.10/site-packages/tensorrt_llm/models/llama/convert.py", line 1261, in quantize
    weights = load_weights_from_hf(
  File "/root/miniconda3/envs/3.10/lib/python3.10/site-packages/tensorrt_llm/models/llama/convert.py", line 1304, in load_weights_from_hf
    weights = convert_hf_llama(
  File "/root/miniconda3/envs/3.10/lib/python3.10/site-packages/tensorrt_llm/models/llama/convert.py", line 630, in convert_hf_llama
    qkv_weight = qkv_para[prefix + 'self_attn.qkv_proj']
KeyError: 'model.layers.0.self_attn.qkv_proj'
```

**Comment by sirodeneko** [comment]
From the official documentation, Mistral's smoothquant should be supported. Maybe my command is wrong. What is the correct command?

**Comment by ghost** [comment]
I have this issue as well.

**Comment by ghost** [comment]
*To clarify, I face the following error on 0.8.0:
`KeyError: 'model.layers.0.self_attn.qkv_proj'`

**Comment by sirodeneko** [comment]
In TensorRT-LLM version 0.9.0.dev2024031900, the issue has been fixed
