### ISSUE TITLE
Unable to convert finetuned llama-7b to TRT checkpoint

### ISSUE THREAD

**Issue by c3-moutasem** [NVIDIA/TensorRT-LLM#1353]
### System Info

`Nvidia A6000 (48 GB) 14 vCPUs, 100 GiB RAM, 200 GiB SSD
`
`Main tag gemma-6-g66ca337
`
`nvidia/cuda:12.1.0-devel-ubuntu22.04`

### Who can help?

@Tracin afrwe running the command below to run my llama-7b tuned model, i get the following error.

Model config: https://huggingface.co/moutasem/merged_llama_torch/blob/main/config.json
tokenizer config: https://huggingface.co/NousResearch/Llama-2-7b-chat-hf/blob/main/tokenizer_config.json

```
root@4c4a03752eaf:/TensorRT-LLM/examples/llama# python3 convert_checkpoint.py \
    --model_dir llama/7b/ \
    --dtype float16 \
    --output_dir ./llama/torch/trt_ckpt/fp16/1-gpu/ \
    --tp_size 1 \
    --pp_size 1 \
    --vocab_size 32000 \
    --n_positions 4096 \
    --n_layer 32 \
    --n_head 32 \
    --n_kv_head 32 \
    --n_embd 4096 \
    --inter_size 11008 \
    --rms_norm_eps 1e-05 \
    --use_weight_only \
    --weight_only_precision int4 \
    --smoothquant 0.5 \
    --per_channel \
    --per_token \
    --int8_kv_cache \
    --group_size 128

```
```
[TensorRT-LLM] TensorRT-LLM version: 0.9.0.dev2024031900
0.9.0.dev2024031900
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:410: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:415: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:410: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:415: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/datasets/table.py:1421: FutureWarning: promote has been superseded by promote_options='default'.
  table = cls._concat_blocks(blocks, axis=0)
calibrating model: 100%|████████████████████████████████████████████████████████████████████████| 512/512 [01:20<00:00,  6.39it/s]
Traceback (most recent call last):
  File "/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 483, in <module>
    main()
  File "/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 475, in main
    convert_and_save_hf(args)
  File "/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 375, in convert_and_save_hf
    LLaMAForCausalLM.quantize(args.model_dir,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/model.py", line 406, in quantize
    convert.quantize(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 1187, in quantize
    act_range, llama_qkv_para, llama_smoother = smooth_quant(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 994, in smooth_quant
    smooth_llama_model(model, act_range, smoothquant, llama_qkv_para,
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 256, in smooth_llama_model
    smoother = smooth_gemm(weight, scales[layer_name_q]["x"],
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 177, in smooth_gemm
    assert gemm.shape[1] == act_scales.numel()
AssertionError
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1 - # Obtain and start the basic docker image environment.
`docker run --rm --runtime=nvidia --gpus all --entrypoint /bin/bash -it nvidia/cuda:12.1.0-devel-ubuntu22.04
`
2 - # Install dependencies, TensorRT-LLM requires Python 3.10
`apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev wget git-lfs bitsandbytes
`
3 - # Install the latest preview version (corresponding to the main branch) of TensorRT-LLM.
# If you want to install the stable version (corresponding to the release branch), please
# remove the `--pre` option.
`pip3 install tensorrt_llm -U --extra-index-url https://pypi.nvidia.com
`
4 - # Check installation
`python3 -c "import tensorrt_llm"
`
5 - `cd examples/llama`

6 - `mkdir -p ./llama/7b && git clone https://huggingface.co/moutasem/merged_llama_torch ./llama/7b`

7 - `cd llama/7b `

8 - Install tokenzier
```
wget https://huggingface.co/NousResearch/Llama-2-7b-chat-hf/resolve/main/special_tokens_map.json
wget https://huggingface.co/NousResearch/Llama-2-7b-chat-hf/resolve/main/tokenizer.json
wget https://huggingface.co/NousResearch/Llama-2-7b-chat-hf/resolve/main/tokenizer.model
wget https://huggingface.co/NousResearch/Llama-2-7b-chat-hf/resolve/main/tokenizer_config.json
wget https://huggingface.co/NousResearch/Llama-2-7b-chat-hf/resolve/main/added_tokens.json
```

9-  run command:
```
python3 convert_checkpoint.py \
    --model_dir llama/7b/ \
    --dtype float16 \
    --output_dir ./llama/torch/trt_ckpt/fp16/1-gpu/ \
    --tp_size 1 \
    --pp_size 1 \
    --vocab_size 32000 \
    --n_positions 4096 \
    --n_layer 32 \
    --n_head 32 \
    --n_kv_head 32 \
    --n_embd 4096 \
    --inter_size 11008 \
    --rms_norm_eps 1e-05 \
    --use_weight_only \
    --weight_only_precision int8 \
    --smoothquant 0.5 \
    --per_channel \
    --per_token \
    --int8_kv_cache \
    --group_size 128
```

### Expected behavior

checkpoints should be converted

### actual behavior

```
[TensorRT-LLM] TensorRT-LLM version: 0.9.0.dev2024031900
0.9.0.dev2024031900
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:410: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:415: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:410: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:415: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/datasets/table.py:1421: FutureWarning: promote has been superseded by promote_options='default'.
  table = cls._concat_blocks(blocks, axis=0)
calibrating model: 100%|████████████████████████████████████████████████████████████████████████| 512/512 [01:20<00:00,  6.39it/s]
Traceback (most recent call last):
  File "/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 483, in <module>
    main()
  File "/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 475, in main
    convert_and_save_hf(args)
  File "/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 375, in convert_and_save_hf
    LLaMAForCausalLM.quantize(args.model_dir,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/model.py", line 406, in quantize
    convert.quantize(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 1187, in quantize
    act_range, llama_qkv_para, llama_smoother = smooth_quant(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 994, in smooth_quant
    smooth_llama_model(model, act_range, smoothquant, llama_qkv_para,
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 256, in smooth_llama_model
    smoother = smooth_gemm(weight, scales[layer_name_q]["x"],
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 177, in smooth_gemm
    assert gemm.shape[1] == act_scales.numel()
AssertionError
```

### additional notes

i tried to match the config file from HF with tensor-rt convert_to_checkpoint args

**Comment by byshiue** [comment]
Could you take a try without any specific flag like
```bash
python3 convert_checkpoint.py \
    --model_dir llama/7b/ \
    --dtype float16 \
    --output_dir ./llama/torch/trt_ckpt/fp16/1-gpu/ 
```

**Comment by c3-moutasem** [comment]
I am pretty sure I tried it before and it returned an error. I am suddenly getting cuda out of memory for both commands now using the same GPU.

I have cleared torch cache and forced garbage collection. Also, nvidia-smi memory consumption is not spiking


root@4228e94e0587:/TensorRT-LLM/examples/llama# python3 convert_checkpoint.py \
    --model_dir llama/7b/ \
    --dtype float16 \
    --output_dir ./llama/torch/trt_ckpt/fp16/1-gpu/ 
[TensorRT-LLM] TensorRT-LLM version: 0.9.0.dev2024032600
0.9.0.dev2024032600
Traceback (most recent call last):
  File "/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 446, in <module>
    main()
  File "/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 438, in main
    convert_and_save_hf(args)
  File "/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 355, in convert_and_save_hf
    hf_model = preload_model(model_dir) if not args.load_by_shard else None
  File "/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 316, in preload_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3434, in from_pretrained
    max_memory = get_balanced_memory(
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/modeling.py", line 807, in get_balanced_memory
    max_memory = get_max_memory(max_memory)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/modeling.py", line 679, in get_max_memory
    _ = torch.tensor([0], device=i)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by c3-moutasem** [comment]
without it, i get shape error.


```
root@e9aacb1c6cf5:/TensorRT-LLM/examples/llama# python3 convert_checkpoint.py --model_dir ./llama/7b/ --dtype float16 --output_dir ./llama/torch/trt_ck
pt/fp16/1-gpu/
[TensorRT-LLM] TensorRT-LLM version: 0.9.0.dev2024032600
0.9.0.dev2024032600
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:410: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:415: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:410: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:415: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
Traceback (most recent call last):
  File "/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 446, in <module>
    main()
  File "/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 438, in main
    convert_and_save_hf(args)
  File "/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 375, in convert_and_save_hf
    execute(args.workers, [convert_and_save_rank] * world_size, args)
  File "/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 397, in execute
    f(args, rank)
  File "/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 362, in convert_and_save_rank
    llama = LLaMAForCausalLM.from_hugging_face(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/model.py", line 244, in from_hugging_face
    llama = convert.from_hugging_face(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 1192, in from_hugging_face
    weights = load_weights_from_hf(config=config,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 1296, in load_weights_from_hf
    weights = convert_hf_llama(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 964, in convert_hf_llama
    convert_layer(l)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 669, in convert_layer
    split_v = split_qkv_tp(qkv_weight, num_attention_heads, hidden_size,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 378, in split_qkv_tp
    v = v.reshape(3, n_hidden, n_hidden)
RuntimeError: shape '[3, 4096, 4096]' is invalid for input of size 25165824
```

**Comment by c3-moutasem** [comment]
Hi - Any update on this?

**Comment by byshiue** [comment]
What version of transformers should I use to load the model? Neither 4.38.2 nor 4.39.2 work on my side.

**Comment by c3-moutasem** [comment]
I don't explicitly install transformers. What error are you getting?

Here is a list of the dependencies that I explicitly install.

```
apt upgrade
apt update

apt-get update
apt-get install wget
apt-get install git-lfs
apt-get install git-all
apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev
pip3 install tensorrt_llm -U --extra-index-url https://pypi.nvidia.com/
pip3 install bitsandbytes
python3 -c "import tensorrt_llm"
```

And then, `pip install -r TensorRT-LLM/examples/llama/requirements.txt`

Let me freeze dependencies and send you that shortly.

**Comment by c3-moutasem** [comment]
It is Version: `4.38.2`

Here is the full list:
```
Package                  Version
------------------------ -------------------
absl-py                  2.1.0
accelerate               0.25.0
aiohttp                  3.9.3
aiosignal                1.3.1
async-timeout            4.0.3
attrs                    23.2.0
bitsandbytes             0.43.0
build                    1.2.1
certifi                  2024.2.2
charset-normalizer       3.3.2
click                    8.1.7
colored                  2.2.4
coloredlogs              15.0.1
cuda-python              12.4.0
datasets                 2.14.6
diffusers                0.15.0
dill                     0.3.7
evaluate                 0.4.1
filelock                 3.13.3
flatbuffers              24.3.25
frozenlist               1.4.1
fsspec                   2023.10.0
h5py                     3.10.0
huggingface-hub          0.22.2
humanfriendly            10.0
idna                     3.6
importlib_metadata       7.1.0
janus                    1.0.0
Jinja2                   3.1.3
joblib                   1.3.2
lark                     1.1.9
MarkupSafe               2.1.5
mpi4py                   3.1.5
mpmath                   1.3.0
multidict                6.0.5
multiprocess             0.70.15
networkx                 3.2.1
ninja                    1.11.1.1
nltk                     3.8.1
numpy                    1.26.4
nvidia-ammo              0.7.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.19.3
nvidia-nvjitlink-cu12    12.4.99
nvidia-nvtx-cu12         12.1.105
onnx                     1.16.0
onnx-graphsurgeon        0.3.25
onnxruntime              1.16.3
optimum                  1.18.0
packaging                24.0
pandas                   2.2.1
pillow                   10.3.0
pip                      22.0.2
polygraphy               0.49.0
protobuf                 5.26.1
psutil                   5.9.8
PuLP                     2.8.0
pyarrow                  15.0.2
pyarrow-hotfix           0.6
pynvml                   11.5.0
pyproject_hooks          1.0.0
python-dateutil          2.9.0.post0
pytz                     2024.1
PyYAML                   6.0.1
regex                    2023.12.25
requests                 2.31.0
responses                0.18.0
rouge-score              0.1.2
safetensors              0.4.2
scipy                    1.12.0
sentencepiece            0.1.99
setuptools               59.6.0
six                      1.16.0
StrEnum                  0.4.15
sympy                    1.12
tensorrt                 9.3.0.post12.dev1
tensorrt-bindings        9.3.0.post12.dev1
tensorrt-libs            9.3.0.post12.dev1
tensorrt-llm             0.9.0.dev2024040200
tokenizers               0.15.2
tomli                    2.0.1
torch                    2.2.2
tqdm                     4.66.2
transformers             4.38.2
triton                   2.2.0
typing_extensions        4.10.0
tzdata                   2024.1
urllib3                  2.2.1
wheel                    0.37.1
xxhash                   3.4.1
yarl                     1.9.4
zipp                     3.18.1
```

**Comment by c3-moutasem** [comment]
Any update on this? Thanks!

**Comment by byshiue** [comment]
Could you take a try on standard llama model?

**Comment by sli057** [comment]
I have encountered the same issue. I figured out the reason is that I used load_in_4bit = True in 🤗 Transformers for fine-tune. TensorRT-LLM does not support loading such 4-bit model.

**Comment by jayakommuru** [comment]
@sli057 @byshiue if TensorRT-LLM doesn't support 4-bit model, is there any other alternative for deploying 4 bit models ?
