### ISSUE TITLE
Installation problem via pip

### ISSUE THREAD

**Issue by thanaphatt1** [NVIDIA/TensorRT-LLM#1362]
### System Info

- CPU architecture: x86_64
- GPU NVIDIA A100
- Container: nvcr.io/nvidia/tritonserver:24.03-trtllm-python-py3

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

pip3 install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com

### Expected behavior

Installation completed

### actual behavior

    Collecting nvidia-cudnn-cu12 (from tensorrt_libs==9.3.0.post12.dev1->tensorrt==9.3.0.post12.dev1->tensorrt_llm)
      Downloading nvidia_cudnn_cu12-9.0.0.312.tar.gz (885 bytes)
      Installing build dependencies ... done
      Getting requirements to build wheel ... done
      Preparing metadata (pyproject.toml) ... error
      error: subprocess-exited-with-error
  
    × Preparing metadata (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [51 lines of output]
          File "/tmp/pip-build-env-32e6id1t/overlay/local/lib/python3.10/dist-packages/nvidia_stub/wheel.py", line 146, in download_wheel
            return download_manual(wheel_directory, distribution, version)
          File "/tmp/pip-build-env-32e6id1t/overlay/local/lib/python3.10/dist-packages/nvidia_stub/wheel.py", line 113, in download_manual
            raise RuntimeError(f"Didn't find wheel for {distribution} {version}")
        Traceback (most recent call last):
          File "/tmp/pip-build-env-32e6id1t/overlay/local/lib/python3.10/dist-packages/nvidia_stub/wheel.py", line 146, in download_wheel
            return download_manual(wheel_directory, distribution, version)
          File "/tmp/pip-build-env-32e6id1t/overlay/local/lib/python3.10/dist-packages/nvidia_stub/wheel.py", line 113, in download_manual
            raise RuntimeError(f"Didn't find wheel for {distribution} {version}")
        RuntimeError: Didn't find wheel for nvidia-cudnn-cu12 9.0.0.312

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-32e6id1t/overlay/local/lib/python3.10/dist-packages/nvidia_stub/buildapi.py", line 29, in build_wheel
          return download_wheel(pathlib.Path(wheel_directory), config_settings)
        File "/tmp/pip-build-env-32e6id1t/overlay/local/lib/python3.10/dist-packages/nvidia_stub/wheel.py", line 148, in download_wheel
          report_install_failure(distribution, version, exception_context)
        File "/tmp/pip-build-env-32e6id1t/overlay/local/lib/python3.10/dist-packages/nvidia_stub/error.py", line 63, in report_install_failure
          raise InstallFailedError(
      nvidia_stub.error.InstallFailedError:
      *******************************************************************************

      The installation of nvidia-cudnn-cu12 for version 9.0.0.312 failed.

      This is a special placeholder package which downloads a real wheel package
      from https://pypi.nvidia.com. If https://pypi.nvidia.com is not reachable, we
      cannot download the real wheel file to install.

      You might try installing this package via
      ```
      $ pip install --extra-index-url https://pypi.nvidia.com nvidia-cudnn-cu12
      ```

      Here is some debug information about your platform to include in any bug
      report:

      Python Version: CPython 3.10.12
      Operating System: Linux 5.4.0-169-generic
      CPU Architecture: x86_64
      Driver Version: 535.129
      CUDA Version: 12.3

      *******************************************************************************

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

### additional notes

Yesterday, I successfully installed it, but today I encountered an issue. Additionally, when attempting to install it via pip install from a requirements.txt file in the examples folder, I encountered the same problem.

**Comment by omarelshehy** [comment]
I have the same problem as well

**Comment by chzblych** [comment]
Can you try with the following WAR? A cuDNN update yesterday breaks the dependencies installation.

```
pip3 install "nvidia-cudnn-cu12~=8.9"
pip3 install -U --pre --extra-index-url https://pypi.nvidia.com/ tensorrt-llm
```

**Comment by thanaphatt1** [comment]
> Can you try with the following WAR? A cuDNN update yesterday breaks the dependencies installation.
> 
> ```
> pip3 install "nvidia-cudnn-cu12~=8.9"
> pip3 install -U --pre --extra-index-url https://pypi.nvidia.com/ tensorrt-llm
> ```

It's work for me, thank you.
