### ISSUE TITLE
benchmark for chatglm2-6b failed

### ISSUE THREAD

**Issue by shaunxiong** [NVIDIA/TensorRT-LLM#141]
I build chatglm2-6b engine with following command:

```bash
python3 build.py --model_dir=./pyTorchModel \
                 --dtype float16 \
                 --use_gpt_attention_plugin float16 \
                 --use_gemm_plugin float16
```

Then I tried to run benchmark:
```bash
python benchmark.py \
    -m chatglm2-6b \
    --mode plugin \
    --batch_size 4 \
    --engine_dir /code/tensorrt_llm/examples/chatglm2-6b/trtModel\
    --input_output_len 200,200
```

It returns this error:
```bash
[10/26/2023-11:28:17] [TRT] [E] 3: [executionContext.cpp::setInputShape::2252] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2252, condition: engineDims.nbDims == dims.nbDims )
Traceback (most recent call last):
  File "/code/tensorrt_llm/benchmarks/python/benchmark.py", line 325, in <module>
    main(args)
  File "/code/tensorrt_llm/benchmarks/python/benchmark.py", line 305, in main
    raise e
  File "/code/tensorrt_llm/benchmarks/python/benchmark.py", line 284, in main
    benchmarker.run(inputs, config)
  File "/code/tensorrt_llm/benchmarks/python/gpt_benchmark.py", line 503, in run
    self.decoder.decode(inputs[0], inputs[1], self.sampling_config)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 514, in wrapper
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1887, in decode
    return self.decode_regular(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1659, in decode_regular
    should_stop, next_step_buffer, tasks, context_lengths, host_context_lengths, attention_mask, logits = self.handle_per_step(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1430, in handle_per_step
    self.runtime._set_shape(context, ctx_shape)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 202, in _set_shape
    raise ValueError(
ValueError: Couldn't assign position_ids with shape torch.Size([4, 2, 200]), engine supports [min, opt, max] = [(1, 1), (2, 1), (4, 4096)]
```

Is this because the engine I built does not support the bs dimension? How should I solve this problem?
Any helpful suggestions would be greatly appreciated！

**Comment by juney-nvidia** [comment]
@shaunxiong it is mainly about that the shape info used in build phase is inconsistent with the Tensor shape set during the runtime phase. Have you tried with the [run.py](https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/examples/chatglm2-6b#3-run) provided in ChatGLM2-6b directory to see whether it works or not?

**Comment by juney-nvidia** [comment]
@shaunxiong also, pls refer [this](https://github.com/NVIDIA/TensorRT-LLM/issues/93#issuecomment-1782493460) and try with the latest main branch to see whether the issue still exist.

**Comment by byshiue** [comment]
Close this bug because the issue is inactivated. Feel free to ask here if you still have question/issue, we will reopen the issue.
