### ISSUE TITLE
Failed to compile TRT-LLM after building the docker image

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/TensorRT-LLM#1420]
GPU: A30
branch: main
commit id:118b3d7e7bab720d8ea9cd95338da60f7512c93a

I did this `sudo make -C docker build` to build docker image.

Then I create container and enter it and build trt-llm.
```
python3 ./scripts/build_wheel.py --cuda_architectures "80-real" --trt_root /usr/local/tensorrt
```

```
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich->bandit==1.7.7->-r requirements-dev.txt (line 17)) (0.1.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
gmake: Makefile: No such file or directory
gmake: *** No rule to make target 'Makefile'.  Stop.
Traceback (most recent call last):
  File "/data/TensorRT-LLM/./scripts/build_wheel.py", line 332, in <module>
    main(**vars(args))
  File "/data/TensorRT-LLM/./scripts/build_wheel.py", line 166, in main
    build_run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cmake --build . --config Release --parallel 144 --target tensorrt_llm nvinfer_plugin_tensorrt_llm th_common bindings ' returned non-zero exit status 2.
```
When I import tensorrt_llm in python, also error:
```
root@bms-airtrunk-d-g18v3-app-10-192-82-3:/data/TensorRT-LLM# python
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorrt_llm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/TensorRT-LLM/tensorrt_llm/__init__.py", line 47, in <module>
    from .hlapi.llm import LLM, ModelConfig
  File "/data/TensorRT-LLM/tensorrt_llm/hlapi/__init__.py", line 1, in <module>
    from .llm import (LLM, KvCacheConfig, ModelConfig, ParallelConfig,
  File "/data/TensorRT-LLM/tensorrt_llm/hlapi/llm.py", line 15, in <module>
    import tensorrt_llm.bindings as tllm
ModuleNotFoundError: No module named 'tensorrt_llm.bindings'
>>> exit()
```

**Comment by byshiue** [comment]
Could you try 
```bash
rm cpp/build -r
python3 ./scripts/build_wheel.py --cuda_architectures "80-real" --trt_root /usr/local/tensorrt --clean
```

**Comment by sleepwalker2017** [comment]
> Could you try
> 
> ```shell
> rm cpp/build -r
> python3 ./scripts/build_wheel.py --cuda_architectures "80-real" --trt_root /usr/local/tensorrt --clean
> ```

Thank you.  It works. I think you can add this to the build scripts.

**Comment by byshiue** [comment]
It is often because you have built the tensorrt_llm once. Now, you want to build again after updating the code.
