### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tensorrt_llm

### ISSUE THREAD

**Issue by cocoza4** [NVIDIA/TensorRT-LLM#1423]
### System Info

```
pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com tensorrt_llm
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
Collecting tensorrt_llm
  Downloading tensorrt-llm-0.8.0.tar.gz (6.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xhp_2ba_/tensorrt-llm_bc72dcf420244d768744f0a9e0f3ea12/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xhp_2ba_/tensorrt-llm_bc72dcf420244d768744f0a9e0f3ea12/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_yn28n60
         cwd: /tmp/pip-install-xhp_2ba_/tensorrt-llm_bc72dcf420244d768744f0a9e0f3ea12/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xhp_2ba_/tensorrt-llm_bc72dcf420244d768744f0a9e0f3ea12/setup.py", line 90, in <module>
        raise RuntimeError("Bad params")
    RuntimeError: Bad params
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/55/37/c2d83dfbe0205c14f913912a66eb19d5a5929e64f9b6aadf75e12729ac38/tensorrt-llm-0.8.0.tar.gz#sha256=8bd59bf59766bb16f81bd330ca38765a532a21a35d323fd33929c80a6ec53eaf (from https://pypi.org/simple/tensorrt-llm/) (requires-python:>=3.7, <4). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading tensorrt-llm-0.7.1.tar.gz (6.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xhp_2ba_/tensorrt-llm_512169f1ad404ff9ada97f443b157ac2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xhp_2ba_/tensorrt-llm_512169f1ad404ff9ada97f443b157ac2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ne95fc75
         cwd: /tmp/pip-install-xhp_2ba_/tensorrt-llm_512169f1ad404ff9ada97f443b157ac2/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xhp_2ba_/tensorrt-llm_512169f1ad404ff9ada97f443b157ac2/setup.py", line 90, in <module>
        raise RuntimeError("Bad params")
    RuntimeError: Bad params
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/0a/fa/489752fa8576bf06142cb225b0da93fc9550786c0ed027113d48de97123c/tensorrt-llm-0.7.1.tar.gz#sha256=10275e2585484f138b43576acddba42ebee073fbb1665fe0954032e421e26e08 (from https://pypi.org/simple/tensorrt-llm/) (requires-python:>=3.7, <4). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading tensorrt-llm-0.7.0.tar.gz (6.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xhp_2ba_/tensorrt-llm_4ed8bda3739f4494ba1d550cc67db6ea/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xhp_2ba_/tensorrt-llm_4ed8bda3739f4494ba1d550cc67db6ea/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-94ds7jaw
         cwd: /tmp/pip-install-xhp_2ba_/tensorrt-llm_4ed8bda3739f4494ba1d550cc67db6ea/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xhp_2ba_/tensorrt-llm_4ed8bda3739f4494ba1d550cc67db6ea/setup.py", line 90, in <module>
        raise RuntimeError("Bad params")
    RuntimeError: Bad params
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ad/cd/44fa06299fde491c8aaf637662fd70ed1f2900d0b8401132445cf1edbe84/tensorrt-llm-0.7.0.tar.gz#sha256=5ce1182c28f60715a2a17b04c30fa033690893e6067ff5676c96b551ac66ae39 (from https://pypi.org/simple/tensorrt-llm/) (requires-python:>=3.7, <4). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading tensorrt-llm-0.6.1.tar.gz (6.8 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xhp_2ba_/tensorrt-llm_c2807f9ff8c742b79b007d2e710df3e2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xhp_2ba_/tensorrt-llm_c2807f9ff8c742b79b007d2e710df3e2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-zbijia8o
         cwd: /tmp/pip-install-xhp_2ba_/tensorrt-llm_c2807f9ff8c742b79b007d2e710df3e2/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xhp_2ba_/tensorrt-llm_c2807f9ff8c742b79b007d2e710df3e2/setup.py", line 137, in <module>
        raise RuntimeError(open("ERROR.txt", "r").read())
    RuntimeError:
    ###########################################################################################
    The package you are trying to install is only a placeholder project on PyPI.org repository.
    This package is hosted on NVIDIA Python Package Index.

    This package can be installed as:
    ```
    $ pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com tensorrt-llm
    ```
    ###########################################################################################

    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/87/c0/af127255e9db8871e60d5d7fee6f75db5b8656057200393eadae6c3859e5/tensorrt-llm-0.6.1.tar.gz#sha256=d6fd5d32d131c3415991648bd88175417119cde48b9fea167e29d3447c7023a8 (from https://pypi.org/simple/tensorrt-llm/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading tensorrt-llm-0.5.0.post1.tar.gz (6.8 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xhp_2ba_/tensorrt-llm_c4a44e3b4a9944c4a34066eacd047d87/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xhp_2ba_/tensorrt-llm_c4a44e3b4a9944c4a34066eacd047d87/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-lwy3kxwz
         cwd: /tmp/pip-install-xhp_2ba_/tensorrt-llm_c4a44e3b4a9944c4a34066eacd047d87/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xhp_2ba_/tensorrt-llm_c4a44e3b4a9944c4a34066eacd047d87/setup.py", line 137, in <module>
        raise RuntimeError(open("ERROR.txt", "r").read())
    RuntimeError:
    ###########################################################################################
    The package you are trying to install is only a placeholder project on PyPI.org repository.
    This package is hosted on NVIDIA Python Package Index.

    This package can be installed as:
    ```
    $ pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com tensorrt-llm
    ```
    ###########################################################################################

    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/4b/a7/596e7529de83ff7462e0bd103f41c8d252db8162e4a99112779e98acbd1e/tensorrt-llm-0.5.0.post1.tar.gz#sha256=8af038b8dd4976254bd2b4fc65ede501ed42263479cfffd5e3fb14047084e323 (from https://pypi.org/simple/tensorrt-llm/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading tensorrt-llm-0.5.0.tar.gz (6.8 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xhp_2ba_/tensorrt-llm_9d5aa3be2e6c4f808b6c1a38e5e9961b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xhp_2ba_/tensorrt-llm_9d5aa3be2e6c4f808b6c1a38e5e9961b/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-yir3a61j
         cwd: /tmp/pip-install-xhp_2ba_/tensorrt-llm_9d5aa3be2e6c4f808b6c1a38e5e9961b/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xhp_2ba_/tensorrt-llm_9d5aa3be2e6c4f808b6c1a38e5e9961b/setup.py", line 137, in <module>
        raise RuntimeError(open("ERROR.txt", "r").read())
    RuntimeError:
    ###########################################################################################
    The package you are trying to install is only a placeholder project on PyPI.org repository.
    This package is hosted on NVIDIA Python Package Index.

    This package can be installed as:
    ```
    $ pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com tensorrt-llm
    ```
    ###########################################################################################

    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/65/d2/73b872b9e7fac4ea0bee7efad1ea3c26c8c104ff7636ce2a62822b471a6e/tensorrt-llm-0.5.0.tar.gz#sha256=a36ece0e255a824d47304964dbe8b710ea558537df081ed9f29b6e27abdefec7 (from https://pypi.org/simple/tensorrt-llm/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement tensorrt_llm
ERROR: No matching distribution found for tensorrt_llm
```

CUDA 11.8

```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com tensorrt_llm

### Expected behavior

I expected the library to be installed successfully

### actual behavior

error mentioned above

### additional notes

N/A

**Comment by byshiue** [comment]
You could run `pip install requirements.txt` first. But note that the root reason might be because you use CUDA 11.8. TensorRT-LLM is only verified on CUDA 12.
