### ISSUE TITLE
"NotImplementedError: Cannot copy out of meta tensor; no data!" for convert checkpoint of Mixtral

### ISSUE THREAD

**Issue by WhatGhost** [NVIDIA/TensorRT-LLM#1440]
I encountered an error while converting the weights of Mixtral as described in the documentation of mixtral
https://github.com/NVIDIA/TensorRT-LLM/tree/655524dd82648edea35591ff146da8be4dcf2e02/examples/mixtral

i use the llama's convert_checkpoint.py to convert weight from [mistralai/Mixtral-8x7B-v0.1](https://huggingface.co/mistralai/Mixtral-8x7B-v0.1). But i met an error. **NotImplementedError: Cannot copy out of meta tensor; no data!**

```
root@188d509b8775:/code/tensorrt_llm/v0.9/TensorRT-LLM/examples/llama# bash run.sh
[TensorRT-LLM] TensorRT-LLM version: 0.9.0.dev2024040200
0.9.0.dev2024040200
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19/19 [00:31<00:00,  1.64s/it]
[04/11/2024-05:58:24] Some parameters are on the meta device device because they were offloaded to the cpu.
Traceback (most recent call last):
  File "/code/tensorrt_llm/v0.9/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 446, in <module>
    main()
  File "/code/tensorrt_llm/v0.9/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 438, in main
    convert_and_save_hf(args)
  File "/code/tensorrt_llm/v0.9/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 375, in convert_and_save_hf
    execute(args.workers, [convert_and_save_rank] * world_size, args)
  File "/code/tensorrt_llm/v0.9/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 397, in execute
    f(args, rank)
  File "/code/tensorrt_llm/v0.9/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 362, in convert_and_save_rank
    llama = LLaMAForCausalLM.from_hugging_face(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/model.py", line 244, in from_hugging_face
    llama = convert.from_hugging_face(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 1192, in from_hugging_face
    weights = load_weights_from_hf(config=config,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 1296, in load_weights_from_hf
    weights = convert_hf_llama(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 964, in convert_hf_llama
    convert_layer(l)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 646, in convert_layer
    q_weight = get_weight(model_params, prefix + 'self_attn.q_proj', dtype)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 401, in get_weight
    return config[prefix + '.weight'].detach().cpu()
NotImplementedError: Cannot copy out of meta tensor; no data!
```

my scripts is
```
python convert_checkpoint.py --model_dir /code/tensorrt_llm/v0.9/TensorRT-LLM/model/moe/Mixtral-8x7B-v0.1 \
                             --output_dir /code/tensorrt_llm/v0.9/TensorRT-LLM/model/moe/tllm_checkpoint_mixtral_wint8 \
                             --dtype float16 \
                             --use_weight_only \
                             --weight_only_precision int8
```

Is there any configuration that I am missing，or any config needs to be changed.
How can I fix this error.

looking forward to a reply!Thanks!

**Comment by OrbitalsGit** [comment]
please i have same issues on llama2 7B . i need help

**Comment by djns99** [comment]
Hi @WhatGhost @OrbitalsGit could you provide details about what GPUs you are using? This usually occurs when the GPU has insufficient memory to load the model.

**Comment by WhatGhost** [comment]
@djns99 Thanks for your reply . 
The GPU i used is NVIDIA A100 with 80G memory. 
If there is no enough memory for load model,how can i solve this problem.
Thanks!

**Comment by djns99** [comment]
@WhatGhost since it needs to load the FP16 weights in order to do the conversion you can't load on one GPU. 
There is a `--load_model_on_cpu` option but I've only had limited success with this so YMMV.

**Comment by WhatGhost** [comment]
@djns99 Thanks, i change the device_map from 'aoto' to 'cpu', it also works.
Thanks very much!

**Comment by chilljudaoren** [comment]
> [@djns99](https://github.com/djns99) Thanks, i change the device_map from 'aoto' to 'cpu', it also works. Thanks very much!

When I changed auto to 'cpu', I still reported the previous error

kwargs = {"device_map": "cpu", "torch_dtype": torch.bfloat16}

How can I solve it?

**Comment by chilljudaoren** [comment]
> Hi [@WhatGhost](https://github.com/WhatGhost) [@OrbitalsGit](https://github.com/OrbitalsGit) could you provide details about what GPUs you are using? This usually occurs when the GPU has insufficient memory to load the model.

When I changed auto to 'cpu', I still reported the previous error

kwargs = {"device_map": "cpu", "torch_dtype": torch.bfloat16}

How can I solve it?

**Comment by LukeLIN-web** [comment]
Sam problem  `NotImplementedError: Cannot copy out of meta tensor; no data!` 

My case is 
```
 print(linear0.weight[:5, :5])
tensor(..., device='meta', size=(5, 5), dtype=torch.bfloat16,
       grad_fn=<SliceBackward0>)
```

**Comment by chilljudaoren** [comment]
I think you should remove "device='meta'".

LukeLin ***@***.***> 于2025年2月28日周五 10:32写道：
