### ISSUE TITLE
fail to build llava-v1.6-vicuna-13b-hf

### ISSUE THREAD

**Issue by gloritygithub11** [NVIDIA/TensorRT-LLM#1441]
### System Info

TensorRT-LLM commit: 118b3d7e7bab720d8ea9cd95338da60f7512c93a
Ubuntu 20.04
python 3.10
A100
TensorRT: install by docker/common/install_tensorrt.sh
CUDA 12.4

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction
```

#export MODEL_NAME="llava-v1.6-vicuna-13b-hf"
#git clone https://huggingface.co/llava-hf/${MODEL_NAME} tmp/hf_models/${MODEL_NAME}

cd example/llama

# instead of clone code, use a cached model dir from hugging face
# model_dir contains the cached model from huggingface
python convert_checkpoint.py \
    --model_dir /home/ateam/.cache/huggingface/hub/models--llava-hf--llava-v1.6-vicuna-13b-hf/snapshots/c892f3e561c2947fafd313014fd68109b2f64517 \
    --output_dir tmp/trt_models/llava-v1.6-vicuna-13b-hf/fp16/1-gpu \
    --dtype float16
```

### Expected behavior

convert success

### actual behavior

```
[TensorRT-LLM] TensorRT-LLM version: 0.9.0.dev2024040900
0.9.0.dev2024040900
Traceback (most recent call last):
  File "/home/ateam/xu.xiaodong/venv_llama/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1128, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/home/ateam/xu.xiaodong/venv_llama/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 825, in __getitem__
    raise KeyError(key)
KeyError: 'llava_next'
```

### additional notes
I tried to upgrade pip install transformers==4.39.3, get error:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorrt-llm 0.9.0.dev2024040200 requires transformers==4.38.2, but you have transformers 4.39.3 which is incompatible.
Successfully installed transformers-4.39.3
```

run above script will get another error:

```
[TensorRT-LLM] TensorRT-LLM version: 0.9.0.dev2024040200
0.9.0.dev2024040200
Traceback (most recent call last):
  File "/home/ateam/xu.xiaodong/tensorrt-llm/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 446, in <module>
    main()
  File "/home/ateam/xu.xiaodong/tensorrt-llm/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 438, in main
    convert_and_save_hf(args)
  File "/home/ateam/xu.xiaodong/tensorrt-llm/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 355, in convert_and_save_hf
    hf_model = preload_model(model_dir) if not args.load_by_shard else None
  File "/home/ateam/xu.xiaodong/tensorrt-llm/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 316, in preload_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/home/ateam/xu.xiaodong/venv_llama/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers.models.llava_next.configuration_llava_next.LlavaNextConfig'> for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, LlamaConfig, CodeGenConfig, CohereConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, FalconConfig, FuyuConfig, GemmaConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MambaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MistralConfig, MixtralConfig, MptConfig, MusicgenConfig, MusicgenMelodyConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PersimmonConfig, PhiConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, Qwen2Config, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, StableLmConfig, Starcoder2Config, TransfoXLConfig, TrOCRConfig, WhisperConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.
```

If I run build without convert_checkpoint(the format already safetensors):
```
trtllm-build \
>     --checkpoint_dir /home/ateam/.cache/huggingface/hub/models--llava-hf--llava-v1.6-vicuna-13b-hf/snapshots/c892f3e561c2947fafd313014fd68109b2f64517 \
>     --output_dir trt_engines/llava-v1.6-vicuna-13b-hf/fp16/1-gpu \
>     --gemm_plugin float16 \
>     --use_fused_mlp \
>     --max_batch_size 1 \
>     --max_input_len 2048 \
>     --max_output_len 512 \
>     --max_multimodal_len 576
```

will get error:
```

Traceback (most recent call last):
  File "/home/ateam/xu.xiaodong/venv_llama/bin/trtllm-build", line 8, in <module>
    sys.exit(main())
  File "/home/ateam/xu.xiaodong/venv_llama/lib/python3.10/site-packages/tensorrt_llm/commands/build.py", line 441, in main
    parallel_build(source, build_config, args.output_dir, workers,
  File "/home/ateam/xu.xiaodong/venv_llama/lib/python3.10/site-packages/tensorrt_llm/commands/build.py", line 314, in parallel_build
    model_config = PretrainedConfig.from_json_file(
  File "/home/ateam/xu.xiaodong/venv_llama/lib/python3.10/site-packages/tensorrt_llm/models/modeling_utils.py", line 232, in from_json_file
    return PretrainedConfig.from_dict(config)
  File "/home/ateam/xu.xiaodong/venv_llama/lib/python3.10/site-packages/tensorrt_llm/models/modeling_utils.py", line 168, in from_dict
    architecture = config.pop('architecture')
KeyError: 'architecture'
```

**Comment by gloritygithub11** [comment]
I can run success on llava-1.5-13b-hf.

**Comment by Iven2132** [comment]
@gloritygithub11 I'm looking for the same - How did you run llava-1.5-13b-hf on TensorRT? Can you please help me out? Do you have any notebook for that?

**Comment by gloritygithub11** [comment]
I use script as follows:

export MODEL_NAME="llava-1.5-13b-hf"

git clone https://huggingface.co/llava-hf/${MODEL_NAME} tmp/hf_models/${MODEL_NAME}
    
python ../llama/convert_checkpoint.py<http://convert_checkpoint.py> \
    --model_dir tmp/hf_models/${MODEL_NAME} \
    --output_dir tmp/trt_models/${MODEL_NAME}/fp16/1-gpu \
    --dtype float16

trtllm-build \
    --checkpoint_dir tmp/trt_models/${MODEL_NAME}/fp16/1-gpu \
    --output_dir trt_engines/${MODEL_NAME}/fp16/1-gpu \
    --gemm_plugin float16 \
    --use_fused_mlp \
    --max_batch_size 1 \
    --max_input_len 2048 \
    --max_output_len 512 \
    --max_multimodal_len 576 # 1 (max_batch_size) * 576 (num_visual_features)
    
python ../multimodal/build_visual_engine.py --model_path tmp/hf_models/${MODEL_NAME} --model_type llava

**Comment by Iven2132** [comment]
@

> I use script as follows: export MODEL_NAME="llava-1.5-13b-hf" git clone https://huggingface.co/llava-hf/${MODEL_NAME} tmp/hf_models/${MODEL_NAME}      python ../llama/convert_checkpoint.py<http://convert_checkpoint.py> \     --model_dir tmp/hf_models/${MODEL_NAME} \     --output_dir tmp/trt_models/${MODEL_NAME}/fp16/1-gpu \     --dtype float16 trtllm-build \     --checkpoint_dir tmp/trt_models/${MODEL_NAME}/fp16/1-gpu \     --output_dir trt_engines/${MODEL_NAME}/fp16/1-gpu \     --gemm_plugin float16 \     --use_fused_mlp \     --max_batch_size 1 \     --max_input_len 2048 \     --max_output_len 512 \     --max_multimodal_len 576 # 1 (max_batch_size) * 576 (num_visual_features)      python ../multimodal/build_visual_engine.py --model_path tmp/hf_models/${MODEL_NAME} --model_type llava

How did you install TensorRT and did all the setup?

**Comment by gloritygithub11** [comment]
there is a script [install_tensorrt.sh](https://github.com/NVIDIA/TensorRT-LLM/blob/main/docker/common/install_tensorrt.sh)

**Comment by HarperGG** [comment]
I also encountered the same problem
```
export MODEL_NAME="llava-v1.6-34b-hf"
 python ../llama/convert_checkpoint.py     --model_dir /workspace/ComfyUI/models/llava/${MODEL_NAME}     --output_dir tmp/trt_models/${MODEL_NAME}/fp16/2-gpu     --dtype float16 --tp_size 2
 ```
