### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorrt_llm.bindings'

### ISSUE THREAD

**Issue by FightingMan** [NVIDIA/TensorRT-LLM#1549]
### System Info

CPU:AMD EPYC 7K83 64-Core Processor
GPU:A10
OS:linux

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

follow the official guide:https://nvidia.github.io/TensorRT-LLM/installation/linux.html

### Expected behavior

OK

### actual behavior

root@a2968a9db901:/TensorRT-LLM# python3 -c "import tensorrt_llm"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/TensorRT-LLM/tensorrt_llm/__init__.py", line 32, in <module>
    import tensorrt_llm.functional as functional
  File "/TensorRT-LLM/tensorrt_llm/functional.py", line 29, in <module>
    from . import graph_rewriting as gw
  File "/TensorRT-LLM/tensorrt_llm/graph_rewriting.py", line 12, in <module>
    from .network import Network
  File "/TensorRT-LLM/tensorrt_llm/network.py", line 26, in <module>
    from tensorrt_llm.module import Module
  File "/TensorRT-LLM/tensorrt_llm/module.py", line 17, in <module>
    from ._common import default_net
  File "/TensorRT-LLM/tensorrt_llm/_common.py", line 30, in <module>
    from ._utils import str_dtype_to_trt
  File "/TensorRT-LLM/tensorrt_llm/_utils.py", line 32, in <module>
    from tensorrt_llm.bindings.BuildInfo import ENABLE_MULTI_DEVICE
ModuleNotFoundError: No module named 'tensorrt_llm.bindings'

### additional notes

1

**Comment by tyfeld** [comment]
I encountered the same issue, have you resolved it?

**Comment by dh12306** [comment]
me too， it seems that  the latest tensorrt_llm didn't work well

**Comment by avinashahuja** [comment]
I'm seeing the same issue

**Comment by WGS-note** [comment]
@FightingMan @avinashahuja @dh12306 @tyfeld @pathorn 

Thanks for the reply, has it been resolved yet? I'm experiencing the same problem.
