### ISSUE TITLE
Error when packaging docker to compile TensorRT-LLM， tensorrt_llm/CMakeFiles/tensorrt_llm.dir/rule] Error 2

### ISSUE THREAD

**Issue by tms2003** [NVIDIA/TensorRT-LLM#165]
Error when packaging docker to compile TensorRT-LLM:
```
#25 2528.0 [98%] Built target kernels_src
#25 2528.0 make[1]: *** [CMakeFiles/Makefile2:684: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/rule] Error 2
#25 2528.0 make: *** [Makefile:179: tensorrt_llm] Error 2
#25 2528.0 Traceback (most recent call last):
#25 2528.0 File "scripts/build_wheel.py", line 248, in <module>
#25 2528.0 main(**vars(args))
#25 2528.0 File "scripts/build_wheel.py", line 152, in main
#25 2528.0 build_run(
#25 2528.0 File "/usr/lib/python3.8/subprocess.py", line 516, in run
#25 2528.0 raise CalledProcessError(retcode, process.args,
#25 2528.0 subprocess.CalledProcessError: Command 'cmake --build . --config Release --parallel 48 --target tensorrt_llm tensorrt_llm_static nvinfer_plugin_tensorrt_llm th_common ' returned non-zero exit status 2.
------
executor failed running [/bin/bash -c python3 scripts/build_wheel.py ${BUILD_WHEEL_ARGS}]: exit code: 1
make: *** [Makefile:47: release_build] Error 1

```

how to change it ?

**Comment by byshiue** [comment]
Have you run
```
git-lfs pull
```

Can you share your end to end building scripts and the full error log?

**Comment by byshiue** [comment]
Close this bug because the issue is inactivated. Feel free to ask here if you still have question/issue, we will reopen the issue.
