### ISSUE TITLE
 Import of the `bindings` module failed after fresh install

### ISSUE THREAD

**Issue by Ciclarion** [NVIDIA/TensorRT-LLM#1656]
### System Info

-CPU : x86_64
-GPU : RTX 3090
-TensorRT_LLM 0.9.0
-OS : Windows 10

### Who can help?

@byshiue 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1)Fresh install of everything using the powershell script from the installation guide. 
2)pip install tensorrt_llm --extra-index-url https://pypi.nvidia.com --extra-index-url https://download.pytorch.org/whl/cu121 
3)python -c "import tensorrt_llm; print(tensorrt_llm._utils.trt_version())"

### Expected behavior

Tesorrt_LLM working fine

### actual behavior

Traceback (most recent call last):
  File "C:\Users\cedri\Desktop\Concours Nvidia\venv\lib\site-packages\tensorrt_llm\__init__.py", line 39, in <module>
    import tensorrt_llm.bindings  # NOQA
ImportError: DLL load failed while importing bindings: Le module spécifié est introuvable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\cedri\Desktop\Concours Nvidia\venv\lib\site-packages\tensorrt_llm\__init__.py", line 41, in <module>
    raise ImportError(
ImportError: Import of the `bindings` module failed. Please check the package integrity. If you are attempting to use the pip development mode (editable installation), please execute `build_wheels.py` first, and then run `pip install -e .`

### additional notes

i have also tried to use the version 0.8.0 of Tesnorrt_llm but got the same error. Note that i've no error message during any phases of the installation

**Comment by Ciclarion** [comment]
Went on Ubuntu and installed without trouble ! Guess the problem come from windows
