### ISSUE TITLE
tensorrt_llm  ImportError: libmpi.so.12: cannot open shared object file

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/TensorRT-LLM#167]
I build the docker image using `make -C docker release_build`
and then I enter the container, but tensorrt_llm import failed.

```shell
>>> import tensorrt_llm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/lib/python3.9/site-packages/tensorrt_llm/__init__.py", line 15, in <module>
    import tensorrt_llm.functional as functional
  File "/root/anaconda3/lib/python3.9/site-packages/tensorrt_llm/functional.py", line 25, in <module>
    from . import graph_rewriting as gw
  File "/root/anaconda3/lib/python3.9/site-packages/tensorrt_llm/graph_rewriting.py", line 10, in <module>
    from .logger import logger
  File "/root/anaconda3/lib/python3.9/site-packages/tensorrt_llm/logger.py", line 19, in <module>
    from mpi4py import MPI
ImportError: libmpi.so.12: cannot open shared object file: No such file or directory
```

**Comment by BasicCoder** [comment]
Try these commands, before you import tensorrt_llm.
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/mpi/lib
export OPAL_PREFIX=/opt/hpcx/ompi
```

**Comment by juney-nvidia** [comment]
@sleepwalker2017 Usually you don't need to explicitly configure the LD_LIBRARTY_PATH after entering into the TensorRT-LLM docker. 
On which branch did you hit with this error? And what command did you use to start the docker? 

June

**Comment by sleepwalker2017** [comment]
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/mpi/lib
> export OPAL_PREFIX=/opt/hpcx/ompi

I tried this, doesn't work.

Actually I can't find this file in /usr/ or /opt/ directory.

**Comment by sleepwalker2017** [comment]
> @sleepwalker2017 Usually you don't need to explicitly configure the LD_LIBRARTY_PATH after entering into the TensorRT-LLM docker. On which branch did you hit with this error? And what command did you use to start the docker?
> 
> June

Here is the branch and commit id.
```
commit 7295ce25aa157548afa6b2d2cea635c33d0cce5c (HEAD -> release/0.5.0, origin/release/0.5.0, origin/HEAD)
Author: Yi Wang <yi.wang.2005@gmail.com>
Date:   Thu Oct 19 19:13:20 2023 -0700

    Fix two deadlinks in README.md (#21)

    * Fix deadlines in README.md

    * Update README.md
```

Here is the command I start docker:
```
sudo docker run -it --gpus all --network host  --name trt-llm-dev  --shm-size=2g \
        -v /data/:/data/       -v /home/toc/SDE/docker_files:/root/ \
        tensorrt_llm/release:latest /bin/bash

sudo docker exec -it trt-llm-dev /bin/bash
```

**Comment by sleepwalker2017** [comment]
> ```shell
> libmpi.so
> ```

In my docker container, I only find this file.
```
root@bms-airtrunk-b-g1v2-app-10-169-60-215:/opt# ls ./hpcx/ompi/lib/libmpi.so
libmpi.so          libmpi.so.40       libmpi.so.40.30.5
```
No libmpi.so.12 is found. Why does it depend on this?  Seems it's a version conflict.

**Comment by sleepwalker2017** [comment]
How I solved this: 

For me, the docker image is ok on A30 machine, but when I use it on V100, the mpi4py complains error.

Finally I recompiled the package according to this:

`https://mpi4py.readthedocs.io/en/stable/install.html#using-distutils`

**Comment by byshiue** [comment]
Close this bug because the issue is resolved. Feel free to ask here if you still have question/issue, we will reopen the issue.
