### ISSUE TITLE
Failed to convert Llama 8B weight in per-tensor SQ  mode

### ISSUE THREAD

**Issue by WDONG66** [NVIDIA/TensorRT-LLM#1686]
### System Info

trt_llm 0.11.0.dev2024052100
trt 10.0.1
device A800
coda for Tensorrt_llm: latest version in main branch

### Who can help?

@by

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

python3 convert_checkpoint.py --model_dir ${model_dir} --output_dir ${output_dir} --dtype float16 --use_smooth_quant --tp_size 1

### Expected behavior

convert checkpoint and build successfully

### actual behavior

[TensorRT-LLM] TensorRT-LLM version: 0.11.0.dev2024052100
0.11.0.dev2024052100
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:10<00:00,  2.66s/it]
/usr/local/lib/python3.10/dist-packages/datasets/load.py:929: FutureWarning: The repository for cnn_dailymail contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at /workspace/ccdv/cnn_dailymail/cnn_dailymail.py
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
calibrating model: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:59<00:00,  8.54it/s]
Traceback (most recent call last):
  File "/workspace/trt_llm/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 458, in <module>
    main()
  File "/workspace/trt_llm/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 450, in main
    convert_and_save_hf(args)
  File "/workspace/trt_llm/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 353, in convert_and_save_hf
    LLaMAForCausalLM.quantize(args.model_dir,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/model.py", line 405, in quantize
    convert.quantize(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 1395, in quantize
    weights = load_weights_from_hf(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 1437, in load_weights_from_hf
    weights = convert_hf_llama(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 1088, in convert_hf_llama
    convert_layer(l)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 724, in convert_layer
    get_tllm_linear_sq_weight(int8_weights,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 609, in get_tllm_linear_sq_weight
    results[prefix + 'per_channel_scale'] = torch.Tensor([
ValueError: only one element tensors can be converted to Python scalars

### additional notes

None

**Comment by nv-guomingz** [comment]
Thanks @WDONG66 for reporint this issue, we've fixed it internally. The next weekly release will contains the  below patch.

<img width="660" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/137257613/b322f6d2-d3c0-4146-8577-76e556b89bd1">

**Comment by WDONG66** [comment]
Thanks~
