### ISSUE TITLE
Cannot run falcon_180B benchmark using fp8

### ISSUE THREAD

**Issue by tohaowu** [NVIDIA/TensorRT-LLM#170]
Description:

I am trying to run the falcon_180B model using TensorRT-LLM with fp8 precision, but I am getting the following error:

```
#OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 mpirun -n 8 python benchmark.py -m falcon_180b --mode plugin     --batch_size "64"     --input_output_len "2048,128" --max_input_len=2048 --max_output_len=2048 --enable_fp8 --dtype float16

Traceback (most recent call last):
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/benchmark.py", line 322, in <module>
    main(args)
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/benchmark.py", line 219, in main
    benchmarker = GPTBenchmark(
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/gpt_benchmark.py", line 142, in __init__
    engine_buffer = self.build()
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/gpt_benchmark.py", line 370, in build
    tensorrt_llm_model = fp8_quantize(tensorrt_llm_model,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/quantized/quant.py", line 371, in fp8_quantize
    return _default_fp8_quantize(model, quant_mode, quant_scales)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/quantized/quant.py", line 354, in _default_fp8_quantize
    assert model.quant_mode == quant_mode, "Quant setting not consistent with model init setting"
AssertionError: Quant setting not consistent with model init setting
Traceback (most recent call last):
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/benchmark.py", line 322, in <module>
    main(args)
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/benchmark.py", line 219, in main
    benchmarker = GPTBenchmark(
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/gpt_benchmark.py", line 142, in __init__
    engine_buffer = self.build()
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/gpt_benchmark.py", line 370, in build
    tensorrt_llm_model = fp8_quantize(tensorrt_llm_model,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/quantized/quant.py", line 371, in fp8_quantize
    return _default_fp8_quantize(model, quant_mode, quant_scales)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/quantized/quant.py", line 354, in _default_fp8_quantize
    assert model.quant_mode == quant_mode, "Quant setting not consistent with model init setting"
AssertionError: Quant setting not consistent with model init setting
Traceback (most recent call last):
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/benchmark.py", line 322, in <module>
    main(args)
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/benchmark.py", line 219, in main
    benchmarker = GPTBenchmark(
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/gpt_benchmark.py", line 142, in __init__
    engine_buffer = self.build()
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/gpt_benchmark.py", line 370, in build
    tensorrt_llm_model = fp8_quantize(tensorrt_llm_model,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/quantized/quant.py", line 371, in fp8_quantize
    return _default_fp8_quantize(model, quant_mode, quant_scales)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/quantized/quant.py", line 354, in _default_fp8_quantize
    assert model.quant_mode == quant_mode, "Quant setting not consistent with model init setting"
AssertionError: Quant setting not consistent with model init setting
Traceback (most recent call last):
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/benchmark.py", line 322, in <module>
    main(args)
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/benchmark.py", line 219, in main
    benchmarker = GPTBenchmark(
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/gpt_benchmark.py", line 142, in __init__
    engine_buffer = self.build()
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/gpt_benchmark.py", line 370, in build
    tensorrt_llm_model = fp8_quantize(tensorrt_llm_model,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/quantized/quant.py", line 371, in fp8_quantize
    return _default_fp8_quantize(model, quant_mode, quant_scales)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/quantized/quant.py", line 354, in _default_fp8_quantize
    assert model.quant_mode == quant_mode, "Quant setting not consistent with model init setting"
AssertionError: Quant setting not consistent with model init setting
Traceback (most recent call last):
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/benchmark.py", line 322, in <module>
    main(args)
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/benchmark.py", line 219, in main
    benchmarker = GPTBenchmark(
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/gpt_benchmark.py", line 142, in __init__
    engine_buffer = self.build()
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/gpt_benchmark.py", line 370, in build
    tensorrt_llm_model = fp8_quantize(tensorrt_llm_model,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/quantized/quant.py", line 371, in fp8_quantize
    return _default_fp8_quantize(model, quant_mode, quant_scales)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/quantized/quant.py", line 354, in _default_fp8_quantize
    assert model.quant_mode == quant_mode, "Quant setting not consistent with model init setting"
AssertionError: Quant setting not consistent with model init setting
Traceback (most recent call last):
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/benchmark.py", line 322, in <module>
    main(args)
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/benchmark.py", line 219, in main
    benchmarker = GPTBenchmark(
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/gpt_benchmark.py", line 142, in __init__
    engine_buffer = self.build()
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/gpt_benchmark.py", line 370, in build
    tensorrt_llm_model = fp8_quantize(tensorrt_llm_model,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/quantized/quant.py", line 371, in fp8_quantize
    return _default_fp8_quantize(model, quant_mode, quant_scales)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/quantized/quant.py", line 354, in _default_fp8_quantize
    assert model.quant_mode == quant_mode, "Quant setting not consistent with model init setting"
AssertionError: Quant setting not consistent with model init setting
Traceback (most recent call last):
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/benchmark.py", line 322, in <module>
    main(args)
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/benchmark.py", line 219, in main
    benchmarker = GPTBenchmark(
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/gpt_benchmark.py", line 142, in __init__
    engine_buffer = self.build()
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/gpt_benchmark.py", line 370, in build
    tensorrt_llm_model = fp8_quantize(tensorrt_llm_model,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/quantized/quant.py", line 371, in fp8_quantize
    return _default_fp8_quantize(model, quant_mode, quant_scales)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/quantized/quant.py", line 354, in _default_fp8_quantize
    assert model.quant_mode == quant_mode, "Quant setting not consistent with model init setting"
AssertionError: Quant setting not consistent with model init setting
Traceback (most recent call last):
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/benchmark.py", line 322, in <module>
    main(args)
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/benchmark.py", line 219, in main
    benchmarker = GPTBenchmark(
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/gpt_benchmark.py", line 142, in __init__
    engine_buffer = self.build()
  File "/app/tensorrt_llm/TensorRT-LLM/benchmarks/python/gpt_benchmark.py", line 370, in build
    tensorrt_llm_model = fp8_quantize(tensorrt_llm_model,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/quantized/quant.py", line 371, in fp8_quantize
    return _default_fp8_quantize(model, quant_mode, quant_scales)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/quantized/quant.py", line 354, in _default_fp8_quantize
    assert model.quant_mode == quant_mode, "Quant setting not consistent with model init setting"
AssertionError: Quant setting not consistent with model init setting
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[36290,1],6]
  Exit code:    1
--------------------------------------------------------------------------
```

Environment:

- TensorRT-LLM version: release/0.5.0
- GPU: 4 H100
- CUDA version: 12.2
- Driver version: 535.104.12
- Python version: 3.10.12

Please investigate this issue and provide a solution. Thank you.

**Comment by jdemouth-nvidia** [comment]
Hi @tohaowu , thanks for reporting the issue. Can you share the `build.py` command that you're using, please? Also, does it also fail with `run.py`? As soon as we have the command-lines, we will see if we can reproduce the issue. Thanks, Julien

**Comment by tohaowu** [comment]
The code path is https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/benchmarks/python/benchmark.py.
The command to reproduce is ``OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 mpirun -n 8 python benchmark.py -m falcon_180b --mode plugin     --batch_size "64"     --input_output_len "2048,128" --max_input_len=2048 --enable_fp8``

**Comment by jaedeok-nvidia** [comment]
Thank @tohaowu for reporting this bug. To fix it, we need to add `quant_mode=self.quant_mode` in constructing a falcon model [here](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/benchmarks/python/gpt_benchmark.py#L355). Like this,
```python
            tensorrt_llm_model = tensorrt_llm.models.FalconForCausalLM(
                num_layers=self.num_layers,
                num_heads=self.num_heads,
                num_kv_heads=self.num_kv_heads,
                hidden_size=self.hidden_size,
                vocab_size=self.vocab_size,
                max_position_embeddings=self.n_positions,
                dtype=kv_dtype,
                bias=self.bias,
                quant_mode=self.quant_mode,    # <-- this option.
                use_alibi=self.use_alibi,
                new_decoder_architecture=self.new_decoder_architecture,
                parallel_attention=self.parallel_attention,
                mapping=tensorrt_llm.Mapping(world_size=self.world_size,
                                             tp_size=self.world_size))
```
This fixes the issue on my end. (It will take time due to engine build.)

Besides that, you need to change `--batch_size 64` to `--batch_size 8` or add `--max_batch_size 64` to set the maximum batch size. Otherwise, you will see this message
```bash
[WARNING] check batch_size(64) <= max_batch_size(8) failed, skipping.
```
It's because the benchmark of falcon-180b sets `max_batch_size=8` by default.

With `--batch_size 8`, I could run the benchmark as below.
```bash
$ OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 mpirun -n 8 --oversubscribe python benchmark.py -m falcon_180b --mode plugin --batch_size "8" --input_output_len "2048,128" --max_input_len=2048 --max_output_len=2048 --enable_fp8 --dtype float16
.....
[BENCHMARK] model_name falcon_180b world_size 8 num_heads 232 num_kv_heads 8 num_layers 80 hidden_size 14848 vocab_size 65024 precision float16 batch_size 8 input_length 2048 output_length 128 gpu_peak_mem(gb) 31.44 build_time(s) 910.02 tokens_per_sec 265.8 percentile95(ms) 3862.287 percentile99(ms) 3862.287 latency(ms) 3852.586 compute_cap sm90
```
We will fix it soon. Thanks for the report.

**Comment by tohaowu** [comment]
It works. Thanks
