### ISSUE TITLE
AssertionError: Each dimension must specify a 3-elements tuple or list in the order of (min,opt,max), got {dim=}

### ISSUE THREAD

**Issue by doruksonmez** [NVIDIA/TensorRT-LLM#1714]
Hi, I want to test NVIDIA's official repo on MLPerf Inference v4.0 on my server with 2x NVIDIA L40S GPUs. I have installed `TensorRT-LLM version: 0.9.0.dev2024022000` within the docker container and I already have quantized the raw GPT-J checkpoints into FP8 with the following command:
```
python3 examples/quantization/quantize.py --dtype=float16  --output_dir=/work/build/models/GPTJ-6B/fp8-quantized-ammo/GPTJ-FP8-quantized/ --model_dir=/work/build/models/GPTJ-6B/gpt-j/checkpoint-final/ --qformat=fp8 --kv_cache_dtype=fp8
```
So now the `/work/build/models/GPTJ-6B/fp8-quantized-ammo/GPTJ-FP8-quantized-02072024` directory looks like this:
```
|
-> config.json
-> rank0.safetensors
```
However, when I want to generate engine with the following command:
```
/usr/bin/python3.8 -m tensorrt_llm.commands.build --gpt_attention_plugin=float16 --max_batch_size=128 --max_input_len=1919 --max_output_len=128 --max_beam_width=4 --max_num_tokens=128 --output_dir=/work/build/engines/doruktest/gptj/Offline/bs0-custom_k_99_MaxP --context_fmha=enable --remove_input_padding=enable --paged_kv_cache=enable --strongly_typed --checkpoint_dir=/work/build/models/GPTJ-6B/fp8-quantized-ammo/GPTJ-FP8-quantized-02072024
```
I get a strange error:
```
[2024-06-03 07:42:47,860 builder.py:207 ERROR] Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/work/build/TRTLLM/tensorrt_llm/commands/build.py", line 523, in <module>
    main()
  File "/work/build/TRTLLM/tensorrt_llm/commands/build.py", line 514, in main
    parallel_build(source, build_config, args.output_dir, workers,
  File "/work/build/TRTLLM/tensorrt_llm/commands/build.py", line 436, in parallel_build
    passed = build_and_save(rank, rank % workers, ckpt_dir,
  File "/work/build/TRTLLM/tensorrt_llm/commands/build.py", line 408, in build_and_save
    engine = build(build_config,
  File "/work/build/TRTLLM/tensorrt_llm/commands/build.py", line 299, in build
    return build_model(model, build_config, use_refit=is_checkpoint_pruned)
  File "/work/build/TRTLLM/tensorrt_llm/commands/build.py", line 193, in build_model
    inputs = model.prepare_inputs(
  File "/work/build/TRTLLM/tensorrt_llm/models/modeling_utils.py", line 376, in prepare_inputs
    model_inputs = self.prepare_basic_inputs(
  File "/work/build/TRTLLM/tensorrt_llm/models/generation_mixin.py", line 359, in prepare_basic_inputs
    input_ids = Tensor(name='input_ids',
  File "/work/build/TRTLLM/tensorrt_llm/functional.py", line 223, in __init__
    self.profiles.append(DimRange(range_shape, dimension_names))
  File "/work/build/TRTLLM/tensorrt_llm/functional.py", line 77, in __init__
    assert len(dim) == 3 and 0 <= dim[0] <= dim[1] <= dim[2], \
AssertionError: Each dimension must specify a 3-elements tuple or list in the order of (min,opt,max), got {dim=}
```

What would be the cause od the issue?

**Comment by nv-guomingz** [comment]
Hi @doruksonmez , thanks for reporting this issue, we'll try to reproduce this issue on our side firstly and then get back to you.

**Comment by Tracin** [comment]
Hi @doruksonmez, I think it works on the latest branch, could you try it?

**Comment by Tracin** [comment]
@doruksonmez Hi, if everything works fine on the latest branch I will close this bug. You can reopen it if you have any update.
