### ISSUE TITLE
Convert checkpoint with tie_word_embeddings error

### ISSUE THREAD

**Issue by SefaZeng** [NVIDIA/TensorRT-LLM#1733]
### System Info

-GPU a10

### Who can help?

@ncomly-nvidia @juney-nvidia 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I try to convert a llama-like model trained by myself but with tie_word_embeddings. I change the code of llama:
```
lm_head_weights = get_weight(model_params, 'lm_head', dtype)
```
to qwen code like:
```
lm_head_weights = v
```
Then it skips this error:
```
Traceback (most recent call last):
  File "/app/tensorrt_llm/examples/llama/convert_checkpoint.py", line 446, in <module>
    main()
  File "/app/tensorrt_llm/examples/llama/convert_checkpoint.py", line 438, in main
    convert_and_save_hf(args)
  File "/app/tensorrt_llm/examples/llama/convert_checkpoint.py", line 375, in convert_and_save_hf
    execute(args.workers, [convert_and_save_rank] * world_size, args)
  File "/app/tensorrt_llm/examples/llama/convert_checkpoint.py", line 397, in execute
    f(args, rank)
  File "/app/tensorrt_llm/examples/llama/convert_checkpoint.py", line 362, in convert_and_save_rank
    llama = LLaMAForCausalLM.from_hugging_face(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/model.py", line 244, in from_hugging_face
    llama = convert.from_hugging_face(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 1192, in from_hugging_face
    weights = load_weights_from_hf(config=config,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 1296, in load_weights_from_hf
    weights = convert_hf_llama(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 999, in convert_hf_llama
    lm_head_weights = get_weight(model_params, 'lm_head', dtype)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 399, in get_weight
    if config[prefix + '.weight'].dtype != dtype:
KeyError: 'lm_head.weight'
```
But it raise another error about share embeddings:
```
[TensorRT-LLM] TensorRT-LLM version: 0.9.0.dev2024040200
0.9.0.dev2024040200
Weights loaded. Total time: 00:00:20
Traceback (most recent call last):
  File "/app/tensorrt_llm/examples/llama/convert_checkpoint.py", line 446, in <module>
    main()
  File "/app/tensorrt_llm/examples/llama/convert_checkpoint.py", line 438, in main
    convert_and_save_hf(args)
  File "/app/tensorrt_llm/examples/llama/convert_checkpoint.py", line 375, in convert_and_save_hf
    execute(args.workers, [convert_and_save_rank] * world_size, args)
  File "/app/tensorrt_llm/examples/llama/convert_checkpoint.py", line 397, in execute
    f(args, rank)
  File "/app/tensorrt_llm/examples/llama/convert_checkpoint.py", line 371, in convert_and_save_rank
    llama.save_checkpoint(args.output_dir, save_config=(rank == 0))
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/modeling_utils.py", line 427, in save_checkpoint
    save_file(weights, os.path.join(output_dir, f'rank{rank}.safetensors'))
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 284, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 480, in _flatten
    raise RuntimeError(
RuntimeError: 
            Some tensors share memory, this will lead to duplicate memory on disk and potential differences when loading them again: [{'lm_head.weight', 'transformer.vocab_embedding.weight'}].
            A potential way to correctly save your model is to use `save_model`.
            More information at https://huggingface.co/docs/safetensors/torch_shared_tensors
```

### Expected behavior

Convert correct

### actual behavior

Convert fail

### additional notes

None

**Comment by hijkzzz** [comment]
Can you provide a more complete reproducible script and weights?
It is recommended that based on the main branch codes.

**Comment by nv-guomingz** [comment]
the code base is outdated for a month at least, please try the latest code base firstly to see if the issue still exists or not.

**Comment by SefaZeng** [comment]
> Can you provide a more complete reproducible script and weights? It is recommended that based on the main branch codes.

I have made some modifications to this codebase, so I would like to keep this codebase. Can you successfully convert the model using tie_word_embedding on the llama model? Please ignore any parameter misalignment issues it may cause.

**Comment by SefaZeng** [comment]
> the code base is outdated for a month at least, please try the latest code base firstly to see if the issue still exists or not.

Hi, I have made some modifications to this codebase, so I would like to keep this codebase. Can you successfully convert the model using tie_word_embedding on the llama model? Please ignore any parameter misalignment issues it may cause.

**Comment by SefaZeng** [comment]
> the code base is outdated for a month at least, please try the latest code base firstly to see if the issue still exists or not.

I thought the main codebase will also raise an error here. If I set tie_word_embedding, the model do not contain `lm_head` in the parameters but the code will try to read it.
Here is the line 1131 to 1173 of TensorRT-LLM/models/llama/convert.py
```
    v = get_weight(model_params, 'model.embed_tokens', dtype)
    if hf_model.config.tie_word_embeddings:
        # lm_head.weight has the same weights as embedding
        if mapping.is_last_pp_rank():
            if config.vocab_size % mapping.tp_size != 0:
                # padding
                vocab_size_padded = pad_vocab_size(config.vocab_size,
                                                   mapping.tp_size)
                pad_width = vocab_size_padded - config.vocab_size

                v = torch.nn.functional.pad(v, (0, 0, 0, pad_width), 'constant',
                                            0)
            weights['lm_head.weight'] = split(v, mapping.tp_size,
                                              mapping.tp_rank)

    if config.use_parallel_embedding:
        v = split_matrix_tp(v,
                            mapping.tp_size,
                            mapping.tp_rank,
                            dim=config.embedding_sharding_dim)

    if mapping.is_first_pp_rank():
        weights['transformer.vocab_embedding.weight'] = v
   
    # read the lm_head parameter while tie_word_embedding is set to True
    lm_head_weights = get_weight(model_params, 'lm_head', dtype)

    if mapping.is_last_pp_rank():
        if config.vocab_size % mapping.tp_size != 0:
            # padding
            vocab_size_padded = pad_vocab_size(config.vocab_size,
                                               mapping.tp_size)
            pad_width = vocab_size_padded - config.vocab_size

            lm_head_weights = torch.nn.functional.pad(lm_head_weights,
                                                      (0, 0, 0, pad_width),
                                                      'constant',
                                                      value=0)
        weights['lm_head.weight'] = split_matrix_tp(lm_head_weights,
                                                    mapping.tp_size,
                                                    mapping.tp_rank,
                                                    dim=0)
        ln_f_w = get_weight(model_params, 'model.norm', dtype)
        weights['transformer.ln_f.weight'] = ln_f_w
```

**Comment by hijkzzz** [comment]
Hi , since TRT-LLM updates are very fast, it is not recommended to try based on older versions

**Comment by SefaZeng** [comment]
> Hi , since TRT-LLM updates are very fast, it is not recommended to try based on older versions

You are right. But, based on the code, it appears that there is an error in the implementation of tensor-rt when using tie_word_embedding.

**Comment by hijkzzz** [comment]
@QiJune Do we currently have an example that supports tie word embedding?

**Comment by hijkzzz** [comment]
@SefaZeng Please just 1. use main branch 2.refer to https://github.com/NVIDIA/TensorRT-LLM/blob/b777bd64750abf30ca7eda48e8b6ba3c5174aafd/tensorrt_llm/models/llama/convert.py#L1132
