### ISSUE TITLE
ValueError: Couldn't assign input_ids with shape torch.Size([7, 346]), engine supports [min, opt, max] = [(1, 1), (2, 1), (4, 1024)]

### ISSUE THREAD

**Issue by lizhixi212** [NVIDIA/TensorRT-LLM#176]
BUG
`ValueError: Couldn't assign input_ids with shape torch.Size([7, 346]), engine supports [min, opt, max] = [(1, 1), (2, 1), (4, 1024)]`
INFO
```
[[TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
input_ids: torch.Size([7, 346])
tensor([[    0,     0,     0,  ..., 55120, 30930,    13],
        [    0,     0,     0,  ..., 55120, 30930,    13],
        [    0,     0,     0,  ..., 35502, 30987,    13],
        ...,
        [    0,     0,     0,  ..., 38217, 30930,    13],
        [    0,     0,     0,  ..., 33727, 30930,    13],
        [    0,     0,     0,  ..., 33727, 30930,    13]], device='cuda:0',
       dtype=torch.int32)
input_lengths: torch.Size([7])
tensor([346, 346, 346, 346, 346, 346, 346], device='cuda:0', dtype=torch.int32)
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/chatglm2-6b/run_batch.py", line 134, in <module>
    output_ids = decoder.decode(input_ids, input_lengths, sampling_config)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 514, in wrapper
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1887, in decode
    return self.decode_regular(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1659, in decode_regular
    should_stop, next_step_buffer, tasks, context_lengths, host_context_lengths, attention_mask, logits = self.handle_per_step(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1430, in handle_per_step
    self.runtime._set_shape(context, ctx_shape)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 202, in _set_shape
    raise ValueError(
ValueError: Couldn't assign input_ids with shape torch.Size([7, 346]), engine supports [min, opt, max] = [(1, 1), (2, 1), (4, 1024)]
```
wanted for help,please!

**Comment by jdemouth-nvidia** [comment]
Hi @lizhixi212 , 

Thanks for reporting the issue. We'd need more details on the command-lines you used to build the engine. 

However based on the error, I would guess that you built the engine with a max batch size of 4 and you're trying to run with a batch size of 7.

```
Couldn't assign input_ids with shape torch.Size([7, 346]), engine supports [min, opt, max] = [(1, 1), (2, 1), (4, 1024)]
```

Indeed, your `input_ids` tensor has a first dimension of `7` (that's how I infer that you run with batch size `7`) when the engine supports at max `(4, 1024)` for the `input_ids` (i.e. a max batch size of `4` and a max sequence length of `1024`).

I hope it helps.

Thanks,
Julien

**Comment by lizhixi212** [comment]
you are absolutely right,i check build args:
`parser.add_argument('--max_batch_size', type=int, default=4)`
Thank you very much for your prompt reply.
