### ISSUE TITLE
Unexpected error from cudaGetDeviceCount() error

### ISSUE THREAD

**Issue by ljm565** [NVIDIA/TensorRT-LLM#1760]
### System Info

I met a trtllm-build issue.
GPU: RTX 3090

I followed official script of the below steps.

1. I ran the below code after installing nvidia container toolkit.
```
docker run --rm --runtime=nvidia --gpus all --entrypoint /bin/bash -it nvidia/cuda:12.4.0-devel-ubuntu22.04
```

2. Then, I installed python, pip, and tensorrt_llm libraries using the below codes.
```
# Install dependencies, TensorRT-LLM requires Python 3.10
apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev git git-lfs

# Install the latest preview version (corresponding to the main branch) of TensorRT-LLM.
# If you want to install the stable version (corresponding to the release branch), please
# remove the `--pre` option.
pip3 install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com

# Check installation
python3 -c "import tensorrt_llm"
```
At this point, `torch.cuda.is_available()` does not work and showed the below error log despite `nvidia-smi` working.
```
/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py:118: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
False
```

3. Then, I converted phi3 model to TensorRT-LLM chekcpoint format as follows.
```
# Get the source code required for running the example
git clone https://github.com/NVIDIA/TensorRT-LLM.git
cd TensorRT-LLM
git lfs install

# Log in to huggingface-cli
# You can get your token from huggingface.co/settings/token
huggingface-cli login --token *****

# Convert the model into TensorRT-LLM checkpoint format
cd examples/phi
export MODEL_TYPE="Phi-3-mini-128k-instruct"
pip install -r requirements.txt
python3 ./convert_checkpoint.py --model_type ${MODEL_TYPE} --model_dir "microsoft/${MODEL_TYPE}"  --output_dir ./phi-checkpoint  --dtype float16
```
Model was converted successfully.

4. But when I was compiling the model using the below codes, cuda error was occured. 
```
# Compile model
trtllm-build --checkpoint_dir phi-checkpoint/ --gemm_plugin float16 --output_dir ./phi3-engine

[TensorRT-LLM] TensorRT-LLM version: 0.11.0.dev2024060400
[06/11/2024-01:01:19] [TRT-LLM] [I] Set bert_attention_plugin to auto.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set gpt_attention_plugin to auto.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set gemm_plugin to float16.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set gemm_swiglu_plugin to None.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set nccl_plugin to auto.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set lookup_plugin to None.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set lora_plugin to None.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set moe_plugin to auto.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set mamba_conv1d_plugin to auto.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set context_fmha to True.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set context_fmha_fp32_acc to False.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set paged_kv_cache to True.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set remove_input_padding to True.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set use_custom_all_reduce to True.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set multi_block_mode to False.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set enable_xqa to True.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set attention_qk_half_accumulation to False.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set tokens_per_block to 64.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set use_paged_context_fmha to False.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set use_fp8_context_fmha to False.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set multiple_profiles to False.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set paged_state to True.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set streamingllm to False.
[06/11/2024-01:01:19] [TRT-LLM] [W] remove_input_padding is enabled, while max_num_tokens is not set, setting to max_batch_size*max_input_len. 
It may not be optimal to set max_num_tokens=max_batch_size*max_input_len when remove_input_padding is enabled, because the number of packed input tokens are very likely to be smaller, we strongly recommend to set max_num_tokens according to your workloads.
Traceback (most recent call last):
  File "/usr/local/bin/trtllm-build", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 441, in main
    cluster_config = infer_cluster_config()
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/auto_parallel/cluster_info.py", line 531, in infer_cluster_config
    device_name = torch.cuda.get_device_name(torch.cuda.current_device())
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 778, in current_device
    _lazy_init()
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. `docker run --rm --runtime=nvidia --gpus all --entrypoint /bin/bash -it nvidia/cuda:12.4.0-devel-ubuntu22.04`
2. 
```
apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev git git-lfs

# Install the latest preview version (corresponding to the main branch) of TensorRT-LLM.
# If you want to install the stable version (corresponding to the release branch), please
# remove the `--pre` option.
pip3 install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com

# Check installation
python3 -c "import tensorrt_llm"
```
3.
```
# Get the source code required for running the example
git clone https://github.com/NVIDIA/TensorRT-LLM.git
cd TensorRT-LLM
git lfs install

# Log in to huggingface-cli
# You can get your token from huggingface.co/settings/token
huggingface-cli login --token *****

# Convert the model into TensorRT-LLM checkpoint format
cd examples/phi
export MODEL_TYPE="Phi-3-mini-128k-instruct"
pip install -r requirements.txt
python3 ./convert_checkpoint.py --model_type ${MODEL_TYPE} --model_dir "microsoft/${MODEL_TYPE}"  --output_dir ./phi-checkpoint  --dtype float16
```
4. `trtllm-build --checkpoint_dir phi-checkpoint/ --gemm_plugin float16 --output_dir ./phi3-engine`

### Expected behavior

Build sucessfully

### actual behavior

```
[TensorRT-LLM] TensorRT-LLM version: 0.11.0.dev2024060400
[06/11/2024-01:01:19] [TRT-LLM] [I] Set bert_attention_plugin to auto.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set gpt_attention_plugin to auto.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set gemm_plugin to float16.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set gemm_swiglu_plugin to None.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set nccl_plugin to auto.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set lookup_plugin to None.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set lora_plugin to None.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set moe_plugin to auto.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set mamba_conv1d_plugin to auto.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set context_fmha to True.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set context_fmha_fp32_acc to False.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set paged_kv_cache to True.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set remove_input_padding to True.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set use_custom_all_reduce to True.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set multi_block_mode to False.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set enable_xqa to True.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set attention_qk_half_accumulation to False.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set tokens_per_block to 64.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set use_paged_context_fmha to False.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set use_fp8_context_fmha to False.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set multiple_profiles to False.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set paged_state to True.
[06/11/2024-01:01:19] [TRT-LLM] [I] Set streamingllm to False.
[06/11/2024-01:01:19] [TRT-LLM] [W] remove_input_padding is enabled, while max_num_tokens is not set, setting to max_batch_size*max_input_len. 
It may not be optimal to set max_num_tokens=max_batch_size*max_input_len when remove_input_padding is enabled, because the number of packed input tokens are very likely to be smaller, we strongly recommend to set max_num_tokens according to your workloads.
Traceback (most recent call last):
  File "/usr/local/bin/trtllm-build", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 441, in main
    cluster_config = infer_cluster_config()
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/auto_parallel/cluster_info.py", line 531, in infer_cluster_config
    device_name = torch.cuda.get_device_name(torch.cuda.current_device())
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 778, in current_device
    _lazy_init()
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW
```

### additional notes

* nvidia-smi works in nvidia-cuda docker environment

**Comment by ljm565** [comment]
This can be resolved by installing nvidia driver version 500 or higher.
