### ISSUE TITLE
Deplot model example raise AttributeError: 'PretrainedConfig' object has no attribute 'ffn_hidden_size' 

### ISSUE THREAD

**Issue by maxjeblick** [NVIDIA/TensorRT-LLM#1766]
### System Info

Driver	Version 535.54.03
CUDA	Version 12.3
Attached	GPUs 1
Product	Name Tesla	V100-SXM2-32GB-LS

Processor   x86_64

tensorrt.__version__  '10.0.1'
tensorrt_llm.__version__  '0.11.0.dev2024060400'

### Who can help?

@bys

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Following the [deplot](https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/multimodal/README.md#deplot) example:

1. `pip3 install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com`
2. Download HF model
3. Run `convert_checkpoint.py`
4. Try to run `trtllm-build`

Steps 2-4 are using the example code.

### Expected behavior

`trtllm-build` runs sucessfully

### actual behavior

I'm getting this error:

```
Traceback (most recent call last):
  File "[/usr/local/bin/trtllm-build", line 8](https://rqtqgiislurxfjnxxm1822-ngc-prd0-sjc3.nv-us-west-2.proxy.ace.ngc.nvidia.com/usr/local/bin/trtllm-build#line=7), in <module>
    sys.exit(main())
  File "[/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 489](https://rqtqgiislurxfjnxxm1822-ngc-prd0-sjc3.nv-us-west-2.proxy.ace.ngc.nvidia.com/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py#line=488), in main
    parallel_build(source, build_config, args.output_dir, workers,
  File "[/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 368](https://rqtqgiislurxfjnxxm1822-ngc-prd0-sjc3.nv-us-west-2.proxy.ace.ngc.nvidia.com/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py#line=367), in parallel_build
    passed = build_and_save(rank, rank % workers, ckpt_dir,
  File "[/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 327](https://rqtqgiislurxfjnxxm1822-ngc-prd0-sjc3.nv-us-west-2.proxy.ace.ngc.nvidia.com/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py#line=326), in build_and_save
    engine = build_model(build_config,
  File "[/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 299](https://rqtqgiislurxfjnxxm1822-ngc-prd0-sjc3.nv-us-west-2.proxy.ace.ngc.nvidia.com/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py#line=298), in build_model
    model = model_cls.from_checkpoint(ckpt_dir, config=rank_config)
  File "[/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/modeling_utils.py", line 396](https://rqtqgiislurxfjnxxm1822-ngc-prd0-sjc3.nv-us-west-2.proxy.ace.ngc.nvidia.com/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/modeling_utils.py#line=395), in from_checkpoint
    model = cls(config)
  File "[/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/modeling_utils.py", line 343](https://rqtqgiislurxfjnxxm1822-ngc-prd0-sjc3.nv-us-west-2.proxy.ace.ngc.nvidia.com/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/modeling_utils.py#line=342), in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "[/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/enc_dec/model.py", line 988](https://rqtqgiislurxfjnxxm1822-ngc-prd0-sjc3.nv-us-west-2.proxy.ace.ngc.nvidia.com/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/enc_dec/model.py#line=987), in __init__
    self.decoder_layers = ModuleList([
  File "[/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/enc_dec/model.py", line 992](https://rqtqgiislurxfjnxxm1822-ngc-prd0-sjc3.nv-us-west-2.proxy.ace.ngc.nvidia.com/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/enc_dec/model.py#line=991), in <listcomp>
    ffn_hidden_size=self.config.ffn_hidden_size,
AttributeError: 'PretrainedConfig' object has no attribute 'ffn_hidden_size'. Did you mean: 'hidden_size'?
```

### additional notes

NA

**Comment by maxjeblick** [comment]
Also tried downgrading `tensorrt_llm`  to 0.10.0, with the same error as above.

**Comment by nv-guomingz** [comment]
Hi @maxjeblick  could u plz try the latest code where trt-llm version should be 0.11.0.dev20240601100?
The issue  couldn't be reproduced with above version.

**Comment by maxjeblick** [comment]
I cannot find the corresponding version:
```
ERROR: Could not find a version that satisfies the requirement tensorrt_llm==0.11.0.dev20240601100 (from versions: 0.5.0, 0.5.0.post1, 0.6.1, 0.7.0, 0.7.1, 0.8.0.dev20240116, 0.8.0.dev20240123, 0.8.0.dev2024011601, 0.8.0.dev2024012301, 0.8.0.dev2024012302, 0.8.0.dev2024013000, 0.8.0, 0.9.0.dev2024020600, 0.9.0.dev2024022000, 0.9.0.dev2024022700, 0.9.0.dev2024030500, 0.9.0.dev2024031200, 0.9.0.dev2024031900, 0.9.0.dev2024032600, 0.9.0.dev2024032601, 0.9.0.dev2024040200, 0.9.0.dev2024040900, 0.9.0, 0.10.0.dev2024041600, 0.10.0.dev2024042300, 0.10.0.dev2024043000, 0.10.0.dev2024050700, 0.10.0, 0.11.0.dev2024051400, 0.11.0.dev2024052100, 0.11.0.dev2024052800, 0.11.0.dev2024060400)
ERROR: No matching distribution found for tensorrt_llm==0.11.0.dev20240601100
```

I'm able to run `trtllm-build`  by manually adding  `"ffn_hidden_size":2048,` to `deplot_tensorrt/trt_models/deplot/float16/decoder/config.json`.

I also noticed that `parse_pix2struct_config` in [convert.py](https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/enc_dec/convert_checkpoint.py#L953) sets  `component_config.ffn_hidden_size`, but the final `tllm_decoder_config` ([here](https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/enc_dec/convert_checkpoint.py#L1265)) does not contain this property. Maybe `additional_settings` list needs to be updated?

**Comment by Shixiaowei02** [comment]
We will upload the newest wheel package today. Sorry for the inconvenience.

**Comment by nv-guomingz** [comment]
@maxjeblick could u plz have a try with https://pypi.org/project/tensorrt-llm/0.11.0.dev2024061100/ and see if the issue still exists or not?

**Comment by maxjeblick** [comment]
Example is running with the latest release, thanks for the help!
Will close the issue.
