### ISSUE TITLE
pypi install of v0.10.0 results in "No module named 'tensorrt'"

### ISSUE THREAD

**Issue by TheCodeWrangler** [NVIDIA/TensorRT-LLM#1791]
### System Info

Debian 11
2 L4 GPUS
CUDA 12.4

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

`pip install tensorrt-llm==0.9.0 -U --extra-index-url https://pypi.nvidia.com`

`trtllm-build --version"

Results in printing: "[TensorRT-LLM] TensorRT-LLM version: 0.9.0"

`pip install tensorrt-llm==0.10.0 -U --extra-index-url https://pypi.nvidia.com`
`trtllm-build --version`

Results in:
```
Traceback (most recent call last):
  File "~/bin/trtllm-build", line 5, in <module>
    from tensorrt_llm.commands.build import main
  File "~/lib/python3.10/site-packages/tensorrt_llm/__init__.py", line 32, in <module>
    import tensorrt_llm.functional as functional
  File ".../python3.10/site-packages/tensorrt_llm/functional.py", line 25, in <module>
    import tensorrt as trt
ModuleNotFoundError: No module named 'tensorrt'
```

### Expected behavior

I expect that the install of tensorrt-llm installs the required dependencies of tensorrt

### actual behavior

import of tensorrt within v0.10.0 leads to an exception in the CLI

### additional notes

NA

**Comment by hijkzzz** [comment]
Please try the container: nvcr.io/nvidia/tritonserver:24.05-trtllm-python-py3
Or build the container using  `make -C docker release_build`

**Comment by littletomatodonkey** [comment]
you can use `pip install tensorrt==10.0.1 --force-reinstall`
