### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorrt_llm.bindings.BuildInfo'

### ISSUE THREAD

**Issue by PoTaTo-Mika** [NVIDIA/TensorRT-LLM#1831]
When building conda env, I met with this problem.
I installed TensorRT by using source code from NVIDIA official Website,and used pip install -r requirement.txt in main and /examples/qwen, when it all finished, I found it unable to import tensorrt_llm.
## Details
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hjzd/miniconda3/envs/TRT/lib/python3.11/site-packages/tensorrt_llm/__init__.py", line 32, in <module>
    import tensorrt_llm.functional as functional
  File "/home/hjzd/miniconda3/envs/TRT/lib/python3.11/site-packages/tensorrt_llm/functional.py", line 28, in <module>
    from . import graph_rewriting as gw
  File "/home/hjzd/miniconda3/envs/TRT/lib/python3.11/site-packages/tensorrt_llm/graph_rewriting.py", line 12, in <module>
    from .network import Network
  File "/home/hjzd/miniconda3/envs/TRT/lib/python3.11/site-packages/tensorrt_llm/network.py", line 27, in <module>
    from tensorrt_llm.module import Module
  File "/home/hjzd/miniconda3/envs/TRT/lib/python3.11/site-packages/tensorrt_llm/module.py", line 17, in <module>
    from ._common import default_net
  File "/home/hjzd/miniconda3/envs/TRT/lib/python3.11/site-packages/tensorrt_llm/_common.py", line 31, in <module>
    from ._utils import str_dtype_to_trt
  File "/home/hjzd/miniconda3/envs/TRT/lib/python3.11/site-packages/tensorrt_llm/_utils.py", line 30, in <module>
    from tensorrt_llm.bindings.BuildInfo import ENABLE_MULTI_DEVICE
ModuleNotFoundError: No module named 'tensorrt_llm.bindings.BuildInfo'

**Comment by hijkzzz** [comment]
Please use the docker container 
See the tutorial: https://nvidia.github.io/TensorRT-LLM/installation/linux.html

**Comment by qeternity** [comment]
These responses are so bad. The TRT-LLM docs and DX is bad enough as is.

Some people don't want to run a docker container. Is Py3.11 not supported?
