### ISSUE TITLE
trtllm-build on GRID vGPU - nvml errors

### ISSUE THREAD

**Issue by edesalve** [NVIDIA/TensorRT-LLM#1861]
### System Info

- Host: VMware ESXi 7
- Host Nvidia drivers: 550.54.16
- VM CPU architecture: x86_64
- VM Nvidia drivers: 550.54.15
- VM OS: Ubuntu LTS 22.04
- Physical GPU: A100
- TensorRT-LLM version: v0.11.0

### Who can help?

@byshiue

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

After proper checkpoint creation:

```
trtllm-build --checkpoint_dir Meta-Llama-3-8B-Instruct-bf16-ckpt --gemm_plugin bfloat16 --gpt_attention_plugin bfloat16 --output_dir Meta-Llama-3-8B-Instruct-bf16-engine
```

### Expected behavior

Successful build of the engine.

### actual behavior

```
[TensorRT-LLM] TensorRT-LLM version: 0.11.0.dev2024062500
[06/28/2024-06:35:05] [TRT-LLM] [I] Set bert_attention_plugin to auto.
[06/28/2024-06:35:05] [TRT-LLM] [I] Set gpt_attention_plugin to bfloat16.
[06/28/2024-06:35:05] [TRT-LLM] [I] Set gemm_plugin to bfloat16.
[06/28/2024-06:35:05] [TRT-LLM] [I] Set gemm_swiglu_plugin to None.
[06/28/2024-06:35:05] [TRT-LLM] [I] Set nccl_plugin to auto.
[06/28/2024-06:35:05] [TRT-LLM] [I] Set lookup_plugin to None.
[06/28/2024-06:35:05] [TRT-LLM] [I] Set lora_plugin to None.
[06/28/2024-06:35:05] [TRT-LLM] [I] Set moe_plugin to auto.
[06/28/2024-06:35:05] [TRT-LLM] [I] Set mamba_conv1d_plugin to auto.
[06/28/2024-06:35:05] [TRT-LLM] [I] Set context_fmha to True.
[06/28/2024-06:35:05] [TRT-LLM] [I] Set context_fmha_fp32_acc to False.
[06/28/2024-06:35:05] [TRT-LLM] [I] Set paged_kv_cache to True.
[06/28/2024-06:35:05] [TRT-LLM] [I] Set remove_input_padding to True.
[06/28/2024-06:35:05] [TRT-LLM] [I] Set use_custom_all_reduce to True.
[06/28/2024-06:35:05] [TRT-LLM] [I] Set reduce_fusion to False.
[06/28/2024-06:35:05] [TRT-LLM] [I] Set multi_block_mode to False.
[06/28/2024-06:35:05] [TRT-LLM] [I] Set enable_xqa to True.
[06/28/2024-06:35:05] [TRT-LLM] [I] Set attention_qk_half_accumulation to False.
[06/28/2024-06:35:05] [TRT-LLM] [I] Set tokens_per_block to 64.
[06/28/2024-06:35:05] [TRT-LLM] [I] Set use_paged_context_fmha to False.
[06/28/2024-06:35:05] [TRT-LLM] [I] Set use_fp8_context_fmha to False.
[06/28/2024-06:35:05] [TRT-LLM] [I] Set multiple_profiles to False.
[06/28/2024-06:35:05] [TRT-LLM] [I] Set paged_state to True.
[06/28/2024-06:35:05] [TRT-LLM] [I] Set streamingllm to False.
[06/28/2024-06:35:05] [TRT-LLM] [I] Compute capability: (8, 0)
[06/28/2024-06:35:05] [TRT-LLM] [I] SM count: 98
Traceback (most recent call last):
  File "/home/s2e/.local/bin/trtllm-build", line 8, in <module>
    sys.exit(main())
  File "/home/s2e/.local/lib/python3.10/site-packages/tensorrt_llm/commands/buil                                                                                                                                                             d.py", line 428, in main
    cluster_config = infer_cluster_config()
  File "/home/s2e/.local/lib/python3.10/site-packages/tensorrt_llm/auto_parallel                                                                                                                                                             /cluster_info.py", line 538, in infer_cluster_config
    cluster_info=infer_cluster_info(),
  File "/home/s2e/.local/lib/python3.10/site-packages/tensorrt_llm/auto_parallel                                                                                                                                                             /cluster_info.py", line 460, in infer_cluster_info
    sm_clock = pynvml.nvmlDeviceGetMaxClockInfo(
  File "/usr/local/lib/python3.10/dist-packages/pynvml/nvml.py", line 2182, in n                                                                                                                                                             vmlDeviceGetMaxClockInfo
    _nvmlCheckReturn(ret)
  File "/usr/local/lib/python3.10/dist-packages/pynvml/nvml.py", line 833, in _n                                                                                                                                                             vmlCheckReturn
    raise NVMLError(ret)
pynvml.nvml.NVMLError_NotSupported: Not Supported
```

### additional notes

The same procedure has already been successfully completed on a VM with GPU `Passthrough`.
The configuration of the VM with vGPU technology has been done correctly (details of the installed drivers at the bottom).
The problem arises during the execution of `infer_cluster_info`. I created a small test in python to go and check all the requests made in the function:

```python
import pynvml
import torch
import sys

# Initialize NVML
pynvml.nvmlInit()

def test_nvml_calls():
    device_index = torch.cuda.current_device()
    handle = pynvml.nvmlDeviceGetHandleByIndex(device_index)

    # List of NVML functions to test
    nvml_functions = [
        ("nvmlDeviceGetCudaComputeCapability", lambda: pynvml.nvmlDeviceGetCudaComputeCapability(handle)),
        ("nvmlDeviceGetMaxClockInfo for SM Clock", lambda: pynvml.nvmlDeviceGetMaxClockInfo(handle, pynvml.NVML_CLOCK_SM)),
        ("nvmlDeviceGetMaxClockInfo for Mem Clock", lambda: pynvml.nvmlDeviceGetMaxClockInfo(handle, pynvml.NVML_CLOCK_MEM)),
        ("nvmlDeviceGetMemoryBusWidth", lambda: pynvml.nvmlDeviceGetMemoryBusWidth(handle)),
        ("nvmlDeviceGetNvLinkState", lambda: pynvml.nvmlDeviceGetNvLinkState(handle, 0)),
        ("nvmlDeviceGetNvLinkVersion", lambda: pynvml.nvmlDeviceGetNvLinkVersion(handle, 0)),
        ("nvmlDeviceGetCurrPcieLinkGeneration", lambda: pynvml.nvmlDeviceGetCurrPcieLinkGeneration(handle)),
        ("nvmlDeviceGetCurrPcieLinkWidth", lambda: pynvml.nvmlDeviceGetCurrPcieLinkWidth(handle)),
    ]

    results = {}
    for func_name, func in nvml_functions:
        try:
            result = func()
            results[func_name] = ("Success", result)
        except pynvml.NVMLError as e:
            results[func_name] = ("Failed", str(e))

    return results

# Run the tests and print the results
results = test_nvml_calls()
for func_name, (status, output) in results.items():
    print(f"{func_name}: {status} - Output/Error: {output}")

# Finalize NVML
pynvml.nvmlShutdown()
```

and this is the output:

```
nvmlDeviceGetCudaComputeCapability: Success - Output/Error: (8, 0)
nvmlDeviceGetMaxClockInfo for SM Clock: Failed - Output/Error: Not Supported
nvmlDeviceGetMaxClockInfo for Mem Clock: Failed - Output/Error: Not Supported
nvmlDeviceGetMemoryBusWidth: Success - Output/Error: 5120
nvmlDeviceGetNvLinkState: Failed - Output/Error: Not Supported
nvmlDeviceGetNvLinkVersion: Failed - Output/Error: Not Supported
nvmlDeviceGetCurrPcieLinkGeneration: Failed - Output/Error: Not Supported
nvmlDeviceGetCurrPcieLinkWidth: Failed - Output/Error: Not Supported
```

This despite setting `pciPassthru0.cfg.enable_profiling` for the VM as suggested in the NVIDIA AI Enterprise User Guide.
Is there something I'm missing or are vGPU simply not supported?

```
nvidia-smi -q

==============NVSMI LOG==============

Timestamp                                 : Fri Jun 28 07:03:27 2024
Driver Version                            : 550.54.15
CUDA Version                              : 12.4

Attached GPUs                             : 1
GPU 00000000:02:00.0
    Product Name                          : GRID A100D-7-80C
    Product Brand                         : NVIDIA Virtual Compute Server
    Product Architecture                  : Ampere
    Display Mode                          : Enabled
    Display Active                        : Disabled
    Persistence Mode                      : Enabled
    Addressing Mode                       : None
    MIG Mode
        Current                           : Enabled
        Pending                           : Enabled
    MIG Device
        Index                             : 0
        GPU Instance ID                   : 0
        Compute Instance ID               : 0
        Device Attributes
            Shared
                Multiprocessor count      : 98
                Copy Engine count         : 7
                Encoder count             : 0
                Decoder count             : 5
                OFA count                 : 1
                JPG count                 : 1
        ECC Errors
            Volatile
                SRAM Uncorrectable        : 0
        FB Memory Usage
            Total                         : 76011 MiB
            Reserved                      : 0 MiB
            Used                          : 0 MiB
            Free                          : 76011 MiB
        BAR1 Memory
            Total                         : 4096 MiB
            Used                          : 0 MiB
            Free                          : 4095 MiB
    Accounting Mode                       : Disabled
    Accounting Mode Buffer Size           : 4000
    Driver Model
        Current                           : N/A
        Pending                           : N/A
    Serial Number                         : N/A
    GPU UUID                              : GPU-be04bb87-20dd-11b2-bae1-30170d8796ab
    Minor Number                          : 0
    VBIOS Version                         : 00.00.00.00.00
    MultiGPU Board                        : No
    Board ID                              : 0x200
    Board Part Number                     : N/A
    GPU Part Number                       : 20B5-893-A1
    FRU Part Number                       : N/A
    Module ID                             : N/A
    Inforom Version
        Image Version                     : N/A
        OEM Object                        : N/A
        ECC Object                        : N/A
        Power Management Object           : N/A
    Inforom BBX Object Flush
        Latest Timestamp                  : N/A
        Latest Duration                   : N/A
    GPU Operation Mode
        Current                           : N/A
        Pending                           : N/A
    GPU C2C Mode                          : N/A
    GPU Virtualization Mode
        Virtualization Mode               : VGPU
        Host VGPU Mode                    : N/A
        vGPU Heterogeneous Mode           : N/A
    vGPU Software Licensed Product
        Product Name                      : NVIDIA Virtual Compute Server
        License Status                    : Licensed (Expiry: 2024-6-29 3:6:29 GMT)
    GPU Reset Status
        Reset Required                    : N/A
        Drain and Reset Recommended       : N/A
    GSP Firmware Version                  : N/A
    IBMNPU
        Relaxed Ordering Mode             : N/A
    PCI
        Bus                               : 0x02
        Device                            : 0x00
        Domain                            : 0x0000
        Base Classcode                    : 0x3
        Sub Classcode                     : 0x2
        Device Id                         : 0x20B510DE
        Bus Id                            : 00000000:02:00.0
        Sub System Id                     : 0x159510DE
        GPU Link Info
            PCIe Generation
                Max                       : N/A
                Current                   : N/A
                Device Current            : N/A
                Device Max                : N/A
                Host Max                  : N/A
            Link Width
                Max                       : N/A
                Current                   : N/A
        Bridge Chip
            Type                          : N/A
            Firmware                      : N/A
        Replays Since Reset               : N/A
        Replay Number Rollovers           : N/A
        Tx Throughput                     : N/A
        Rx Throughput                     : N/A
        Atomic Caps Inbound               : N/A
        Atomic Caps Outbound              : N/A
    Fan Speed                             : N/A
    Performance State                     : P0
    Clocks Event Reasons                  : N/A
    Sparse Operation Mode                 : N/A
    FB Memory Usage
        Total                             : 81920 MiB
        Reserved                          : 5908 MiB
        Used                              : 0 MiB
        Free                              : 76011 MiB
    BAR1 Memory Usage
        Total                             : 4096 MiB
        Used                              : 0 MiB
        Free                              : 4096 MiB
    Conf Compute Protected Memory Usage
        Total                             : 0 MiB
        Used                              : 0 MiB
        Free                              : 0 MiB
    Compute Mode                          : Default
    Utilization
        Gpu                               : N/A
        Memory                            : N/A
        Encoder                           : N/A
        Decoder                           : N/A
        JPEG                              : N/A
        OFA                               : N/A
    Encoder Stats
        Active Sessions                   : 0
        Average FPS                       : 0
        Average Latency                   : 0
    FBC Stats
        Active Sessions                   : 0
        Average FPS                       : 0
        Average Latency                   : 0
    ECC Mode
        Current                           : Enabled
        Pending                           : Enabled
    ECC Errors
        Volatile
            SRAM Correctable              : N/A
            SRAM Uncorrectable Parity     : N/A
            SRAM Uncorrectable SEC-DED    : N/A
            DRAM Correctable              : 0
            DRAM Uncorrectable            : 0
        Aggregate
            SRAM Correctable              : N/A
            SRAM Uncorrectable Parity     : N/A
            SRAM Uncorrectable SEC-DED    : N/A
            DRAM Correctable              : 0
            DRAM Uncorrectable            : 0
            SRAM Threshold Exceeded       : N/A
        Aggregate Uncorrectable SRAM Sources
            SRAM L2                       : N/A
            SRAM SM                       : N/A
            SRAM Microcontroller          : N/A
            SRAM PCIE                     : N/A
            SRAM Other                    : N/A
    Retired Pages
        Single Bit ECC                    : N/A
        Double Bit ECC                    : N/A
        Pending Page Blacklist            : N/A
    Remapped Rows                         : N/A
    Temperature
        GPU Current Temp                  : N/A
        GPU T.Limit Temp                  : N/A
        GPU Shutdown Temp                 : N/A
        GPU Slowdown Temp                 : N/A
        GPU Max Operating Temp            : N/A
        GPU Target Temperature            : N/A
        Memory Current Temp               : N/A
        Memory Max Operating Temp         : N/A
    GPU Power Readings
        Power Draw                        : N/A
        Current Power Limit               : N/A
        Requested Power Limit             : N/A
        Default Power Limit               : N/A
        Min Power Limit                   : N/A
        Max Power Limit                   : N/A
    GPU Memory Power Readings
        Power Draw                        : N/A
    Module Power Readings
        Power Draw                        : N/A
        Current Power Limit               : N/A
        Requested Power Limit             : N/A
        Default Power Limit               : N/A
        Min Power Limit                   : N/A
        Max Power Limit                   : N/A
    Clocks
        Graphics                          : 1410 MHz
        SM                                : 1410 MHz
        Memory                            : 1512 MHz
        Video                             : 1275 MHz
    Applications Clocks
        Graphics                          : N/A
        Memory                            : N/A
    Default Applications Clocks
        Graphics                          : N/A
        Memory                            : N/A
    Deferred Clocks
        Memory                            : N/A
    Max Clocks
        Graphics                          : N/A
        SM                                : N/A
        Memory                            : N/A
        Video                             : N/A
    Max Customer Boost Clocks
        Graphics                          : N/A
    Clock Policy
        Auto Boost                        : N/A
        Auto Boost Default                : N/A
    Voltage
        Graphics                          : N/A
    Fabric
        State                             : N/A
        Status                            : N/A
        CliqueId                          : N/A
        ClusterUUID                       : N/A
        Health
            Bandwidth                     : N/A
    Processes                             : None
```

```
nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:19:38_PST_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0
```

**Comment by nv-guomingz** [comment]
what's the output of nvidia-smi under your env?

**Comment by edesalve** [comment]
@nv-guomingz I pasted the output of `nvidia-smi -q` in the first message, in the following the output of `nvidia-smi`:

```
Fri Jun 28 10:31:44 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.42.02              Driver Version: 555.42.02      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100 80GB PCIe          Off |   00000000:03:00.0 Off |                    0 |
| N/A   30C    P0             42W /  300W |       1MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

**Comment by nv-guomingz** [comment]
Thanks @edesalve 
We'll try to reproduce your issue internally but it more looks like a issue related with nvml package.

@yuxianq could we war this issue?

**Comment by yuxianq** [comment]
@edesalve Some nvml API is unavailable in vGPU environment due to safety. We have already workaround it by fallbacking to a default cluster key when any nvml API fails. This bugfix will be provided in the next weekly release of main branch.

**Comment by edesalve** [comment]
Thank you for the very quick response, I will wait for next week's version!

**Comment by edesalve** [comment]
@yuxianq Just installed the new version and the build finished successfully as expected:

```
[TensorRT-LLM] TensorRT-LLM version: 0.12.0.dev2024070200
[07/04/2024-13:50:35] [TRT-LLM] [I] Set bert_attention_plugin to auto.
[07/04/2024-13:50:35] [TRT-LLM] [I] Set gpt_attention_plugin to bfloat16.
[07/04/2024-13:50:35] [TRT-LLM] [I] Set gemm_plugin to bfloat16.
[07/04/2024-13:50:35] [TRT-LLM] [I] Set gemm_swiglu_plugin to None.
[07/04/2024-13:50:35] [TRT-LLM] [I] Set nccl_plugin to auto.
[07/04/2024-13:50:35] [TRT-LLM] [I] Set lookup_plugin to None.
[07/04/2024-13:50:35] [TRT-LLM] [I] Set lora_plugin to None.
[07/04/2024-13:50:35] [TRT-LLM] [I] Set moe_plugin to auto.
[07/04/2024-13:50:35] [TRT-LLM] [I] Set mamba_conv1d_plugin to auto.
[07/04/2024-13:50:35] [TRT-LLM] [I] Set context_fmha to True.
[07/04/2024-13:50:35] [TRT-LLM] [I] Set context_fmha_fp32_acc to False.
[07/04/2024-13:50:35] [TRT-LLM] [I] Set paged_kv_cache to True.
[07/04/2024-13:50:35] [TRT-LLM] [I] Set remove_input_padding to True.
[07/04/2024-13:50:35] [TRT-LLM] [I] Set use_custom_all_reduce to True.
[07/04/2024-13:50:35] [TRT-LLM] [I] Set reduce_fusion to False.
[07/04/2024-13:50:35] [TRT-LLM] [I] Set multi_block_mode to False.
[07/04/2024-13:50:35] [TRT-LLM] [I] Set enable_xqa to True.
[07/04/2024-13:50:35] [TRT-LLM] [I] Set tokens_per_block to 64.
[07/04/2024-13:50:35] [TRT-LLM] [I] Set use_paged_context_fmha to False.
[07/04/2024-13:50:35] [TRT-LLM] [I] Set use_fp8_context_fmha to False.
[07/04/2024-13:50:35] [TRT-LLM] [I] Set multiple_profiles to False.
[07/04/2024-13:50:35] [TRT-LLM] [I] Set paged_state to True.
[07/04/2024-13:50:35] [TRT-LLM] [I] Set streamingllm to False.
[07/04/2024-13:50:35] [TRT-LLM] [I] Compute capability: (8, 0)
[07/04/2024-13:50:35] [TRT-LLM] [I] SM count: 98
[07/04/2024-13:50:36] [TRT-LLM] [W] Failed to infer cluster info for GRID A100D-7-80C MIG 7g.80gb, treat it as a L40 node with 79 GB memory. This setting makes no effect if you do not use auto parallel.
[07/04/2024-13:50:36] [TRT-LLM] [I] max_seq_len is not specified, using value 8192
[07/04/2024-13:50:36] [TRT-LLM] [W] remove_input_padding is enabled, while opt_num_tokens is not set, setting to max_batch_size*max_beam_width.

[07/04/2024-13:50:36] [TRT-LLM] [W] padding removal and fMHA are both enabled, max_input_len is not required and will be ignored
[07/04/2024-13:50:36] [TRT-LLM] [I] Set dtype to bfloat16.
[07/04/2024-13:50:36] [TRT] [I] [MemUsageChange] Init CUDA: CPU +2, GPU +0, now: CPU 150, GPU 6287 (MiB)
[07/04/2024-13:50:39] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1927, GPU +354, now: CPU 2224, GPU 6641 (MiB)
[07/04/2024-13:50:39] [TRT] [W] profileSharing0806 is on by default in TensorRT 10.0. This flag is deprecated and has no effect.
[07/04/2024-13:50:39] [TRT-LLM] [I] Set nccl_plugin to None.
[07/04/2024-13:50:39] [TRT-LLM] [I] Set use_custom_all_reduce to True.
[07/04/2024-13:50:39] [TRT-LLM] [I] Build TensorRT engine Unnamed Network 0
[07/04/2024-13:50:39] [TRT] [W] Unused Input: position_ids
[07/04/2024-13:50:39] [TRT] [W] [RemoveDeadLayers] Input Tensor position_ids is unused or used only at compile-time, but is not being removed.
[07/04/2024-13:50:39] [TRT] [I] Global timing cache in use. Profiling results in this builder pass will be stored.
[07/04/2024-13:50:43] [TRT] [I] [GraphReduction] The approximate region cut reduction algorithm is called.
[07/04/2024-13:50:43] [TRT] [I] Detected 14 inputs and 1 output network tensors.
[07/04/2024-13:50:56] [TRT] [I] Total Host Persistent Memory: 92512
[07/04/2024-13:50:56] [TRT] [I] Total Device Persistent Memory: 0
[07/04/2024-13:50:56] [TRT] [I] Total Scratch Memory: 134250496
[07/04/2024-13:50:56] [TRT] [I] [BlockAssignment] Started assigning block shifts. This will take 559 steps to complete.
[07/04/2024-13:50:56] [TRT] [I] [BlockAssignment] Algorithm ShiftNTopDown took 19.7677ms to assign 16 blocks to 559 nodes requiring 838866432 bytes.
[07/04/2024-13:50:56] [TRT] [I] Total Activation Memory: 838865408
[07/04/2024-13:50:56] [TRT] [I] Total Weights Memory: 16064716800
[07/04/2024-13:50:56] [TRT] [I] Engine generation completed in 16.958 seconds.
[07/04/2024-13:50:56] [TRT] [I] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 4 MiB, GPU 24576 MiB
[07/04/2024-13:51:06] [TRT] [I] [MemUsageStats] Peak memory usage during Engine building and serialization: CPU: 34869 MiB
[07/04/2024-13:51:06] [TRT-LLM] [I] Total time of building Unnamed Network 0: 00:00:26
[07/04/2024-13:51:06] [TRT] [I] Serialized 26 bytes of code generator cache.
[07/04/2024-13:51:06] [TRT] [I] Serialized 137497 bytes of compilation cache.
[07/04/2024-13:51:06] [TRT] [I] Serialized 6 timing cache entries
[07/04/2024-13:51:06] [TRT-LLM] [I] Timing cache serialized to model.cache
[07/04/2024-13:51:06] [TRT-LLM] [I] Serializing engine to Meta-Llama-3-8B-Instruct-bf16-engine/rank0.engine...
[07/04/2024-13:51:28] [TRT-LLM] [I] Engine serialized. Total time: 00:00:21
[07/04/2024-13:51:29] [TRT-LLM] [I] Total time of building all engines: 00:00:53
```

However trying the example inference through:

```
 python3 examples/run.py --engine_dir Meta-Llama-3-8B-Instruct-bf16-engine --max_output_len 100 --tokenizer_dir ~/meta-llama_Meta-Llama-3-8B-Instruct --input_text "How do I count to nine in French?"
```

gives the following error:

```
[TensorRT-LLM] TensorRT-LLM version: 0.12.0.dev2024070200
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/home/s2e/TensorRT-LLM/examples/run.py", line 532, in <module>
    main(args)
  File "/home/s2e/TensorRT-LLM/examples/run.py", line 364, in main
    runner = runner_cls.from_dir(**runner_kwargs)
  File "/home/s2e/.local/lib/python3.10/site-packages/tensorrt_llm/runtime/model_runner_cpp.py", line 240, in from_dir
    executor = trtllm.Executor(engine_dir, trtllm.ModelType.DECODER_ONLY,
RuntimeError: [TensorRT-LLM][ERROR] CUDA runtime error in cudaDeviceGetDefaultMemPool(&memPool, device): operation not supported (/home/jenkins/agent/workspace/LLM/main/L0_PostMerge/tensorrt_llm/cpp/tensorrt_llm/runtime/bufferManager.cpp:211)
1       0x7fb2d6a9397e void tensorrt_llm::common::check<cudaError>(cudaError, char const*, char const*, int) + 94
2       0x7fb2d838953c tensorrt_llm::runtime::BufferManager::initMemoryPool(int) + 124
3       0x7fb2d838b567 tensorrt_llm::runtime::BufferManager::BufferManager(std::shared_ptr<tensorrt_llm::runtime::CudaStream>, bool) + 663
4       0x7fb2d845eb72 tensorrt_llm::runtime::TllmRuntime::TllmRuntime(tensorrt_llm::runtime::RawEngine const&, nvinfer1::ILogger*, float, bool) + 370
5       0x7fb2d867b42a tensorrt_llm::batch_manager::TrtGptModelInflightBatching::TrtGptModelInflightBatching(std::shared_ptr<nvinfer1::ILogger>, tensorrt_llm::runtime::ModelConfig const&, tensorrt_llm::runtime::WorldConfig const&, tensorrt_llm::runtime::RawEngine const&, bool, tensorrt_llm::batch_manager::TrtGptModelOptionalParams const&) + 954
6       0x7fb2d869ece3 tensorrt_llm::executor::Executor::Impl::createModel(tensorrt_llm::runtime::RawEngine const&, tensorrt_llm::runtime::ModelConfig const&, tensorrt_llm::runtime::WorldConfig const&, tensorrt_llm::executor::ExecutorConfig const&) + 419
7       0x7fb2d869f4e8 tensorrt_llm::executor::Executor::Impl::loadModel(std::optional<std::filesystem::path> const&, std::optional<std::vector<unsigned char, std::allocator<unsigned char> > > const&, tensorrt_llm::runtime::GptJsonConfig const&, tensorrt_llm::executor::ExecutorConfig const&, bool) + 1272
8       0x7fb2d86a4714 tensorrt_llm::executor::Executor::Impl::Impl(std::filesystem::path const&, std::optional<std::filesystem::path> const&, tensorrt_llm::executor::ModelType, tensorrt_llm::executor::ExecutorConfig const&) + 1764
9       0x7fb2d86992e0 tensorrt_llm::executor::Executor::Executor(std::filesystem::path const&, tensorrt_llm::executor::ModelType, tensorrt_llm::executor::ExecutorConfig const&) + 64
10      0x7fb36322d4b2 /home/s2e/.local/lib/python3.10/site-packages/tensorrt_llm/bindings.cpython-310-x86_64-linux-gnu.so(+0xb64b2) [0x7fb36322d4b2]
11      0x7fb3631d01dc /home/s2e/.local/lib/python3.10/site-packages/tensorrt_llm/bindings.cpython-310-x86_64-linux-gnu.so(+0x591dc) [0x7fb3631d01dc]
12      0x55dd7935210e python3(+0x15a10e) [0x55dd7935210e]
13      0x55dd79348a7b _PyObject_MakeTpCall + 603
14      0x55dd79360c20 python3(+0x168c20) [0x55dd79360c20]
15      0x55dd7935d087 python3(+0x165087) [0x55dd7935d087]
16      0x55dd79348e2b python3(+0x150e2b) [0x55dd79348e2b]
17      0x7fb3631cf7fb /home/s2e/.local/lib/python3.10/site-packages/tensorrt_llm/bindings.cpython-310-x86_64-linux-gnu.so(+0x587fb) [0x7fb3631cf7fb]
18      0x55dd79348a7b _PyObject_MakeTpCall + 603
19      0x55dd79341629 _PyEval_EvalFrameDefault + 27257
20      0x55dd793607f1 python3(+0x1687f1) [0x55dd793607f1]
21      0x55dd79361492 PyObject_Call + 290
22      0x55dd7933d5d7 _PyEval_EvalFrameDefault + 10791
23      0x55dd793529fc _PyFunction_Vectorcall + 124
24      0x55dd7933b26d _PyEval_EvalFrameDefault + 1725
25      0x55dd793379c6 python3(+0x13f9c6) [0x55dd793379c6]
26      0x55dd7942d256 PyEval_EvalCode + 134
27      0x55dd79458108 python3(+0x260108) [0x55dd79458108]
28      0x55dd794519cb python3(+0x2599cb) [0x55dd794519cb]
29      0x55dd79457e55 python3(+0x25fe55) [0x55dd79457e55]
30      0x55dd79457338 _PyRun_SimpleFileObject + 424
31      0x55dd79456f83 _PyRun_AnyFileObject + 67
32      0x55dd79449a5e Py_RunMain + 702
33      0x55dd7942002d Py_BytesMain + 45
34      0x7fb4bbb69d90 /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7fb4bbb69d90]
35      0x7fb4bbb69e40 __libc_start_main + 128
36      0x55dd7941ff25 _start + 37
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
```

I have found other people experiencing a similar issue, someone states it's solved but it's not clear how. Concerning `pciPassthru` parameters both `pciPassthru.64bitMMIOSizeGB=256` and `pciPassthru.use64bitMMIO=TRUE` are set.
