### ISSUE TITLE
compile error for TRT-LLM on L40

### ISSUE THREAD

**Issue by littletomatodonkey** [NVIDIA/TensorRT-LLM#1912]
Hi, when i compile TRT-LLM, the following errors occurs.
```
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/mnt/bn/vgraph/gry/TensorRT-LLM-github/setup.py", line 84, in <module>
          sanity_check()
        File "/mnt/bn/vgraph/gry/TensorRT-LLM-github/setup.py", line 48, in sanity_check
          raise ImportError(
      ImportError: The `bindings` module does not exist. Please check the package integrity. If you are attempting to use the pip development mode (editable installation), please execute `build_wheels.py` first, and then run `pip install -e .`.
```

Others.

* device: L40
* cuda version: 12.2
* TRT: 10.1.0
* file `bindings.cpython-310-x86_64-linux-gnu.so` exists in dir `tensorrt_llm/`. 
* build command:

```
python3 ./scripts/build_wheel.py \
--trt_root /usr/local/tensorrt \
--clean
```

**Comment by littletomatodonkey** [comment]
I add `--python_bindings` for the compilation, and it passed.
