### ISSUE TITLE
Failed to run benchmark with llama-7B

### ISSUE THREAD

**Issue by hurun** [NVIDIA/TensorRT-LLM#192]
os: centos 7
nvidia : v100*4

## step 1: generate the engine file
```bash
python build.py --model_dir /code/tensorrt_llm/models/llama2-7b \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --use_gemm_plugin float16 \
                --max_output_len 1024 \
                --max_batch_size 2 \
                --output_dir /code/tensorrt_llm/models/llama2-7b/
```
## step 2: test one example, it is ok
```bash

python3 run.py --max_output_len=1024 \
 --tokenizer_dir /code/tensorrt_llm/models/llama2-7b \
 --engine_dir=/code/tensorrt_llm/models/llama2-7b/
```

## step 3: run benchmark, return error
```bash

python benchmark.py \
    -m llama_7b \
    --mode plugin \
    --batch_size "1" \
    --engine_dir /code/tensorrt_llm/models/llama2-7b/ \
    --input_output_len "128,128"
```

return error detail 
```bash

Traceback (most recent call last):
  File "/code/tensorrt_llm/benchmarks/python/benchmark.py", line 322, in <module>
    main(args)
  File "/code/tensorrt_llm/benchmarks/python/benchmark.py", line 312, in main
    benchmarker.report(config,
  File "/code/tensorrt_llm/benchmarks/python/gpt_benchmark.py", line 457, in report
    report_dict = super().get_report_dict()
  File "/code/tensorrt_llm/benchmarks/python/base_benchmark.py", line 111, in get_report_dict
    report_dict["compute_cap"] = "sm" + get_compute_cap()
  File "/code/tensorrt_llm/benchmarks/python/base_benchmark.py", line 27, in get_compute_cap
    output = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nvidia-smi', '--query-gpu=compute_cap', '--format=csv']' returned non-zero exit status 2.

```

**Comment by byshiue** [comment]
It fails when it try to parse the sm version of your GPU https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/benchmarks/python/base_benchmark.py#L27-L30. I am not sure the reason, it may be because some driver version. Can you share your driver version? 

A quick workaround for your case is changing the codes to
```python
def get_compute_cap():
    return 70
```
directly.

**Comment by hurun** [comment]
> It fails when it try to parse the sm version of your GPU https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/benchmarks/python/base_benchmark.py#L27-L30. I am not sure the reason, it may be because some driver version. Can you share your driver version?
> 
> A quick workaround for your case is changing the codes to
> 
> ```python
> def get_compute_cap():
>     return 70
> ```
> 
> directly.

it works. Thanks a lot
def get_compute_cap():
    return '70'

**Comment by hurun** [comment]
close issue
