### ISSUE TITLE
KV-int8 calibration  OOM

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/TensorRT-LLM#195]
I'm using 2 V100 to test kv-int8 performance.

But it complains OOM. 

How can we fix this error?

```shell
CUDA_VISIBLE_DEVICES=0,1 python3 hf_llama_convert.py -i /data/vicuna-13b/vicuna-13b-v1.5/ -o ./llama-kv-int8/smooth_llama_13B/int8_kv_cache/ --calibrate-kv-cache -t fp16 -tp 2
```

**Comment by sleepwalker2017** [comment]
```
saving weights: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 280/280 [01:38<00:00,  2.83it/s]
Process SpawnPoolWorker-13:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/root/anaconda3/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "/root/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 147, in rebuild_cuda_tensor
    storage = storage_cls._new_shared_cuda(
  File "/root/anaconda3/lib/python3.9/site-packages/torch/storage.py", line 1085, in _new_shared_cuda
    return torch.UntypedStorage._new_shared_cuda(*args, **kwargs)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by byshiue** [comment]
You can try using single processor to convert the model (`--processes 1`).

**Comment by sleepwalker2017** [comment]
> You can try using single processor to convert the model (`--processes 1`).

thank you. I used -p 2, and it's done.
