### ISSUE TITLE
Is MPI required even multi device is disabled?

### ISSUE THREAD

**Issue by jlewi** [NVIDIA/TensorRT-LLM#1959]
### System Info

- CPU x86_64

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I'm trying to build the wheel as follows

```
python3 ../tensorrt_llm/scripts/build_wheel.py --trt_root ${TRT_ROOT} -D "CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-12.3/" -D "ENABLE_MULTI_DEVICE=0"
```

I end up with a linking error because MPI is missing.

```
[100%] Building CXX object tensorrt_llm/executor_worker/CMakeFiles/executorWorker.dir/executorWorker.cpp.o
[100%] Linking CXX executable executorWorker
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `ompi_mpi_char'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Wait'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Mrecv'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `ompi_mpi_uint64_t'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Comm_spawn'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Get_count'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `tensorrt_llm::mpi::MpiComm::MpiComm(ompi_communicator_t*, bool)'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `ompi_mpi_comm_self'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Info_set'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `ompi_mpi_comm_world'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `tensorrt_llm::mpi::MpiComm::mprobe(int, int, ompi_message_t**, ompi_status_public_t*) const'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Info_create'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Barrier'
collect2: error: ld returned 1 exit status
make[3]: *** [tensorrt_llm/executor_worker/CMakeFiles/executorWorker.dir/build.make:112: tensorrt_llm/executor_worker/executorWorker] Error 1
make[2]: *** [CMakeFiles/Makefile2:1192: tensorrt_llm/executor_worker/CMakeFiles/executorWorker.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1199: tensorrt_llm/executor_worker/CMakeFiles/executorWorker.dir/rule] Error 2
make: *** [Makefile:335: executorWorker] Error 2
Traceback (most recent call last):
  File "/home/build/backend/build/../tensorrt_llm/scripts/build_wheel.py", line 352, in <module>
    main(**vars(args))
  File "/home/build/backend/build/../tensorrt_llm/scripts/build_wheel.py", line 166, in main
    build_run(
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
```

I don't have MPI which is why I was disabling multi-device. 

### Expected behavior

I expect this to compile with out MPI being needed. My assumption was that MPI is only required for multi-device. That assumption could be incorrect. I was hoping to be able to compile for single device without needing MPI. Is MPI needed even for single device? 

### actual behavior

I got a linking error because MPI is missing

```
[100%] Building CXX object tensorrt_llm/executor_worker/CMakeFiles/executorWorker.dir/executorWorker.cpp.o
[100%] Linking CXX executable executorWorker
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `ompi_mpi_char'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Wait'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Mrecv'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `ompi_mpi_uint64_t'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Comm_spawn'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Get_count'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `tensorrt_llm::mpi::MpiComm::MpiComm(ompi_communicator_t*, bool)'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `ompi_mpi_comm_self'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Info_set'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `ompi_mpi_comm_world'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `tensorrt_llm::mpi::MpiComm::mprobe(int, int, ompi_message_t**, ompi_status_public_t*) const'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Info_create'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Barrier'
collect2: error: ld returned 1 exit status
make[3]: *** [tensorrt_llm/executor_worker/CMakeFiles/executorWorker.dir/build.make:112: tensorrt_llm/executor_worker/executorWorker] Error 1
make[2]: *** [CMakeFiles/Makefile2:1192: tensorrt_llm/executor_worker/CMakeFiles/executorWorker.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1199: tensorrt_llm/executor_worker/CMakeFiles/executorWorker.dir/rule] Error 2
make: *** [Makefile:335: executorWorker] Error 2
Traceback (most recent call last):
  File "/home/build/backend/build/../tensorrt_llm/scripts/build_wheel.py", line 352, in <module>
    main(**vars(args))
  File "/home/build/backend/build/../tensorrt_llm/scripts/build_wheel.py", line 166, in main
    build_run(
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
```

### additional notes

I also had to remove `mpi4py` from `requirements.txt` to try to get to build without MultiDevice support.

```
  # N.B Hack: We remove mpi4py from the requirements because we don't have mpi libraries.
      # Hopefully that should only be needed for multi device support
      sed '/mpi4py/d' -i ../tensorrt_llm/requirements.txt 
```

**Comment by QiJune** [comment]
@Funatiq  Could you please have a look? Thanks

**Comment by achartier** [comment]
Could you try with the following option to build_wheel.py
```
--extra-cmake-vars ENABLE_MULTI_DEVICE=0
```

**Comment by jlewi** [comment]
I'm trying to build it now with openmpi. It takes such a long time to build that if I have success with OpenMPI I may not want to bother with rerunning the experiments.

**Comment by achartier** [comment]
Fair enough. If building for a specific target architecture, `-a native` can provide a significant build time reduction.

**Comment by liuweijie19980216** [comment]
Its a Bug, I also have the issue.

**Comment by whitesscott** [comment]
### The error I get is identical to this issue. I'm compiling it on nvidia agx orin dev kit. ###
If you can tell me where in the code the ""ld: ../libtensorrt_llm.so: undefined reference to..."" are I'll edit them out and try again. 

_Here is how I attempt to build tensorrt-llm._ 
Installed these ubuntu packages
libopenmpi-dev libopenmpi3 libcaf-openmpi-3 openmpi-bin openmpi-common

_Added the following hoping openmpi lib's location would help._ 
export LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/openmpi/lib:$LD_LIBRARY_PATH

_This is the build command._
python3 ./scripts/build_wheel.py --cuda_architectures "native" \
--extra-cmake-vars "ENABLE_MULTI_DEVICE=0" \
--python_bindings

_This is where compilation has errored out._
[100%] Built target nvinfer_plugin_tensorrt_llm
[100%] Building CXX object tensorrt_llm/executor_worker/CMakeFiles/executorWorker.dir/executorWorker.cpp.o
[100%] Linking CXX executable executorWorker
/usr/bin/ld: ../libtensorrt_llm.so: undefined reference to `ompi_mpi_comm_null'
/usr/bin/ld: ../libtensorrt_llm.so: undefined reference to `ompi_mpi_char'
/usr/bin/ld: ../libtensorrt_llm.so: undefined reference to `ompi_mpi_group_null'
/usr/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Comm_group'
/usr/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Recv'
/usr/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Wait'
/usr/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Mrecv'
/usr/bin/ld: ../libtensorrt_llm.so: undefined reference to `ompi_mpi_uint64_t'
/usr/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Group_size'
/usr/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Comm_spawn'
/usr/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Comm_create_group'
/usr/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Get_count'
/usr/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Group_incl'
/usr/bin/ld: ../libtensorrt_llm.so: undefined reference to `tensorrt_llm::mpi::MpiComm::MpiComm(ompi_communicator_t*, bool)'
/usr/bin/ld: ../libtensorrt_llm.so: undefined reference to `ompi_mpi_comm_self'
/usr/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Info_set'
/usr/bin/ld: ../libtensorrt_llm.so: undefined reference to `ompi_mpi_comm_world'
/usr/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Group_rank'
/usr/bin/ld: ../libtensorrt_llm.so: undefined reference to `tensorrt_llm::mpi::MpiComm::mprobe(int, int, ompi_message_t**, ompi_status_public_t*) const'
/usr/bin/ld: ../libtensorrt_llm.so: undefined reference to `ompi_mpi_int64_t'
/usr/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Info_create'
/usr/bin/ld: ../libtensorrt_llm.so: undefined reference to `MPI_Barrier'
collect2: error: ld returned 1 exit status

gmake[3]: *** [tensorrt_llm/executor_worker/CMakeFiles/executorWorker.dir/build.make:115: tensorrt_llm/executor_worker/executorWorker] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:1458: tensorrt_llm/executor_worker/CMakeFiles/executorWorker.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:1465: tensorrt_llm/executor_worker/CMakeFiles/executorWorker.dir/rule] Error 2
gmake: *** [Makefile:400: executorWorker] Error 2
Traceback (most recent call last):
  File "/home/scott/.git/TensorRT-LLM/./scripts/build_wheel.py", line 404, in <module>
    main(**vars(args))
  File "/home/scott/.git/TensorRT-LLM/./scripts/build_wheel.py", line 195, in main
    build_run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cmake --build . --config Release --parallel 8 --target tensorrt_llm nvinfer_plugin_tensorrt_llm th_common bindings   executorWorker  ' returned non-zero exit status 2.

**Comment by Shixiaowei02** [comment]
The issue has disappeared in the latest main branch.
