### ISSUE TITLE
[Bug] Mistral Nemo 12B smoothquant convert error

### ISSUE THREAD

**Issue by fan-niu** [NVIDIA/TensorRT-LLM#2005]
### System Info

GPU: NVIDIA A100
Driver Version: 545.23.08
CUDA: 12.3
versions:
https://github.com/NVIDIA/TensorRT-LLM.git (ab49b93718b906030bcec0c817b10ebb373d4179)
https://github.com/triton-inference-server/tensorrtllm_backend.git (97feb8fbca593c6b89eb9d4ed7f016bf37ceb848)

### Who can help?
@kaiyux @Tracin @ncomly-nvidia 

_No response_

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Convert script:
model_path=Mistral-Nemo-Instruct-2407   (https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407)
convert_model_path=Mistral-Nemo-Instruct-2407-smoothquant
python3 ./tensorrtllm_backend/tensorrt_llm/examples/llama/convert_checkpoint.py \
    --model_dir ${model_path} \
    --output_dir ${convert_model_path} \
    --dtype float16 \
    --smoothquant 0.5 \
    --per_token \
    --per_channel \
    --tp_size 1

### Expected behavior

Generate the converted model normally

### actual behavior

Error log:
`[TensorRT-LLM] TensorRT-LLM version: 0.11.0
0.11.0
Loading checkpoint shards:   0%|                                                                                                | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/code/./tensorrtllm_backend/tensorrt_llm/examples/llama/convert_checkpoint.py", line 461, in <module>
    main()
  File "/code/./tensorrtllm_backend/tensorrt_llm/examples/llama/convert_checkpoint.py", line 453, in main
    convert_and_save_hf(args)
  File "/code/./tensorrtllm_backend/tensorrt_llm/examples/llama/convert_checkpoint.py", line 339, in convert_and_save_hf
    LLaMAForCausalLM.quantize(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/model.py", line 411, in quantize
    convert.quantize(hf_model_dir,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 1226, in quantize
    hf_model = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3838, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 4298, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 895, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/modeling.py", line 362, in set_module_tensor_to_device
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([1024, 5120]) in "weight" (which has shape torch.Size([1280, 5120])), this look incorrect.
][TensorRT-LLM] TensorRT-LLM version: 0.11.0
`

### additional notes

I tried converting to float16, but it also reported an error. But mainly focus on smoothquant

**Comment by fan-niu** [comment]
@kaiyux @Tracin @ncomly-nvidia Could you please pay attention to this issue? Thanks a lot if there are any updates

**Comment by eleapttn** [comment]
Hello!

Similar issue here. Any news about the integration of this model?
Is it related to transformers version and this PR? https://github.com/huggingface/transformers/pull/32050

The logs are the following (`pp_size` and `tp_size` at `1`)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/modeling_utils.py", line 465, in load
    param.value = weights[name]
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/parameter.py", line 133, in value
    assert v.shape == self.shape, \
AssertionError: The value updated is not the same shape as the original. Updated: (6144, 5120), original: (7680, 5120)
```

Thanks!
