### ISSUE TITLE
Failed to run Llama 2 70B model with tp_size = 2

### ISSUE THREAD

**Issue by yunfeng-scale** [NVIDIA/TensorRT-LLM#203]
Built engine with
```
python /code/tensorrt_llm/examples/llama/build.py \
  --model_dir /model_weights/llama-2-70b \
  --dtype float16 \
  --remove_input_padding \
  --use_gpt_attention_plugin float16 \
  --enable_context_fmha \
  --use_gemm_plugin float16 \
  --output_dir /model_weights/llama-2-70b-trt-llm \
  --max_batch_size 50 \
  --max_input_len 4096 \
  --max_output_len 4096 \
  --world_size 2 \
  --tp_size 2
```

and run the engine on 2xA100 80G with
```
mpirun -n 2 --allow-run-as-root python3 /code/tensorrt_llm/examples/llama/run.py \
  --max_output_len=100 \
  --tokenizer_dir /model_weights/llama-2-70b/ \
  --engine_dir=/model_weights/llama-2-70b-trt-llm/ \
  --input_text "San Francisco is a" \
  --streaming
```

Error I'm seeing is
```
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/llama/run.py", line 275, in <module>
    generate(**vars(args))
  File "/code/tensorrt_llm/examples/llama/run.py", line 236, in generate
    decoder = tensorrt_llm.runtime.GenerationSession(model_config,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 306, in __init__
    self.runtime = _Runtime(engine_buffer, mapping)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 143, in __init__
    self.__prepare(mapping, engine_buffer)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 163, in __prepare
    address = CUASSERT(cudart.cudaMalloc(self.engine.device_memory_size))[0]
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 92, in CUASSERT
    raise RuntimeError(
RuntimeError: CUDA ERROR: 2, error code reference: https://nvidia.github.io/cuda-python/module/cudart.html#cuda.cudart.cudaError_t
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/llama/run.py", line 275, in <module>
    generate(**vars(args))
  File "/code/tensorrt_llm/examples/llama/run.py", line 236, in generate
    decoder = tensorrt_llm.runtime.GenerationSession(model_config,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 306, in __init__
    self.runtime = _Runtime(engine_buffer, mapping)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 143, in __init__
    self.__prepare(mapping, engine_buffer)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 163, in __prepare
    address = CUASSERT(cudart.cudaMalloc(self.engine.device_memory_size))[0]
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 92, in CUASSERT
    raise RuntimeError(
RuntimeError: CUDA ERROR: 2, error code reference: https://nvidia.github.io/cuda-python/module/cudart.html#cuda.cudart.cudaError_t
Exception ignored in: <function _Runtime.__del__ at 0x7fdc14fa7c70>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 232, in __del__
    cudart.cudaFree(self.address)
AttributeError: '_Runtime' object has no attribute 'address'
Exception ignored in: <function _Runtime.__del__ at 0x7fcec9dabc70>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 232, in __del__
    cudart.cudaFree(self.address)
AttributeError: '_Runtime' object has no attribute 'address'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[40766,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by byshiue** [comment]
It may be OOM. Can you try smaller batch size and input/output length when you build the engine?

**Comment by yunfeng-scale** [comment]
posted to wrong issue, reposting here:

> I think this is due to the engine is trying to allocate too large of a KV cache? is my calculation correct?
> 2(k and v)*2(float16)*80(layer)*8192(hidden size)/8(kv heads ratio)*4096(max_seq_len)*150(batch size)/2(tp_size)

**Comment by yunfeng-scale** [comment]
@byshiue yes it's due to OOM, it's trying to allocate memory with `self.engine.device_memory_size` which is 25GB. can you help me understand how it gets to 25GB here? my rough calculation gets me 100GB which is 4x of what's being requested

**Comment by byshiue** [comment]
`self.engine.device_memory_size` is the workspace size required by TensorRT engine, it does not contains the k/v cache. k/v cache is allocated outside and pass into TensorRT engine as an input.

**Comment by yunfeng-scale** [comment]
Is there a way for me to calculate `self.engine.device_memory_size`?

**Comment by byshiue** [comment]
It is little hard. The workspace contains workspace for TensorRT fused kernels. We don't know how many workspace they  need.

**Comment by byshiue** [comment]
Close this bug because it is in-activate. Feel free to reopen it if needed.
