### ISSUE TITLE
ERROR: No matching distribution found for nvidia-modelopt==0.9.3

### ISSUE THREAD

**Issue by KeitaW** [NVIDIA/TensorRT-LLM#2078]
### System Info

Tested with nvcr.io/nvidia/tritonserver:24.07-trtllm-python-py3 

### Who can help?

Hi @Tracin,

https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/quantization advises to use `nvidia-modelopt==0.93` but it seems that the version has been depilated (https://pypi.nvidia.com/nvidia-modelopt/). 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com nvidia-modelopt==0.9.3
```

### Expected behavior

pip installs `nvidia-modelopt==0.9.3`.

### actual behavior

```
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
ERROR: Could not find a version that satisfies the requirement nvidia-modelopt==0.9.3 (from versions: 0.11.0, 0.11.1, 0.11.2, 0.13.0, 0.13.1, 0.15.0)
ERROR: No matching distribution found for nvidia-modelopt==0.9.3
```

### additional notes

I have also tried to install `nvidia-modelopt==0.15.0` per instruction in https://github.com/NVIDIA/TensorRT-Model-Optimizer. However, installing this version of `nvidia-modelopt` in `nvcr.io/nvidia/tritonserver:24.07-trtllm-python-py3` causes following import error:

```
Traceback (most recent call last):
  File "/workspace/src/llama/quantize.py", line 5, in <module>
    from tensorrt_llm.quantization import (quantize_and_export,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/__init__.py", line 32, in <module>
    import tensorrt_llm.functional as functional
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/functional.py", line 28, in <module>
    from . import graph_rewriting as gw
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/graph_rewriting.py", line 12, in <module>
    from .network import Network
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/network.py", line 27, in <module>
    from tensorrt_llm.module import Module
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/module.py", line 17, in <module>
    from ._common import default_net
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_common.py", line 31, in <module>
    from ._utils import str_dtype_to_trt
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_utils.py", line 30, in <module>
    from tensorrt_llm.bindings.BuildInfo import ENABLE_MULTI_DEVICE
ImportError: /usr/local/lib/python3.10/dist-packages/tensorrt_llm/bindings.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
make: *** [Makefile:65: quantize-llama] Error 1
```

Appreciate if you could advice `nvidia-modelopt` version I should install to this container image. Thank you!

**Comment by KeitaW** [comment]
Found existing issue https://github.com/NVIDIA/TensorRT-LLM/issues/1895. Closing.
