### ISSUE TITLE
Conver qwen2-57B-A14B failed

### ISSUE THREAD

**Issue by zymy-chen** [NVIDIA/TensorRT-LLM#2109]
### System Info

GPU Name: 8 * H20
TensorRT-LLM : 0.12.0.dev2024080600
NVIDIA-SMI 535.154.05            Driver Version: 535.154.05   CUDA Version: 12.4 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

python convert_checkpoint.py --model_dir /home/jiangkun/qwen2-moe-57B-A14B/  --output_dir /home/jiangkun/L20_checkpoint/0110/qwen2-moe-57B-A14B/fp16/8-gpu/ --dtype float16   --tp_size 8  --workers 8

### Expected behavior

convert checkpoint success

### actual behavior

python convert_checkpoint.py --model_dir /home/jiangkun/qwen2-moe-57B-A14B/  --output_dir /home/jiangkun/L20_checkpoint/0110/qwen2-moe-57B-A14B/fp16/8-gpu/ --dtype float16   --tp_size 8
[TensorRT-LLM] TensorRT-LLM version: 0.12.0.dev2024080600
0.12.0.dev2024080600
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 29/29 [09:15<00:00, 19.16s/it]
Traceback (most recent call last):
  File "/home/cj/main_8.8/0808_trtllm_master/TensorRT-LLM/examples/qwen/convert_checkpoint.py", line 309, in <module>
    main()
  File "/home/cj/main_8.8/0808_trtllm_master/TensorRT-LLM/examples/qwen/convert_checkpoint.py", line 301, in main
    convert_and_save_hf(args)
  File "/home/cj/main_8.8/0808_trtllm_master/TensorRT-LLM/examples/qwen/convert_checkpoint.py", line 257, in convert_and_save_hf
    execute(args.workers, [convert_and_save_rank] * world_size, args)
  File "/home/cj/main_8.8/0808_trtllm_master/TensorRT-LLM/examples/qwen/convert_checkpoint.py", line 264, in execute
    f(args, rank)
  File "/home/cj/main_8.8/0808_trtllm_master/TensorRT-LLM/examples/qwen/convert_checkpoint.py", line 247, in convert_and_save_rank
    qwen = QWenForCausalLM.from_hugging_face(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/qwen/model.py", line 316, in from_hugging_face
    weights = load_weights_from_hf_model(hf_model, config)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/qwen/convert.py", line 1239, in load_weights_from_hf_model
    weights = convert_hf_qwen(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/qwen/convert.py", line 756, in convert_hf_qwen
    k_bias = dup_kv_weight(k_bias, num_key_value_heads,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/qwen/convert.py", line 526, in dup_kv_weight
    v.shape[1])
IndexError: tuple index out of range

### additional notes

It work qwen2-72B normally

**Comment by nv-guomingz** [comment]
I think this issue is a expected error since the num_attention_heads of this model is 28 which can not divided by tp_size 8.
Please try to run this model with tp4 rather than tp8.

**Comment by zymy-chen** [comment]
> I think this issue is a expected error since the num_attention_heads of this model is 28 which can not divided by tp_size 8. Please try to run this model with tp4 rather than tp8.
but it doesn't work on H20，it comes up oom

**Comment by lfr-0531** [comment]
> > but it doesn't work on H20，it comes up oom

You can try quantization to compress the model, then deploy on H20.
