### ISSUE TITLE
token_ids = -1 when setting temperature=0.0001 for int4_awq quantization

### ISSUE THREAD

**Issue by AGI-player** [NVIDIA/TensorRT-LLM#2138]
version: 
[TensorRT-LLM] TensorRT-LLM version: 0.12.0.dev2024080600

checkpoint convert:
python /load/trt_llm/TensorRT-LLM/examples/quantization/quantize.py --model_dir /load/Qwen1.5-14B-Chat/ --dtype bfloat16 --qformat int4_awq --awq_block_size 128 --output_dir /load/output/trt_llm/trt_ckpts_qw14/bf16_awq_1gpu/ --calib_dataset /load/data/train_all_data_2qw.json --calib_size 40 --batch_size 1 --calib_max_seq_length 512 --tp_size 1

build engine:
trtllm-build --checkpoint_dir /load/output/trt_llm/trt_ckpts_qw14/bf16_awq_1gpu/ --output_dir /load/output/trt_llm/Qwen1.5-14B-Chat/bf16_awq_1gpu/ --max_batch_size 128 --max_input_len 8192 --max_seq_len 8192 --gemm_plugin bfloat16 --gpt_attention_plugin bfloat16 --paged_kv_cache enable --remove_input_padding enable --context_fmha enable --multiple_profiles enable --max_num_tokens 49152 --workers 1

using fastapi_server:
python /load/trt_llm/TensorRT-LLM/examples/apps/fastapi_server.py /load/output/trt_llm/Qwen1.5-14B-Chat/bf16_awq_1gpu/ --tokenizer /load/Qwen1.5-14B-Chat/ --port 9001 --tp_size 1

request as follow is ok:
![image](https://github.com/user-attachments/assets/3dc094ce-6339-4d31-8874-3eba765722c8)

but when i set temperature=0.0001, got errors:
RROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/env/trt_llm/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/env/trt_llm/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/env/trt_llm/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/env/trt_llm/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/env/trt_llm/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/env/trt_llm/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/env/trt_llm/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/env/trt_llm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/env/trt_llm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/env/trt_llm/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/env/trt_llm/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/env/trt_llm/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/env/trt_llm/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/env/trt_llm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/env/trt_llm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/env/trt_llm/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/env/trt_llm/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/env/trt_llm/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/load/trt_llm/TensorRT-LLM/examples/apps/fastapi_server.py", line 65, in generate
    await promise.aresult()
  File "/env/trt_llm/lib/python3.10/site-packages/tensorrt_llm/executor.py", line 213, in aresult
    await self.aresult_step()
  File "/env/trt_llm/lib/python3.10/site-packages/tensorrt_llm/executor.py", line 204, in aresult_step
    self.handle_generation_msg(tensors, error)
  File "/env/trt_llm/lib/python3.10/site-packages/tensorrt_llm/hlapi/llm.py", line 47, in handle_generation_msg
    beam_output.text = self.tokenizer.decode(beam_output.token_ids)
  File "/env/trt_llm/lib/python3.10/site-packages/tensorrt_llm/hlapi/tokenizer.py", line 33, in decode
    return self.tokenizer.decode(token_ids, *args, **kwargs)
  File "/env/trt_llm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 4034, in decode
    return self._decode(
  File "/env/trt_llm/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 651, in _decode
    text = self._tokenizer.decode(token_ids, skip_special_tokens=skip_special_tokens)
OverflowError: out of range integral type conversion attempted

try to debug and find token_ids = -1
![image](https://github.com/user-attachments/assets/306173e4-a73f-4025-b0d5-92dc7ebf1c6c)

**Comment by LinPoly** [comment]
Hi @AGI-player , thanks for reporting this! We don't have your calibration dataset but I think the finding is dataset agnostic. In your build settings, the logits_dtype would be float16, whose range is [-65504, 65504], being divided by 0.0001 (your second temperature) could lead to huge cancellation error or even overflow. I set **logits_dtype to float32** and get normal output. Could you please add this build option and try again?

**Comment by AGI-player** [comment]
> Hi [@AGI-player](https://github.com/AGI-player) , thanks for reporting this! We don't have your calibration dataset but I think the finding is dataset agnostic. In your build settings, the logits_dtype would be float16, whose range is [-65504, 65504], being divided by 0.0001 (your second temperature) could lead to huge cancellation error or even overflow. I set **logits_dtype to float32** and get normal output. Could you please add this build option and try again?

ok，thanks~
