### ISSUE TITLE
Fail to set max_output_len to 400 on starcoder

### ISSUE THREAD

**Issue by xiyuecangxin** [NVIDIA/TensorRT-LLM#214]
The code runs well when `max_output_len` is set to 300. However, it throws an error when set to 400. Could you please look into the reason?
Here is the info from `/usr/local/mpi/bin/mpirun -np 2 python3 /app/tensorrt_llm/examples/gpt/run.py --engine_dir /xxx/starcoder_outputs_tp2 --tokenizer /xxx/starcoder-16bit --input_text def\ print_hello_world\(\): --max_output_len 400`
```
[10/31/2023-06:37:02] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
Traceback (most recent call last):
  File "/app/tensorrt_llm/examples/gpt/run.py", line 351, in <module>
    generate(**vars(args))
  File "/app/tensorrt_llm/examples/gpt/run.py", line 327, in generate
    outputs = decoder.decode(input_ids,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 514, in wrapper
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1887, in decode
    return self.decode_regular(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1659, in decode_regular
    should_stop, next_step_buffer, tasks, context_lengths, host_context_lengths, attention_mask, logits = self.handle_per_step(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1430, in handle_per_step
    self.runtime._set_shape(context, ctx_shape)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 202, in _set_shape
    raise ValueError(
ValueError: Couldn't assign past_key_value_0 with shape torch.Size([1, 2, 1, 405, 128]), engine supports [min, opt, max] = [(1, 2, 1, 0, 128), (128, 2, 1, 200, 128), (256, 2, 1, 400, 128)]
[10/31/2023-06:37:02] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
Traceback (most recent call last):
  File "/app/tensorrt_llm/examples/gpt/run.py", line 351, in <module>
    generate(**vars(args))
  File "/app/tensorrt_llm/examples/gpt/run.py", line 327, in generate
    outputs = decoder.decode(input_ids,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 514, in wrapper
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1887, in decode
    return self.decode_regular(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1659, in decode_regular
    should_stop, next_step_buffer, tasks, context_lengths, host_context_lengths, attention_mask, logits = self.handle_per_step(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1430, in handle_per_step
    self.runtime._set_shape(context, ctx_shape)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 202, in _set_shape
    raise ValueError(
ValueError: Couldn't assign past_key_value_0 with shape torch.Size([1, 2, 1, 405, 128]), engine supports [min, opt, max] = [(1, 2, 1, 0, 128), (128, 2, 1, 200, 128), (256, 2, 1, 400, 128)]
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[36005,1],1]
  Exit code:    1
```

**Comment by jdemouth-nvidia** [comment]
Hi @xiyuecangxin ,

I suspect you’re building a model with a max seqlen of 400 based on that text in the error message:

```
[min, opt, max] = [(1, 2, 1, 0, 128), (128, 2, 1, 200, 128), (256, 2, 1, 400, 128)]
```

Can you increase the max sequence length when building the engine, please?

Or, provide us with the build command if you don’t think it’s the issue. 

Thanks,
Julien

**Comment by xiyuecangxin** [comment]
> Refe

Thanks, it works

**Comment by jdemouth-nvidia** [comment]
Cool. Thanks!
