### ISSUE TITLE
KeyError: 'llava_llama'

### ISSUE THREAD

**Issue by tiend1** [NVIDIA/TensorRT-LLM#2158]
Hi TensorRT-LLM team, Your work is incredible.

By following the READme file for [multi-modeling](https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/multimodal/README.md), we were sucess to run the VILA model with fp16.
To get better optimization,  we want to do int4 optimize. 
```
Different quantization methods supported in LLaMA can be applied to LLaVA/VILA as well, such as INT4/INT8 weight-only, SmoothQuant, and INT4 Activation-Aware Quantization (AWQ). Detailed instructions can be found in LLaMA [README](https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/llama/README.md).

For example,

# INT4 weight only
python ../llama/convert_checkpoint.py \
     --model_dir tmp/hf_models/${MODEL_NAME} \
     --dtype float16 \
     --output_dir tmp/trt_models/${MODEL_NAME}/int4_weightonly/1-gpu \
     --use_weight_only \
     --weight_only_precision int4

# INT4 AWQ
python ../quantization/quantize.py \
     --model_dir tmp/hf_models/${MODEL_NAME} \
     --output_dir tmp/trt_models/${MODEL_NAME}/int4_awq/1-gpu \
     --dtype float16 \
     --qformat int4_awq \
     --calib_size 32
```

However, the bug related to the architecture "KeyError: 'llava_llama'". So we really need a help to fix this bug.
```
python3 ../quantization/quantize.py      --model_dir tmp/hf_models/${MODEL_NAME}      --output_dir tmp/trt_models/${MODEL_NAME}/int4_awq/1-gpu      --dtype float16      --qformat int4_awq      --calib_size 32
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[TensorRT-LLM] TensorRT-LLM version: 0.13.0.dev2024082700
/usr/local/lib/python3.10/dist-packages/modelopt/torch/quantization/tensor_quant.py:92: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  scaled_e4m3_abstract = torch.library.impl_abstract("trt::quantize_fp8")(
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 982, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 684, in __getitem__
    raise KeyError(key)
KeyError: 'llava_llama'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/develop/llm/VILA/demo_trt_llm/TensorRT-LLM/examples/multimodal/../quantization/quantize.py", line 107, in <module>
    quantize_and_export(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/quantization/quantize_by_modelopt.py", line 388, in quantize_and_export
    model = get_model(model_dir, dtype, device=device)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/quantization/quantize_by_modelopt.py", line 175, in get_model
    hf_config = AutoConfig.from_pretrained(ckpt_path, trust_remote_code=True)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 984, in from_pretrained
    raise ValueError(
ValueError: The checkpoint you are trying to load has model type `llava_llama` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
/usr/lib/python3.10/tempfile.py:1008: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpkwnu1es5'>
  _warnings.warn(warn_message, ResourceWarning)
root@tienduchoang-pc:/develop/llm/VILA/demo_trt_llm/TensorRT-LLM/examples/multimodal# python3 ../quantization/quantize.py      --model_dir tmp/hf_models/${MODEL_NAME}      --output_dir tmp/trt_models/${MODEL_NAME}/int4_awq/1-gpu      --dtype float16      --qformat int4_awq      --calib_size 32
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[TensorRT-LLM] TensorRT-LLM version: 0.13.0.dev2024082700
/usr/local/lib/python3.10/dist-packages/modelopt/torch/quantization/tensor_quant.py:92: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  scaled_e4m3_abstract = torch.library.impl_abstract("trt::quantize_fp8")(
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 982, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 684, in __getitem__
    raise KeyError(key)
KeyError: 'llava_llama'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/develop/llm/VILA/demo_trt_llm/TensorRT-LLM/examples/multimodal/../quantization/quantize.py", line 107, in <module>
    quantize_and_export(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/quantization/quantize_by_modelopt.py", line 388, in quantize_and_export
    model = get_model(model_dir, dtype, device=device)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/quantization/quantize_by_modelopt.py", line 175, in get_model
    hf_config = AutoConfig.from_pretrained(ckpt_path, trust_remote_code=True)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 984, in from_pretrained
    raise ValueError(
ValueError: The checkpoint you are trying to load has model type `llava_llama` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
/usr/lib/python3.10/tempfile.py:1008: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmp805483cm'>
  _warnings.warn(warn_message, ResourceWarning)
```

**Comment by amukkara** [comment]
This is an issue with transformers library. `model_type=llava_llama` specified in [config.json](https://huggingface.co/Efficient-Large-Model/VILA1.5-3b/blob/42d1dda6807cc521ef27674ca2ae157539d17026/config.json#L167) is not recognized by transformers.

This code snippet faces same error:
```
from transformers import AutoConfig                                                            
hf_config = AutoConfig.from_pretrained("tmp/hf_models/${MODEL_NAME}", trust_remote_code=True)
```

**Comment by yueshen2016** [comment]
Hi @tiend1 , could you check if these three [steps](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/multimodal#llava-llava-next-and-vila:~:text=For%20VILA%2C%20we%20need%20a%20few%20more%20steps%20until%20it%20is%20added%20to%20HF%20model%20zoo) are executed before running `convert_checkpoint.py` and `quantize.py`?

**Comment by olibartfast** [comment]
fp16 also works for me with TensorRT-LLM, but fails with the same 'llava_llama' error when I run it on Triton (r24.08).

**Comment by willosonico** [comment]
same error for me here


```shell

/app/TRT-LLM/venv/lib/python3.10/site-packages/megatron/core/tensor_parallel/layers.py:220: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  def forward(ctx, input, weight, bias, gradient_accumulation_fusion,
/app/TRT-LLM/venv/lib/python3.10/site-packages/megatron/core/tensor_parallel/layers.py:250: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  def backward(ctx, grad_output):
[NeMo W 2024-11-04 22:19:57 nemo_logging:349] /app/TRT-LLM/venv/lib/python3.10/site-packages/lightning_fabric/plugins/environments/xla.py:18: DeprecationWarning: `ModuleAvailableCache` is a special case of `RequirementCache`. Please use `RequirementCache(module=...)` instead.
      from lightning_fabric.accelerators.tpu import _XLA_AVAILABLE, TPUAccelerator
    
CONFIG_MAPPING _LazyConfigMapping()
Traceback (most recent call last):
  File "/app/TRT-LLM/venv/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1024, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/app/TRT-LLM/venv/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 725, in __getitem__
    raise KeyError(key)
KeyError: 'llava_llama'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/TRT-LLM/quantize.py", line 141, in <module>
    quantize_and_export(
  File "/app/TRT-LLM/venv/lib/python3.10/site-packages/tensorrt_llm/quantization/quantize_by_modelopt.py", line 519, in quantize_and_export
    model = get_model(model_dir, dtype, device=device)
  File "/app/TRT-LLM/venv/lib/python3.10/site-packages/tensorrt_llm/quantization/quantize_by_modelopt.py", line 197, in get_model
    hf_config = AutoConfig.from_pretrained(ckpt_path, trust_remote_code=True)
  File "/app/TRT-LLM/venv/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1026, in from_pretrained
    raise ValueError(
ValueError: The checkpoint you are trying to load has model type `llava_llama` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
[NeMo W 2024-11-04 22:19:58 nemo_logging:349] /usr/lib/python3.10/tempfile.py:1008: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmp4ohqzzw3'>
      _warnings.warn(warn_message, ResourceWarning)

```
