### ISSUE TITLE
Failed to load Lora adapter for Mixtral-8x7B v 0.1

### ISSUE THREAD

**Issue by u650080** [NVIDIA/TensorRT-LLM#2192]
### System Info

Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 57 bits virtual
  Byte Order:            Little Endian
memeory :500G
GPU :
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA H100 80GB HBM3          Off |   00000000:55:00.0 Off |                    0 |
| N/A   37C    P0             72W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA H100 80GB HBM3          Off |   00000000:68:00.0 Off |                    0 |
| N/A   37C    P0             72W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA H100 80GB HBM3          Off |   00000000:D2:00.0 Off |                    0 |
| N/A   37C    P0             70W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA H100 80GB HBM3          Off |   00000000:E4:00.0 Off |                    0 |
| N/A   37C    P0             72W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
Ubuntu 22.04.4 LTS
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian

nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-modelopt          0.15.1
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.6.68
nvidia-nvtx-cu12         12.1.105
onnx                     1.16.2
optimum                  1.21.4
packaging                24.1
pandas                   2.2.2
pillow                   10.3.0
pip                      22.0.2
polygraphy               0.49.9
protobuf                 5.28.0
psutil                   6.0.0
PuLP                     2.9.0
pyarrow                  17.0.0
pyarrow-hotfix           0.6
pydantic                 2.9.0b2
pydantic_core            2.23.1
Pygments                 2.18.0
pynvml                   11.5.3
pyproject_hooks          1.1.0
python-dateutil          2.9.0.post0
pytz                     2024.1
PyYAML                   6.0.2
regex                    2024.7.24
requests                 2.32.3
rich                     13.8.0
rouge-score              0.1.2
safetensors              0.4.4
scipy                    1.14.1
sentencepiece            0.1.99
setuptools               59.6.0
six                      1.16.0
StrEnum                  0.4.15
sympy                    1.13.2
tensorrt                 10.3.0
tensorrt-cu12            10.3.0
tensorrt-cu12-bindings   10.3.0
tensorrt-cu12-libs       10.3.0
tensorrt-llm             0.13.0.dev2024082700
tokenizers               0.19.1
tomli                    2.0.1
torch                    2.4.0
tqdm                     4.66.5
transformers             4.42.4

It is running inside container.

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

First I fine-tuned models using  Mixtral-8x-7B-v0,1 with lora  (huggingface )with different datasets, so I create 2 adapters 
Lora config :
--lora_r 64 
--lora_alpha 64 
--use_rslora True 
--lora_dropout 0.1 
--lora_target_modules "q_proj,k_proj,v_proj,o_proj" 
So 2 adapters:
   adapter_1 and adapter_2
loging to the tenserrt_llm container:
I follow instruction how to convert Mixtral-8x7B-v0.1 from HF to tensorRT format:

python3 llama/convert_checkpoint.py --model_dir /models/Mixtral-8x7B-v0.1 \
                             --output_dir /app/tllm_checkpoint_mixtral_2gpu_l \
                             --dtype bfloat16 \
                             --tp_size 2 \
                             --lora_plugin  bfloat16 \
                             --moe_ep_size 2

trtllm-build --checkpoint_dir /app/tllm_checkpoint_mixtral_2gpu \
                 --output_dir /app/trt_engines/mixtral/lora_ep2 \
                 --gemm_plugin bfloat16 \
                 --lora_plugin auto \
                 --lora_dir "/app/adapters/adapte_1r" "/app/adapters/adapter_2"\
                 --lora_target_modules attn_q attn_k attn_v

This is output :
[TensorRT-LLM] TensorRT-LLM version: 0.13.0.dev2024082700
[09/04/2024-17:31:42] [TRT-LLM] [I] Set bert_attention_plugin to auto.
[09/04/2024-17:31:42] [TRT-LLM] [I] Set gpt_attention_plugin to auto.
[09/04/2024-17:31:42] [TRT-LLM] [I] Set gemm_plugin to bfloat16.
[09/04/2024-17:31:42] [TRT-LLM] [I] Set gemm_swiglu_plugin to None.
[09/04/2024-17:31:42] [TRT-LLM] [I] Set fp8_rowwise_gemm_plugin to None.
[09/04/2024-17:31:42] [TRT-LLM] [I] Set nccl_plugin to auto.
[09/04/2024-17:31:42] [TRT-LLM] [I] Set lookup_plugin to None.
[09/04/2024-17:31:42] [TRT-LLM] [I] Set lora_plugin to auto.
[09/04/2024-17:31:42] [TRT-LLM] [I] Set moe_plugin to auto.
[09/04/2024-17:31:42] [TRT-LLM] [I] Set mamba_conv1d_plugin to auto.
[09/04/2024-17:31:42] [TRT-LLM] [I] Set context_fmha to True.
[09/04/2024-17:31:42] [TRT-LLM] [I] Set bert_context_fmha_fp32_acc to False.
[09/04/2024-17:31:42] [TRT-LLM] [I] Set remove_input_padding to True.
[09/04/2024-17:31:42] [TRT-LLM] [I] Set reduce_fusion to False.
[09/04/2024-17:31:42] [TRT-LLM] [I] Set enable_xqa to True.
[09/04/2024-17:31:42] [TRT-LLM] [I] Set tokens_per_block to 64.
[09/04/2024-17:31:42] [TRT-LLM] [I] Set use_paged_context_fmha to False.
[09/04/2024-17:31:42] [TRT-LLM] [I] Set use_fp8_context_fmha to False.
[09/04/2024-17:31:42] [TRT-LLM] [I] Set multiple_profiles to False.
[09/04/2024-17:31:42] [TRT-LLM] [I] Set paged_state to True.
[09/04/2024-17:31:42] [TRT-LLM] [I] Set streamingllm to False.
[09/04/2024-17:31:42] [TRT-LLM] [I] Set use_fused_mlp to True.
[09/04/2024-17:31:43] [TRT-LLM] [I] Set dtype to bfloat16.
[09/04/2024-17:31:43] [TRT-LLM] [I] Set paged_kv_cache to True.
[09/04/2024-17:31:43] [TRT-LLM] [W] Overriding paged_state to False
[09/04/2024-17:31:43] [TRT-LLM] [I] Set paged_state to False.
[09/04/2024-17:31:43] [TRT-LLM] [I] max_seq_len is not specified, using deduced value 32768
[09/04/2024-17:31:43] [TRT-LLM] [W] remove_input_padding is enabled, while opt_num_tokens is not set, setting to max_batch_size*max_beam_width. 

[09/04/2024-17:31:43] [TRT-LLM] [W] padding removal and fMHA are both enabled, max_input_len is not required and will be ignored
[09/04/2024-17:31:43] [TRT] [I] [MemUsageChange] Init CUDA: CPU +16, GPU +0, now: CPU 151, GPU 528 (MiB)
[09/04/2024-17:31:46] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +4582, GPU +1268, now: CPU 4889, GPU 1796 (MiB)
[09/04/2024-17:31:46] [TRT] [W] profileSharing0806 is on by default in TensorRT 10.0. This flag is deprecated and has no effect.
[09/04/2024-17:31:46] [TRT-LLM] [I] Set nccl_plugin to bfloat16.
Traceback (most recent call last):
  File "/usr/local/bin/trtllm-build", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 520, in main
    parallel_build(model_config, ckpt_dir, build_config, args.output_dir,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 384, in parallel_build
    passed = build_and_save(rank, rank % workers, ckpt_dir,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 351, in build_and_save
    engine = build_model(build_config,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 344, in build_model
    return build(model, build_config)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/builder.py", line 1101, in build
    model(**inputs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/module.py", line 40, in __call__
    output = self.forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/modeling_utils.py", line 770, in forward
    hidden_states = self.transformer.forward(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/model.py", line 243, in forward
    hidden_states = self.layers.forward(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/modeling_utils.py", line 385, in forward
    hidden_states = layer(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/module.py", line 40, in __call__
    output = self.forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/model.py", line 194, in forward
    hidden_states = self.mlp(hidden_states,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/module.py", line 40, in __call__
    output = self.forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/layers/moe.py", line 520, in forward
    return self.forward_experts(hidden_states, routing, finished,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/layers/moe.py", line 569, in forward_experts
    output = _moe_plugin(self.moe_config,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/layers/moe.py", line 267, in _moe_plugin
    0, "moe_4h_to_h").lora_weights_pointers
AttributeError: 'NoneType' object has no attribute 'lora_weights_pointers'

### Expected behavior

It should be able to load lora adapters  for Mixtral-8x7B.

### actual behavior

It is failing to load a layer which I didn't finetune  it.

### additional notes

why it is looking the layer which it is not finetuned !

**Comment by zongfeijing** [comment]
The params `lora_target_modules` should contain moe releated module names, the module name you can refer this [link](https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/advanced/lora.md#lora-module-id-mapping).

**Comment by u650080** [comment]
even it isn't finetunned it in lora ?
