### ISSUE TITLE
Failed to convert Qwen2-57B-A14B-Instruct when tp_size 8

### ISSUE THREAD

**Issue by kazyun** [NVIDIA/TensorRT-LLM#2200]
when i set tp_size 8 

[TensorRT-LLM] TensorRT-LLM version: 0.12.0.dev2024080600
0.12.0.dev2024080600
Loading checkpoint shards: 100%|████████████████████████████████████████████████| 29/29 [00:03<00:00,  8.20it/s]
############## tp_size:  8 ############# num_head:  4
v.shape: torch.Size([512, 3584])
############## tp_size:  8 ############# num_head:  4
v.shape: torch.Size([512, 3584])
############## tp_size:  8 ############# num_head:  4
v.shape: torch.Size([512])
Traceback (most recent call last):
  File "/root/TensorRT-LLM/examples/qwen/convert_checkpoint.py", line 308, in <module>
    main()
  File "/root/TensorRT-LLM/examples/qwen/convert_checkpoint.py", line 300, in main
    convert_and_save_hf(args)
  File "/root/TensorRT-LLM/examples/qwen/convert_checkpoint.py", line 256, in convert_and_save_hf
    execute(args.workers, [convert_and_save_rank] * world_size, args)
  File "/root/TensorRT-LLM/examples/qwen/convert_checkpoint.py", line 263, in execute
    f(args, rank)
  File "/root/TensorRT-LLM/examples/qwen/convert_checkpoint.py", line 246, in convert_and_save_rank
    qwen = QWenForCausalLM.from_hugging_face(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/qwen/model.py", line 315, in from_hugging_face
    weights = load_weights_from_hf_model(hf_model, config)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/qwen/convert.py", line 1223, in load_weights_from_hf_model
    weights = convert_hf_qwen(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/qwen/convert.py", line 758, in convert_hf_qwen
    k_bias = dup_kv_weight(k_bias, num_key_value_heads,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/qwen/convert.py", line 528, in dup_kv_weight
    v.shape[1])
IndexError: tuple index out of range

But when i set tp_size 4 its OK

**Comment by lfr-0531** [comment]
Similar issue to https://github.com/NVIDIA/TensorRT-LLM/issues/2198.
> currently we don't support the situation when num_attention_heads % tp_size != 0.
