### ISSUE TITLE
Building INT8 Engine for hugging face models

### ISSUE THREAD

**Issue by prawin-srini** [NVIDIA/TensorRT-LLM#2278]
### System Info

TensorRT Model Optimizer: 0.15.1
TensortRT-LLM version: 0.14.0.dev2024100100
Python version 
OS: Ubuntu 22.04
CPU Arch: x86_63
Driver version: 555.42.02
CUDA Version:12.5

### Who can help?

@Tracin 

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Followed the steps highlighted in : [TensorRT-LLM Deployment](https://nvidia.github.io/TensorRT-LLM/architecture/checkpoint.html)

1. Quantized the hugging face GPT2 model to INT8 using the TensorRT Model Optimizer with the default INT8 configuration (INT8_DEFAULT_CFG) from mtq [quantize_script.txt](https://github.com/user-attachments/files/17203020/quantize_script.txt)
2. The quantized model summary is in line with the configuration where attention outputs, lm heads and embeddings are not quantized. While the others have the fake tensors [quantize_model_summary.txt](https://github.com/user-attachments/files/17203060/quantize_model_summary.txt)
3.  The quantized model is then exported into the TensorRT-LLM checkpoint to build the engine. The export was successful with the params default to float16[config.txt](https://github.com/user-attachments/files/17203140/config.txt)

### Expected behavior

Successfully build the TensorRT LLM Engine from the quantized model checkpoint

### actual behavior

The build is unsuccessful resulting in the following error:
Traceback (most recent call last):
  File "/local/home/user/.pyenv/versions/trtllm/bin/trtllm-build", line 8, in <module>
    sys.exit(main())
  File "/local/home/user/.pyenv/versions/3.10.0/envs/trtllm/lib/python3.10/site-packages/tensorrt_llm/commands/build.py", line 575, in main
    parallel_build(model_config, ckpt_dir, build_config, args.output_dir,
  File "/local/home/user/.pyenv/versions/3.10.0/envs/trtllm/lib/python3.10/site-packages/tensorrt_llm/commands/build.py", line 429, in parallel_build
    passed = build_and_save(rank, rank % workers, ckpt_dir,
  File "/local/home/user/.pyenv/versions/3.10.0/envs/trtllm/lib/python3.10/site-packages/tensorrt_llm/commands/build.py", line 396, in build_and_save
    engine = build_model(build_config,
  File "/local/home/user/.pyenv/versions/3.10.0/envs/trtllm/lib/python3.10/site-packages/tensorrt_llm/commands/build.py", line 365, in build_model
    model = model_cls.from_checkpoint(ckpt_dir, config=rank_config)
  File "/local/home/user/.pyenv/versions/3.10.0/envs/trtllm/lib/python3.10/site-packages/tensorrt_llm/models/modeling_utils.py", line 496, in from_checkpoint
    model.load(weights, from_pruned=is_checkpoint_pruned)
  File "/local/home/user/.pyenv/versions/3.10.0/envs/trtllm/lib/python3.10/site-packages/tensorrt_llm/models/modeling_utils.py", line 509, in load
    raise RuntimeError(
RuntimeError: Required but not provided tensors:{'transformer.layers.11.mlp.fc.prequant_scaling_factor', 'transformer.layers.1.mlp.fc.prequant_scaling_factor', 'transformer.layers.2.attention.qkv.prequant_scaling_factor', 'transformer.layers.1.attention.dense.prequant_scaling_factor', 'transformer.layers.8.mlp.fc.prequant_scaling_factor', 'transformer.layers.10.attention.qkv.prequant_scaling_factor', 'transformer.layers.0.mlp.proj.prequant_scaling_factor', 'transformer.layers.5.mlp.proj.prequant_scaling_factor', 'transformer.layers.9.attention.qkv.prequant_scaling_factor', 'transformer.layers.0.mlp.fc.prequant_scaling_factor', 'transformer.layers.0.attention.dense.prequant_scaling_factor', 'transformer.layers.9.mlp.fc.prequant_scaling_factor', 'transformer.layers.4.attention.qkv.prequant_scaling_factor', 'transformer.layers.7.attention.qkv.prequant_scaling_factor', 'transformer.layers.5.attention.qkv.prequant_scaling_factor', 'transformer.layers.5.attention.dense.prequant_scaling_factor', 'transformer.layers.10.attention.dense.prequant_scaling_factor', 'transformer.layers.9.mlp.proj.prequant_scaling_factor', 'transformer.layers.1.mlp.proj.prequant_scaling_factor', 'transformer.layers.3.attention.dense.prequant_scaling_factor', 'transformer.layers.3.attention.qkv.prequant_scaling_factor', 'transformer.layers.6.mlp.fc.prequant_scaling_factor', 'transformer.layers.8.attention.qkv.prequant_scaling_factor', 'transformer.layers.5.mlp.fc.prequant_scaling_factor', 'transformer.layers.7.attention.dense.prequant_scaling_factor', 'transformer.layers.6.attention.dense.prequant_scaling_factor', 'transformer.layers.11.mlp.proj.prequant_scaling_factor', 'transformer.layers.11.attention.dense.prequant_scaling_factor', 'transformer.layers.0.attention.qkv.prequant_scaling_factor', 'transformer.layers.4.mlp.proj.prequant_scaling_factor', 'transformer.layers.4.attention.dense.prequant_scaling_factor', 'transformer.layers.1.attention.qkv.prequant_scaling_factor', 'transformer.layers.8.mlp.proj.prequant_scaling_factor', 'transformer.layers.7.mlp.fc.prequant_scaling_factor', 'transformer.layers.10.mlp.fc.prequant_scaling_factor', 'transformer.layers.11.attention.qkv.prequant_scaling_factor', 'transformer.layers.6.mlp.proj.prequant_scaling_factor', 'transformer.layers.7.mlp.proj.prequant_scaling_factor', 'transformer.layers.4.mlp.fc.prequant_scaling_factor', 'transformer.layers.2.mlp.fc.prequant_scaling_factor', 'transformer.layers.3.mlp.fc.prequant_scaling_factor', 'transformer.layers.8.attention.dense.prequant_scaling_factor', 'transformer.layers.2.mlp.proj.prequant_scaling_factor', 'transformer.layers.2.attention.dense.prequant_scaling_factor', 'transformer.layers.6.attention.qkv.prequant_scaling_factor', 'transformer.layers.3.mlp.proj.prequant_scaling_factor', 'transformer.layers.10.mlp.proj.prequant_scaling_factor', 'transformer.layers.9.attention.dense.prequant_scaling_factor'}

### additional notes

Fix the examples

**Comment by syuoni** [comment]
Hi @prawin-srini , 

The config file seems OK, but the error log shows that some scaling factors are missing from the exported checkpoint (.safetensors file). I suggest trying our script for modelopt quantization: https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/quantization/quantize.py. You can find a demo for int8 SQ here: https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/mpt/README.md#17-smoothquant-and-int8-kv-cache-with-modelopt

Thanks!
