### ISSUE TITLE
crashing on exit

### ISSUE THREAD

**Issue by stas00** [NVIDIA/TensorRT-LLM#2301]
in the docker image: 
```
$ docker run --rm --ipc=host --runtime=nvidia --gpus all --entrypoint /bin/bash -it nvidia/cuda:12.5.1-devel-ubuntu22.04
$ apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev git git-lfs wget
$ pip3 install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com
$ wget https://raw.githubusercontent.com/NVIDIA/TensorRT-LLM/refs/heads/main/examples/llm-api/llm_generate_distributed.py
$ python llm_generate_distributed.py
```
runs but finishes with an error:
```
Exception ignored in: <function IpcQueue.__del__ at 0x7f511f362290>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/executor.py", line 990, in __del__
    self.conn.close()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 177, in close
    self._close()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 361, in _close
    _close(self._handle)
OSError: [Errno 9] Bad file descriptor
```
same with 0.13 or `main`

**Comment by Superjomn** [comment]
The MPIPoolExecutor used in LLM API could conflict with some cluster schedulers such as Slurm, you can try this trick `mpirun -n 1 --oversubscribe python llm_generate_distributed.py`.
