### ISSUE TITLE
llama examples fail to run

### ISSUE THREAD

**Issue by stas00** [NVIDIA/TensorRT-LLM#2303]
Following instructions at https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/llama/README.md
I tried a bunch of different models and they all fail in `run.py` on:
```
Traceback (most recent call last):
  File "/data/stas/faster-ttft/core/dawn/exp/infer/faster-ttft/trt-llm/TensorRT-LLM/examples/llama/../run.py", line 874, in <module>
    main(args)
  File "/data/stas/faster-ttft/core/dawn/exp/infer/faster-ttft/trt-llm/TensorRT-LLM/examples/llama/../run.py", line 681, in main
    runner = runner_cls.from_dir(**runner_kwargs)
  File "/env/lib/conda/ctx-shared-trt-stable/lib/python3.10/site-packages/tensorrt_llm/runtime/model_runner_cpp.py", line 311, in from_dir
    assert max_batch_size <= model_config.max_batch_size
AssertionError
Traceback (most recent call last):
  File "/data/stas/faster-ttft/core/dawn/exp/infer/faster-ttft/trt-llm/TensorRT-LLM/examples/llama/../run.py", line 874, in <module>
    main(args)
  File "/data/stas/faster-ttft/core/dawn/exp/infer/faster-ttft/trt-llm/TensorRT-LLM/examples/llama/../run.py", line 681, in main
    runner = runner_cls.from_dir(**runner_kwargs)
  File "/env/lib/conda/ctx-shared-trt-stable/lib/python3.10/site-packages/tensorrt_llm/runtime/model_runner_cpp.py", line 311, in from_dir
    assert max_batch_size <= model_config.max_batch_size
AssertionError
```

here is a full repro:
```
git clone https://github.com/NVIDIA/TensorRT-LLM/
cd TensorRT-LLM/examples/llama
pip install -r requirements.txt
git clone https://huggingface.co/meta-llama/Llama-2-7b-chat-hf
python convert_checkpoint.py --model_dir Llama-2-7b-chat-hf \
                            --output_dir Llama-2-7b-chat-hf_2gpu_tp2 \
                            --dtype float16 \
                            --tp_size 2
trtllm-build --checkpoint_dir Llama-2-7b-chat-hf_2gpu_tp2 \
            --output_dir trt_engines/Llama-2-7b-chat-hf_2gpu_tp2 \
            --gemm_plugin auto

wget https://www.gutenberg.org/cache/epub/64317/pg64317.txt
awk '{printf "%s\\n", $0} END {printf "\\nSummarize this story:"}' pg64317.txt > pg64317_sanitized.txt

mpirun -n 2 --allow-run-as-root --oversubscribe \
    python ../run.py \
    --max_output_len 128 \
    --max_input_length 32768 \
    --input_file pg64317_sanitized.txt \
    --engine_dir  trt_engines/Llama-2-7b-chat-hf_2gpu_tp2 \
    --tokenizer_dir Llama-2-7b-chat-hf
```

**Comment by karljang** [comment]
@stas00 , Thank you for trying the instructions and sorry about the very delayed response! 😊
The error:
```log
assert max_batch_size <= model_config.max_batch_size
``` 
occurs because TensorRT-LLM treats each line in the input text file as a separate batch item. When you use `--input_file pg64317_sanitized.txt`, the runtime calls `txt_file.readlines()` which splits the file by lines, creating a batch size equal to the number of lines in the file.

Instead, you can create single-line input using this command:
```shell
   awk '{printf "%s", $0} END {printf " Summarize this story:"}' pg64317.txt > pg64317_sanitized.txt
```
But in this case the input length will be much larger than the maximum input length of the model~ :)

**Comment by stas00** [comment]
Better late than never ;) Thank you for addressing my question, @karljang. 

With so many problems with TRT I moved on to vllm/sglang, so can't validate your suggestion any longer.

**Comment by karljang** [comment]
Sorry to hear that. Hope to have you back in the future~ :)
