### ISSUE TITLE
Build docker  image failed: libtensorrt_llm_batch_manager_static.a: file format not recognized

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/TensorRT-LLM#231]
Hi, I'm using V100, the command is:
```
make -C docker release_build CUDA_ARCHS="70-real"
```
But it complains this error:

```
717.7 [ 98%] Linking CXX static library libtensorrt_llm_static.a
719.3 [ 98%] Built target tensorrt_llm_static
719.3 [100%] Linking CXX shared library libtensorrt_llm.so
719.5 /usr/bin/ld:/src/tensorrt_llm/cpp/tensorrt_llm/batch_manager/x86_64-linux-gnu/libtensorrt_llm_batch_manager_static.a: file format not recognized; treating as linker script
719.5 /usr/bin/ld:/src/tensorrt_llm/cpp/tensorrt_llm/batch_manager/x86_64-linux-gnu/libtensorrt_llm_batch_manager_static.a:1: syntax error
719.5 collect2: error: ld returned 1 exit status
719.5 gmake[3]: *** [tensorrt_llm/CMakeFiles/tensorrt_llm.dir/build.make:714: tensorrt_llm/libtensorrt_llm.so] Error 1
719.5 gmake[2]: *** [CMakeFiles/Makefile2:677: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/all] Error 2
719.5 gmake[1]: *** [CMakeFiles/Makefile2:684: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/rule] Error 2
719.5 gmake: *** [Makefile:179: tensorrt_llm] Error 2
719.5 Traceback (most recent call last):
719.5   File "/src/tensorrt_llm/scripts/build_wheel.py", line 248, in <module>
719.5     main(**vars(args))
719.5   File "/src/tensorrt_llm/scripts/build_wheel.py", line 152, in main
719.5     build_run(
719.5   File "/usr/lib/python3.10/subprocess.py", line 526, in run
719.5     raise CalledProcessError(retcode, process.args,
719.5 subprocess.CalledProcessError: Command 'cmake --build . --config Release --parallel 48 --target tensorrt_llm tensorrt_llm_static nvinfer_plugin_tensorrt_llm th_common ' returned non-zero exit status 2.
------
Dockerfile.multi:48
--------------------
  46 |
  47 |     ARG BUILD_WHEEL_ARGS="--clean --trt_root /usr/local/tensorrt"
  48 | >>> RUN python3 scripts/build_wheel.py ${BUILD_WHEEL_ARGS}
  49 |
  50 |     FROM devel as release
--------------------
ERROR: failed to solve: process "/bin/bash -c python3 scripts/build_wheel.py ${BUILD_WHEEL_ARGS}" did not complete successfully: exit code: 1
make: *** [Makefile:47: release_build] Error 1
make: Leaving directory '/data/TensorRT-LLM/docker'
```

**Comment by vicwer** [comment]
me too...
RUN: `python3 scripts/build_wheel.py --clean --trt_root /usr/local/tensorrt`
```
[ 98%] Built target kernels_src
[ 98%] Linking CXX static library libtensorrt_llm_static.a
[ 98%] Built target tensorrt_llm_static
[100%] Linking CXX shared library libtensorrt_llm.so

/usr/bin/ld:/root/tensorrt_llm_requirements/tensorrt_llm/TensorRT-LLM/cpp/tensorrt_llm/batch_manager/x86_64-linux-gnu/libtensorrt_llm_batch_manager_static.a: file format not recognized; treating as linker script
/usr/bin/ld:/root/tensorrt_llm_requirements/tensorrt_llm/TensorRT-LLM/cpp/tensorrt_llm/batch_manager/x86_64-linux-gnu/libtensorrt_llm_batch_manager_static.a:1: syntax error
collect2: error: ld returned 1 exit status
gmake[3]: *** [tensorrt_llm/CMakeFiles/tensorrt_llm.dir/build.make:714: tensorrt_llm/libtensorrt_llm.so] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:677: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:684: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/rule] Error 2
gmake: *** [Makefile:179: tensorrt_llm] Error 2
Traceback (most recent call last):
  File "/root/tensorrt_llm_requirements/tensorrt_llm/TensorRT-LLM/scripts/build_wheel.py", line 248, in <module>
    main(**vars(args))
  File "/root/tensorrt_llm_requirements/tensorrt_llm/TensorRT-LLM/scripts/build_wheel.py", line 152, in main
    build_run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cmake --build . --config Release --parallel 32 --target tensorrt_llm tensorrt_llm_static nvinfer_plugin_tensorrt_llm th_common ' returned non-zero exit status 2.
```

**Comment by sleepwalker2017** [comment]
> me too...
> 
> ```
> [ 98%] Built target kernels_src
> [ 98%] Linking CXX static library libtensorrt_llm_static.a
> [ 98%] Built target tensorrt_llm_static
> [100%] Linking CXX shared library libtensorrt_llm.so
> 
> /usr/bin/ld:/root/tensorrt_llm_requirements/tensorrt_llm/TensorRT-LLM/cpp/tensorrt_llm/batch_manager/x86_64-linux-gnu/libtensorrt_llm_batch_manager_static.a: file format not recognized; treating as linker script
> /usr/bin/ld:/root/tensorrt_llm_requirements/tensorrt_llm/TensorRT-LLM/cpp/tensorrt_llm/batch_manager/x86_64-linux-gnu/libtensorrt_llm_batch_manager_static.a:1: syntax error
> collect2: error: ld returned 1 exit status
> gmake[3]: *** [tensorrt_llm/CMakeFiles/tensorrt_llm.dir/build.make:714: tensorrt_llm/libtensorrt_llm.so] Error 1
> gmake[2]: *** [CMakeFiles/Makefile2:677: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/all] Error 2
> gmake[1]: *** [CMakeFiles/Makefile2:684: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/rule] Error 2
> gmake: *** [Makefile:179: tensorrt_llm] Error 2
> Traceback (most recent call last):
>   File "/root/tensorrt_llm_requirements/tensorrt_llm/TensorRT-LLM/scripts/build_wheel.py", line 248, in <module>
>     main(**vars(args))
>   File "/root/tensorrt_llm_requirements/tensorrt_llm/TensorRT-LLM/scripts/build_wheel.py", line 152, in main
>     build_run(
>   File "/usr/lib/python3.10/subprocess.py", line 526, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command 'cmake --build . --config Release --parallel 32 --target tensorrt_llm tensorrt_llm_static nvinfer_plugin_tensorrt_llm th_common ' returned non-zero exit status 2.
> ```

Hi, the latest commit has introduced some bug.

checkout this one solves the problem: `d0b56df751c78d24bf79624ac5633c3988044e8c`

**Comment by Shixiaowei02** [comment]
Please refer to https://github.com/NVIDIA/TensorRT-LLM/issues/71 , thanks!
