### ISSUE TITLE
ModelRunner cannot start engine with "multi-rank nemo LoRA" checkpoints

### ISSUE THREAD

**Issue by jolyons123** [NVIDIA/TensorRT-LLM#2376]
Hi,

I try to use my LoRA weights that I got from PEFT using NeMo Framework container (with tp=pp=2, 4 gpus) with TensorRT-LLM ModelRunner (the [TensorRT-LLM/examples/run.py](https://github.com/NVIDIA/TensorRT-LLM/blob/v0.13.0/examples/run.py) script) . The megatron_gpt_peft_lora_tuning.nemo LoRA checkpoint content is as follows:
```
./                                                                                                                                                                           
./model_config.yaml                                                                                                                                                          
./tp_rank_00_pp_rank_000/
./tp_rank_00_pp_rank_000/model_weights.ckpt 
./tp_rank_00_pp_rank_001/
./tp_rank_00_pp_rank_001/model_weights.ckpt 
./tp_rank_01_pp_rank_000/
./tp_rank_01_pp_rank_000/model_weights.ckpt 
./tp_rank_01_pp_rank_001/
./tp_rank_01_pp_rank_001/model_weights.ckpt
```

Environment: Docker on Rocky-Linux, x64, H100 GPUs
Libraries:
- TensorRT-LLM v0.13.0 + corresponding git repo tag, container based on cuda devel image
- NeMo dev container

Steps to reproduce:
1. Convert .nemo model (Llama 3.1 8B) to TensorRT checkpoint for 4gpu setup (tp=pp=2) using corresponding conversion scripts. Command skipped.
2. Build engine with specifying LoRA checkpoint (from training run in NeMo container with tp=pp=2) using trtllm-build.  Command: `trtllm-build --checkpoint_dir /workspace/my_models/trt/checkpoints/llama-3.1-8b-4gpu --output_dir /workspace/my_models/trt/engines/my_tuned_llama3.1-8b/fp16/4gpu/ --lora_dir /workspace/my_models/my_loras/nemo/test_251024_135501/checkpoints/megatron_gpt_peft_lora_tuning.nemo --lora_ckpt_source nemo --lora_target_modules attn_qkv --lora_plugin auto`
3. Use run.py from examples directory to do inference. Command: `mpirun --allow-run-as-root --np 4 python3 run.py --engine_dir /workspace/my_models/trt/engines/my_tuned_llama31-8b/fp16/4gpu/ --tokenizer_dir /workspace/my_models/HF/Meta-Llama-3.1-8B/ --max_output_len 5 --input_text "Hello, my name is "`

After running step 3. the error is as follows:
```
Traceback (most recent call last):                                                                                                                                           
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/lora_manager.py", line 327, in unpack_nemo_weights                                                              
    model_weights = tar.extractfile("model_weights.ckpt")                                                                                                                    
  File "/usr/lib/python3.10/tarfile.py", line 2386, in extractfile                                                                                                           
    tarinfo = self.getmember(member)                                                                                                                                         
  File "/usr/lib/python3.10/tarfile.py", line 2007, in getmember                                                                                                             
    raise KeyError("filename %r not found" % name)                                                                                                                           
KeyError: "filename 'model_weights.ckpt' not found" 
```
So [lora_manager.py](https://github.com/NVIDIA/TensorRT-LLM/blob/v0.13.0/tensorrt_llm/lora_manager.py#L327) expects only a single model_weights.ckpt whereas I have multiple ranks.

NeMo repository has a [script to merge lora weights](https://github.com/NVIDIA/NeMo/blob/main/scripts/nlp_language_modeling/merge_lora_weights/merge.py) into a base model, but that's not something I want to do. I want to "plug in" my LoRA weights resulting from training by either specifying it as args to run.py or by specifying it as args to the trtllm-build command.

Any help appreciated!

**Comment by syuoni** [comment]
Hi @jolyons123 , 

Thanks for reporting this issue. Is there any open-sourced multi-gpu nemo lora checkpoints? If so, I can fix the parsing logics and evaluate the accuracy based on that.

**Comment by jolyons123** [comment]
Hi @syuoni ,

I am sorry to say that I do not have any open-sourced multi-gpu nemo lora checkpoints. But could we maybe re-use contents from [this function](https://github.com/NVIDIA/NeMo/blob/main/scripts/nlp_language_modeling/merge_lora_weights/merge.py#L135) in NeMo repo?

**Comment by karljang** [comment]
Closing as stale since the TensorRT engine-build path is deprecated in favor of the PyTorch backend. Please open a new issue if the problem persists in the latest version.
