### ISSUE TITLE
FP8 Conversion failure when using Mixtral 8x7B with use_fp8_rowwise

### ISSUE THREAD

**Issue by ValeGian** [NVIDIA/TensorRT-LLM#2377]
### System Info

CPU architecture: x86_64
GPU: 8 NVIDIA H100
Libraries
TensorRT-LLM: v0.12.0
TensorRT: 10.3.0
Modelopt: 0.1.1
CUDA: 12.4
NVIDIA driver version: 550.90.12

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

1. Get a Mixtral 8x7B model
2. Convert it to FP8 using the [convert_checkpoint.py](https://github.com/NVIDIA/TensorRT-LLM/blob/v0.12.0/examples/llama/convert_checkpoint.py) script. The command is
`convert_checkpoint.py --model_dir=<MODEL DIR> --dtype=float16 --tp_size=2 --output_dir=<CHECKPOINT DIR> --use_fp8_rowwise`

### Expected behavior

The expected output would be a correctly FP8 row-wise converted Mixtral 8x7B checkpoint.

### actual behavior

The checkpoint conversion crashes with the following message:
```
[TensorRT-LLM] TensorRT-LLM version: 0.12.0
0.12.0
8it [00:00, 11.22it/s]
Traceback (most recent call last):
  File "convert_checkpoint.py", line 487, in <module>
    main()
  File "convert_checkpoint.py", line 479, in main
    convert_and_save_hf(args)
  File "convert_checkpoint.py", line 421, in convert_and_save_hf
    execute(args.workers, [convert_and_save_rank] * world_size, args)
  File "convert_checkpoint.py", line 428, in execute
    f(args, rank)
  File "convert_checkpoint.py", line 410, in convert_and_save_rank
    llama = LLaMAForCausalLM.from_hugging_face(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/model.py", line 363, in from_hugging_face
    loader.generate_tllm_weights(model)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/model_weights_loader.py", line 330, in generate_tllm_weights
    tllm_weights.update(self.load(tllm_key))
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/model_weights_loader.py", line 279, in load
    if not v.is_contiguous():
AttributeError: 'NoneType' object has no attribute 'is_contiguous'
Exception ignored in: <function PretrainedModel.__del__ at 0x7061e3970f70>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/modeling_utils.py", line 449, in __del__
    self.release()
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/modeling_utils.py", line 446, in release
    release_gc()
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_utils.py", line 469, in release_gc
    torch.cuda.ipc_collect()
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 904, in ipc_collect
    _lazy_init()
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 333, in _lazy_init
    raise DeferredCudaCallError(msg) from e
torch.cuda.DeferredCudaCallError: CUDA call failed lazily at initialization with error: 'NoneType' object is not iterable

CUDA call was originally invoked at:

  File "convert_checkpoint.py", line 8, in <module>
    from transformers import AutoConfig
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "<frozen importlib._bootstrap>", line 1078, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/__init__.py", line 27, in <module>
    from .chat_template_utils import DocstringParsingException, TypeHintParsingException, get_json_schema
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/chat_template_utils.py", line 39, in <module>
    from torch import Tensor
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 1694, in <module>
    _C._initExtension(_manager_path())
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 1470, in <module>
    _lazy_call(_register_triton_kernels)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 256, in _lazy_call
    _queued_calls.append((callable, traceback.format_stack()))
```

### additional notes

The conversion works when using [quantize.py](https://github.com/NVIDIA/TensorRT-LLM/blob/v0.12.0/examples/quantization/quantize.py) script with command
`quantize.py --model_dir=<MODEL DIR> --dtype=float16 --tp_size=2 --output_dir=<CHECKPOINT DIR> --qformat=fp8 --kv_cache_dtype=fp8 --calib_dataset=<CALIB DATASET> --calib_size=512 --batch_size=8 --calib_max_seq_length=1024`

It also works using the [convert_checkpoint.py](https://github.com/NVIDIA/TensorRT-LLM/blob/v0.12.0/examples/llama/convert_checkpoint.py) command if applied to a Mistral model or a LLaMA-3.1 model.

**Comment by djns99** [comment]
Hi @ValeGian, thanks for your interest in TRT-LLM.
Unfortunately, MOE models do not currently support FP8 rowwise quantization. We do not have a plan to add this currently, but if you are able to share more details about your use case we would be happy to consider this further.

I have submitted a pull request to the internal development branch that should make the error much clearer in the future.

**Comment by ValeGian** [comment]
Hi @djns99, thanks for the clarification!

Our use case is as follows: we have fine-tuned the Mixtral 8x7B model and are aiming to optimize inference time and throughput. The base model is in FP16, and we attempted quantization as one of our optimization strategies. So far, we’ve successfully quantized the model with **_TensorRT-LLM 11_** using:

- FP8 (**QuantAlgo.FP8**) via [quantize.py](https://github.com/NVIDIA/TensorRT-LLM/blob/v0.11.0/examples/quantization/quantize.py) with the following:
`quantize.py --model_dir=<MODEL DIR> --dtype=float16 --output_dir=<CHECKPOINT DIR> --qformat=fp8 --kv_cache_dtype=fp8 --calib_dataset=<CALIB DATASET> --calib_size=512 --calib_max_seq_length=1024`
- INT8 (**QuantAlgo.W8A16**) via [convert_checkpoint.py](https://github.com/NVIDIA/TensorRT-LLM/blob/v0.11.0/examples/llama/convert_checkpoint.py) with the following:
`convert_checkpoint.py --model_dir=<MODEL DIR> --dtype=float16 --output_dir=<CHECKPOINT DIR> --use_weight_only --weight_only_precision=int8`

We observed noticeable improvements in inference time and throughput with FP8 compared to INT8. However, there’s a drawback: we’re experiencing a quality drop where FP8 < INT8 < FP16. The difference isn’t substantial but is consistently noticeable across different test cases. This was unexpected based on [this documentation](https://github.com/NVIDIA/TensorRT-LLM/blob/v0.13.0/docs/source/blogs/quantization-in-TRT-LLM.md#best-practices-to-choose-the-right-quantization-methods), which suggests FP8 should have a "_**Very Low**_" impact on quality, while INT8 has a "**_Low_**" impact, implying INT8 < FP8.

One of our tracks to address this is exploring new quantization strategies, including FP8 rowwise (**QuantAlgo.FP8_PER_CHANNEL_PER_TOKEN**), which should be more accurate. Any insights you could share to help with our investigation would be greatly appreciated!

Do you have any practical advice on how best to approach this FP8 quality issue?

**Comment by djns99** [comment]
Hi @ValeGian thanks for sharing, It's hard to give specific recommendations. Our internal experiments show that FP8 Mixtral scores very similar on MMLU to the default BF16 model.

My understanding is that base Mixtral uses bfloat16, so there may be some extra conversion cost incurred by using float16 as in your commands. 
You could also try experiment with a different calibration dataset, or an increased sample size during calibration.

**Comment by ValeGian** [comment]
Hi @djns99

We already tried using production-like data for calibration, testing different amounts, but no major improvement was seen.

I see that [convert_checkpoint.py](https://github.com/NVIDIA/TensorRT-LLM/blob/v0.14.0/examples/llama/convert_checkpoint.py) now integrates a lot of FP8 conversion logic. Is there any major difference in using such script wrt using [quantize.py](https://github.com/NVIDIA/TensorRT-LLM/blob/v0.14.0/examples/quantization/quantize.py)?

**Comment by djns99** [comment]
To the best of my knowledge both convert_checkpoint and quantize call the same function, so both should give largely equivalent results. 
You mentioned that you are using a custom fine tuned version of Mixtral, does base Mixtral without fine tuning also display the same behavior with FP8 < INT8 < BF16 on your test dataset?

**Comment by ValeGian** [comment]
Thank you for clarifying the two scripts.

As for the second point, because base Mixtral doesn’t perform well on our use case without fine-tuning, we haven’t measured the quality impact of quantization on it. The only way we could evaluate this would be by using standard public test sets, and for those, we trust the results you've provided.

Do you have any best practices at a lower level for detecting potential issues during quantization, such as monitoring scale factors or identifying outliers?

**Comment by djns99** [comment]
I can't seem to find any specific recommendations in any of our documentation. Checking for outliers, and understanding what the dynamic range is for your weight and activation values are good starting points. Perhaps comparing intermediate values (see [troubleshooting.md](https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/reference/troubleshooting.md#debug-on-e2e-models)) between FP8 and FP16 to identify which layers are contributing the most to the drop in accuracy will help focus your efforts.

Sorry I can't be of more help.

**Comment by ValeGian** [comment]
Thank you @djns99 for the guidance!
I’ll look into outliers and compare FP8 and FP16 values as suggested.

For now, I'll close the issue. Your help is much appreciated!
