### ISSUE TITLE
Why is the performance worse than release 0.12.0 when I run the benchmark of release 0.13.0

### ISSUE THREAD

**Issue by rexmxw02** [NVIDIA/TensorRT-LLM#2395]
### System Info

Why is the performance worse than release 0.12.0 when I run the benchmark of release 0.13.0
(fp16,fp8,int8) llama2 70b

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Why is the performance worse than release 0.12.0 when I run the benchmark of release 0.13.0
(fp16,fp8,int8) llama2 70b

### Expected behavior

Why is the performance worse than release 0.12.0 when I run the benchmark of release 0.13.0
(fp16,fp8,int8) llama2 70b

### actual behavior

Why is the performance worse than release 0.12.0 when I run the benchmark of release 0.13.0
(fp16,fp8,int8) llama2 70b

### additional notes

Why is the performance worse than release 0.12.0 when I run the benchmark of release 0.13.0
(fp16,fp8,int8) llama2 70b

**Comment by hello-11** [comment]
Could you give us more details about the performance and what's your hardware? @rexmxw02

**Comment by rexmxw02** [comment]
nvidia gpu h20 and a800

**Comment by thalapandi** [comment]
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.


when install tenosrrt llm in windows from below 

https://nvidia.github.io/TensorRT-LLM/installation/windows.html

so how can i resolve this issue?

**Comment by hello-11** [comment]
@rexmxw02 Could you try to use the newest version?

**Comment by hello-11** [comment]
@thalapandi  Thanks for your interest. You can submit a separate issue and provide us with more details.

**Comment by thalapandi** [comment]
Environment path found: C:\Users\jayme\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag
App running with config
 {
    "models": {
        "supported": [
            {
                "name": "Mistral 7B int4",
                "installed": true,
                "metadata": {
                    "model_path": "model\\mistral\\mistral7b_int4_engine",
                    "engine": "llama_float16_tp1_rank0.engine",
                    "tokenizer_path": "model\\mistral\\mistral7b_hf",
                    "max_new_tokens": 1024,
                    "max_input_token": 7168,
                    "temperature": 0.1
                }
            },
            {
                "name": "Llama 2 13B int4",
                "installed": true,
                "metadata": {
                    "model_path": "model\\llama\\llama13_int4_engine",
                    "engine": "llama_float16_tp1_rank0.engine",
                    "tokenizer_path": "model\\llama\\llama13_hf",
                    "max_new_tokens": 1024,
                    "max_input_token": 3900,
                    "temperature": 0.1
                }
            }
        ],
        "selected": "Mistral 7B int4"
    },
    "sample_questions": [
        {
            "query": "How does NVIDIA ACE generate emotional responses?"
        },
        {
            "query": "What is Portal prelude RTX?"
        },
        {
            "query": "What is important about Half Life 2 RTX?"
        },
        {
            "query": "When is the launch date for Ratchet & Clank: Rift Apart on PC?"
        }
    ],
    "dataset": {
        "sources": [
            "directory",
            "youtube",
            "nodataset"
        ],
        "selected": "directory",
        "path": "dataset",
        "isRelative": true
    },
    "strings": {
        "directory": "Folder Path",
        "youtube": "YouTube URL",
        "nodataset": "AI model default"
    }
}
Traceback (most recent call last):
  File "C:\Users\jayme\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\langchain\embeddings\huggingface.py", line 58, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jayme\AppData\Local\NVIDIA\ChatWithRTX\RAG\trt-llm-rag-windows-main\app.py", line 114, in <module>
    embed_model = HuggingFaceEmbeddings(model_name=embedded_model)
  File "C:\Users\jayme\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\langchain\embeddings\huggingface.py", line 61, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
Press any key to continue . . .


especially got this ?

https://forums.developer.nvidia.com/t/chat-with-rtx-error-modulenotfounderror-no-module-named-sentence-transformers/283151
tried many things but could not resolve of an issue

**Comment by rexmxw02** [comment]
@hello-11  master or release 0.13.0?

**Comment by hello-11** [comment]
@rexmxw02 please try the latest main branch.

**Comment by hello-11** [comment]
@thalapandi please submit another issue.

**Comment by white-wolf-tech** [comment]
when I test Qwen series model. only V0.10.0 is OK. 
V0.11.0\V0.12.0\V0.13.0, they are worse than release 0.10.0 in the performance  issue.
But there is no response yet

**Comment by hello-11** [comment]
@white-wolf-tech Could you try the newest branch? If the problem still exists, please submit another issue regarding your situation.

**Comment by white-wolf-tech** [comment]
> [@white-wolf-tech](https://github.com/white-wolf-tech) Could you try the newest branch? If the problem still exists, please submit another issue regarding your situation.

I have tried the latest release v0.14.0, still have this issue. even slower than vllm.
I have opened an issue sevral months ago. https://github.com/NVIDIA/TensorRT-LLM/issues/2117 .  but still no response.

do you have plan to fix this issue? @hello-11

**Comment by rexmxw02** [comment]
the latest master is ok

**Comment by white-wolf-tech** [comment]
> the latest master is ok

you mean build from the latest source code?

**Comment by rexmxw02** [comment]
> > the latest master is ok
> 
> you mean build from the latest source code?

yes

**Comment by white-wolf-tech** [comment]
> > > the latest master is ok
> > 
> > 
> > you mean build from the latest source code?
> 
> yes

ok. thank you. 
by the way. could you tell me more details? the driver version, the images you have used. 
thanks a lot.

**Comment by karljang** [comment]
Closing this issue, hoping it has been resolved as noted by the OP If the problem persists in the latest release, please feel free to open a new one.
Thank you!
