### ISSUE TITLE
attempt to run benchmark with batch_size>=512 and input_output_len=1024,128 result in tensor volume exceeds 2147483647 error

### ISSUE THREAD

**Issue by dmonakhov** [NVIDIA/TensorRT-LLM#2422]
System config: 
- CPU arch x86_64
- GPU: H200
- Tensorrt-LLM:v0.14.0
- OS: ubuntu-22.04
- runtime-env: docker container build from sources via official [build script](https://techcommunity.microsoft.com/blog/azurehighperformancecomputingblog/optimizing-language-model-inference-on-azure/4248271)

Hi I try to follow [Azure's paper](https://techcommunity.microsoft.com/blog/azurehighperformancecomputingblog/optimizing-language-model-inference-on-azure/4248271)  and try to reproduce result for "Experimental maximum batch size as a function of tensor parallelism (TP) for inference with LLAMA 3 8B on the ND H200 v5 virtual machine with sequence total length 1152."
Idea is to measure performance as a function of tensor parallelism. But attempt to run benchmark for seq_size=1024,128 is failing if batch_size >=512 it fails with assert about  "tensor volume exceeds 2< 31"
```
11/07/2024-12:28:19] [TRT] [E] IExecutionContext::enqueueV3: Error Code 7: Internal Error (LLaMAForCausalLM/transformer/vocab_embedding/embedding_L2661/GATHER_0_output_0: \
tensor volume exceeds 2147483647, dimensions are [num_tokens,4096] Condition '<' violated: 524288 >= 524288. Instruction: CHECK_LESS 524288 524288.)
Traceback (most recent call last):
  File "/app/tensorrt_llm/benchmarks/python/benchmark.py", line 255, in main
    benchmarker.run(inputs, config)
  File "/app/tensorrt_llm/benchmarks/python/gpt_benchmark.py", line 165, in run
    self.decoder.decode_batch(inputs[0],
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 3725, in decode_batch
    return self.decode(input_ids,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1062, in wrapper
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 3953, in decode
    return self.decode_regular(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 3559, in decode_regular
    should_stop, next_step_tensors, tasks, context_lengths, host_context_lengths, attention_mask, context_logits, generation_logits, encoder_input_lengths = self.handle_per\
_
step(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 3170, in handle_per_step
    raise RuntimeError(f"Executing TRT engine failed step={step}!")
RuntimeError: Executing TRT engine failed step=0!
```

As far as I understand this is known issue from [tensorrt-10.1.0](https://docs.nvidia.com/deeplearning/tensorrt/release-notes/index.html#rel-10-1-0)
, but it was fixed long time
```
TensorRT did not support attention operations for tensors larger than int32_t maximum. Plugins could be used to workaround this issue. The issue has been fixed.
```
And official script use reasonably fresh package
```
pip list  |grep tensorrt
tensorrt                  10.4.0
tensorrt-llm              0.14.0
torch-tensorrt            2.5.0a0
```
# Build container image, nothing fancy, just follows official guide
```
git reset --hard v0.14.0      
git submodule update --init --recursive
git lfs pull
make -C docker `release_build`
```
# Start container like follows, also nothing fancy
```
docker run -it --rm -d -v $(pwd)/data:/data \
       --shm-size=4g --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 --gpus=all --privileged \
       --name llm-bench \
       tensorrt_llm_benchmark:latest
```

# Checkpoint and build engine scripts
```
# Install llama's deps
#python3 -m pip install -r examples/llama/requirements.txt

# Checkpoints for TP=9
python3 /app/tensorrt_llm/examples/quantization/quantize.py \
        --model_dir /data/models/Meta-Llama-3-8B \
        --qformat fp8 \
        --kv_cache_dtype fp8 \
        --output_dir /data/checkpoints/Meta-Llama-3-8B/tp_8/float16 \
        --dtype float16 \
        --tp_size 8

#### Build engine, idea is to build engine for all ranges of batch_size up to 1024
# From https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/performance/perf-overview.md#engine-building                                                                           
# --max_seq_len = (max_input + max_output) in our case it is 1024 + 128                                                                                                                    
# From                                                                                                                                                                                     
 # https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama#long-context-evaluation                                                                                                  
 # https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/performance/perf-best-practices.md                                                                                            # --max_num_tokens = (max_batch_size * max_input_len), in our case it is 1024*1024 => 1M 

trtllm-build \
    --checkpoint_dir /data/checkpoints/Meta-Llama-3-8B/tp_8/float16 \
    --output_dir /data/engines/Meta-Llama-3-8B/tp_8/float16 \
    --workers 8 \
    --max_batch_size 1024 \
    --max_num_tokens 1048576 \
    --max_input_len 1048576 \
    --max_seq_len 1152 \
    --gemm_plugin auto
```

# Benchmarks
```
# Benckmark with batch_size=511, works OK                                                                                                                                                                          
mpirun -n 8 --bind-to none -display-map --allow-run-as-root \
       python3 /app/tensorrt_llm/benchmarks/python/benchmark.py \
       --engine_dir /data/engines/Meta-Llama-3-8B/tp_8/float16 \
       --batch_size 511 \
       --dtype float16 \
       --input_output_len 1024,128 \
       --warm_up 10 \
       --num_runs 5 \
       -m dec
## Benchmark with batch_size=512, fails  with   "tensor volume exceeds 214748364"  assert                                                                                                                                                                      
mpirun -n 8 --bind-to none -display-map --allow-run-as-root \                                                                                                                                                     
       python3 /app/tensorrt_llm/benchmarks/python/benchmark.py \                                                                                                                                                 
       --engine_dir /data/engines/Meta-Llama-3-8B/tp_8/float16 \                                                                                                                                                  
       --batch_size 512 \                                                                                                                                                                                         
       --dtype float16 \                                                                                                                                                                                          
       --input_output_len 1024,128 \                                                                                                                                                                              
       --warm_up 10 \                                                                                                                                                                                             
       --num_runs 5 \                                                                                                                                                                                             
       -m dec 
```
[pip_list.txt](https://github.com/user-attachments/files/17661924/pip_list.txt)

**Comment by hello-11** [comment]
@dmonakhov Thanks for your interest in TrtLLM. You can try to use benchmarks/cpp/gptManagerBenchmark.cpp to benchmark your application.

**Comment by dmonakhov** [comment]
I've tried gptManagerBenchmark and with [emulated static batch_size](https://github.com/NVIDIA/TensorRT-LLM/tree/main/benchmarks/cpp#emulated-static-batching)  it fails with same error if static_emulated_batch_size >=512, but works w/o issues if static_emulated_batch_size <512, 

Here is example:
```
mpirun --allow-run-as-root --bind-to none  \
       -n $tp_size \
       --tag-output \
        ./benchmarks/cpp/gptManagerBenchmark \
        --engine_dir $engine_dir \
        --request_rate -1 \
        -- 512 \
        --static_emulated_timeout 100 \
        --dataset $dataset_file \
        --output_csv result-${tp_size}.csv \
        --max_num_samples 1000
```

```
[TensorRT-LLM][ERROR] IExecutionContext::inferShapes: Error Code 7: Internal Error (LLaMAForCausalLM/transformer/vocab_embedding/embedding_L2657/GATHER_0_output_0: tensor volume exceeds 2147483647, dimensions are [num_tokens,4096] Condition '<' violated: 524288 >= 524288. Instruction: CHECK_LESS 524288 524288.)
[TensorRT-LLM][ERROR] Encountered an error in forwardAsync function: Invalid input shape (/src/tensorrt_llm/cpp/tensorrt_llm/runtime/tllmRuntime.cpp:251)
       0x77baf0773b1b /app/tensorrt_llm/lib/libtensorrt_llm.so(+0x554b1b) [0x77baf0773b1b]
       0x77baf20d4c3f tensorrt_llm::batch_manager::TrtGptModelInflightBatching::executeStep(std::vector<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest>, std::allocator<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest> > > const&, std::vector<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest>, std::allocator<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest> > > const&, int) + 207
       0x77baf20d4dc6 tensorrt_llm::batch_manager::TrtGptModelInflightBatching::executeBatch(tensorrt_llm::batch_manager::ScheduledRequests const&) + 246
       0x77baf20d5759 tensorrt_llm::batch_manager::TrtGptModelInflightBatching::forwardAsync(std::__cxx11::list<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest>, std::allocator<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest> > > const&) + 2425
       0x77baf20f6a03 tensorrt_llm::executor::Executor::Impl::forwardAsync(std::__cxx11::list<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest>, std::allocator<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest> > >&) + 387
       0x77baf20fb577 tensorrt_llm::executor::Executor::Impl::executionLoop() + 695
       0x77baeeba7480 /app/tensorrt_llm/lib/libtensorrt_llm_nvrtc_wrapper.so(+0x31e3480) [0x77baeeba7480]
       0x77baeb3dbac3 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x77baeb3dbac3]
       0x77baeb46d850 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x126850) [0x77baeb46d850]
[TensorRT-LLM][ERROR] Cannot get the result for a response with an error (/home/jenkins/agent/workspace/LLM/main/L0_PostMerge/llm/cpp/tensorrt_llm/executor/responseImpl.h:62)
       0x77baf07a34ce /app/tensorrt_llm/lib/libtensorrt_llm.so(+0x5844ce) [0x77baf07a34ce]
       0x6224a64c56d8 ./benchmarks/cpp/gptManagerBenchmark(+0x3b6d8) [0x6224a64c56d8]
       0x6224a64be8d1 ./benchmarks/cpp/gptManagerBenchmark(+0x348d1) [0x6224a64be8d1]
       0x77baeb370d90 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x77baeb370d90]
       0x77baeb370e40 __libc_start_main + 128
       0x6224a64c1315 ./benchmarks/cpp/gptManagerBenchmark(+0x37315) [0x6224a64c1315]
```

Same behavior is observed in case of default [benchmark mode](https://github.com/NVIDIA/TensorRT-LLM/tree/main/benchmarks/cpp#launch-benchmarking) where ```--request_rate``` option is provided, if request_rate >= ~TP*64

```
mpirun --allow-run-as-root --bind-to none  \
       -n $tp_size \
       --tag-output \
        ./benchmarks/cpp/gptManagerBenchmark \
        --engine_dir $engine_dir \
        --request_rate 510 \
        --dataset $dataset_file \
        --output_csv result-${tp_size}.csv \
        --max_num_samples 1000
...
[TensorRT-LLM][ERROR] IExecutionContext::inferShapes: Error Code 7: Internal Error (LLaMAForCausalLM/transformer/vocab_embedding/embedding_L2657/GATHER_0_output_0: tensor volume exceeds 2147483647, dimensions are [num_tokens,4096] Condition '<' violated: 676180 >= 524288. Instruction: CHECK_LESS 676180 524288.)
[TensorRT-LLM][ERROR] Encountered an error in forwardAsync function: Invalid input shape (/src/tensorrt_llm/cpp/tensorrt_llm/runtime/tllmRuntime.cpp:251)
       0x7b652fc74b1b /app/tensorrt_llm/lib/libtensorrt_llm.so(+0x554b1b) [0x7b652fc74b1b]
       0x7b65315d5c3f tensorrt_llm::batch_manager::TrtGptModelInflightBatching::executeStep(std::vector<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest>, std::allocator<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest> > > const&, std::vector<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest>, std::allocator<std::shared_ptr<tensorrt_llm::batch_manager::LlmR$
       0x7b65315d5dc6 tensorrt_llm::batch_manager::TrtGptModelInflightBatching::executeBatch(tensorrt_llm::batch_manager::ScheduledRequests const&) + 246
       0x7b65315d6759 tensorrt_llm::batch_manager::TrtGptModelInflightBatching::forwardAsync(std::__cxx11::list<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest>, std::allocator<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest> > > const&) + 2425
       0x7b65315f7a03 tensorrt_llm::executor::Executor::Impl::forwardAsync(std::__cxx11::list<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest>, std::allocator<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest> > >&) + 387
       0x7b65315fc577 tensorrt_llm::executor::Executor::Impl::executionLoop() + 695
       0x7b652e0a8480 /app/tensorrt_llm/lib/libtensorrt_llm_nvrtc_wrapper.so(+0x31e3480) [0x7b652e0a8480]
       0x7b652a8dcac3 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7b652a8dcac3]
       0x7b652a96e850 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x126850) [0x7b652a96e850]
terminate called after throwing an instance of 'tensorrt_llm::common::TllmException'
  what():  Cannot get the result for a response with an error (/home/jenkins/agent/workspace/LLM/main/L0_PostMerge/llm/cpp/tensorrt_llm/executor/responseImpl.h:62)
       0x7b652fca44ce /app/tensorrt_llm/lib/libtensorrt_llm.so(+0x5844ce) [0x7b652fca44ce]
       0x5567a7e456d8 ./benchmarks/cpp/gptManagerBenchmark(+0x3b6d8) [0x5567a7e456d8]
       0x7b652e0a8480 /app/tensorrt_llm/lib/libtensorrt_llm_nvrtc_wrapper.so(+0x31e3480) [0x7b652e0a8480]
       0x7b652a8dcac3 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7b652a8dcac3]
       0x7b652a96e850 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x126850) [0x7b652a96e850]
```

So my question is this expected? May be I've missed something? 
For now it is not a blocker since using batches which is that large is not practical since tokens_per_sec performance is already reaching a plateau, and only latency is increased, but this may be a blocker for next gen GPUs, probably B100,B200 will hit this limitation. 

One more question which I do not have answer,  [paper](https://techcommunity.microsoft.com/blog/azurehighperformancecomputingblog/optimizing-language-model-inference-on-azure/4248271) claims that they are able to scale Meta-Llama-3-8B with input_len=1024,out_len=128, TP=8  up to  batch_size=750, which seems impossible because of this issue. So the only reasonable explanation I see is that paper is not correct and smaller sequence size was used, probably input_len=512,out_len=64  or less. Any ideas?
