### ISSUE TITLE
trt_build for Llama 3.1 70B w4a8 fails with CUDA error

### ISSUE THREAD

**Issue by chrisreese-if** [NVIDIA/TensorRT-LLM#2428]
### System Info

+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+

4xH100
tensorRT version 0.14.0
triton docker container version 24.10

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Download Llama 3.1 70B Instruct weights
2. python3.10 ./tensorrtllm_backend/tensorrt_llm/examples/quantization/quantize.py --model_dir /workspace/meta-llama/Llama-3.1-70B-Instruct  --qformat w4a8_awq --output_dir  /workspace/trt/llama/llama-3.1-70b-ckpt-w4a8/ --tp_size 4
3.  trtllm-build --checkpoint_dir /workspace/trt/llama/llama-3.1-70b-ckpt-w4a8/ --max_batch_size 10 --max_num_tokens 15000 --context_fmha enab
le --max_seq_len 15000 --output_dir /workspace/trt/llama/llama-3.1-70b-checkpoint-engine/

### Expected behavior

Model engine gets build

### actual behavior

Build fails:
Error log:
[TensorRT-LLM] TensorRT-LLM version: 0.14.0
[11/08/2024-21:07:45] [TRT-LLM] [I] Set bert_attention_plugin to auto.
[11/08/2024-21:07:45] [TRT-LLM] [I] Set gpt_attention_plugin to auto.
[11/08/2024-21:07:45] [TRT-LLM] [I] Set gemm_plugin to None.
[11/08/2024-21:07:45] [TRT-LLM] [I] Set gemm_swiglu_plugin to None.
[11/08/2024-21:07:45] [TRT-LLM] [I] Set fp8_rowwise_gemm_plugin to None.
[11/08/2024-21:07:45] [TRT-LLM] [I] Set nccl_plugin to auto.
[11/08/2024-21:07:45] [TRT-LLM] [I] Set lookup_plugin to None.
[11/08/2024-21:07:45] [TRT-LLM] [I] Set lora_plugin to None.
[11/08/2024-21:07:45] [TRT-LLM] [I] Set moe_plugin to auto.
[11/08/2024-21:07:45] [TRT-LLM] [I] Set mamba_conv1d_plugin to auto.
[11/08/2024-21:07:45] [TRT-LLM] [I] Set low_latency_gemm_plugin to None.
[11/08/2024-21:07:45] [TRT-LLM] [I] Set context_fmha to True.
[11/08/2024-21:07:45] [TRT-LLM] [I] Set bert_context_fmha_fp32_acc to False.
[11/08/2024-21:07:45] [TRT-LLM] [I] Set remove_input_padding to True.
[11/08/2024-21:07:45] [TRT-LLM] [I] Set reduce_fusion to False.
[11/08/2024-21:07:45] [TRT-LLM] [I] Set enable_xqa to True.
[11/08/2024-21:07:45] [TRT-LLM] [I] Set tokens_per_block to 64.
[11/08/2024-21:07:45] [TRT-LLM] [I] Set use_paged_context_fmha to False.
[11/08/2024-21:07:45] [TRT-LLM] [I] Set use_fp8_context_fmha to False.
[11/08/2024-21:07:45] [TRT-LLM] [I] Set multiple_profiles to False.
[11/08/2024-21:07:45] [TRT-LLM] [I] Set paged_state to True.
[11/08/2024-21:07:45] [TRT-LLM] [I] Set streamingllm to False.
[11/08/2024-21:07:45] [TRT-LLM] [I] Set use_fused_mlp to True.
[11/08/2024-21:07:45] [TRT-LLM] [W] Implicitly setting LLaMAConfig.producer = {'name': 'modelopt', 'version': '0.17.0'}
[11/08/2024-21:07:45] [TRT-LLM] [W] Implicitly setting LLaMAConfig.bias = False
[11/08/2024-21:07:45] [TRT-LLM] [W] Implicitly setting LLaMAConfig.rotary_pct = 1.0
[11/08/2024-21:07:45] [TRT-LLM] [W] Implicitly setting LLaMAConfig.rank = 3
[11/08/2024-21:07:45] [TRT-LLM] [W] Implicitly setting LLaMAConfig.decoder = llama
[11/08/2024-21:07:45] [TRT-LLM] [W] Implicitly setting LLaMAConfig.rmsnorm = True
[11/08/2024-21:07:45] [TRT-LLM] [W] Implicitly setting LLaMAConfig.lm_head_bias = False
[11/08/2024-21:08:44] [TRT-LLM] [I] Set dtype to float16.
[11/08/2024-21:08:44] [TRT-LLM] [I] Set paged_kv_cache to True.
[11/08/2024-21:08:44] [TRT-LLM] [W] Overriding paged_state to False
[11/08/2024-21:08:44] [TRT-LLM] [I] Set paged_state to False.
[11/08/2024-21:08:44] [TRT-LLM] [W] remove_input_padding is enabled, while opt_num_tokens is not set, setting to max_batch_size*max_beam_width. 

[11/08/2024-21:08:44] [TRT-LLM] [W] padding removal and fMHA are both enabled, max_input_len is not required and will be ignored
[11/08/2024-21:08:44] [TRT] [I] [MemUsageChange] Init CUDA: CPU +16, GPU +0, now: CPU 8703, GPU 527 (MiB)
[11/08/2024-21:08:48] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +4634, GPU +1274, now: CPU 13492, GPU 1801 (MiB)
[11/08/2024-21:08:48] [TRT-LLM] [I] Set weight_only_groupwise_quant_matmul_plugin to float16.
[11/08/2024-21:08:48] [TRT-LLM] [I] Set nccl_plugin to float16.
[11/08/2024-21:08:49] [TRT-LLM] [I] Total time of constructing network from module object 5.220484256744385 seconds
[11/08/2024-21:08:49] [TRT-LLM] [I] Total optimization profiles added: 1
[11/08/2024-21:08:49] [TRT-LLM] [I] Total time to initialize the weights in network Unnamed Network 0: 00:00:00
[11/08/2024-21:08:49] [TRT-LLM] [I] Build TensorRT engine Unnamed Network 0
[11/08/2024-21:08:49] [TRT] [W] Unused Input: position_ids
[11/08/2024-21:08:49] [TRT] [W] [RemoveDeadLayers] Input Tensor position_ids is unused or used only at compile-time, but is not being removed.
[11/08/2024-21:08:49] [TRT] [I] Global timing cache in use. Profiling results in this builder pass will be stored.
[11/08/2024-21:08:49] [TRT] [I] Compiler backend is used during engine build.

Internal Error: MyelinCheckException: autotuner.cpp:655: CHECK(!lpm.mvmf().empty() && "compile resulted in null program?") failed. 
[11/08/2024-21:15:48] [TRT] [E] Error Code: 9: Skipping tactic 0x0000000000000000 due to exception [operation.cpp:finalize_cask_heuristic_result:2003] Platform (Cuda) error
[11/08/2024-21:15:48] [TRT] [E] [scopedCudaResources.cpp::~ScopedCudaStream::55] Error Code 1: Cuda Runtime (unspecified launch failure)
[11/08/2024-21:15:48] [TRT] [E] IBuilder::buildSerializedNetwork: Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[LLaMAForCausalLM/transformer/ln_f/rms_norm_L5302/elementwise_binary_L2849/broadcast_helper_L2791/constant_to_tensor__L2723/constant_L1151/CONSTANT_0 + LLaMAForCausalLM/transformer/ln_f/rms_norm_L5302/elementwise_binary_L2849/broadcast_helper_L2801/expand_dims_like_L1906/expand_dims_L1738/view_L1646/SHUFFLE_0...LLaMAForCausalLM/lm_head/multiply_collect_L272/multiply_and_lora_
Traceback (most recent call last):
  File "/usr/local/bin/trtllm-build", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 568, in main
    parallel_build(model_config, ckpt_dir, build_config, args.output_dir,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 423, in parallel_build
    passed = build_and_save(rank, rank % workers, ckpt_dir,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 390, in build_and_save
    engine = build_model(build_config,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 383, in build_model
    return build(model, build_config)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/builder.py", line 1189, in build
    engine = None if build_config.dry_run else builder.build_engine(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_common.py", line 204, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/builder.py", line 418, in build_engine
    assert engine is not None, 'Engine building failed, please check the error log.'
AssertionError: Engine building failed, please check the error log.

### additional notes

N/A

**Comment by hello-11** [comment]
@chrisreese-if Could you try to add --workers 4 when you use trtllm-build?
