### ISSUE TITLE
trt_build for Llama 3.1 70B fp8 fails with CUDA error

### ISSUE THREAD

**Issue by chrisreese-if** [NVIDIA/TensorRT-LLM#2429]
### System Info

+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03 Driver Version: 560.35.03 CUDA Version: 12.6 |
|-----------------------------------------+------------------------+----------------------+

4xH100
tensorRTLLM version 0.14.0
triton docker container version 24.10

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. python3.10 ./tensorrtllm_backend/tensorrt_llm/examples/quantization/quantize.py --model_dir /workspace/meta-llama/Llama-3.1-70B-Instruct  --qformat fp8 --output_dir  /workspace/trt/llama/llama-3.1-70b-ckpt-fp8/ --tp_size 4 --calib_size 512
2. trtllm-build --checkpoint_dir /workspace/trt/llama/llama-3.1-70b-ckpt-fp8/ --use_paged_context_fmha enable --max_batch_size 10 --max_num_tokens 15000 --context_fmha enable --max_seq_len 15000 --output_dir /workspace/trt/llama/llama-3.1-70b-checkpoint-fp8-engine/ --gemm_plugin auto

### Expected behavior

Build succeeds

### actual behavior

$ trtllm-build --checkpoint_dir /workspace/trt/llama/llama-3.1-70b-ckpt-fp8/ --use_paged_context_fmha enable --max_batch_size 10 --max_num_tokens 15000 --context_fmha enable --max_seq_len 15000 --output_dir /workspace/trt/llama/llama-3.1-70b-checkpoint-fp8-engine/ --gemm_plugin auto
[TensorRT-LLM] TensorRT-LLM version: 0.14.0
[11/08/2024-23:33:45] [TRT-LLM] [I] Set bert_attention_plugin to auto.
[11/08/2024-23:33:45] [TRT-LLM] [I] Set gpt_attention_plugin to auto.
[11/08/2024-23:33:45] [TRT-LLM] [I] Set gemm_plugin to auto.
[11/08/2024-23:33:45] [TRT-LLM] [I] Set gemm_swiglu_plugin to None.
[11/08/2024-23:33:45] [TRT-LLM] [I] Set fp8_rowwise_gemm_plugin to None.
[11/08/2024-23:33:45] [TRT-LLM] [I] Set nccl_plugin to auto.
[11/08/2024-23:33:45] [TRT-LLM] [I] Set lookup_plugin to None.
[11/08/2024-23:33:45] [TRT-LLM] [I] Set lora_plugin to None.
[11/08/2024-23:33:45] [TRT-LLM] [I] Set moe_plugin to auto.
[11/08/2024-23:33:45] [TRT-LLM] [I] Set mamba_conv1d_plugin to auto.
[11/08/2024-23:33:45] [TRT-LLM] [I] Set low_latency_gemm_plugin to None.
[11/08/2024-23:33:45] [TRT-LLM] [I] Set context_fmha to True.
[11/08/2024-23:33:45] [TRT-LLM] [I] Set bert_context_fmha_fp32_acc to False.
[11/08/2024-23:33:45] [TRT-LLM] [I] Set remove_input_padding to True.
[11/08/2024-23:33:45] [TRT-LLM] [I] Set reduce_fusion to False.
[11/08/2024-23:33:45] [TRT-LLM] [I] Set enable_xqa to True.
[11/08/2024-23:33:45] [TRT-LLM] [I] Set tokens_per_block to 64.
[11/08/2024-23:33:45] [TRT-LLM] [I] Set use_paged_context_fmha to True.
[11/08/2024-23:33:45] [TRT-LLM] [I] Set use_fp8_context_fmha to False.
[11/08/2024-23:33:45] [TRT-LLM] [I] Set multiple_profiles to False.
[11/08/2024-23:33:45] [TRT-LLM] [I] Set paged_state to True.
[11/08/2024-23:33:45] [TRT-LLM] [I] Set streamingllm to False.
[11/08/2024-23:33:45] [TRT-LLM] [I] Set use_fused_mlp to True.
[11/08/2024-23:33:45] [TRT-LLM] [W] Implicitly setting LLaMAConfig.producer = {'name': 'modelopt', 'version': '0.17.0'}
[11/08/2024-23:33:45] [TRT-LLM] [W] Implicitly setting LLaMAConfig.bias = False
[11/08/2024-23:33:45] [TRT-LLM] [W] Implicitly setting LLaMAConfig.rotary_pct = 1.0
[11/08/2024-23:33:45] [TRT-LLM] [W] Implicitly setting LLaMAConfig.rank = 3
[11/08/2024-23:33:45] [TRT-LLM] [W] Implicitly setting LLaMAConfig.decoder = llama
[11/08/2024-23:33:45] [TRT-LLM] [W] Implicitly setting LLaMAConfig.rmsnorm = True
[11/08/2024-23:33:45] [TRT-LLM] [W] Implicitly setting LLaMAConfig.lm_head_bias = False
[11/08/2024-23:33:46] [TRT-LLM] [W] Provided but not expected tensors: {'transformer.layers.10.attention.kv_cache_scaling_factor', 'transformer.layers.79.attention.kv_cache_scaling_factor', 'transformer.layers.29.attention.kv_cache_scaling_factor', 'transformer.layers.9.attention.kv_cache_scaling_factor', 'transformer.layers.77.attention.kv_cache_scaling_factor', 'transformer.layers.2.attention.kv_cache_scaling_factor', 'transformer.layers.40.attention.kv_cache_scaling_factor', 'transformer.layers.38.attention.kv_cache_scaling_factor', 'transformer.layers.22.attention.kv_cache_scaling_factor', 'transformer.layers.19.attention.kv_cache_scaling_factor', 'transformer.layers.58.attention.kv_cache_scaling_factor', 'transformer.layers.32.attention.kv_cache_scaling_factor', 'transformer.layers.55.attention.kv_cache_scaling_factor', 'transformer.layers.76.attention.kv_cache_scaling_factor', 'transformer.layers.75.attention.kv_cache_scaling_factor', 'transformer.layers.39.attention.kv_cache_scaling_factor', 'transformer.layers.8.attention.kv_cache_scaling_factor', 'transformer.layers.16.attention.kv_cache_scaling_factor', 'transformer.layers.46.attention.kv_cache_scaling_factor', 'transformer.layers.31.attention.kv_cache_scaling_factor', 'transformer.layers.4.attention.kv_cache_scaling_factor', 'transformer.layers.34.attention.kv_cache_scaling_factor', 'transformer.layers.73.attention.kv_cache_scaling_factor', 'transformer.layers.28.attention.kv_cache_scaling_factor', 'transformer.layers.23.attention.kv_cache_scaling_factor', 'transformer.layers.18.attention.kv_cache_scaling_factor', 'transformer.layers.15.attention.kv_cache_scaling_factor', 'transformer.layers.42.attention.kv_cache_scaling_factor', 'transformer.layers.68.attention.kv_cache_scaling_factor', 'transformer.layers.72.attention.kv_cache_scaling_factor', 'transformer.layers.20.attention.kv_cache_scaling_factor', 'transformer.layers.11.attention.kv_cache_scaling_factor', 'transformer.layers.71.attention.kv_cache_scaling_factor', 'transformer.layers.49.attention.kv_cache_scaling_factor', 'transformer.layers.25.attention.kv_cache_scaling_factor', 'transformer.layers.61.attention.kv_cache_scaling_factor', 'transformer.layers.78.attention.kv_cache_scaling_factor', 'transformer.layers.3.attention.kv_cache_scaling_factor', 'transformer.layers.63.attention.kv_cache_scaling_factor', 'transformer.layers.43.attention.kv_cache_scaling_factor', 'transformer.layers.36.attention.kv_cache_scaling_factor', 'transformer.layers.60.attention.kv_cache_scaling_factor', 'transformer.layers.35.attention.kv_cache_scaling_factor', 'transformer.layers.70.attention.kv_cache_scaling_factor', 'transformer.layers.26.attention.kv_cache_scaling_factor', 'transformer.layers.74.attention.kv_cache_scaling_factor', 'transformer.layers.66.attention.kv_cache_scaling_factor', 'transformer.layers.64.attention.kv_cache_scaling_factor', 'transformer.layers.54.attention.kv_cache_scaling_factor', 'transformer.layers.24.attention.kv_cache_scaling_factor', 'transformer.layers.53.attention.kv_cache_scaling_factor', 'transformer.layers.57.attention.kv_cache_scaling_factor', 'transformer.layers.37.attention.kv_cache_scaling_factor', 'transformer.layers.56.attention.kv_cache_scaling_factor', 'transformer.layers.41.attention.kv_cache_scaling_factor', 'transformer.layers.59.attention.kv_cache_scaling_factor', 'transformer.layers.50.attention.kv_cache_scaling_factor', 'transformer.layers.65.attention.kv_cache_scaling_factor', 'transformer.layers.5.attention.kv_cache_scaling_factor', 'transformer.layers.0.attention.kv_cache_scaling_factor', 'transformer.layers.17.attention.kv_cache_scaling_factor', 'transformer.layers.51.attention.kv_cache_scaling_factor', 'transformer.layers.13.attention.kv_cache_scaling_factor', 'transformer.layers.67.attention.kv_cache_scaling_factor', 'transformer.layers.45.attention.kv_cache_scaling_factor', 'transformer.layers.1.attention.kv_cache_scaling_factor', 'transformer.layers.33.attention.kv_cache_scaling_factor', 'transformer.layers.44.attention.kv_cache_scaling_factor', 'transformer.layers.7.attention.kv_cache_scaling_factor', 'transformer.layers.52.attention.kv_cache_scaling_factor', 'transformer.layers.12.attention.kv_cache_scaling_factor', 'transformer.layers.27.attention.kv_cache_scaling_factor', 'transformer.layers.30.attention.kv_cache_scaling_factor', 'transformer.layers.6.attention.kv_cache_scaling_factor', 'transformer.layers.21.attention.kv_cache_scaling_factor', 'transformer.layers.62.attention.kv_cache_scaling_factor', 'transformer.layers.69.attention.kv_cache_scaling_factor', 'transformer.layers.48.attention.kv_cache_scaling_factor', 'transformer.layers.47.attention.kv_cache_scaling_factor', 'transformer.layers.14.attention.kv_cache_scaling_factor'}
[11/08/2024-23:33:46] [TRT-LLM] [I] Set dtype to float16.
[11/08/2024-23:33:46] [TRT-LLM] [I] Set paged_kv_cache to True.
[11/08/2024-23:33:46] [TRT-LLM] [W] Overriding paged_state to False
[11/08/2024-23:33:46] [TRT-LLM] [I] Set paged_state to False.
[11/08/2024-23:33:46] [TRT-LLM] [W] remove_input_padding is enabled, while opt_num_tokens is not set, setting to max_batch_size*max_beam_width. 

[11/08/2024-23:33:46] [TRT-LLM] [W] padding removal and fMHA are both enabled, max_input_len is not required and will be ignored
[11/08/2024-23:34:45] [TRT] [I] [MemUsageChange] Init CUDA: CPU +16, GPU +0, now: CPU 9248, GPU 527 (MiB)
[11/08/2024-23:34:54] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +4634, GPU +1274, now: CPU 14037, GPU 1801 (MiB)
[11/08/2024-23:34:54] [TRT-LLM] [I] Set nccl_plugin to float16.
[11/08/2024-23:34:56] [TRT-LLM] [I] Total time of constructing network from module object 69.56684184074402 seconds
[11/08/2024-23:34:56] [TRT-LLM] [I] Total optimization profiles added: 1
[11/08/2024-23:34:56] [TRT-LLM] [I] Total time to initialize the weights in network Unnamed Network 0: 00:00:00
[11/08/2024-23:34:56] [TRT-LLM] [I] Build TensorRT engine Unnamed Network 0
[11/08/2024-23:34:56] [TRT] [W] Unused Input: position_ids
[11/08/2024-23:34:57] [TRT] [W] [RemoveDeadLayers] Input Tensor position_ids is unused or used only at compile-time, but is not being removed.
[11/08/2024-23:34:57] [TRT] [I] Global timing cache in use. Profiling results in this builder pass will be stored.
[11/08/2024-23:34:57] [TRT] [I] Compiler backend is used during engine build.
Internal Error: MyelinCheckException: autotuner.cpp:655: CHECK(!lpm.mvmf().empty() && "compile resulted in null program?") failed. 
[11/08/2024-23:42:30] [TRT] [E] Error Code: 9: Skipping tactic 0x0000000000000000 due to exception [operation.cpp:finalize_cask_heuristic_result:2003] Platform (Cuda) error
[11/08/2024-23:42:30] [TRT] [E] [scopedCudaResources.cpp::~ScopedCudaStream::55] Error Code 1: Cuda Runtime (unspecified launch failure)
[11/08/2024-23:42:30] [TRT] [E] IBuilder::buildSerializedNetwork: Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[LLaMAForCausalLM/transformer/layers/0/attention/qkv/value_L147/get_tensor_L138/get_constant_tensor_L129/_create_constant_tensor_L113/constant_L1151/CONSTANT_2...LLaMAForCausalLM/transformer/layers/0/attention/qkv/multiply_collect_L272/multiply_and_lora_L246/matmul_L1049/cast_L856/CAST_0]}.)
Traceback (most recent call last):
  File "/usr/local/bin/trtllm-build", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 568, in main
    parallel_build(model_config, ckpt_dir, build_config, args.output_dir,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 423, in parallel_build
    passed = build_and_save(rank, rank % workers, ckpt_dir,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 390, in build_and_save
    engine = build_model(build_config,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 383, in build_model
    return build(model, build_config)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/builder.py", line 1189, in build
    engine = None if build_config.dry_run else builder.build_engine(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_common.py", line 204, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/builder.py", line 418, in build_engine
    assert engine is not None, 'Engine building failed, please check the error log.'
AssertionError: Engine building failed, please check the error log.

### additional notes

I was able to build the model with gemm_plugin fp8 but deploying it using triton used to make it hang and not give any response (i waited 10 mins for a token, with 1 input of size 3k tokens) (all 4 H100 were at 100% utilization)

**Comment by hello-11** [comment]
@chrisreese-if Thanks for your interest in TrtLLM. Could you try to add `--workers 4` when you use trtllm-build?
