### ISSUE TITLE
Issues with installing on Windows

### ISSUE THREAD

**Issue by PyroGenesis** [NVIDIA/TensorRT-LLM#2489]
### System Info

- CPU architecture: x64
- Libraries
  - TensorRT-LLM: 0.14.0
  - CUDA: 12.6, 12.4, 12.1
- OS: Windows 10

### Who can help?

@byshiue 

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I'm trying to follow the guide for Installation on Windows here: https://nvidia.github.io/TensorRT-LLM/installation/windows.html

1. I Installed all the prerequisites using the provided PowerShell script which installed Python 3.10 and CUDA 12.6
2. On running the verification command `python -c "import tensorrt_llm; print(tensorrt_llm._utils.trt_version())"` the first time, I got the error `ModuleNotFoundError: No module named 'tensorrt_bindings'`
3. I found the package `tensorrt-cu12-bindings` mentioned in other issues so I installed that
4. Now when running the verification command again, I get a different error `FileNotFoundError: Could not find: nvinfer_10.dll`

### Expected behavior

Expected TensorRT-LLM to be installed

### actual behavior

```
(trt-llm-py3.10) PS C:\Users\PyroDev\Documents\trt-llm> python -c "import tensorrt_llm; print(tensorrt_llm._utils.trt_version())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\PyroDev\Documents\trt-llm\.venv\lib\site-packages\tensorrt_llm\__init__.py", line 32, in <module>
    import tensorrt_llm.functional as functional
  File "C:\Users\PyroDev\Documents\trt-llm\.venv\lib\site-packages\tensorrt_llm\functional.py", line 25, in <module>
    import tensorrt as trt
  File "C:\Users\PyroDev\Documents\trt-llm\.venv\lib\site-packages\tensorrt\__init__.py", line 18, in <module>
    from tensorrt_bindings import *
  File "C:\Users\PyroDev\Documents\trt-llm\.venv\lib\site-packages\tensorrt_bindings\__init__.py", line 69, in <module>
    lib_path = find_lib(lib)
  File "C:\Users\PyroDev\Documents\trt-llm\.venv\lib\site-packages\tensorrt_bindings\__init__.py", line 46, in find_lib
    raise FileNotFoundError(
FileNotFoundError: Could not find: nvinfer_10.dll. Is it on your PATH?
Note: Paths searched were:
['C:\\Users\\PyroDev\\Documents\\trt-llm\\.venv/Scripts', 'C:\\Program Files\\Python310', 'C:\\Program Files\\Python310\\Scripts', 'C:\\Program Files\\PowerShell\\7', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.6\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.6\\libnvvp', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.4\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.4\\libnvvp', 'C:\\Program Files\\OpenSSL 3\\bin\\', 'C:\\Program Files\\Python311\\Scripts\\', 'C:\\Program Files\\Python311\\', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1\\libnvvp', 'C:\\Program Files\\Python310\\Scripts\\', 'C:\\Program Files\\Python310\\', 'C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Windows\\System32\\OpenSSH\\', 'C:\\ProgramData\\chocolatey\\bin', 'C:\\Program Files\\Git\\cmd', 'C:\\Program Files\\Microsoft VS Code\\bin', 'C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common', 'C:\\Program Files\\ESET\\ESET Security\\', 'C:\\Program Files\\dotnet\\', 'C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\', 'C:\\Program Files\\Docker\\Docker\\resources\\bin', 'C:\\Users\\PyroDev\\FFmpeg\\bin', 'C:\\Program Files\\PowerShell\\7\\', 'C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2024.3.2\\', 'C:\\Users\\PyroDev\\AppData\\Local\\Microsoft\\WindowsApps', 'C:\\Users\\PyroDev\\AppData\\Roaming\\Python\\Scripts', 'C:\\Users\\PyroDev\\.dotnet\\tools', 'C:\\Users\\PyroDev\\AppData\\Local\\Microsoft\\WindowsApps', 'C:\\Users\\PyroDev\\AppData\\Roaming\\Python\\Scripts', 'C:\\Users\\PyroDev\\.dotnet\\tools', 'C:\\Program Files\\Python310', 'C:\\Program Files\\Python310\\Scripts', '']
```

### additional notes

This is the list of all my Python packages:

```
Package                  Version
------------------------ ------------
accelerate               1.1.1
aiohappyeyeballs         2.4.3
aiohttp                  3.11.7
aiosignal                1.3.1
annotated-types          0.7.0
async-timeout            5.0.1
attrs                    24.2.0
build                    1.2.2.post1
certifi                  2024.8.30
charset-normalizer       3.4.0
cloudpickle              3.1.0
colorama                 0.4.6
colored                  2.2.4
coloredlogs              15.0.1
cuda-python              12.5.0
datasets                 2.14.4
diffusers                0.31.0
dill                     0.3.7
evaluate                 0.4.3
filelock                 3.16.1
frozenlist               1.5.0
fsspec                   2024.10.0
h5py                     3.10.0
huggingface-hub          0.26.2
humanfriendly            10.0
idna                     3.10
importlib_metadata       8.5.0
janus                    1.1.0
Jinja2                   3.1.4
markdown-it-py           3.0.0
MarkupSafe               3.0.2
mdurl                    0.1.2
mpmath                   1.3.0
multidict                6.1.0
multiprocess             0.70.15
networkx                 3.4.2
ninja                    1.11.1.1
numpy                    1.26.4
nvidia-cuda-runtime-cu12 12.4.99
nvidia-modelopt          0.17.0
onnx                     1.17.0
optimum                  1.23.3
packaging                24.2
pandas                   2.2.3
pillow                   11.0.0
pip                      24.2
polygraphy               0.49.9
propcache                0.2.0
protobuf                 5.28.3
psutil                   6.1.0
PuLP                     2.9.0
pyarrow                  18.0.0
pydantic                 2.10.1
pydantic_core            2.27.1
Pygments                 2.18.0
pynvml                   11.5.3
pyproject_hooks          1.2.0
pyreadline3              3.5.4
python-dateutil          2.9.0.post0
pytz                     2024.2
pywin32                  308
PyYAML                   6.0.2
regex                    2024.11.6
requests                 2.32.3
rich                     13.9.4
safetensors              0.4.5
scipy                    1.14.1
sentencepiece            0.2.0
setuptools               75.2.0
six                      1.16.0
StrEnum                  0.4.15
sympy                    1.13.3
tensorrt                 10.4.0
tensorrt-cu12            10.4.0
tensorrt-cu12_bindings   10.6.0.post1
tensorrt-llm             0.14.0
tokenizers               0.20.3
tomli                    2.1.0
torch                    2.4.1+cu124
torchprofile             0.0.4
torchvision              0.19.1+cu124
tqdm                     4.67.0
transformers             4.45.1
typing_extensions        4.12.2
tzdata                   2024.2
urllib3                  2.2.3
wheel                    0.45.1
xxhash                   3.5.0
yarl                     1.18.0
zipp                     3.21.0
```

**Comment by PyroGenesis** [comment]
I tried downgrading `tensorrt_cu12_bindings` to 10.4.0, but that didn't help.

When I look for nvinfer on my system, I only see `nvinfer_plugin_tensorrt_llm.dll` in `C:\Users\PyroDev\Documents\trt-llm\.venv\Lib\site-packages\tensorrt_llm\libs`

**Comment by Liuqh12** [comment]
same question.
I do this:
1. download : https://developer.nvidia.com/tensorrt/download/10x
2. unzip 
3. cd TensorRT-10.4.0.26\python
4. pip install tensorrt-10.4.0-cp310-none-win_amd64.whl  --force-reinstall
After this:
python -c "import tensorrt_llm; print(tensorrt_llm._utils.trt_version())"
i got:
[TensorRT-LLM] TensorRT-LLM version: 0.14.0
10.4.0

**Comment by hello-11** [comment]
@PyroGenesis Do you still have the issue?

**Comment by PyroGenesis** [comment]
We fixed this by downloading TensorRT (10.4.0) zip, extracting it and then moving `nvinfer_10.dll` and other DLLs from the `/lib` folder to our `.venv/Scripts` folder.

It would be great if this step was added to the PowerShell script and/or the documentation.
