### ISSUE TITLE
Ambiguous error message when config.json is missing.

### ISSUE THREAD

**Issue by Wonder-donbury** [NVIDIA/TensorRT-LLM#2505]
### System Info

on main.

### Who can help?

@byshiue 

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```bash
(venv) admin@llm-inference-l4x4-96gb-admin-linux:~/tensorrt$ python3 ./TensorRT-LLM/examples/qwen/convert_checkpoint.py --model_dir ./Qwen2.5_7B_instruct_240920 --output_dir ./trt_engines/Qwen2.5_7B_instruct_240920_4gpu_tp
2_pp2 --dtype float16 --tp_size 2 --pp_size 2
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
[TensorRT-LLM] TensorRT-LLM version: 0.16.0.dev2024111900
0.16.0.dev2024111900
Traceback (most recent call last):
  File "/home/admin/tensorrt/./TensorRT-LLM/examples/qwen/convert_checkpoint.py", line 308, in <module>
    main()
  File "/home/admin/tensorrt/./TensorRT-LLM/examples/qwen/convert_checkpoint.py", line 300, in main
    convert_and_save_hf(args)
  File "/home/admin/tensorrt/./TensorRT-LLM/examples/qwen/convert_checkpoint.py", line 256, in convert_and_save_hf
    execute(args.workers, [convert_and_save_rank] * world_size, args)
  File "/home/admin/tensorrt/./TensorRT-LLM/examples/qwen/convert_checkpoint.py", line 263, in execute
    f(args, rank)
  File "/home/admin/tensorrt/./TensorRT-LLM/examples/qwen/convert_checkpoint.py", line 246, in convert_and_save_rank
    qwen = QWenForCausalLM.from_hugging_face(
  File "/home/admin/tensorrt/venv/lib/python3.10/site-packages/tensorrt_llm/models/qwen/model.py", line 301, in from_hugging_face
    config = QWenConfig.from_hugging_face(hf_config_or_dir,
  File "/home/admin/tensorrt/venv/lib/python3.10/site-packages/tensorrt_llm/models/qwen/config.py", line 83, in from_hugging_face
    hf_config = transformers.AutoConfig.from_pretrained(
  File "/home/admin/tensorrt/venv/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1038, in from_pretrained
    raise ValueError(
ValueError: Unrecognized model in ./Qwen2.5_7B_instruct_240920. Should have a `model_type` key in its config.json, or contain one of the following strings in its name:
```

### Expected behavior

In the convert_checkpoint.py  under `examples/qwen/` When the `model_dir` is wrong, the error message says that 'model_type' key is missing. I found it a bit misleading.

I think the code should first determine if there's a `config.json` in the model path, and if the json file is missing, then error message should be something like "There isn't any 'config.json' in the `model_dir`"

I've been wasting hours to figure out why the code couldn't locate the key in my json file XD.

### actual behavior

The ValueError indicates the wrong cause of the error.

### additional notes

none

**Comment by byshiue** [comment]
The error message is replied by `transformers`. It is not handled by TensorRT-LLM. You can open an issue to transformers to ask improving.
