### ISSUE TITLE
Was doing a demo task (replaced chatglm3_6b with chatglm3_6b_32k) and encountered AttributeError

### ISSUE THREAD

**Issue by TriDefender** [NVIDIA/TensorRT-LLM#2517]
I ran 
`(trt) C:\LLM\TensorRT-LLM\examples\chatglm>trtllm-build --checkpoint_dir trt_ckpt/chatglm3_6b_32k/fp16/1-gpu --gemm_plugin float16  --output_dir trt_engines/chatglm3_6b_32k/fp16/1-gpu`
and got:
```
[TensorRT-LLM] TensorRT-LLM version: 0.14.0
[12/01/2024-13:36:10] [TRT-LLM] [I] Compute capability: (8, 9)
[12/01/2024-13:36:10] [TRT-LLM] [I] SM count: 34
[12/01/2024-13:36:10] [TRT-LLM] [I] SM clock: 3105 MHz
[12/01/2024-13:36:10] [TRT-LLM] [I] int4 TFLOPS: 216
[12/01/2024-13:36:10] [TRT-LLM] [I] int8 TFLOPS: 108
[12/01/2024-13:36:10] [TRT-LLM] [I] fp8 TFLOPS: 108
[12/01/2024-13:36:10] [TRT-LLM] [I] float16 TFLOPS: 54
[12/01/2024-13:36:10] [TRT-LLM] [I] bfloat16 TFLOPS: 54
[12/01/2024-13:36:10] [TRT-LLM] [I] float32 TFLOPS: 27
[12/01/2024-13:36:10] [TRT-LLM] [I] Total Memory: 15 GiB
[12/01/2024-13:36:10] [TRT-LLM] [I] Memory clock: 9001 MHz
[12/01/2024-13:36:10] [TRT-LLM] [I] Memory bus width: 128
[12/01/2024-13:36:10] [TRT-LLM] [I] Memory bandwidth: 288 GB/s
[12/01/2024-13:36:10] [TRT-LLM] [I] PCIe speed: 16000 Mbps
[12/01/2024-13:36:10] [TRT-LLM] [I] PCIe link width: 8
[12/01/2024-13:36:10] [TRT-LLM] [I] PCIe bandwidth: 16 GB/s
Traceback (most recent call last):
  File "C:\Users\18913\anaconda3\envs\trt\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\18913\anaconda3\envs\trt\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\18913\anaconda3\envs\trt\Scripts\trtllm-build.exe\__main__.py", line 7, in <module>
  File "C:\Users\18913\anaconda3\envs\trt\lib\site-packages\tensorrt_llm\commands\build.py", line 568, in main
    parallel_build(model_config, ckpt_dir, build_config, args.output_dir,
  File "C:\Users\18913\anaconda3\envs\trt\lib\site-packages\tensorrt_llm\commands\build.py", line 423, in parallel_build
    passed = build_and_save(rank, rank % workers, ckpt_dir,
  File "C:\Users\18913\anaconda3\envs\trt\lib\site-packages\tensorrt_llm\commands\build.py", line 390, in build_and_save
    engine = build_model(build_config,
  File "C:\Users\18913\anaconda3\envs\trt\lib\site-packages\tensorrt_llm\commands\build.py", line 335, in build_model
    assert not build_config.plugin_config.streamingllm or architecture == "LlamaForCausalLM", \
  File "C:\Users\18913\anaconda3\envs\trt\lib\site-packages\tensorrt_llm\plugin\plugin.py", line 95, in prop
    field_value = getattr(self, storage_name)
AttributeError: 'PluginConfig' object has no attribute '_streamingllm'. Did you mean: '_streamingllm'?
``
For more info this is a RTX 4060ti running on windows 11, tried with `--streamingllm ` and got same error, python is 3.10.0
```
(trt) C:\LLM\TensorRT-LLM\examples\chatglm>pip list
Package                  Version
------------------------ ------------
absl-py                  2.1.0
accelerate               1.1.1
aiohappyeyeballs         2.4.4
aiohttp                  3.11.8
aiosignal                1.3.1
annotated-types          0.7.0
async-timeout            5.0.1
attrs                    24.2.0
build                    1.2.2.post1
certifi                  2024.8.30
charset-normalizer       3.4.0
click                    8.1.7
cloudpickle              3.1.0
colorama                 0.4.6
colored                  2.2.4
coloredlogs              15.0.1
cuda-python              12.5.0
datasets                 2.14.7
diffusers                0.31.0
dill                     0.3.7
evaluate                 0.4.3
filelock                 3.16.1
flatbuffers              24.3.25
frozenlist               1.5.0
fsspec                   2023.10.0
h5py                     3.10.0
huggingface-hub          0.26.3
humanfriendly            10.0
idna                     3.10
importlib_metadata       8.5.0
janus                    1.1.0
Jinja2                   3.1.4
joblib                   1.4.2
markdown-it-py           3.0.0
MarkupSafe               3.0.2
mdurl                    0.1.2
mpmath                   1.3.0
multidict                6.1.0
multiprocess             0.70.15
networkx                 3.4.2
ninja                    1.11.1.2
nltk                     3.9.1
numpy                    1.26.4
nvidia-cuda-runtime-cu12 12.6.77
nvidia-modelopt          0.17.0
onnx                     1.17.0
onnxruntime              1.15.1
optimum                  1.23.3
packaging                24.2
pandas                   2.2.3
pillow                   11.0.0
pip                      24.2
polygraphy               0.49.9
propcache                0.2.0
protobuf                 5.29.0
psutil                   6.1.0
PuLP                     2.9.0
pyarrow                  18.1.0
pyarrow-hotfix           0.6
pydantic                 2.10.2
pydantic_core            2.27.1
Pygments                 2.18.0
pynvml                   11.5.3
pyproject_hooks          1.2.0
pyreadline3              3.5.4
python-dateutil          2.9.0.post0
pytz                     2024.2
pywin32                  308
PyYAML                   6.0.2
regex                    2024.11.6
requests                 2.32.3
rich                     13.9.4
rouge_score              0.1.2
safetensors              0.4.5
scipy                    1.14.1
sentencepiece            0.2.0
setuptools               75.1.0
six                      1.16.0
StrEnum                  0.4.15
sympy                    1.13.3
tensorrt                 10.4.0
tensorrt-cu12            10.4.0
tensorrt-cu12_bindings   10.4.0
tensorrt-cu12_libs       10.4.0
tensorrt-llm             0.14.0
tiktoken                 0.8.0
tokenizers               0.19.1
tomli                    2.2.1
torch                    2.4.1+cu124
torchprofile             0.0.4
torchvision              0.19.1+cu124
tqdm                     4.67.1
transformers             4.43.0
typing_extensions        4.12.2
tzdata                   2024.2
urllib3                  2.2.3
wheel                    0.44.0
xxhash                   3.5.0
yarl                     1.18.0
zipp                     3.21.0
```

**Comment by TriDefender** [comment]
```
PS C:\Users\18913> nvidia-smi
Sun Dec  1 13:42:33 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.14                 Driver Version: 566.14         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 Ti   WDDM  |   00000000:01:00.0  On |                  N/A |
|  0%   49C    P8              4W /  176W |     974MiB /  16380MiB |      3%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
```

**Comment by karljang** [comment]
Sorry we never replied to this one. Closing as stale since the TensorRT engine-build path is deprecated in favor of the PyTorch backend. Please open a new issue if the problem persists in the latest version.
