### ISSUE TITLE
INT8 weight only + INT8 KV cache for codeLlama-7b has errors

### ISSUE THREAD

**Issue by activezhao** [NVIDIA/TensorRT-LLM#254]
I download CodeLlama-7b from HF, and I use the command for hf_llama_convert as following:
```
python3 hf_llama_convert.py -i ./META-CodeLlama-7b-hf/ -o /tensorrtllm_backend/smooth_llama_7B/int8_kv_cache/ --calibrate-kv-cache -t fp16 -tp 4

=============== Argument ===============
out_dir: /tensorrtllm_backend/smooth_llama_7B/int8_kv_cache/
in_file: ./META-CodeLlama-7b-hf/
tensor_parallelism: 4
processes: 4
calibrate_kv_cache: True
smoothquant: None
storage_type: fp16
multi_query_mode: False
========================================
The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
```

Then I try to build engines for `INT8 weight only + INT8 KV cache`, I meet an error with `no file named config.json,` the error is this:
```
python build.py --model_dir  /tensorrtllm_backend/smooth_llama_7B/int8_kv_cache/4-gpu/  \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --paged_kv_cache \
                --use_inflight_batching \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --output_dir /trt_llama_7b_fp16_int8_kv_cache_weight_only/4-gpu/  \
                --world_size 4 \
                --tp_size 4 \
                --int8_kv_cache \
                --use_weight_only

Traceback (most recent call last):
  File "/tensorrtllm_backend/tensorrt_llm/examples/llama/build.py", line 707, in <module>
    args = parse_arguments()
  File "/tensorrtllm_backend/tensorrt_llm/examples/llama/build.py", line 402, in parse_arguments
    hf_config = LlamaConfig.from_pretrained(args.model_dir)
  File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 590, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 617, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 672, in _get_config_dict
    resolved_config_file = cached_file(
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 388, in cached_file
    raise EnvironmentError(
OSError: /tensorrtllm_backend/smooth_llama_7B/int8_kv_cache/4-gpu/ does not appear to have a file named config.json. Checkout 'https://huggingface.co//tensorrtllm_backend/smooth_llama_7B/int8_kv_cache/4-gpu//main' for available files.
```

 I have no choice but copy a config.json original META-CodeLlama-7b-hf, then I get another error like this:
```
python build.py --model_dir  /tensorrtllm_backend/smooth_llama_7B/int8_kv_cache/4-gpu/                  --dtype float16                 --remove_input_padding                 --use_gpt_attention_plugin float16                 --paged_kv_cache                 --use_inflight_batching                 --enable_context_fmha                 --use_gemm_plugin float16                 --output_dir /trt_llama_7b_fp16_int8_kv_cache_weight_only/4-gpu/                  --world_size 4                 --tp_size 4                 --int8_kv_cache                 --use_weight_only

[11/02/2023-11:14:06] [TRT-LLM] [I] Serially build TensorRT engines.
[11/02/2023-11:14:06] [TRT] [I] [MemUsageChange] Init CUDA: CPU +13, GPU +0, now: CPU 118, GPU 228 (MiB)
[11/02/2023-11:14:08] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1799, GPU +312, now: CPU 2053, GPU 540 (MiB)
[11/02/2023-11:14:08] [TRT-LLM] [W] Invalid timing cache, using freshly created one
[11/02/2023-11:14:10] [TRT-LLM] [I] Loading HF LLaMA ... from /tensorrtllm_backend/smooth_llama_7B/int8_kv_cache/4-gpu/
Traceback (most recent call last):
  File "/tensorrtllm_backend/tensorrt_llm/examples/llama/build.py", line 718, in <module>
    build(0, args)
  File "/tensorrtllm_backend/tensorrt_llm/examples/llama/build.py", line 689, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/tensorrtllm_backend/tensorrt_llm/examples/llama/build.py", line 553, in build_rank_engine
    hf_llama = LlamaForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 2474, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /tensorrtllm_backend/smooth_llama_7B/int8_kv_cache/4-gpu/.
```

Now, I do not know what to do to solve the errors.

**Comment by atyshka** [comment]
I think you're calling it with the wrong args. `--model_dir` is for a huggingface model, which is not quantized. You have a 
binary model (FasterTransformer format) so you should use the `--ft_model_dir` arg like in the README:
```
# Build model with both INT8 weight-only and INT8 KV cache enabled
python build.py --ft_model_dir=/llama/smooth_llama_7B/int8_kv_cache/1-gpu/ \
                --dtype float16 \
                --use_gpt_attention_plugin float16 \
                --use_gemm_plugin float16 \
                --output_dir ./tmp/llama/7B/trt_engines/int8_kv_cache_weight_only/1-gpu \
                --int8_kv_cache \
                --use_weight_only
```

**Comment by activezhao** [comment]
> I think you're calling it with the wrong args. `--model_dir` is for a huggingface model, which is not quantized. You have a 
> binary model (FasterTransformer format) so you should use the `--ft_model_dir` arg like in the README:
> ```
> # Build model with both INT8 weight-only and INT8 KV cache enabled
> python build.py --ft_model_dir=/llama/smooth_llama_7B/int8_kv_cache/1-gpu/ \
>                 --dtype float16 \
>                 --use_gpt_attention_plugin float16 \
>                 --use_gemm_plugin float16 \
>                 --output_dir ./tmp/llama/7B/trt_engines/int8_kv_cache_weight_only/1-gpu \
>                 --int8_kv_cache \
>                 --use_weight_only
> ```

@atyshka OK, thanks for your reply, I will try it.

**Comment by activezhao** [comment]
> > I think you're calling it with the wrong args. `--model_dir` is for a huggingface model, which is not quantized. You have a
> > binary model (FasterTransformer format) so you should use the `--ft_model_dir` arg like in the README:
> > ```
> > # Build model with both INT8 weight-only and INT8 KV cache enabled
> > python build.py --ft_model_dir=/llama/smooth_llama_7B/int8_kv_cache/1-gpu/ \
> >                 --dtype float16 \
> >                 --use_gpt_attention_plugin float16 \
> >                 --use_gemm_plugin float16 \
> >                 --output_dir ./tmp/llama/7B/trt_engines/int8_kv_cache_weight_only/1-gpu \
> >                 --int8_kv_cache \
> >                 --use_weight_only
> > ```
> 
> @atyshka OK, thanks for your reply, I will try it.

@atyshka It works, thanks.

But, when I use smoothquant, I encountered some strange things.
`https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/llama/README.md#smoothquant`


I download CodeLlama-7B-HF from HuggingFace, and I use A10.

First, I use the following command for **hf_llama_convert**:

```
python3 hf_llama_convert.py -i /tensorrtllm_backend/tensorrt_llm/examples/llama/META-CodeLlama-7b-hf/ -o /tensorrtllm_backend/smooth_llama_7B/sq0.5/ -sq 0.5 --tensor-parallelism 4 --storage-type fp16 --multi-query-mode
```

Here is the log:
```
=============== Argument ===============
out_dir: /tensorrtllm_backend/smooth_llama_7B/sq0.5/
in_file: /tensorrtllm_backend/tensorrt_llm/examples/llama/META-CodeLlama-7b-hf/
tensor_parallelism: 4
processes: 4
calibrate_kv_cache: False
smoothquant: 0.5
storage_type: fp16
multi_query_mode: True
========================================
The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:09<00:00,  5.00s/it]
Some weights of LlamaForCausalLM were not initialized from the model checkpoint at /tensorrtllm_backend/tensorrt_llm/examples/llama/META-CodeLlama-7b-hf/ and are newly initialized: ['model.layers.0.self_attn.rotary_emb.inv_freq', 'model.layers.15.self_attn.rotary_emb.inv_freq', 'model.layers.9.self_attn.rotary_emb.inv_freq', 'model.layers.11.self_attn.rotary_emb.inv_freq', 'model.layers.17.self_attn.rotary_emb.inv_freq', 'model.layers.31.self_attn.rotary_emb.inv_freq', 'model.layers.19.self_attn.rotary_emb.inv_freq', 'model.layers.28.self_attn.rotary_emb.inv_freq', 'model.layers.29.self_attn.rotary_emb.inv_freq', 'model.layers.5.self_attn.rotary_emb.inv_freq', 'model.layers.13.self_attn.rotary_emb.inv_freq', 'model.layers.4.self_attn.rotary_emb.inv_freq', 'model.layers.6.self_attn.rotary_emb.inv_freq', 'model.layers.27.self_attn.rotary_emb.inv_freq', 'model.layers.7.self_attn.rotary_emb.inv_freq', 'model.layers.16.self_attn.rotary_emb.inv_freq', 'model.layers.10.self_attn.rotary_emb.inv_freq', 'model.layers.21.self_attn.rotary_emb.inv_freq', 'model.layers.22.self_attn.rotary_emb.inv_freq', 'model.layers.12.self_attn.rotary_emb.inv_freq', 'model.layers.3.self_attn.rotary_emb.inv_freq', 'model.layers.20.self_attn.rotary_emb.inv_freq', 'model.layers.2.self_attn.rotary_emb.inv_freq', 'model.layers.8.self_attn.rotary_emb.inv_freq', 'model.layers.23.self_attn.rotary_emb.inv_freq', 'model.layers.24.self_attn.rotary_emb.inv_freq', 'model.layers.26.self_attn.rotary_emb.inv_freq', 'model.layers.30.self_attn.rotary_emb.inv_freq', 'model.layers.14.self_attn.rotary_emb.inv_freq', 'model.layers.25.self_attn.rotary_emb.inv_freq', 'model.layers.18.self_attn.rotary_emb.inv_freq', 'model.layers.1.self_attn.rotary_emb.inv_freq']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using the latest cached version of the module from /root/.cache/huggingface/modules/datasets_modules/datasets/ccdv--cnn_dailymail/0107f7388b5c6fae455a5661bcd134fc22da53ea75852027040d8d1e997f101f (last modified on Thu Nov  2 09:30:00 2023) since it couldn't be found locally at ccdv/cnn_dailymail., or remotely on the Hugging Face Hub.
/usr/local/lib/python3.10/dist-packages/datasets/table.py:1421: FutureWarning: promote has been superseded by mode='default'.
  table = cls._concat_blocks(blocks, axis=0)
calibrating model:   0%|                                                                                                                                      | 0/512 [00:00<?, ?it/s]Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
calibrating model: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [08:53<00:00,  1.04s/it]
saving weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 288/288 [01:37<00:00,  2.95it/s]
[W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
```

Then I use the following command for **building engines**:
```
python3 build.py --ft_model_dir=/tensorrtllm_backend/smooth_llama_7B/sq0.5/4-gpu/ \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --paged_kv_cache \
                --use_inflight_batching \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --max_batch_size 64  \
                --use_smooth_quant \
                --per_token \
                --per_channel\
                --world_size 4 \
                --tp_size 4 \
                --output_dir /tensorrtllm_backend/trt_llama_7b_sq_pt_pc/sq0.5/4-gpu/
```
I find sth strange in the log, here are part of them:
```
[11/07/2023-03:01:26] [TRT] [W] IElementWiseLayer with inputs LLaMAForCausalLM/layers/31/mlp/ELEMENTWISE_PROD_1_output_0 and LLaMAForCausalLM/layers/31/mlp/SHUFFLE_0_output_0: first input has type Half but second input has type Float.
[11/07/2023-03:01:26] [TRT] [W] ITensor::setType(Int8) was called on non I/O tensor: LLaMAForCausalLM/layers/31/mlp/PLUGIN_V2_QuantizePerToken_0_output_0. This will have no effect unless this tensor is marked as an output.
[11/07/2023-03:01:26] [TRT] [W] ITensor::setType(Float) was called on non I/O tensor: LLaMAForCausalLM/layers/31/mlp/PLUGIN_V2_QuantizePerToken_1_output_1. This will have no effect unless this tensor is marked as an output.
[11/07/2023-03:01:26] [TRT] [W] A shape layer can only run in INT32 precision
[11/07/2023-03:01:26] [TRT] [W] IElementWiseLayer with inputs LLaMAForCausalLM/layers/31/ELEMENTWISE_SUM_1_output_0 and LLaMAForCausalLM/ln_f/SHUFFLE_0_output_0: first input has type Half but second input has type Float.
[11/07/2023-03:01:26] [TRT] [W] A shape layer can only run in INT32 precision
[11/07/2023-03:01:26] [TRT] [W] IElementWiseLayer with inputs LLaMAForCausalLM/ln_f/REDUCE_AVG_0_output_0 and LLaMAForCausalLM/ln_f/SHUFFLE_1_output_0: first input has type Half but second input has type Float.
[11/07/2023-03:01:26] [TRT-LLM] [I] Build TensorRT engine llama_float16_tp4_rank0.engine
[11/07/2023-03:01:26] [TRT] [W] Unused Input: position_ids
[11/07/2023-03:01:26] [TRT] [W] Calibrator is not being used. Users must provide dynamic range for all tensors that are not Int32 or Bool.
[11/07/2023-03:01:26] [TRT] [W] Missing scale and zero-point for tensor input_ids, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[11/07/2023-03:01:26] [TRT] [W] Missing scale and zero-point for tensor position_ids, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[11/07/2023-03:01:26] [TRT] [W] Missing scale and zero-point for tensor kv_cache_block_pointers_0, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[11/07/2023-03:01:26] [TRT] [W] Missing scale and zero-point for tensor kv_cache_block_pointers_1, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[11/07/2023-03:01:26] [TRT] [W] Missing scale and zero-point for tensor kv_cache_block_pointers_2, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
```

One key sentence is
```
Missing scale and zero-point for tensor kv_cache_block_pointers_2, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
```

So what I am confused about is that it seem like int8 doesn't take effect? Will this affect the performance?

Finally, I made some tests between FP16 and smoothquant:

I found that the number of tokens per second of smoothquant is about 18% higher than that of FP16.

Is this within the expected range? Or should it be higher normally?

Thanks.

**Comment by Tracin** [comment]
@activezhao 
1. I think those log is ok since those parameters should not runs in int8, you can check the engine size, it should be halved.
2. What is your GPUs and input / output lens and batch size? Basically 18% improvement make sense.

**Comment by activezhao** [comment]
> @activezhao
> 
> 1. I think those log is ok since those parameters should not runs in int8, you can check the engine size, it should be halved.
> 2. What is your GPUs and input / output lens and batch size? Basically 18% improvement make sense.

@Tracin Thanks for  your reply.

1、As you said, smoothquant is almost half the size compared to FP16.

The file sizes of smoothquant:
```
root@71f4db8725fe:/tensorrtllm_backend/trt_llama_7b_sq_pt_pc/sq0.5/4-gpu# du -hs *
4.0K    config.json
1.9G    llama_float16_tp4_rank0.engine
1.9G    llama_float16_tp4_rank1.engine
1.9G    llama_float16_tp4_rank2.engine
1.9G    llama_float16_tp4_rank3.engine
92K     model.cache
```

The file sizes of FP16:
```
root@71f4db8725fe:/tensorrtllm_backend/trt_llama_7b_fp16_kv_cache_inflight_batching/4-gpu# du -hs *
4.0K    config.json
3.4G    llama_float16_tp4_rank0.engine
3.4G    llama_float16_tp4_rank1.engine
3.4G    llama_float16_tp4_rank2.engine
3.4G    llama_float16_tp4_rank3.engine
232K    model.cache
```


2、I use A10, InputTokens lens is 500, output lens is 256, max_batch_size is 64. 

Here is the information of GPUs:
```
(base) [root@VM ~]# nvidia-smi 
Tue Nov  7 14:27:15 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.82.01    Driver Version: 470.82.01    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A10          On   | 00000000:00:08.0 Off |                    0 |
|  0%   45C    P0    59W / 150W |  20830MiB / 22731MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A10          On   | 00000000:00:09.0 Off |                    0 |
|  0%   47C    P0    60W / 150W |  20834MiB / 22731MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A10          On   | 00000000:00:0A.0 Off |                    0 |
|  0%   49C    P0    62W / 150W |  20834MiB / 22731MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A10          On   | 00000000:00:0B.0 Off |                    0 |
|  0%   49C    P0    62W / 150W |  20814MiB / 22731MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```


What's more, I just test [INT8 weight only + INT8 KV cache](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/llama/README.md#int8-weight-only--int8-kv-cache), the number of tokens per second of `INT8 weight only + INT8 KV cache` is about 25% higher than that of FP16.

That means `INT8 weight only + INT8 KV cache` performs better than smoothquant. Is this within the expected?
