### ISSUE TITLE
pip install errors out with HTTP error 404

### ISSUE THREAD

**Issue by HeyangQin** [NVIDIA/TensorRT-LLM#2542]
According to the documentation https://nvidia.github.io/TensorRT-LLM/installation/linux.html, I run `python -m pip install tensorrt-llm` yet it gives
```
Collecting tensorrt-llm
  Using cached tensorrt_llm-0.15.0.tar.gz (1.3 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [98 lines of output]
        File "/tmp/pip-build-env-ybw8xx6w/overlay/lib/python3.12/site-packages/wheel_stub/wheel.py", line 226, in download_wheel
          return download_manual(wheel_directory, distribution, version, config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ybw8xx6w/overlay/lib/python3.12/site-packages/wheel_stub/wheel.py", line 160, in download_manual
          index_response = urlopen_with_retry(project_url)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ybw8xx6w/overlay/lib/python3.12/site-packages/wheel_stub/wheel.py", line 83, in urlopen_with_retry
          return urlopen(url, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/mnt/heyangqin/envs/heyangqin/lib/python3.12/urllib/request.py", line 215, in urlopen
          return opener.open(url, data, timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/mnt/heyangqin/envs/heyangqin/lib/python3.12/urllib/request.py", line 521, in open
          response = meth(req, response)
                     ^^^^^^^^^^^^^^^^^^^
        File "/mnt/heyangqin/envs/heyangqin/lib/python3.12/urllib/request.py", line 630, in http_response
          response = self.parent.error(
                     ^^^^^^^^^^^^^^^^^^
        File "/mnt/heyangqin/envs/heyangqin/lib/python3.12/urllib/request.py", line 559, in error
          return self._call_chain(*args)
                 ^^^^^^^^^^^^^^^^^^^^^^^
        File "/mnt/heyangqin/envs/heyangqin/lib/python3.12/urllib/request.py", line 492, in _call_chain
          result = func(*args)
                   ^^^^^^^^^^^
        File "/mnt/heyangqin/envs/heyangqin/lib/python3.12/urllib/request.py", line 639, in http_error_default
          raise HTTPError(req.full_url, code, msg, hdrs, fp)
      Traceback (most recent call last):
        File "/tmp/pip-build-env-ybw8xx6w/overlay/lib/python3.12/site-packages/wheel_stub/wheel.py", line 226, in download_wheel
          return download_manual(wheel_directory, distribution, version, config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ybw8xx6w/overlay/lib/python3.12/site-packages/wheel_stub/wheel.py", line 160, in download_manual
          index_response = urlopen_with_retry(project_url)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ybw8xx6w/overlay/lib/python3.12/site-packages/wheel_stub/wheel.py", line 83, in urlopen_with_retry
          return urlopen(url, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/mnt/heyangqin/envs/heyangqin/lib/python3.12/urllib/request.py", line 215, in urlopen
          return opener.open(url, data, timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/mnt/heyangqin/envs/heyangqin/lib/python3.12/urllib/request.py", line 521, in open
          response = meth(req, response)
                     ^^^^^^^^^^^^^^^^^^^
        File "/mnt/heyangqin/envs/heyangqin/lib/python3.12/urllib/request.py", line 630, in http_response
          response = self.parent.error(
                     ^^^^^^^^^^^^^^^^^^
        File "/mnt/heyangqin/envs/heyangqin/lib/python3.12/urllib/request.py", line 559, in error
          return self._call_chain(*args)
                 ^^^^^^^^^^^^^^^^^^^^^^^
        File "/mnt/heyangqin/envs/heyangqin/lib/python3.12/urllib/request.py", line 492, in _call_chain
          result = func(*args)
                   ^^^^^^^^^^^
        File "/mnt/heyangqin/envs/heyangqin/lib/python3.12/urllib/request.py", line 639, in http_error_default
          raise HTTPError(req.full_url, code, msg, hdrs, fp)
      urllib.error.HTTPError: HTTP Error 404: Not Found
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/mnt/heyangqin/envs/heyangqin/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/mnt/heyangqin/envs/heyangqin/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/mnt/heyangqin/envs/heyangqin/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ybw8xx6w/overlay/lib/python3.12/site-packages/wheel_stub/buildapi.py", line 29, in build_wheel
          return download_wheel(pathlib.Path(wheel_directory), config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ybw8xx6w/overlay/lib/python3.12/site-packages/wheel_stub/wheel.py", line 228, in download_wheel
          report_install_failure(distribution, version, config, exception_context)
        File "/tmp/pip-build-env-ybw8xx6w/overlay/lib/python3.12/site-packages/wheel_stub/error.py", line 67, in report_install_failure
          raise InstallFailedError(
      wheel_stub.error.InstallFailedError:
      *******************************************************************************
      
      The installation of tensorrt-llm for version 0.15.0 failed.
      
      This is a special placeholder package which downloads a real wheel package
      from https://pypi.nvidia.com/. If https://pypi.nvidia.com/ is not reachable, we
      cannot download the real wheel file to install.
      
      You might try installing this package via
      ```
      $ pip install --extra-index-url https://pypi.nvidia.com/ tensorrt-llm
      ```
      
      Here is some debug information about your platform to include in any bug
      report:
      
      Python Version: CPython 3.12.7
      Operating System: Linux 6.8.0-1017-azure
      CPU Architecture: x86_64
      Driver Version: 550.127
      CUDA Version: 12.4
      
      *******************************************************************************
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

I tried the `--extra-index-url https://pypi.nvidia.com/` and the error is same

**Comment by TriDefender** [comment]
Oh the good old place holder, had same issue when installing on windows, but resolved via:
`pip install tensorrt_llm==0.14.0 --extra-index-url https://download.pytorch.org/whl/`
They did upgrade the guidance database with ==0.15.0 but you are just gonna get a place holder


**Edit: On further investigation, the versions available are:** 
` (from versions: 0.5.0, 0.5.0.post1, 0.6.1, 0.7.0, 0.7.1, 0.8.0.dev20240116, 0.8.0.dev20240123, 0.8.0.dev2024011601, 0.8.0.dev2024012301, 0.8.0.dev2024012302, 0.8.0.dev2024013000, 0.8.0, 0.9.0.dev2024020600, 0.9.0.dev2024022000, 0.9.0.dev2024022700, 0.9.0.dev2024030500, 0.9.0.dev2024031200, 0.9.0.dev2024031900, 0.9.0.dev2024032600, 0.9.0.dev2024040200, 0.9.0.dev2024040900, 0.9.0, 0.10.0.dev2024041600, 0.10.0.dev2024042300, 0.10.0.dev2024043000, 0.10.0.dev2024050700, 0.10.0, 0.11.0.dev2024051400, 0.11.0.dev2024052100, 0.11.0.dev2024052800, 0.11.0.dev2024060400, 0.11.0.dev2024061100, 0.11.0.dev2024061800, 0.11.0.dev2024062500, 0.11.0, 0.12.0.dev2024070200, 0.12.0.dev2024070900, 0.12.0.dev2024071600, 0.12.0.dev2024072300, 0.12.0.dev2024072301, 0.12.0.dev2024072302, 0.12.0.dev2024073000, 0.12.0.dev2024080600, 0.12.0, 0.13.0.dev2024081300, 0.13.0.dev2024082000, 0.13.0.dev2024082700, 0.13.0.dev2024090300, 0.13.0, 0.14.0.dev2024091000, 0.14.0.dev2024091700, 0.14.0.dev2024092400, 0.14.0.dev2024092401, 0.14.0.dev2024100100, 0.14.0.dev2024100800, 0.14.0, 0.15.0.dev2024101500, 0.15.0.dev2024102200, 0.15.0.dev2024102900, 0.15.0.dev2024110500, 0.15.0.dev2024111200, 0.15.0, 0.16.0.dev2024111900, 0.16.0.dev2024112600, 0.16.0.dev2024120300)`

**Comment by HeyangQin** [comment]
@TriDefender That solves my issue. Thank you! I will leave this issue open so the trtllm team can fix the doc so it doesn't confuse more users haha

**Comment by TriDefender** [comment]
They also need fix the requirements.txt, the current one just uses
tensorrt-llm and you end up with a place holder

Heyang Qin ***@***.***> 于 2024年12月5日周四 20:42写道：

**Comment by nv-guomingz** [comment]
Feel free to reopen this ticket if needed.
