### ISSUE TITLE
Fail to build smoothquant model for llama 2 70B

### ISSUE THREAD

**Issue by yunfeng-scale** [NVIDIA/TensorRT-LLM#263]
Hi, I'm failing to build a llama 2 70B engine with latest main branch. Model is converted with:

```
python3 /code/tensorrt_llm/examples/llama/hf_llama_convert.py -i /model_weights/llama-2-70b/ -o /model_weights/llama-2-70b-sq/sq0.5/ -sq 0.5 --tensor-parallelism 2 --storage-type fp16
```
then built with
```
python /code/tensorrt_llm/examples/llama/build.py --ft_model_dir /model_weights/llama-2-70b-sq/sq0.5/2-gpu/                 --dtype float16                 --remove_input_padding                 --use_gpt_attention_plugin float16                 --enable_context_fmha                 --use_gemm_plugin float16                 --output_dir /model_weights/llama-2-70b-trt-llm-smoothquant                 --max_batch_size 50                 --max_input_len 4096                 --max_output_len 4096                                 --tokens_per_block 16                 --world_size 2                 --tp_size 2                 --use_smooth_quant
```

Error is model can't be loaded:
```
[11/03/2023-06:20:14] [TRT-LLM] [I] Loading weights from FT...
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/llama/build.py", line 728, in <module>
    build(0, args)
  File "/code/tensorrt_llm/examples/llama/build.py", line 699, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/code/tensorrt_llm/examples/llama/build.py", line 575, in build_rank_engine
    load_from_binary(tensorrt_llm_llama,
  File "/code/tensorrt_llm/examples/llama/weight.py", line 658, in load_from_binary
    tensorrt_llm_llama.layers[idx].input_layernorm.weight.value = (fromfile(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/parameter.py", line 79, in value
    assert isinstance(v, np.ndarray)
AssertionError
```

I think might be related to https://github.com/NVIDIA/TensorRT-LLM/issues/239 since I'm seeing exact error before moving to latest main.
Also I could successfully build a tp==1 7B model with smoothquant.

**Comment by yunfeng-scale** [comment]
For some reason using the given flags there are virtually no files in the built folder and that's why build.py complains it can't fetch layer's values

**Comment by yunfeng-scale** [comment]
i missed the error from hf_llama_convert.py
```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/code/tensorrt_llm/examples/llama/convert.py", line 290, in split_and_save_weight
    val = val.reshape(hidden_dim, 3, local_dim)
ValueError: cannot reshape array of size 83886080 into shape (8192,3,3413)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/llama/hf_llama_convert.py", line 342, in <module>
    hf_gpt_converter(args)
  File "/code/tensorrt_llm/examples/llama/hf_llama_convert.py", line 276, in hf_gpt_converter
    pool.starmap(split_and_save_weight, starmap_args)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
ValueError: cannot reshape array of size 83886080 into shape (8192,3,3413)
```

if adding `--multi-query-mode` to `hf_llama_convert.py` it does appear to outputs all weights and I could build an engine successfully, however running the model it outputs gibberish like
```
root@ip-10-202-98-80-release:/code/tensorrt_llm# mpirun -n 2 --allow-run-as-root python3 /code/tensorrt_llm/examples/llama/run.py --max_output_len=100                --tokenizer_dir /model_weights/llama-2-70b/                --engine_dir=/model_weights/llama-2-70b-trt-llm-smoothquant --input_text "San Francisco is a"
Running the float16 engine ...
Input: "San Francisco is a"
Output: "task=t 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 "
```

**Comment by Tracin** [comment]
Hi, please add `--per_token --per_channel` for `build.py` for smoothquant, otherwise it will quantize per-tensor and has bad accuracy. I can get right results after doing this.

**Comment by yunfeng-scale** [comment]
@Tracin thanks for the suggestion. model built with `--per_token --per_channel` does produce good results.
