### ISSUE TITLE
Multi-Modal on TRT-LLM on aarch64 (Holoscan IGX Devkit) fails to build the visual engine

### ISSUE THREAD

**Issue by MMelQin** [NVIDIA/TensorRT-LLM#2638]
### System Info

- CPU architecture aarch64
- CPU mem 64 GB
- GPU
  - GPU name RTX6000
  - GPU mem 48 GB
- Libraries
  - TensorRT-LLM main, pulled on 12/23/2024
  - Container built from source on host
- Nvidia driver version 535.171.04, CUDA version 12.6
- OS Ubuntu 22.04 (host)

### Who can help?

@byshiue
Built and launched the container on the host, per README and Quick Start Guide
Ran the example/llama successfully after having to modify the dtype to bfloat16 per output from `convert_checkpoint`
Tried to run the example/multimodal with VILA but ran into an issue with required dependencies
- pulled the model successfully
- ran `convert_checkpoint` per instruction but got complaint of missing dependencies of `deepspeed`, then `loguru`, and `hydra`
- `pip install hydra` failed

After some more digging, it was confirmed that transformers max version supported by TRT-LLM needs to be reinstalled because VILA 1.5 requirements pins transformers==4.36.2, lower then even the min req by TRT-LLM, and, hydra package name is hydra-core

```
pip install deepspeed loguru hydra-core transformers==4.45.1
``` 

Having the installs mentioned above before Step 2 succeeded in running the step. So, please update the README for this modification

But then error occurred on building the visual engine
```
root@ubuntu-NVIDIA-IGX-Orin-Development-Kit-release:/code/tensorrt_llm/examples/multimodal# python build_visual_engine.py --model_path tmp/hf_models/${MODEL_NAME} --model_type vila --vila_path ${VILA_PATH}
[TensorRT-LLM] TensorRT-LLM version: 0.17.0.dev2024121700
[2024-12-31 01:26:06,405] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/code/tensorrt_llm/examples/multimodal/tmp/hf_models/VILA/llava/model/qlinear_te.py:95: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @amp.custom_fwd(cast_inputs=torch.bfloat16)
/code/tensorrt_llm/examples/multimodal/tmp/hf_models/VILA/llava/model/qlinear_te.py:146: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @amp.custom_bwd
/code/tensorrt_llm/examples/multimodal/tmp/hf_models/VILA/llava/model/llava_arch.py:113: UserWarning: model_dtype not found in config, defaulting to torch.float16.
  warnings.warn("model_dtype not found in config, defaulting to torch.float16.")
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.74s/it]
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/multimodal/build_visual_engine.py", line 12, in <module>
    builder.build()
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/tools/multimodal_builder.py", line 116, in build
    build_vila_engine(args)
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/tools/multimodal_builder.py", line 529, in build_vila_engine
    model = AutoModel.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/tensorrt_llm/examples/multimodal/tmp/hf_models/VILA/llava/model/language_model/llava_llama.py", line 67, in from_pretrained
    return cls.load_pretrained(
           ^^^^^^^^^^^^^^^^^^^^
  File "/code/tensorrt_llm/examples/multimodal/tmp/hf_models/VILA/llava/model/llava_arch.py", line 132, in load_pretrained
    vlm = cls(config, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/tensorrt_llm/examples/multimodal/tmp/hf_models/VILA/llava/model/language_model/llava_llama.py", line 49, in __init__
    self.init_vlm(config=config, *args, **kwargs)
  File "/code/tensorrt_llm/examples/multimodal/tmp/hf_models/VILA/llava/model/llava_arch.py", line 74, in init_vlm
    self.llm, self.tokenizer = build_llm_and_tokenizer(llm_cfg, config, *args, **kwargs)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/tensorrt_llm/examples/multimodal/tmp/hf_models/VILA/llava/model/language_model/builder.py", line 203, in build_llm_and_tokenizer
    tokenizer.stop_tokens = infer_stop_tokens(tokenizer)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/tensorrt_llm/examples/multimodal/tmp/hf_models/VILA/llava/utils/tokenizer.py", line 176, in infer_stop_tokens
    template = tokenize_conversation(DUMMY_CONVERSATION, tokenizer, overrides={"gpt": SENTINEL_TOKEN})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/tensorrt_llm/examples/multimodal/tmp/hf_models/VILA/llava/utils/tokenizer.py", line 110, in tokenize_conversation
    text = tokenizer.apply_chat_template(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py", line 1809, in apply_chat_template
    chat_template = self.get_chat_template(chat_template, tools)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py", line 1970, in get_chat_template
    raise ValueError(
ValueError: Cannot use chat template functions because tokenizer.chat_template is not set and no template argument was passed! For information about writing templates and setting the tokenizer.chat_template attribute, please see the documentation at https://huggingface.co/docs/transformers/main/en/chat_templating
root@ubuntu-NVIDIA-IGX-Orin-Development-Kit-release:/code/tensorrt_llm/examples/multimodal#
```

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. On a host with aarch64, clone repo and build TensorRT-LLM container, which will take over 6.5 hrs.
2. Follow the [multimodal example for VILA](https://github.com/NVIDIA/TensorRT-LLM/blob/v0.12.0/examples/multimodal/README.md) 

### Expected behavior

Example should succeed, and it does for x86_64 as there is a MR to add TRT-LLM for VILA, though using TRT-LLM v0.12.

### actual behavior

Could not build the dependency hydra on the host with aarch64 after the source zip has been downloaded.

### additional notes

Understood the error is in the example/multimodal and specifically VILA, though ideally it should work with TRT-LLM.

**Comment by karljang** [comment]
Sorry we never replied to this one. Closing as stale since the TensorRT engine-build path is deprecated in favor of the PyTorch backend. Please open a new issue if the problem persists in the latest version.
