### ISSUE TITLE
Failed to build engine with lookahead_decoding

### ISSUE THREAD

**Issue by aikitoria** [NVIDIA/TensorRT-LLM#2641]
### System Info

- 8x 4090 on dual Epyc server running Debian testing
- CUDA toolkit version 12.6.3, driver version 565.77
- Release container compiled from main branch

### Who can help?

@byshiue 

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1) Download model https://huggingface.co/mistralai/Mistral-Large-Instruct-2411
2) Create checkpoint
` python convert_checkpoint.py --model_dir /raid/models/raw/Mistral-Large-Instruct-2411/ --tp_size 8 --dtype bfloat16 --use_fp8_rowwise --load_by_shard --output_dir /raid/models/checkpoint/Mistral-Large-Instruct-2411_fp8_rowwise/ --workers 8`
3) Attempt to use the arguments mentioned here: https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/lookahead
`trtllm-build --checkpoint_dir /raid/models/checkpoint/Mistral-Large-Instruct-2411_fp8_rowwise --max_batch_size 32 --gemm_plugin bfloat16 --fp8_rowwise_gemm_plugin bfloat16 --use_paged_context_fmha enable --max_draft_len 83 --speculative_decoding_mode lookahead_decoding --output_dir /raid/models/engine/Mistral-Large-Instruct-2411_fp8_rowwise_gemm_b32_l83`

### Expected behavior

It compiles the engine successfully, like it does when `--max_draft_len 83 --speculative_decoding_mode lookahead_decoding` arguments are not included

### actual behavior

It fails to compile the engine

```
[TensorRT-LLM] TensorRT-LLM version: 0.17.0.dev2024121700
[12/31/2024-21:25:45] [TRT-LLM] [I] Set bert_attention_plugin to auto.
[12/31/2024-21:25:45] [TRT-LLM] [I] Set gpt_attention_plugin to auto.
[12/31/2024-21:25:45] [TRT-LLM] [I] Set gemm_plugin to bfloat16.
[12/31/2024-21:25:45] [TRT-LLM] [I] Set gemm_swiglu_plugin to None.
[12/31/2024-21:25:45] [TRT-LLM] [I] Set fp8_rowwise_gemm_plugin to bfloat16.
[12/31/2024-21:25:45] [TRT-LLM] [I] Set nccl_plugin to auto.
[12/31/2024-21:25:45] [TRT-LLM] [I] Set lora_plugin to None.
[12/31/2024-21:25:45] [TRT-LLM] [I] Set moe_plugin to auto.
[12/31/2024-21:25:45] [TRT-LLM] [I] Set mamba_conv1d_plugin to auto.
[12/31/2024-21:25:45] [TRT-LLM] [I] Set low_latency_gemm_plugin to None.
[12/31/2024-21:25:45] [TRT-LLM] [I] Set low_latency_gemm_swiglu_plugin to None.
[12/31/2024-21:25:45] [TRT-LLM] [I] Set context_fmha to True.
[12/31/2024-21:25:45] [TRT-LLM] [I] Set bert_context_fmha_fp32_acc to False.
[12/31/2024-21:25:45] [TRT-LLM] [I] Set remove_input_padding to True.
[12/31/2024-21:25:45] [TRT-LLM] [I] Set reduce_fusion to False.
[12/31/2024-21:25:45] [TRT-LLM] [I] Set user_buffer to False.
[12/31/2024-21:25:45] [TRT-LLM] [I] Set tokens_per_block to 64.
[12/31/2024-21:25:45] [TRT-LLM] [I] Set use_paged_context_fmha to True.
[12/31/2024-21:25:45] [TRT-LLM] [I] Set use_fp8_context_fmha to False.
[12/31/2024-21:25:45] [TRT-LLM] [I] Set multiple_profiles to False.
[12/31/2024-21:25:45] [TRT-LLM] [I] Set paged_state to True.
[12/31/2024-21:25:45] [TRT-LLM] [I] Set streamingllm to False.
[12/31/2024-21:25:45] [TRT-LLM] [I] Set use_fused_mlp to True.
[12/31/2024-21:25:45] [TRT-LLM] [I] Set pp_reduce_scatter to False.
[12/31/2024-21:25:45] [TRT-LLM] [W] Implicitly setting LLaMAConfig.fc_after_embed = False
[12/31/2024-21:25:45] [TRT-LLM] [W] Implicitly setting LLaMAConfig.use_input_layernorm_in_first_layer = True
[12/31/2024-21:25:45] [TRT-LLM] [W] Implicitly setting LLaMAConfig.use_last_layernorm = True
[12/31/2024-21:25:45] [TRT-LLM] [W] Implicitly setting LLaMAConfig.layer_idx_offset = 0
[12/31/2024-21:25:45] [TRT-LLM] [W] Implicitly setting LLaMAConfig.tie_word_embeddings = False
[12/31/2024-21:25:45] [TRT-LLM] [I] Compute capability: (8, 9)
[12/31/2024-21:25:45] [TRT-LLM] [I] SM count: 128
[12/31/2024-21:25:45] [TRT-LLM] [I] SM clock: 3135 MHz
[12/31/2024-21:25:45] [TRT-LLM] [I] int4 TFLOPS: 821
[12/31/2024-21:25:45] [TRT-LLM] [I] int8 TFLOPS: 410
[12/31/2024-21:25:45] [TRT-LLM] [I] fp8 TFLOPS: 410
[12/31/2024-21:25:45] [TRT-LLM] [I] float16 TFLOPS: 205
[12/31/2024-21:25:45] [TRT-LLM] [I] bfloat16 TFLOPS: 205
[12/31/2024-21:25:45] [TRT-LLM] [I] float32 TFLOPS: 102
[12/31/2024-21:25:45] [TRT-LLM] [I] Total Memory: 23 GiB
[12/31/2024-21:25:45] [TRT-LLM] [I] Memory clock: 10501 MHz
[12/31/2024-21:25:45] [TRT-LLM] [I] Memory bus width: 384
[12/31/2024-21:25:45] [TRT-LLM] [I] Memory bandwidth: 1008 GB/s
[12/31/2024-21:25:45] [TRT-LLM] [I] PCIe speed: 2500 Mbps
[12/31/2024-21:25:45] [TRT-LLM] [I] PCIe link width: 16
[12/31/2024-21:25:45] [TRT-LLM] [I] PCIe bandwidth: 5 GB/s
[12/31/2024-21:25:45] [TRT-LLM] [W] Provided but not required tensors: {'transformer.layers.79.mlp.clamp_val', 'transformer.layers.37.post_layernorm.clamp_val', 'transformer.layers.32.input_layernorm.clamp_val', 'transformer.layers.79.attention.clamp_val', 'transformer.layers.67.post_layernorm.clamp_val', 'transformer.layers.70.input_layernorm.clamp_val', 'transformer.layers.12.attention.clamp_val', 'transformer.layers.55.input_layernorm.clamp_val', 'transformer.layers.52.mlp.clamp_val', 'transformer.layers.73.attention.clamp_val', 'transformer.layers.41.attention.clamp_val', 'transformer.layers.66.input_layernorm.clamp_val', 'transformer.layers.80.mlp.clamp_val', 'transformer.layers.35.post_layernorm.clamp_val', 'transformer.layers.52.post_layernorm.clamp_val', 'transformer.layers.29.attention.clamp_val', 'transformer.layers.6.input_layernorm.clamp_val', 'transformer.layers.85.post_layernorm.clamp_val', 'transformer.layers.20.post_layernorm.clamp_val', 'transformer.layers.4.attention.clamp_val', 'transformer.layers.44.input_layernorm.clamp_val', 'transformer.layers.33.mlp.clamp_val', 'transformer.layers.42.input_layernorm.clamp_val', 'transformer.layers.14.input_layernorm.clamp_val', 'transformer.layers.56.input_layernorm.clamp_val', 'transformer.layers.40.attention.clamp_val', 'transformer.layers.25.post_layernorm.clamp_val', 'transformer.layers.24.post_layernorm.clamp_val', 'transformer.layers.30.attention.clamp_val', 'transformer.layers.64.attention.clamp_val', 'transformer.layers.3.mlp.clamp_val', 'transformer.layers.69.attention.clamp_val', 'transformer.layers.71.input_layernorm.clamp_val', 'transformer.layers.82.attention.clamp_val', 'transformer.layers.39.mlp.clamp_val', 'transformer.layers.9.mlp.clamp_val', 'transformer.layers.5.attention.clamp_val', 'transformer.layers.23.input_layernorm.clamp_val', 'transformer.layers.16.post_layernorm.clamp_val', 'transformer.layers.67.input_layernorm.clamp_val', 'transformer.layers.74.post_layernorm.clamp_val', 'transformer.layers.43.attention.clamp_val', 'transformer.layers.6.mlp.clamp_val', 'transformer.layers.40.post_layernorm.clamp_val', 'transformer.layers.11.mlp.clamp_val', 'transformer.layers.19.input_layernorm.clamp_val', 'transformer.layers.73.input_layernorm.clamp_val', 'transformer.layers.29.post_layernorm.clamp_val', 'transformer.layers.32.post_layernorm.clamp_val', 'transformer.layers.83.attention.clamp_val', 'transformer.layers.48.input_layernorm.clamp_val', 'transformer.layers.65.mlp.clamp_val', 'transformer.layers.2.input_layernorm.clamp_val', 'transformer.layers.87.input_layernorm.clamp_val', 'transformer.layers.46.mlp.clamp_val', 'transformer.layers.74.input_layernorm.clamp_val', 'transformer.layers.59.post_layernorm.clamp_val', 'transformer.layers.63.input_layernorm.clamp_val', 'transformer.layers.1.post_layernorm.clamp_val', 'transformer.layers.78.post_layernorm.clamp_val', 'transformer.layers.34.input_layernorm.clamp_val', 'transformer.layers.60.mlp.clamp_val', 'transformer.layers.4.post_layernorm.clamp_val', 'transformer.layers.58.post_layernorm.clamp_val', 'transformer.layers.50.mlp.clamp_val', 'transformer.layers.77.post_layernorm.clamp_val', 'transformer.layers.49.mlp.clamp_val', 'transformer.layers.66.attention.clamp_val', 'transformer.layers.35.mlp.clamp_val', 'transformer.layers.33.attention.clamp_val', 'transformer.layers.52.input_layernorm.clamp_val', 'transformer.layers.81.post_layernorm.clamp_val', 'transformer.layers.7.mlp.clamp_val', 'transformer.layers.85.attention.clamp_val', 'transformer.layers.69.post_layernorm.clamp_val', 'transformer.layers.76.post_layernorm.clamp_val', 'transformer.layers.36.attention.clamp_val', 'transformer.layers.47.post_layernorm.clamp_val', 'transformer.layers.54.post_layernorm.clamp_val', 'transformer.layers.36.input_layernorm.clamp_val', 'transformer.layers.56.post_layernorm.clamp_val', 'transformer.layers.43.mlp.clamp_val', 'transformer.layers.72.input_layernorm.clamp_val', 'transformer.layers.82.post_layernorm.clamp_val', 'transformer.layers.25.input_layernorm.clamp_val', 'transformer.layers.24.input_layernorm.clamp_val', 'transformer.layers.46.post_layernorm.clamp_val', 'transformer.layers.39.attention.clamp_val', 'transformer.layers.2.mlp.clamp_val', 'transformer.layers.74.attention.clamp_val', 'transformer.layers.18.attention.clamp_val', 'transformer.layers.83.input_layernorm.clamp_val', 'transformer.layers.38.post_layernorm.clamp_val', 'transformer.layers.78.attention.clamp_val', 'transformer.layers.5.input_layernorm.clamp_val', 'transformer.layers.78.input_layernorm.clamp_val', 'transformer.layers.37.mlp.clamp_val', 'transformer.layers.8.post_layernorm.clamp_val', 'transformer.layers.1.mlp.clamp_val', 'transformer.layers.83.post_layernorm.clamp_val', 'transformer.layers.53.mlp.clamp_val', 'transformer.layers.34.attention.clamp_val', 'transformer.layers.85.input_layernorm.clamp_val', 'transformer.layers.18.post_layernorm.clamp_val', 'transformer.layers.18.mlp.clamp_val', 'transformer.layers.35.attention.clamp_val', 'transformer.layers.65.post_layernorm.clamp_val', 'transformer.layers.36.post_layernorm.clamp_val', 'transformer.layers.37.attention.clamp_val', 'transformer.layers.84.post_layernorm.clamp_val', 'transformer.layers.53.input_layernorm.clamp_val', 'transformer.layers.36.mlp.clamp_val', 'transformer.layers.73.post_layernorm.clamp_val', 'transformer.layers.3.input_layernorm.clamp_val', 'transformer.layers.20.mlp.clamp_val', 'transformer.layers.26.input_layernorm.clamp_val', 'transformer.layers.72.post_layernorm.clamp_val', 'transformer.layers.22.post_layernorm.clamp_val', 'transformer.layers.23.mlp.clamp_val', 'transformer.layers.61.mlp.clamp_val', 'transformer.layers.51.input_layernorm.clamp_val', 'transformer.layers.14.post_layernorm.clamp_val', 'transformer.layers.21.attention.clamp_val', 'transformer.layers.32.attention.clamp_val', 'transformer.layers.66.post_layernorm.clamp_val', 'transformer.layers.25.mlp.clamp_val', 'transformer.layers.62.input_layernorm.clamp_val', 'transformer.layers.30.post_layernorm.clamp_val', 'transformer.layers.38.mlp.clamp_val', 'transformer.layers.21.mlp.clamp_val', 'transformer.layers.46.input_layernorm.clamp_val', 'transformer.layers.33.post_layernorm.clamp_val', 'transformer.layers.51.mlp.clamp_val', 'transformer.layers.73.mlp.clamp_val', 'transformer.layers.50.post_layernorm.clamp_val', 'transformer.layers.65.input_layernorm.clamp_val', 'transformer.layers.5.mlp.clamp_val', 'transformer.layers.16.mlp.clamp_val', 'transformer.layers.28.mlp.clamp_val', 'transformer.layers.3.post_layernorm.clamp_val', 'transformer.layers.71.post_layernorm.clamp_val', 'transformer.layers.19.post_layernorm.clamp_val', 'transformer.layers.45.post_layernorm.clamp_val', 'transformer.layers.23.attention.clamp_val', 'transformer.layers.47.mlp.clamp_val', 'transformer.layers.44.post_layernorm.clamp_val', 'transformer.layers.32.mlp.clamp_val', 'transformer.layers.75.input_layernorm.clamp_val', 'transformer.layers.0.mlp.clamp_val', 'transformer.layers.39.input_layernorm.clamp_val', 'transformer.layers.21.input_layernorm.clamp_val', 'transformer.layers.8.attention.clamp_val', 'transformer.layers.62.attention.clamp_val', 'transformer.layers.76.attention.clamp_val', 'transformer.layers.76.mlp.clamp_val', 'transformer.layers.80.attention.clamp_val', 'transformer.layers.20.attention.clamp_val', 'transformer.layers.49.input_layernorm.clamp_val', 'transformer.layers.15.post_layernorm.clamp_val', 'transformer.layers.22.attention.clamp_val', 'transformer.layers.43.input_layernorm.clamp_val', 'transformer.layers.27.post_layernorm.clamp_val', 'transformer.layers.24.attention.clamp_val', 'transformer.layers.40.input_layernorm.clamp_val', 'transformer.layers.40.mlp.clamp_val', 'transformer.layers.12.post_layernorm.clamp_val', 'transformer.layers.9.post_layernorm.clamp_val', 'embed_positions_for_gpt_attention', 'transformer.layers.82.mlp.clamp_val', 'transformer.layers.18.input_layernorm.clamp_val', 'transformer.layers.16.attention.clamp_val', 'transformer.layers.55.attention.clamp_val', 'transformer.layers.62.post_layernorm.clamp_val', 'transformer.layers.75.mlp.clamp_val', 'transformer.layers.68.post_layernorm.clamp_val', 'transformer.layers.30.mlp.clamp_val', 'transformer.layers.8.mlp.clamp_val', 'transformer.layers.69.mlp.clamp_val', 'transformer.layers.13.post_layernorm.clamp_val', 'transformer.layers.10.input_layernorm.clamp_val', 'transformer.layers.62.mlp.clamp_val', 'transformer.layers.82.input_layernorm.clamp_val', 'transformer.layers.61.input_layernorm.clamp_val', 'transformer.layers.83.mlp.clamp_val', 'transformer.layers.29.mlp.clamp_val', 'transformer.layers.85.mlp.clamp_val', 'transformer.layers.59.attention.clamp_val', 'transformer.layers.55.post_layernorm.clamp_val', 'transformer.layers.77.mlp.clamp_val', 'transformer.layers.6.attention.clamp_val', 'transformer.layers.38.input_layernorm.clamp_val', 'transformer.layers.41.input_layernorm.clamp_val', 'transformer.layers.9.attention.clamp_val', 'transformer.layers.87.mlp.clamp_val', 'transformer.layers.7.attention.clamp_val', 'transformer.layers.42.attention.clamp_val', 'transformer.layers.35.input_layernorm.clamp_val', 'transformer.layers.44.attention.clamp_val', 'transformer.layers.71.attention.clamp_val', 'transformer.layers.58.mlp.clamp_val', 'transformer.layers.58.attention.clamp_val', 'transformer.layers.27.attention.clamp_val', 'transformer.layers.50.attention.clamp_val', 'transformer.layers.31.attention.clamp_val', 'transformer.layers.57.post_layernorm.clamp_val', 'transformer.layers.17.input_layernorm.clamp_val', 'transformer.layers.55.mlp.clamp_val', 'transformer.layers.7.input_layernorm.clamp_val', 'transformer.layers.17.mlp.clamp_val', 'transformer.layers.58.input_layernorm.clamp_val', 'transformer.layers.50.input_layernorm.clamp_val', 'transformer.layers.79.post_layernorm.clamp_val', 'transformer.layers.45.mlp.clamp_val', 'transformer.layers.57.input_layernorm.clamp_val', 'transformer.layers.72.mlp.clamp_val', 'transformer.layers.27.input_layernorm.clamp_val', 'transformer.layers.86.mlp.clamp_val', 'transformer.layers.42.mlp.clamp_val', 'transformer.layers.23.post_layernorm.clamp_val', 'transformer.layers.67.mlp.clamp_val', 'transformer.layers.56.mlp.clamp_val', 'transformer.layers.15.attention.clamp_val', 'transformer.layers.53.post_layernorm.clamp_val', 'transformer.layers.52.attention.clamp_val', 'transformer.layers.51.post_layernorm.clamp_val', 'transformer.layers.49.post_layernorm.clamp_val', 'transformer.layers.47.input_layernorm.clamp_val', 'transformer.layers.12.input_layernorm.clamp_val', 'transformer.layers.11.post_layernorm.clamp_val', 'transformer.layers.59.input_layernorm.clamp_val', 'transformer.layers.21.post_layernorm.clamp_val', 'transformer.layers.33.input_layernorm.clamp_val', 'transformer.layers.42.post_layernorm.clamp_val', 'transformer.layers.65.attention.clamp_val', 'transformer.layers.26.mlp.clamp_val', 'transformer.layers.86.attention.clamp_val', 'transformer.layers.4.input_layernorm.clamp_val', 'transformer.layers.79.input_layernorm.clamp_val', 'transformer.layers.46.attention.clamp_val', 'transformer.layers.30.input_layernorm.clamp_val', 'transformer.layers.59.mlp.clamp_val', 'transformer.layers.28.attention.clamp_val', 'transformer.layers.41.mlp.clamp_val', 'transformer.layers.57.attention.clamp_val', 'transformer.layers.14.attention.clamp_val', 'transformer.layers.6.post_layernorm.clamp_val', 'transformer.layers.56.attention.clamp_val', 'transformer.layers.84.input_layernorm.clamp_val', 'transformer.layers.70.post_layernorm.clamp_val', 'transformer.layers.20.input_layernorm.clamp_val', 'transformer.layers.84.mlp.clamp_val', 'transformer.layers.49.attention.clamp_val', 'transformer.layers.72.attention.clamp_val', 'transformer.layers.70.attention.clamp_val', 'transformer.layers.8.input_layernorm.clamp_val', 'transformer.layers.16.input_layernorm.clamp_val', 'transformer.layers.17.post_layernorm.clamp_val', 'transformer.layers.51.attention.clamp_val', 'transformer.layers.54.mlp.clamp_val', 'transformer.layers.61.attention.clamp_val', 'transformer.layers.22.mlp.clamp_val', 'transformer.layers.19.attention.clamp_val', 'transformer.layers.24.mlp.clamp_val', 'transformer.layers.39.post_layernorm.clamp_val', 'transformer.layers.28.post_layernorm.clamp_val', 'transformer.layers.81.attention.clamp_val', 'transformer.layers.69.input_layernorm.clamp_val', 'transformer.layers.25.attention.clamp_val', 'transformer.layers.71.mlp.clamp_val', 'transformer.layers.75.post_layernorm.clamp_val', 'transformer.layers.53.attention.clamp_val', 'transformer.layers.80.post_layernorm.clamp_val', 'transformer.layers.78.mlp.clamp_val', 'transformer.layers.81.input_layernorm.clamp_val', 'transformer.layers.77.input_layernorm.clamp_val', 'transformer.layers.26.attention.clamp_val', 'transformer.layers.67.attention.clamp_val', 'transformer.layers.10.post_layernorm.clamp_val', 'transformer.layers.41.post_layernorm.clamp_val', 'transformer.layers.34.post_layernorm.clamp_val', 'transformer.layers.81.mlp.clamp_val', 'transformer.layers.45.attention.clamp_val', 'transformer.layers.0.input_layernorm.clamp_val', 'transformer.layers.44.mlp.clamp_val', 'transformer.layers.31.mlp.clamp_val', 'transformer.layers.2.post_layernorm.clamp_val', 'transformer.layers.13.input_layernorm.clamp_val', 'transformer.layers.9.input_layernorm.clamp_val', 'transformer.layers.28.input_layernorm.clamp_val', 'transformer.layers.54.input_layernorm.clamp_val', 'transformer.layers.76.input_layernorm.clamp_val', 'transformer.layers.84.attention.clamp_val', 'transformer.layers.64.post_layernorm.clamp_val', 'transformer.layers.1.attention.clamp_val', 'transformer.layers.31.input_layernorm.clamp_val', 'transformer.layers.0.attention.clamp_val', 'transformer.layers.19.mlp.clamp_val', 'transformer.layers.38.attention.clamp_val', 'transformer.layers.13.mlp.clamp_val', 'transformer.layers.80.input_layernorm.clamp_val', 'transformer.layers.47.attention.clamp_val', 'transformer.layers.1.input_layernorm.clamp_val', 'transformer.layers.75.attention.clamp_val', 'transformer.layers.87.post_layernorm.clamp_val', 'embed_positions', 'transformer.layers.48.mlp.clamp_val', 'transformer.layers.27.mlp.clamp_val', 'transformer.layers.61.post_layernorm.clamp_val', 'transformer.layers.37.input_layernorm.clamp_val', 'transformer.layers.13.attention.clamp_val', 'transformer.layers.15.mlp.clamp_val', 'transformer.layers.26.post_layernorm.clamp_val', 'transformer.layers.17.attention.clamp_val', 'transformer.layers.68.mlp.clamp_val', 'transformer.layers.5.post_layernorm.clamp_val', 'transformer.layers.68.attention.clamp_val', 'transformer.layers.63.mlp.clamp_val', 'transformer.layers.22.input_layernorm.clamp_val', 'transformer.layers.63.post_layernorm.clamp_val', 'transformer.layers.15.input_layernorm.clamp_val', 'transformer.layers.12.mlp.clamp_val', 'transformer.layers.74.mlp.clamp_val', 'transformer.layers.64.input_layernorm.clamp_val', 'transformer.layers.86.post_layernorm.clamp_val', 'transformer.layers.63.attention.clamp_val', 'transformer.layers.48.post_layernorm.clamp_val', 'transformer.layers.2.attention.clamp_val', 'transformer.layers.86.input_layernorm.clamp_val', 'transformer.layers.11.input_layernorm.clamp_val', 'transformer.layers.34.mlp.clamp_val', 'transformer.layers.60.attention.clamp_val', 'transformer.layers.68.input_layernorm.clamp_val', 'transformer.layers.70.mlp.clamp_val', 'transformer.layers.29.input_layernorm.clamp_val', 'rotary_inv_freq', 'transformer.layers.7.post_layernorm.clamp_val', 'transformer.layers.60.input_layernorm.clamp_val', 'transformer.layers.57.mlp.clamp_val', 'transformer.layers.14.mlp.clamp_val', 'transformer.layers.10.mlp.clamp_val', 'transformer.layers.64.mlp.clamp_val', 'transformer.layers.48.attention.clamp_val', 'transformer.layers.77.attention.clamp_val', 'transformer.layers.60.post_layernorm.clamp_val', 'transformer.layers.87.attention.clamp_val', 'transformer.layers.45.input_layernorm.clamp_val', 'transformer.layers.4.mlp.clamp_val', 'transformer.layers.0.post_layernorm.clamp_val', 'transformer.layers.54.attention.clamp_val', 'transformer.layers.43.post_layernorm.clamp_val', 'transformer.layers.11.attention.clamp_val', 'transformer.layers.3.attention.clamp_val', 'transformer.layers.31.post_layernorm.clamp_val', 'transformer.layers.66.mlp.clamp_val', 'transformer.layers.10.attention.clamp_val'}
[12/31/2024-21:25:45] [TRT-LLM] [I] Set dtype to bfloat16.
[12/31/2024-21:25:45] [TRT-LLM] [I] Set paged_kv_cache to True.
[12/31/2024-21:25:45] [TRT-LLM] [W] Overriding paged_state to False
[12/31/2024-21:25:45] [TRT-LLM] [I] Set paged_state to False.
[12/31/2024-21:25:45] [TRT-LLM] [I] max_seq_len is not specified, using deduced value 131072
[12/31/2024-21:25:45] [TRT-LLM] [W] remove_input_padding is enabled, while opt_num_tokens is not set, setting to max_batch_size*max_beam_width.

[12/31/2024-21:25:45] [TRT-LLM] [W] padding removal and fMHA are both enabled, max_input_len is not required and will be ignored
[12/31/2024-21:25:45] [TRT-LLM] [I] Increasing max_seq_len (131072) by max_draft_len (83) to account for speculative decoding implementation specifics. Maximum number of generated tokens remains the same. New max_seq_len is set to 131155
[12/31/2024-21:25:47] [TRT] [I] [MemUsageChange] Init CUDA: CPU -14, GPU +0, now: CPU 7588, GPU 392 (MiB)
[12/31/2024-21:25:49] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +2283, GPU +440, now: CPU 10017, GPU 832 (MiB)
[12/31/2024-21:25:49] [TRT-LLM] [I] Set fp8_rowwise_gemm_plugin to bfloat16.
[12/31/2024-21:25:49] [TRT-LLM] [I] Set rmsnorm_quantization_plugin to bfloat16.
[12/31/2024-21:25:49] [TRT-LLM] [I] Set quantize_per_token_plugin to True.
[12/31/2024-21:25:49] [TRT-LLM] [I] Set quantize_tensor_plugin to True.
[12/31/2024-21:25:49] [TRT-LLM] [I] Set nccl_plugin to bfloat16.
Traceback (most recent call last):
  File "/usr/local/bin/trtllm-build", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/commands/build.py", line 627, in main
    parallel_build(model_config, ckpt_dir, build_config, args.output_dir,
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/commands/build.py", line 425, in parallel_build
    passed = build_and_save(rank, rank % workers, ckpt_dir,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/commands/build.py", line 390, in build_and_save
    engine = build_model(build_config,
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/commands/build.py", line 383, in build_model
    return build(model, build_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/builder.py", line 1240, in build
    model(**inputs)
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/module.py", line 52, in __call__
    output = self.forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/models/modeling_utils.py", line 988, in forward
    hidden_states = self.transformer.forward(**kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/models/llama/model.py", line 311, in forward
    hidden_states = self.layers.forward(
                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/models/modeling_utils.py", line 543, in forward
    hidden_states = layer(
                    ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/module.py", line 52, in __call__
    output = self.forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/models/llama/model.py", line 163, in forward
    attention_output = self.attention(
                       ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/module.py", line 52, in __call__
    output = self.forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/quantization/layers.py", line 1992, in forward
    context, past_key_value = gpt_attention(
                              ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/graph_rewriting.py", line 562, in wrapper
    outs = f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/functional.py", line 5443, in gpt_attention
    assert spec_decoding_use is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

### additional notes

Maybe it doesn't work with fp8_rowwise?

**Comment by karljang** [comment]
Sorry we never replied to this one. Closing as stale since the TensorRT engine-build path is deprecated in favor of the PyTorch backend. Please open a new issue if the problem persists in the latest version.
