### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by yuqie** [NVIDIA/TensorRT-LLM#290]
Hi, I failed to build TensorRT-LLM, when I run the following option：
```
python3 ./scripts/build_wheel.py --clean  --trt_root /usr/local/tensorrt
```
with the error as following:
```
[ 96%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/unfusedAttentionKernels_2.cu.o
[ 97%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/weightOnlyBatchedGemv/weightOnlyBatchedGemvBs2Int4b.cu.o
[ 97%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/weightOnlyBatchedGemv/weightOnlyBatchedGemvBs2Int8b.cu.o
[ 98%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/weightOnlyBatchedGemv/weightOnlyBatchedGemvBs4Int8b.cu.o
[ 98%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/weightOnlyBatchedGemv/weightOnlyBatchedGemvBs4Int4b.cu.o
In file included from /app/tensorrt_llm/cpp/tensorrt_llm/runtime/runtimeBuffers.cpp:26:
/app/tensorrt_llm/cpp/include/tensorrt_llm/batch_manager/kvCacheManager.h: In member function ‘bool tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::schedulingHasFreeBlocks(std::size_t) const’:
/app/tensorrt_llm/cpp/include/tensorrt_llm/batch_manager/kvCacheManager.h:183:41: warning: comparison of integer expressions of different signedness: ‘const SizeType’ {aka ‘const int’} and ‘std::size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
  183 |         return mSchedulingNumFreeBlocks >= numRequired;
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
In file included from /app/tensorrt_llm/cpp/tensorrt_llm/runtime/gptSession.cpp:23:
/app/tensorrt_llm/cpp/include/tensorrt_llm/batch_manager/kvCacheManager.h: In member function ‘bool tensorrt_llm::batch_manager::kv_cache_manager::BlockManager::schedulingHasFreeBlocks(std::size_t) const’:
/app/tensorrt_llm/cpp/include/tensorrt_llm/batch_manager/kvCacheManager.h:183:41: warning: comparison of integer expressions of different signedness: ‘const SizeType’ {aka ‘const int’} and ‘std::size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
  183 |         return mSchedulingNumFreeBlocks >= numRequired;
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
[ 98%] Built target layers_src
[ 98%] Built target common_src
[ 98%] Built target runtime_src
^[[ 98%] Built target kernels_src
[ 98%] Linking CXX static library libtensorrt_llm_static.a
[ 98%] Built target tensorrt_llm_static
[100%] Linking CXX shared library libtensorrt_llm.so
/usr/bin/ld:/app/tensorrt_llm/cpp/tensorrt_llm/batch_manager/x86_64-linux-gnu/libtensorrt_llm_batch_manager_static.a: file format not recognized; treating as linker script
/usr/bin/ld:/app/tensorrt_llm/cpp/tensorrt_llm/batch_manager/x86_64-linux-gnu/libtensorrt_llm_batch_manager_static.a:1: syntax error
collect2: error: ld returned 1 exit status
gmake[3]: *** [tensorrt_llm/CMakeFiles/tensorrt_llm.dir/build.make:714: tensorrt_llm/libtensorrt_llm.so] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:677: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:684: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/rule] Error 2
gmake: *** [Makefile:179: tensorrt_llm] Error 2
Traceback (most recent call last):
  File "/app/tensorrt_llm/scripts/build_wheel.py", line 249, in <module>
    main(**vars(args))
  File "/app/tensorrt_llm/scripts/build_wheel.py", line 153, in main
    build_run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cmake --build . --config Release --parallel 192 --target tensorrt_llm tensorrt_llm_static nvinfer_plugin_tensorrt_llm th_common ' returned non-zero exit status 2.
```

RTX4090 is used and following is the basic environment I used:
```
OS：Ubuntu 22.04.2 LTS
Python 3.10.12
gcc version 9.4.0 
cmake version 3.27.1
cudnn 8.9.4
TensorRT version：9.1.0.4
CUDA version Inside the container is CUDA 12.2.
Driver Version: 535.113.01
```
I am not familiar with cmake and could anyone help me with this error? any suggestion would be appreciated.

**Comment by byshiue** [comment]
Duplicated issue discussed in https://github.com/NVIDIA/TensorRT-LLM/issues/28.

**Comment by yuqie** [comment]
> Duplicated issue discussed in #28.

Thanks!
