### ISSUE TITLE
Import Error: from tensorrt_llm.builder import Builder

### ISSUE THREAD

**Issue by tiandiao123** [NVIDIA/TensorRT-LLM#307]
someone knows what caused this error? 
```
>>> from tensorrt_llm.builder import Builder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lclcq/share/miniconda3/lib/python3.11/site-packages/tensorrt_llm/__init__.py", line 15, in <module>
    import tensorrt_llm.functional as functional
  File "/home/lclcq/share/miniconda3/lib/python3.11/site-packages/tensorrt_llm/functional.py", line 25, in <module>
    from . import graph_rewriting as gw
  File "/home/lclcq/share/miniconda3/lib/python3.11/site-packages/tensorrt_llm/graph_rewriting.py", line 11, in <module>
    from .network import Network
  File "/home/lclcq/share/miniconda3/lib/python3.11/site-packages/tensorrt_llm/network.py", line 26, in <module>
    from ._common import set_network
  File "/home/lclcq/share/miniconda3/lib/python3.11/site-packages/tensorrt_llm/_common.py", line 21, in <module>
    from ._utils import str_dtype_to_trt
  File "/home/lclcq/share/miniconda3/lib/python3.11/site-packages/tensorrt_llm/_utils.py", line 81, in <module>
    int64=trt.int64,
          ^^^^^^^^^
AttributeError: module 'tensorrt' has no attribute 'int64'. Did you mean: 'int32'?
```

**Comment by byshiue** [comment]
Can you check your tensorrt version? It looks you don't use tensorrt 9.0 because tensorrt supports int64 since 9.0.

**Comment by tiandiao123** [comment]
> Can you check your tensorrt version? It looks you don't use tensorrt 9.0 because tensorrt supports int64 since 9.0.

Thanks!

**Comment by natureLanguageQing** [comment]
'tensorrt' has no attribute 'int64'. Did you mean: 'int32'
I have same problem

**Comment by byshiue** [comment]
See this https://github.com/NVIDIA/TensorRT-LLM/blob/v0.6.1/docker/common/install_tensorrt.sh#L66 to install 9.2 TRT
