### ISSUE TITLE
Does TensorRT-LLM support Baichuan2-7B-Chat-4bits？

### ISSUE THREAD

**Issue by smallmocha** [NVIDIA/TensorRT-LLM#311]
when i build Baichuan2-7B-Chat-4bits model，i got error

[11/08/2023-03:35:36] [TRT-LLM] [I] Serially build TensorRT engines.
[11/08/2023-03:35:37] [TRT] [I] [MemUsageChange] Init CUDA: CPU +13, GPU +0, now: CPU 115, GPU 105 (MiB)
[11/08/2023-03:35:38] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +978, GPU +180, now: CPU 1229, GPU 285 (MiB)
[11/08/2023-03:35:38] [TRT-LLM] [W] Invalid timing cache, using freshly created one
[11/08/2023-03:35:48] [TRT-LLM] [I] Loading HF Baichuan v2_7b ... from /data0/Baichuan2-7B-Chat-4bits
[11/08/2023-03:35:57] The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
[11/08/2023-03:35:58] [TRT-LLM] [I] HF Baichuan v2_7b loaded. Total time: 00:00:10
[11/08/2023-03:35:58] [TRT-LLM] [I] Loading weights from HF Baichuan v2_7b...
Traceback (most recent call last):
  File "/root/work/TensorRT-LLM/examples/baichuan/build.py", line 477, in <module>
    build(0, args)
  File "/root/work/TensorRT-LLM/examples/baichuan/build.py", line 447, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/root/work/TensorRT-LLM/examples/baichuan/build.py", line 347, in build_rank_engine
    load_from_hf_baichuan(tensorrt_llm_baichuan,
  File "/root/work/TensorRT-LLM/examples/baichuan/weight.py", line 111, in load_from_hf_baichuan
    dst.value = np.ascontiguousarray(split_v)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/parameter.py", line 66, in value
    assert v.shape == self._value.shape, \
AssertionError: ('The value updated is not the same shape as the original. ', 'Updated: (25165824, 1), original: (12288, 4096)')

python build.py --model_version v2_7b \
                          --model_dir /data0/Baichuan2-7B-Chat-4bits \
                          --dtype float16 \
                          --use_gemm_plugin float16 \
                          --use_gpt_attention_plugin float16 \
                          --output_dir /data0//data0/Baichuan2-7B-Chat-4bits/trt_engines/fp16/1-gpu/

**Comment by byshiue** [comment]
@smallmocha Thank you for the report. The model you try is a quantized model provided by HF, which is trained with NF4. TensorRT-LLM does not support this model. You could try the quantization method (smooth quant, int8 weight only) mentioned in document. 

If you hope TensorRT-LLM supports this model and quantization method, you can change your title or create another issue to explain your requirement.

**Comment by byshiue** [comment]
Close this bug. Feel free to reopen it if needed.

**Comment by jayakommuru** [comment]
@byshiue Are NF4 quantized models supported in tensor RT LLM ? I have fine-tuned version of this base NF4 quantized model: https://huggingface.co/unsloth/Llama-3.2-1B-bnb-4bit , can I deploy it using tensorRT-LLM ?

**Comment by byshiue** [comment]
> [@byshiue](https://github.com/byshiue) Are NF4 quantized models supported in tensor RT LLM ? I have fine-tuned version of this base NF4 quantized model: https://huggingface.co/unsloth/Llama-3.2-1B-bnb-4bit , can I deploy it using tensorRT-LLM ?

Please create another bug to ask this question because NF4 is very different to INT4.
