### ISSUE TITLE
Fail to build per channel smoothquant model for Llama 2 70B

### ISSUE THREAD

**Issue by yunfeng-scale** [NVIDIA/TensorRT-LLM#313]
Using the follow commandline to build an engine for llama 2 70b with per channel smoothquant.
```
python /code/tensorrt_llm/examples/llama/build.py --ft_model_dir /model_weights/llama-2-70b-sq/sq0.5/2-gpu/ \
                 --dtype float16 \
                 --remove_input_padding \
                 --use_gpt_attention_plugin float16 \
                 --enable_context_fmha \
                 --use_gemm_plugin float16 \
                 --output_dir /model_weights/llama-2-70b-trt-llm-smoothquant-per-channel-tp2 \
                 --max_batch_size 50 \
                 --max_input_len 4096 \
                 --max_output_len 4096 \
                 --tokens_per_block 16 \
                 --world_size 2 \
                 --tp_size 2 \
                 --use_smooth_quant \
                 --per_channel
```
Error is
```
[11/08/2023-05:30:29] [TRT-LLM] [I] Loading weights from FT...
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/llama/build.py", line 728, in <module>
    build(0, args)
  File "/code/tensorrt_llm/examples/llama/build.py", line 699, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/code/tensorrt_llm/examples/llama/build.py", line 575, in build_rank_engine
    load_from_binary(tensorrt_llm_llama,
  File "/code/tensorrt_llm/examples/llama/weight.py", line 668, in load_from_binary
    set_smoothquant_scale_factors(
  File "/code/tensorrt_llm/examples/llama/weight.py", line 590, in set_smoothquant_scale_factors
    module.per_channel_scale.value = t
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/parameter.py", line 79, in value
    assert isinstance(v, np.ndarray)
AssertionError
```

**Comment by nv-guomingz** [comment]
Hi @yunfeng-scale  thanks for reprorting this issue.
May I know your trt-llm version, 0.5.0 or latest [main ](https://github.com/NVIDIA/TensorRT-LLM/commit/f044eb8d94d5b064cd1645abb92a54f3804e54d5)? 
And what's your gpu model?

**Comment by yunfeng-scale** [comment]
~0.5.0~ 4de32a86ae92bc49a7ec17c00ec2f2d03663c198 on main and GPU is A100

**Comment by yunfeng-scale** [comment]
Had some misunderstanding for smoothquant. closing
