### ISSUE TITLE
When build with smooth quant on LLama2-7, 13B model, got shape unmatched error

### ISSUE THREAD

**Issue by tolry418** [NVIDIA/TensorRT-LLM#330]
I command like it below to build llama2-13b model. 
I'd like to see what happen when i use smooth quant , but i got error . 
How to solve it?

python build.py --model_dir ../../LLaMA2-13B/ --dtype bfloat16 --remove_input_padding --use_gpt_attention_plugin bfloat16 --enable_context_fmha --world_size 1 --tp_size 1 --use_inflight_batching --use_smooth_quant --max_output_len 2000 --paged_kv_cache --use_gemm_plugin bfloat16 --output_dir ./tmp/llama/13B/trt_engines/bf16/paged_kv_cache_smooth_quant_maxoutput2000/1-gpu

```
[11/09/2023-05:58:15] [TRT-LLM] [I] Serially build TensorRT engines.
[11/09/2023-05:58:15] [TRT] [I] [MemUsageChange] Init CUDA: CPU +13, GPU +0, now: CPU 126, GPU 427 (MiB)
[11/09/2023-05:58:17] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1974, GPU +350, now: CPU 2236, GPU 777 (MiB)
[11/09/2023-05:58:17] [TRT-LLM] [W] Invalid timing cache, using freshly created one
[11/09/2023-05:58:39] [TRT-LLM] [I] Loading HF LLaMA ... from ../../LLaMA2-13B/
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:12<00:00,  4.19s/it]
[11/09/2023-05:58:51] [TRT-LLM] [I] HF LLaMA loaded. Total time: 00:00:12
[11/09/2023-05:58:51] [TRT-LLM] [I] Loading weights from HF LLaMA...
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/llama/build.py", line 718, in <module>
    build(0, args)
  File "/code/tensorrt_llm/examples/llama/build.py", line 689, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/code/tensorrt_llm/examples/llama/build.py", line 563, in build_rank_engine
    load_from_hf_llama(tensorrt_llm_llama,
  File "/code/tensorrt_llm/examples/llama/weight.py", line 293, in load_from_hf_llama
    dst.value = np.ascontiguousarray(split_v)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/parameter.py", line 66, in value
    assert v.shape == self._value.shape, \
AssertionError: ('The value updated is not the same shape as the original. ', 'Updated: (5120, 5120), original: (5120, 1280)')

```

Thank you in advance .

**Comment by nv-guomingz** [comment]
Did u pre-process the weights before building the engine?
Please refer to this [section](https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/examples/llama#smoothquant)

**Comment by tolry418** [comment]
@nv-guomingz Thank you for ur instruction. 
I followed SmoothQuant pre-processed sequence and got many .bin files at directory tmp/smooth_llama_7B/sq0.8/1-gpu .
And i tried to build like below, but i got error reshape array. how to i solve it?
```
root@c4caf306b9f4:/code/tensorrt_llm/examples/llama# python build.py --ft_model_dir tmp/smooth_llama_7B/sq0.8/1-gpu --dtype bfloat16 --remove_input_padding --use_gpt_attention_plugin bfloat16 --enable_context_fmha --world_size 1 --tp_size 1 --use_inflight_batching --use_smooth_quant --max_output_len 2000 --paged_kv_cache --use_gemm_plugin bfloat16 --output_dir ./tmp/llama/7B/trt_engines/bf16/paged_kv_cache_smooth_quant_maxoutput2000/1-gpu --per_token
[11/15/2023-05:23:53] [TRT-LLM] [W] Set rms_norm_eps to 1e-06 directly.
[11/15/2023-05:23:53] [TRT-LLM] [I] Serially build TensorRT engines.
[11/15/2023-05:23:54] [TRT] [I] [MemUsageChange] Init CUDA: CPU +13, GPU +0, now: CPU 126, GPU 427 (MiB)
[11/15/2023-05:23:56] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1974, GPU +350, now: CPU 2236, GPU 777 (MiB)
[11/15/2023-05:23:56] [TRT-LLM] [W] Invalid timing cache, using freshly created one
[11/15/2023-05:24:12] [TRT-LLM] [I] Loading weights from FT...
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/llama/build.py", line 718, in <module>
    build(0, args)
  File "/code/tensorrt_llm/examples/llama/build.py", line 689, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/code/tensorrt_llm/examples/llama/build.py", line 569, in build_rank_engine
    load_from_binary(tensorrt_llm_llama,
  File "/code/tensorrt_llm/examples/llama/weight.py", line 641, in load_from_binary
    tensorrt_llm_llama.vocab_embedding.weight.value = (fromfile(
  File "/code/tensorrt_llm/examples/llama/weight.py", line 558, in fromfile
    t = t.reshape(shape)
ValueError: cannot reshape array of size 65536000 into shape (32000,4096)
```
Thank you in advance.

**Comment by wm2012011492** [comment]
Hi @tolry418 , could you take a try whether `--dtype float16` can work? It seems a bug that LLaMA [load_from_binary function  ](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/llama/weight.py#L548) only supports float16 and float32, cc @nv-guomingz . Maybe we should support bfloat16 as well like [GPT example](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/gpt/weight.py#L116).

**Comment by tolry418** [comment]
@wm2012011492 , thanks your advice. It works with --dtype float16. 
In this point i'm wondering one thing about  SmoothQaunt(SQ). I compared memory-usage with SQ and without SQ. But there is no difference. With SQ occupied 70GB, without SQ occupied 71GB. Is SQ work well?

**Comment by nv-guomingz** [comment]
> Hi @tolry418 , could you take a try whether `--dtype float16` can work? It seems a bug that LLaMA [load_from_binary function ](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/llama/weight.py#L548) only supports float16 and float32, cc @nv-guomingz . Maybe we should support bfloat16 as well like [GPT example](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/gpt/weight.py#L116).

I don't think it's a bug for llama since you need to specify the data type to float16 or float32 explicitly.  BF16 it's not a valid option for smoothquant case here.  Even for gpt example, it's not valid option for setting stroage type to bfloat16.

**Comment by nv-guomingz** [comment]
Hi @tolry418  Do you have more questions on llama smoothquant usage?

**Comment by tolry418** [comment]
Hi @nv-guomingz Thank your explaination. It's enough.
