### ISSUE TITLE
ValueError: Couldn't assign tasks with shape torch.Size([1, 1, 1]), engine supports [min, opt, max] = [(1, 1), (20, 1), (40, 1)]

### ISSUE THREAD

**Issue by jessiewiswjc** [NVIDIA/TensorRT-LLM#341]
When i follow the example blip2 on **branch release/0.5.0**, there is an error in fp16 pipeline:
```
root@bbd04c24e7ba:/wangjiancheng/TensorRT-LLM/examples/blip2# python run.py --num_beams 1               --max_txt_len 32               --max_output_len 30               --input_text "Question: which city is this? Answer:"               --engine_dir ./plan               --opt_engine_dir trt_engine/blip-2-opt-2.7b/fp16/1-gpu               --input_dir image.pt               --query_tokens query_tokens.pt
[11/10/2023-02:02:45] [TRT-LLM] [I] Loading engine from ./plan/visual_encoder/visual_encoder_fp16.plan
[11/10/2023-02:02:47] [TRT-LLM] [I] Creating session from engine ./plan/visual_encoder/visual_encoder_fp16.plan
[11/10/2023-02:02:47] [TRT] [I] Loaded engine size: 1884 MiB
[11/10/2023-02:02:49] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +1881, now: CPU 0, GPU 1881 (MiB)
[11/10/2023-02:02:50] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +32, now: CPU 0, GPU 1913 (MiB)
[11/10/2023-02:02:50] [TRT-LLM] [I] Loading engine from ./plan/Qformer/Qformer_fp16.plan
[11/10/2023-02:02:50] [TRT-LLM] [I] Creating session from engine ./plan/Qformer/Qformer_fp16.plan
[11/10/2023-02:02:50] [TRT] [I] Loaded engine size: 207 MiB
[11/10/2023-02:02:50] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +204, now: CPU 0, GPU 2117 (MiB)
[11/10/2023-02:02:50] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +11, now: CPU 0, GPU 2128 (MiB)
[11/10/2023-02:02:54] [TRT] [I] Loaded engine size: 5303 MiB
[11/10/2023-02:02:56] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 9950, GPU 7746 (MiB)
[11/10/2023-02:02:56] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +2, GPU +10, now: CPU 9952, GPU 7756 (MiB)
[11/10/2023-02:02:56] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +5302, now: CPU 0, GPU 7430 (MiB)
[11/10/2023-02:02:56] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 9952, GPU 15904 (MiB)
[11/10/2023-02:02:56] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 9952, GPU 15912 (MiB)
[11/10/2023-02:02:56] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 7430 (MiB)
[11/10/2023-02:02:56] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 9954, GPU 15920 (MiB)
[11/10/2023-02:02:56] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +10, now: CPU 9954, GPU 15930 (MiB)
[11/10/2023-02:02:56] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 7430 (MiB)
[11/10/2023-02:02:58] [TRT] [E] 3: [executionContext.cpp::setInputShape::2252] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2252, condition: engineDims.nbDims == dims.nbDims )
Traceback (most recent call last):
  File "/wangjiancheng/TensorRT-LLM/examples/blip2/run.py", line 309, in <module>
    stripped_text = opt_blip2(prompt, inputs_opt, atts_opt)
  File "/wangjiancheng/TensorRT-LLM/examples/blip2/run.py", line 287, in opt_blip2
    output_ids = tensorrt_llm_opt.decode(input_ids, input_lengths,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 514, in wrapper
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1887, in decode
    return self.decode_regular(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1659, in decode_regular
    should_stop, next_step_buffer, tasks, context_lengths, host_context_lengths, attention_mask, logits = self.handle_per_step(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1430, in handle_per_step
    self.runtime._set_shape(context, ctx_shape)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 202, in _set_shape
    raise ValueError(
ValueError: Couldn't assign tasks with shape torch.Size([1, 1, 1]), engine supports [min, opt, max] = [(1, 1), (20, 1), (40, 1)]
```

wanted for help, please!

**Comment by juney-nvidia** [comment]
@jessiewiswjc 

Can you share your full build command and run command so it is easy for us to reproduce the issue?

Thanks
June

**Comment by jessiewiswjc** [comment]
@juney-nvidia Thanks for your reply. And my run command is the same as readme of the example blip2. The complete context is as follows:

```
root@bbd04c24e7ba:/wangjiancheng/TensorRT-LLM/examples/blip2# python onnx_export.py
WARNING:root:Pytorch pre-release version 2.1.0a0+29c30b1 - assuming intent to test it
['singapore']
/usr/local/lib/python3.10/dist-packages/lavis/models/eva_vit.py:201: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert H == self.img_size[0] and W == self.img_size[1], \
=========== Diagnostic Run torch.onnx.export version 2.1.0a0+29c30b1 ===========
verbose: False, log level: 40
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

/usr/local/lib/python3.10/dist-packages/lavis/models/blip2_models/Qformer.py:429: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if query_length > 0:
/usr/local/lib/python3.10/dist-packages/lavis/models/blip2_models/Qformer.py:455: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attention_output.shape[1] > query_length:
=========== Diagnostic Run torch.onnx.export version 2.1.0a0+29c30b1 ===========
verbose: False, log level: 40
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

root@bbd04c24e7ba:/wangjiancheng/TensorRT-LLM/examples/blip2# python build_vit_qformer.py 0
Succeeded parsing onnx/visual_encoder/visual_encoder.onnx
Succeeded building plan/visual_encoder/visual_encoder_fp16.plan in 200 s
root@bbd04c24e7ba:/wangjiancheng/TensorRT-LLM/examples/blip2# python build_vit_qformer.py 1
Succeeded parsing onnx/Qformer/Qformer.onnx
Succeeded building plan/Qformer/Qformer_fp16.plan in 77 s
root@bbd04c24e7ba:/wangjiancheng/TensorRT-LLM/examples/blip2# cd ../opt/
root@bbd04c24e7ba:/wangjiancheng/TensorRT-LLM/examples/opt# python3 hf_opt_convert.py -i /wangjiancheng/opt-2.7b -o c-model/opt-2.7b/fp16 -i_g 1 -weight_data_type fp16
[11/12/2023-07:17:02] [TRT-LLM] [I] 
=============== Argument ===============
[11/12/2023-07:17:02] [TRT-LLM] [I] saved_dir: c-model/opt-2.7b/fp16
[11/12/2023-07:17:02] [TRT-LLM] [I] in_file: /wangjiancheng/opt-2.7b
[11/12/2023-07:17:02] [TRT-LLM] [I] trained_gpu_num: 1
[11/12/2023-07:17:02] [TRT-LLM] [I] infer_gpu_num: 1
[11/12/2023-07:17:02] [TRT-LLM] [I] processes: 4
[11/12/2023-07:17:02] [TRT-LLM] [I] weight_data_type: fp16
[11/12/2023-07:17:02] [TRT-LLM] [I] log_level: info
[11/12/2023-07:17:02] [TRT-LLM] [I] ========================================
[11/12/2023-07:18:18] [TRT-LLM] [I] [INFO] Spend 0:01:16.651914 (h:m:s) to convert the model
root@bbd04c24e7ba:/wangjiancheng/TensorRT-LLM/examples/opt# python build.py --model_dir=./c-model/opt-2.7b/fp16/1-gpu \
                --max_batch_size 8 \
                --dtype float16 \
                --use_gpt_attention_plugin float16 \
                --use_gemm_plugin float16 \
                --use_layernorm_plugin float16 \
                --max_input_len 924 \
                --max_output_len 100 \
                --max_beam_width 5 \
                --world_size 1 \
                --output_dir ../blip2/trt_engine/blip-2-opt-2.7b/fp16/1-gpu \
                --do_layer_norm_before \
                --pre_norm \
                --hidden_act relu \
                --max_prompt_embedding_table_size 256
[11/12/2023-07:19:07] [TRT-LLM] [I] Serially build TensorRT engines.
[11/12/2023-07:19:07] [TRT] [I] [MemUsageChange] Init CUDA: CPU +13, GPU +0, now: CPU 112, GPU 262 (MiB)
[11/12/2023-07:19:11] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1799, GPU +312, now: CPU 2047, GPU 574 (MiB)
[11/12/2023-07:19:11] [TRT-LLM] [W] Invalid timing cache, using freshly created one
[11/12/2023-07:19:16] [TRT-LLM] [I] Loading weights from FT...
[11/12/2023-07:19:43] [TRT-LLM] [I] Weights loaded. Total time: 00:00:26
[11/12/2023-07:19:44] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/0/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:44] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:44] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/1/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:44] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_1. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:44] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/2/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:44] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_2. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:45] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/3/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:45] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_3. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:45] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/4/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:45] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_4. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:45] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/5/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:45] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_5. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:46] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/6/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:46] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_6. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:46] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/7/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:46] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_7. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:46] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/8/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:46] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_8. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:46] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/9/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:47] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_9. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:47] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/10/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:47] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_10. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:47] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/11/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:47] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_11. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:47] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/12/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:47] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_12. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:48] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/13/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:48] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_13. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:48] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/14/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:48] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_14. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:48] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/15/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:48] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_15. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:48] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/16/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:48] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_16. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:49] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/17/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:49] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_17. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:49] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/18/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:49] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_18. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:49] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/19/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:49] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_19. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:49] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/20/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:49] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_20. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:50] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/21/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:50] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_21. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:50] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/22/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:50] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_22. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:50] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/23/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:50] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_23. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:50] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/24/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:50] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_24. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:51] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/25/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:51] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_25. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:51] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/26/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:51] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_26. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:51] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/27/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:51] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_27. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:51] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/28/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:51] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_28. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:52] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/29/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:52] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_29. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:52] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/30/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:52] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_30. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:52] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: OPTLMHeadModel/layers/31/attention/PLUGIN_V2_GPTAttention_1_output_0. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:52] [TRT] [W] ITensor::setType(Half) was called on non I/O tensor: present_key_value_31. This will have no effect unless this tensor is marked as an output.
[11/12/2023-07:19:52] [TRT-LLM] [I] Build TensorRT engine opt_float16_tp1_rank0.engine
[11/12/2023-07:19:52] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 7396, GPU 1126 (MiB)
[11/12/2023-07:19:52] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +2, GPU +10, now: CPU 7398, GPU 1136 (MiB)
[11/12/2023-07:19:52] [TRT] [I] Global timing cache in use. Profiling results in this builder pass will be stored.
[11/12/2023-07:21:15] [TRT] [I] [GraphReduction] The approximate region cut reduction algorithm is called.
[11/12/2023-07:21:15] [TRT] [I] Detected 43 inputs and 33 output network tensors.
[11/12/2023-07:21:20] [TRT] [I] Total Host Persistent Memory: 98256
[11/12/2023-07:21:20] [TRT] [I] Total Device Persistent Memory: 0
[11/12/2023-07:21:20] [TRT] [I] Total Scratch Memory: 7415945088
[11/12/2023-07:21:20] [TRT] [I] [BlockAssignment] Started assigning block shifts. This will take 489 steps to complete.
[11/12/2023-07:21:20] [TRT] [I] [BlockAssignment] Algorithm ShiftNTopDown took 18.8908ms to assign 9 blocks to 489 nodes requiring 8551358976 bytes.
[11/12/2023-07:21:20] [TRT] [I] Total Activation Memory: 8551358976
[11/12/2023-07:21:21] [TRT] [I] Total Weights Memory: 5560248360
[11/12/2023-07:21:21] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +1, GPU +8, now: CPU 7705, GPU 6458 (MiB)
[11/12/2023-07:21:21] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 7705, GPU 6466 (MiB)
[11/12/2023-07:21:21] [TRT] [I] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 255 MiB, GPU 5303 MiB
[11/12/2023-07:21:21] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in building engine: CPU +0, GPU +5303, now: CPU 0, GPU 5303 (MiB)
[11/12/2023-07:21:26] [TRT] [I] [MemUsageStats] Peak memory usage during Engine building and serialization: CPU: 13265 MiB
[11/12/2023-07:21:26] [TRT-LLM] [I] Total time of building opt_float16_tp1_rank0.engine: 00:01:33
[11/12/2023-07:21:26] [TRT-LLM] [I] Config saved to ../blip2/trt_engine/blip-2-opt-2.7b/fp16/1-gpu/config.json.
[11/12/2023-07:21:26] [TRT-LLM] [I] Serializing engine to ../blip2/trt_engine/blip-2-opt-2.7b/fp16/1-gpu/opt_float16_tp1_rank0.engine...
[11/12/2023-07:21:35] [TRT-LLM] [I] Engine serialized. Total time: 00:00:09
[11/12/2023-07:21:35] [TRT-LLM] [I] Timing cache serialized to ../blip2/trt_engine/blip-2-opt-2.7b/fp16/1-gpu/model.cache
[11/12/2023-07:21:36] [TRT-LLM] [I] Total time of building all 1 engines: 00:02:28
root@bbd04c24e7ba:/wangjiancheng/TensorRT-LLM/examples/opt# cd ../blip2/
root@bbd04c24e7ba:/wangjiancheng/TensorRT-LLM/examples/blip2# python run.py --num_beams 1 \
              --max_txt_len 32 \
              --max_output_len 30 \
              --input_text "Question: which city is this? Answer:" \
              --engine_dir ./plan \
              --opt_engine_dir trt_engine/blip-2-opt-2.7b/fp16/1-gpu \
              --input_dir image.pt \
              --query_tokens query_tokens.pt
[11/12/2023-07:23:01] [TRT-LLM] [I] Loading engine from ./plan/visual_encoder/visual_encoder_fp16.plan
[11/12/2023-07:23:02] [TRT-LLM] [I] Creating session from engine ./plan/visual_encoder/visual_encoder_fp16.plan
[11/12/2023-07:23:02] [TRT] [I] Loaded engine size: 1884 MiB
[11/12/2023-07:23:04] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +1881, now: CPU 0, GPU 1881 (MiB)
[11/12/2023-07:23:05] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +32, now: CPU 0, GPU 1913 (MiB)
[11/12/2023-07:23:05] [TRT-LLM] [I] Loading engine from ./plan/Qformer/Qformer_fp16.plan
[11/12/2023-07:23:05] [TRT-LLM] [I] Creating session from engine ./plan/Qformer/Qformer_fp16.plan
[11/12/2023-07:23:05] [TRT] [I] Loaded engine size: 207 MiB
[11/12/2023-07:23:05] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +204, now: CPU 0, GPU 2117 (MiB)
[11/12/2023-07:23:06] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +11, now: CPU 0, GPU 2128 (MiB)
[11/12/2023-07:23:10] [TRT] [I] Loaded engine size: 5303 MiB
[11/12/2023-07:23:12] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 9954, GPU 7746 (MiB)
[11/12/2023-07:23:12] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +2, GPU +10, now: CPU 9956, GPU 7756 (MiB)
[11/12/2023-07:23:12] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +5302, now: CPU 0, GPU 7430 (MiB)
[11/12/2023-07:23:12] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 9955, GPU 15904 (MiB)
[11/12/2023-07:23:12] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +1, GPU +8, now: CPU 9956, GPU 15912 (MiB)
[11/12/2023-07:23:12] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 7430 (MiB)
[11/12/2023-07:23:12] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 9958, GPU 15920 (MiB)
[11/12/2023-07:23:12] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +10, now: CPU 9958, GPU 15930 (MiB)
[11/12/2023-07:23:12] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 7430 (MiB)
[11/12/2023-07:23:14] [TRT] [E] 3: [executionContext.cpp::setInputShape::2252] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2252, condition: engineDims.nbDims == dims.nbDims )
Traceback (most recent call last):
  File "/wangjiancheng/TensorRT-LLM/examples/blip2/run.py", line 309, in <module>
    stripped_text = opt_blip2(prompt, inputs_opt, atts_opt)
  File "/wangjiancheng/TensorRT-LLM/examples/blip2/run.py", line 287, in opt_blip2
    output_ids = tensorrt_llm_opt.decode(input_ids, input_lengths,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 514, in wrapper
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1887, in decode
    return self.decode_regular(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1659, in decode_regular
    should_stop, next_step_buffer, tasks, context_lengths, host_context_lengths, attention_mask, logits = self.handle_per_step(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1430, in handle_per_step
    self.runtime._set_shape(context, ctx_shape)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 202, in _set_shape
    raise ValueError(
ValueError: Couldn't assign tasks with shape torch.Size([1, 1, 1]), engine supports [min, opt, max] = [(1, 1), (20, 1), (40, 1)]

```

**Comment by jessiewiswjc** [comment]
@juney-nvidia  I'm happy to tell you that the commit https://github.com/NVIDIA/TensorRT-LLM/commit/6755a3f077bc39d51b74bbcb50403f54663cc8dc on **branch main** can fix for me. It seems that `max_prompt_embedding_table_size` is not passed down?
