### ISSUE TITLE
llama2-13b  build.py oom

### ISSUE THREAD

**Issue by Midcc** [NVIDIA/TensorRT-LLM#346]
env:
A100 

python build.py --model_dir /Llama-2-13-chat-hf/                 --dtype float16                 --remove_input_padding                 --use_gpt_attention_plugin float16                 --use_gemm_plugin float16                  --max_output_len 2048                 --max_batch_size 16                 --output_dir ./tmp/llama/13B/trt_engines/fp16/1-gpu/

[11/10/2023-06:30:19] [TRT] [I] [GraphReduction] The approximate region cut reduction algorithm is called.
[11/10/2023-06:30:19] [TRT] [I] Detected 49 inputs and 41 output network tensors.
[11/10/2023-06:30:40] [TRT] [E] 2: [virtualMemoryBuffer.cpp::resizePhysical::140] Error Code 2: OutOfMemory (no further information)
[11/10/2023-06:30:40] [TRT] [E] 2: [virtualMemoryBuffer.cpp::resizePhysical::140] Error Code 2: OutOfMemory (no further information)
[11/10/2023-06:30:40] [TRT] [W] Requested amount of GPU memory (24793579520 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.
[11/10/2023-06:30:40] [TRT] [E] 2: 
[11/10/2023-06:30:40] [TRT] [E] 2: [globWriter.cpp::makeResizableGpuMemory::423] Error Code 2: OutOfMemory (no further information)
[11/10/2023-06:30:40] [TRT-LLM] [E] Engine building failed, please check the error log.
[11/10/2023-06:30:40] [TRT-LLM] [I] Config saved to ./tmp/llama/13B/trt_engines/fp16/1-gpu/config.json.
Traceback (most recent call last):
  File "/TensorRT-LLM-release-0.5.0/examples/llama/build.py", line 722, in <module>
    build(0, args)
  File "/TensorRT-LLM-release-0.5.0/examples/llama/build.py", line 695, in build
    assert engine is not None, f'Failed to build engine for rank {cur_rank}'
AssertionError: Failed to build engine for rank 0

**Comment by wm2012011492** [comment]
Could you use smaller max_batch_size/max_output_len? Or you can try `--enable_context_fmha` which can save lots of memory.

**Comment by Midcc** [comment]
The same error occurs with this command：
python build.py --model_dir /Llama-2-13-chat-hf/                 --dtype float16                 --remove_input_padding                 --use_gpt_attention_plugin float16                 --use_gemm_plugin float16                  --max_output_len 1024                 --max_batch_size 1                 --enable_context_fmha



[11/10/2023-07:47:56] [TRT] [I] Detected 49 inputs and 41 output network tensors.
[11/10/2023-07:48:06] [TRT] [E] 2: [virtualMemoryBuffer.cpp::resizePhysical::140] Error Code 2: OutOfMemory (no further information)
[11/10/2023-07:48:06] [TRT] [E] 2: [virtualMemoryBuffer.cpp::resizePhysical::140] Error Code 2: OutOfMemory (no further information)
[11/10/2023-07:48:06] [TRT] [W] Requested amount of GPU memory (25092423680 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.
[11/10/2023-07:48:07] [TRT] [E] 2: 
[11/10/2023-07:48:07] [TRT] [E] 2: [globWriter.cpp::makeResizableGpuMemory::423] Error Code 2: OutOfMemory (no further information)
[11/10/2023-07:48:07] [TRT-LLM] [E] Engine building failed, please check the error log.
[11/10/2023-07:48:07] [TRT-LLM] [I] Config saved to llama_outputs/config.json.
Traceback (most recent call last):
  File "/TensorRT-LLM-release-0.5.0/examples/llama/build.py", line 722, in <module>
    build(0, args)
  File "/TensorRT-LLM-release-0.5.0/examples/llama/build.py", line 695, in build
    assert engine is not None, f'Failed to build engine for rank {cur_rank}'
AssertionError: Failed to build engine for rank 0
bash: --output_dir: command not found

**Comment by nv-guomingz** [comment]
A100 80GB or A100 40GB?

**Comment by Midcc** [comment]
A100 40G

**Comment by wm2012011492** [comment]
[A100_40G_release0.5.0_fp16_bs16_seqlen2048_fmha_build.log](https://github.com/NVIDIA/TensorRT-LLM/files/13325036/A100_40G_release0.5.0_fp16_bs16_seqlen2048_fmha_build.log)
[config.json](https://github.com/NVIDIA/TensorRT-LLM/files/13325037/config.json)
Hi @Midcc , I can succeed to build the engine with your command on A100 40G. Attached are the verbose building log and model config for your viz. By the way, which docker image are you using?

**Comment by byshiue** [comment]
Close this bug. Reopen if needed.
