### ISSUE TITLE
Failed to Build Llama-7b Engine Because of Insufficient Memory

### ISSUE THREAD

**Issue by taozhang9527** [NVIDIA/TensorRT-LLM#352]
Building the engine inside the docker container, it used to work fine, but with latest files pulled from repo, I got insufficient memory issue.

Command: 
`python3 examples/llama/build.py --model_dir Llama-2-7b-chat-hf --dtype float16 --use_gpt_attention_plugin float16 --use_gemm_plugin float16 --remove_input_padding --use_inflight_batching --paged_kv_cache --max_output_len 2048 --max_batch_size 64 --output_dir examples/llama/out/7b/fp16_1gpu_ifb`

Got following errors:

`[11/10/2023-21:47:10] [TRT] [W] UNSUPPORTED_STATESkipping tactic 2 due to insufficient memory on requested size of 132096 detected for tactic 0x000000000000001f.
[11/10/2023-21:47:10] [TRT] [I] [GraphReduction] The approximate region cut reduction algorithm is called.
[11/10/2023-21:47:10] [TRT] [I] Detected 41 inputs and 1 output network tensors.
[11/10/2023-21:47:10] [TRT] [E] 4: Internal error: plugin node LLaMAForCausalLM/layers/0/attention/PLUGIN_V2_GPTAttention_0 requires 56405524864 bytes of scratch space, but only 47590277120 is available. Try increasing the workspace size with IBuilderConfig::setMemoryPoolLimit().

[11/10/2023-21:47:10] [TRT] [E] 4: [pluginV2Builder.cpp::makeRunner::519] Error Code 4: Internal Error (Internal error: plugin node LLaMAForCausalLM/layers/0/attention/PLUGIN_V2_GPTAttention_0 requires 56405524864 bytes of scratch space, but only 47590277120 is available. Try increasing the workspace size with IBuilderConfig::setMemoryPoolLimit().
)
[11/10/2023-21:47:10] [TRT-LLM] [E] Engine building failed, please check the error log.
[11/10/2023-21:47:10] [TRT-LLM] [I] Config saved to examples/llama/out/7b/fp16_1gpu_ifb/config.json.
Traceback (most recent call last):
  File "/opt/tritonserver/TensorRT-LLM/examples/llama/build.py", line 718, in <module>
    build(0, args)
  File "/opt/tritonserver/TensorRT-LLM/examples/llama/build.py", line 691, in build
    assert engine is not None, f'Failed to build engine for rank {cur_rank}'
AssertionError: Failed to build engine for rank 0
`

Docker version: `23.10-trtllm-python-py3`
Driver version: `535.129.03`
Cuda version: `12.2`
GPU: `L40`

It seems asking for ~50+GB GPU memory but L40 only has ~48GB. Why building the engine requires so much memory? I tried ` --parallel_build` to use all 4xL40 but it didn't work and failed with same errors. Any ideas what should be done?

**Comment by taozhang9527** [comment]
I am able to build it by removing `--max_batch_size 64` in the command. Looks like the pre-allocated memory for the large batch size exceeds the GPU memory.

**Comment by wm2012011492** [comment]
Hi @taozhang9527 , could you try `--enable_context_fmha` ? It can save lots of memory.

**Comment by nv-guomingz** [comment]
Yes, the building won't fail if you set **--enable_context_fmha**  flag as @wm2012011492 said

**Comment by taozhang9527** [comment]
Verified that --enable_context_fmha resolved the insufficient memory issue. The generated engine file has almost the same size. To confirm, this command won't change the outcomes (so generate the same engine files), only impact the build process?

**Comment by byshiue** [comment]
> Verified that --enable_context_fmha resolved the insufficient memory issue. The generated engine file has almost the same size. To confirm, this command won't change the outcomes (so generate the same engine files), only impact the build process?

The results of `--enable_context_fmha` may be little different to without the flag due to different computation order of kernel fusion, but the correctness should be fine. If you encounter accuracy issue, you could try `--enable_context_fmha_fp32_acc`, which provides better accuracy on sensitive case.

Close this bug. Feel free to reopen it if needed.
