### ISSUE TITLE
Smoothquant conversion fails for Llama-2-70b model

### ISSUE THREAD

**Issue by rohithkrn** [NVIDIA/TensorRT-LLM#358]
Command:
`
python hf_llama_convert.py -i /workspace/llama/llama-2-70b-hf/ -o /workspace/trt-llm/workspace/sq/sq_l70b_8p/ --storage-type fp16 --processes 8 --tensor-parallelism 8 -sq 0.8 
`

Hardware: AWS EC2 p4de.24xlarge

Error log:

```
=============== Argument ===============                                                                                                                         
out_dir: /workspace/trt-llm/workspace/sq/sq_l70b_8p/                                                                                                             
in_file: /workspace/llama/llama-2-70b-hf/                                                                                                                        
tensor_parallelism: 8                                                                                                                                            
processes: 8                                                                                                                                                     
calibrate_kv_cache: False                                                                                                                                        
smoothquant: 0.8                                                                                                                                                 
storage_type: fp16                                                                                                                                               
multi_query_mode: False                                                                                                                                          
========================================                                                                                                                         
Loading checkpoint shards: 100%|██████████| 15/15 [01:32<00:00,  6.18s/it]                                                                                       
Downloading builder script: 100%|██████████| 9.27k/9.27k [00:00<00:00, 42.2MB/s]                                                                                 
Downloading readme: 100%|██████████| 13.9k/13.9k [00:00<00:00, 55.9MB/s]                                                                                         
Downloading data: 100%|██████████| 159M/159M [00:01<00:00, 112MB/s]                                                                                              
Downloading data: 100%|██████████| 376M/376M [00:03<00:00, 114MB/s]t]                                                                                            
Downloading data: 2.11MB [00:00, 25.7MB/s]                  3.04s/it]                                                                                            
Downloading data: 46.4MB [00:00, 76.2MB/s]/5 [00:06<00:03,  1.83s/it]                                                                                            
Downloading data: 2.43MB [00:00, 27.4MB/s]                  1.47s/it] 
Downloading data files: 100%|██████████| 5/5 [00:07<00:00,  1.49s/it]
Extracting data files: 100%|██████████| 5/5 [01:16<00:00, 15.25s/it]
Generating train split: 287113 examples [00:55, 5203.42 examples/s]
Generating validation split: 13368 examples [00:02, 5871.87 examples/s]
Generating test split: 11490 examples [00:02, 5225.36 examples/s]
/usr/local/lib/python3.10/dist-packages/datasets/table.py:1421: FutureWarning: promote has been superseded by mode='default'.
  table = cls._concat_blocks(blocks, axis=0)
calibrating model:   0%|          | 0/512 [00:00<?, ?it/s]Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
calibrating model: 100%|██████████| 512/512 [53:12<00:00,  6.24s/it]
saving weights: 100%|██████████| 720/720 [06:35<00:00,  1.82it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds)) 
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/workspace/trt-llm/tensorrt_llm/examples/llama/convert.py", line 290, in split_and_save_weight
    val = val.reshape(hidden_dim, 3, local_dim)
ValueError: cannot reshape array of size 83886080 into shape (8192,3,3413)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/trt-llm/tensorrt_llm/examples/llama/hf_llama_convert.py", line 335, in <module>
    hf_gpt_converter(args)
  File "/workspace/trt-llm/tensorrt_llm/examples/llama/hf_llama_convert.py", line 269, in hf_gpt_converter
    pool.starmap(split_and_save_weight, starmap_args)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
ValueError: cannot reshape array of size 83886080 into shape (8192,3,3413)
[W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]

```

**Comment by Tracin** [comment]
Llama70 uses GQA, so please add `--multi-query-mode` or use the latest `main` branch which will add this option automaticly.

**Comment by rohithkrn** [comment]
@Tracin what's the impact of adding `--multi-query-mode` to llama2-7b and llama2-13b models, does it ignore this parameter?

**Comment by Tracin** [comment]
> @Tracin what's the impact of adding `--multi-query-mode` to llama2-7b and llama2-13b models, does it ignore this parameter?

I am afraid adding to 7b and 13b model probably lead to confusing errors. Please do not do that since you are pretty sure 7b and 13b do not use GQA.
