### ISSUE TITLE
Building in TensorRT docker container

### ISSUE THREAD

**Issue by makaveli10** [NVIDIA/TensorRT-LLM#36]
Hello, I am using TensorRT docker container `23.09` and then building TensorRT-LLM inside the container,
I follow these steps:
```
apt-get update && apt-get -y install git git-lfs

git clone https://github.com/NVIDIA/TensorRT-LLM.git
cd TensorRT-LLM
git submodule update --init --recursive
git lfs install
git lfs pull
```
then I change the tensorrt lib include path in `scripts/build.py` since the tensorrt header files in docker container are stored in `/usr/include/x86_64-linux-gnu`, so i had to change:
```
if trt_root is not None:
        trt_root = trt_root.replace("\\", "/")
        trt_lib_dir_candidates = (
            f"/usr/lib/x86_64-linux-gnu/",
            f"{trt_root}/lib")
        try:
            trt_lib_dir = next(
                filter(lambda x: Path(x).exists(), trt_lib_dir_candidates))
        except StopIteration:
            trt_lib_dir = trt_lib_dir_candidates[0]
        cmake_def_args.append(f"-DTRT_LIB_DIR={trt_lib_dir}")
        cmake_def_args.append(f"-DTRT_INCLUDE_DIR={trt_root}")
```
ANd then i run to build wheel:
```
python3 ./scripts/build_wheel.py --clean  --trt_root /usr/include/x86_64-linux-gnu/
```
But I face this error:
```
[ 91%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/weightOnlyBatchedGemv/weightOnlyBatchedGemvBs4Int8b.cu.o
[ 91%] Built target kernels_src
gmake[1]: *** [CMakeFiles/Makefile2:684: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/rule] Error 2
gmake: *** [Makefile:179: tensorrt_llm] Error 2
Traceback (most recent call last):
  File "/workspace/TensorRT-LLM/./scripts/build_wheel.py", line 248, in <module>
    main(**vars(args))
  File "/workspace/TensorRT-LLM/./scripts/build_wheel.py", line 152, in main
    build_run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cmake --build . --config Release --parallel 6 --target tensorrt_llm tensorrt_llm_static nvinfer_plugin_tensorrt_llm th_common ' returned non-zero exit status 2.
```

**Comment by makaveli10** [comment]
I also see these make errors:
```
/workspace/TensorRT-LLM/cpp/include/tensorrt_llm/runtime/iBuffer.h:100:40: error: ‘kINT64’ is not a member of ‘nvinfer1::DataType’; did you mean ‘kINT8’?
  100 | struct CppDataType<nvinfer1::DataType::kINT64>
      |                                        ^~~~~~
      |                                        kINT8
/workspace/TensorRT-LLM/cpp/include/tensorrt_llm/runtime/iBuffer.h:100:46: error: template argument 1 is invalid
  100 | struct CppDataType<nvinfer1::DataType::kINT64>
      |                                              ^
/workspace/TensorRT-LLM/cpp/include/tensorrt_llm/runtime/iBuffer.h:112:40: error: ‘kINT64’ is not a member of ‘nvinfer1::DataType’; did you mean ‘kINT8’?
  112 | struct CppDataType<nvinfer1::DataType::kINT64, true>
      |                                        ^~~~~~
      |                                        kINT8
/workspace/TensorRT-LLM/cpp/include/tensorrt_llm/runtime/iBuffer.h:112:52: error: template argument 1 is invalid
  112 | struct CppDataType<nvinfer1::DataType::kINT64, true>
      |                                                    ^
/workspace/TensorRT-LLM/cpp/include/tensorrt_llm/runtime/iBuffer.h:131:40: error: ‘kBF16’ is not a member of ‘nvinfer1::DataType’
  131 | struct CppDataType<nvinfer1::DataType::kBF16>
      |                                        ^~~~~
/workspace/TensorRT-LLM/cpp/include/tensorrt_llm/runtime/iBuffer.h:131:45: error: template argument 1 is invalid
  131 | struct CppDataType<nvinfer1::DataType::kBF16>
      |                                             ^
/workspace/TensorRT-LLM/cpp/include/tensorrt_llm/runtime/iBuffer.h:163:65: error: ‘kINT64’ is not a member of ‘nvinfer1::DataType’; did you mean ‘kINT8’?
  163 |     static auto constexpr kTrtPointerType = nvinfer1::DataType::kINT64;
      |                                                                 ^~~~~~
      |                                                                 kINT8
/workspace/TensorRT-LLM/cpp/include/tensorrt_llm/runtime/iBuffer.h: In member function ‘constexpr std::size_t tensorrt_llm::runtime::BufferDataType::getSize() const’:
/workspace/TensorRT-LLM/cpp/include/tensorrt_llm/runtime/iBuffer.h:194:34: error: ‘kINT64’ is not a member of ‘nvinfer1::DataType’; did you mean ‘kINT8’?
  194 |         case nvinfer1::DataType::kINT64: return 8;
      |                                  ^~~~~~
      |                                  kINT8
/workspace/TensorRT-LLM/cpp/include/tensorrt_llm/runtime/iBuffer.h:197:34: error: ‘kBF16’ is not a member of ‘nvinfer1::DataType’
  197 |         case nvinfer1::DataType::kBF16: [[fallthrough]];
      |                                  ^~~~~
/workspace/TensorRT-LLM/cpp/include/tensorrt_llm/runtime/iBuffer.h: At global scope:
/workspace/TensorRT-LLM/cpp/include/tensorrt_llm/runtime/iBuffer.h:252:55: error: ‘kINT64’ is not a member of ‘nvinfer1::DataType’; did you mean ‘kINT8’?
  252 |     static constexpr auto value = nvinfer1::DataType::kINT64;
      |                                                       ^~~~~~
      |                                                       kINT8
/workspace/TensorRT-LLM/cpp/include/tensorrt_llm/runtime/iBuffer.h:258:70: error: ‘kINT64’ is not a member of ‘nvinfer1::DataType’; did you mean ‘kINT8’?
  258 |     static constexpr auto value = BufferDataType{nvinfer1::DataType::kINT64, true};
      |                                                                      ^~~~~~
      |                                                                      kINT8
/workspace/TensorRT-LLM/cpp/include/tensorrt_llm/runtime/iBuffer.h:258:82: error: no matching function for call to ‘tensorrt_llm::runtime::BufferDataType::BufferDataType(<brace-enclosed initializer list>)’
  258 |     static constexpr auto value = BufferDataType{nvinfer1::DataType::kINT64, true};
      |                               
```
the tensorrt version 8.6.1 doesnt support the datatypes yet?

**Comment by byshiue** [comment]
Yes. These datatypes are supported in TensorRT 9. You can find on https://github.com/NVIDIA/TensorRT/releases/tag/v9.1.0 or https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/secure/9.1.0/tars/tensorrt-9.1.0.4.linux.x86_64-gnu.cuda-12.2.tar.gz

**Comment by makaveli10** [comment]
SO, i guess i'll have to build tensorrt from source in that case, I cant really use tensorrt docker container?

**Comment by byshiue** [comment]
> SO, i guess i'll have to build tensorrt from source in that case, I cant really use tensorrt docker container?

We suggest using the provided docker file to build the docker for TensorRT-LLM. To use tensorrt docker container, you need to install the TensorRT 9 manually and setup other environments/packages.

**Comment by makaveli10** [comment]
BUt then I wonder why do the requirements mention tensorrt>=8.6.0 when it doesnt work with the docker container having tensorrt version 8.6.1?

**Comment by byshiue** [comment]
> BUt then I wonder why do the requirements mention tensorrt>=8.6.0 when it doesnt work with the docker container having tensorrt version 8.6.1?

That's because trt 9 is not published by pypi yet. Officially, TensorRT-LLM requires TensorRT 9 and it is mentioned [here](https://github.com/NVIDIA/TensorRT-LLM#release-notes). We will update the requirements ASAP.

**Comment by jdemouth** [comment]
It may be an oversight. The README indicates that TensorRT-LLM depends on TensorRT 9.1 (at the top, above the Table of Contents). Sorry for the confusion.

**Comment by makaveli10** [comment]
Thanks for the swift response, I was referencing the requirements file https://github.com/NVIDIA/TensorRT-LLM/blob/7295ce25aa157548afa6b2d2cea635c33d0cce5c/requirements.txt#L10

I'll go ahead and install TensorRT 9 manually to proceed with setting up TensorRT-LLM.

**Comment by juney-nvidia** [comment]
Hi @makaveli10  is everything ok after installing TensorRT 9 manually?

If so, then we can close this issue:)
