### ISSUE TITLE
Cannot convert GPT-J model with 'world_size=2'

### ISSUE THREAD

**Issue by skyser2003** [NVIDIA/TensorRT-LLM#380]
I am trying to upload a large size GPT-J model to use two GPUs when inferencing.
This is the command I used to build the engine.

```
python3 build.py --dtype=float16 \
                 --world_size=2 \
                 --log_level=verbose \
                 --enable_context_fmha \
                 --use_gpt_attention_plugin=float16 \
                 --paged_kv_cache \
                 --use_inflight_batching \
                 --use_gemm_plugin float16 \
                 --max_batch_size=4 \
                 --max_input_len=1024 \
                 --max_output_len=1024 \
                 --remove_input_padding \
                 --output_dir=gptj_engine \
                 --model_dir=gptj_model 2>&1 | tee build.log
```

This is the output.

```
[11/14/2023-08:39:04] [TRT-LLM] [I] Loading HF GPTJ model from /language-data/lm_team/varco-llm/varco-llm-24b-FM_231109-v2/...
Loading checkpoint shards: 100%|██████████| 5/5 [03:32<00:00, 42.47s/it]
[11/14/2023-08:44:57] [TRT-LLM] [I] Serially build TensorRT engines.
[11/14/2023-08:44:57] [TRT] [I] [MemUsageChange] Init CUDA: CPU +13, GPU +0, now: CPU 92058, GPU 417 (MiB)
[11/14/2023-08:44:57] [TRT] [V] Trying to load shared library libnvinfer_builder_resource.so.9.1.0
[11/14/2023-08:44:57] [TRT] [V] Loaded shared library libnvinfer_builder_resource.so.9.1.0
[11/14/2023-08:44:59] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1974, GPU +350, now: CPU 94168, GPU 767 (MiB)
[11/14/2023-08:44:59] [TRT] [V] CUDA lazy loading is enabled.
[11/14/2023-08:44:59] [TRT-LLM] [W] Invalid timing cache, using freshly created one
[11/14/2023-08:45:06] [TRT-LLM] [I] Loading weights from HF GPT-J...
Traceback (most recent call last):
  File "/projects/TensorRT-LLM/examples/gptj/build.py", line 494, in <module>
    run_build()
  File "/projects/TensorRT-LLM/examples/gptj/build.py", line 486, in run_build
    build(0, args)
  File "/projects/TensorRT-LLM/examples/gptj/build.py", line 457, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/projects/TensorRT-LLM/examples/gptj/build.py", line 351, in build_rank_engine
    load_from_hf_gpt_j(tensorrt_llm_gpt,
  File "/projects/TensorRT-LLM/examples/gptj/weight.py", line 174, in load_from_hf_gpt_j
    setattr(layer, 'value', v.to(torch_dtype).cpu().numpy())
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/parameter.py", line 66, in value
    assert v.shape == self._value.shape, \
AssertionError: ('The value updated is not the same shape as the original. ', 'Updated: (24960, 6240), original: (12480, 6240)')
```

24960 is double of 12480, so I looked into the source code.

https://github.com/NVIDIA/TensorRT-LLM/blob/73a9ee4b1c96e46af7c4a52860cab75d24856011/tensorrt_llm/layers/linear.py#L70

```cpp
class Linear(Module):

    def __init__(self,
                 in_features,
                 out_features,
                 bias=True,
                 dtype=None,
                 tp_group=None,
                 tp_size=1,
                 gather_output=True,
                 share_weight=None):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features // tp_size
        self.dtype = dtype
```

It seems the division by tp_size is the reason of the size mismatch.

**Comment by byshiue** [comment]
TensorRT-LLM does not support model parallelism on GPT-J now.

**Comment by skyser2003** [comment]
Ah ok.
The 'world_size' parameter description on gptj/build.py is written 'world size, only support tensor parallelism now',
so I thought it would work.

**Comment by byshiue** [comment]
Sorry for confusion. Although we left the related arguments, Tensor prallelism is not really supported on GPT-J now.
