### ISSUE TITLE
Failure to build on g5.12xlarge

### ISSUE THREAD

**Issue by NickBusey** [NVIDIA/TensorRT-LLM#400]
On a fresh g5.12xlarge running  amazon/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20230919, trying to build the docker image fails reproducibly.

```
git clone https://github.com/NVIDIA/TensorRT-LLM.git
cd TensorRT-LLM
git submodule update --init --recursive
make -C docker release_build

....

368.9 [ 97%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/weightOnlyBatchedGemv/weightOnlyBatchedGemvBs4Int4b.cu.o
391.8 [ 98%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/weightOnlyBatchedGemv/weightOnlyBatchedGemvBs4Int8b.cu.o
1626.3 [ 98%] Built target kernels_src
1626.3 [ 98%] Linking CXX static library libtensorrt_llm_static.a
1645.3 [ 98%] Built target tensorrt_llm_static
1645.3 [100%] Linking CXX shared library libtensorrt_llm.so
1645.4 /usr/bin/ld:/src/tensorrt_llm/cpp/tensorrt_llm/batch_manager/x86_64-linux-gnu/libtensorrt_llm_batch_manager_static.a: file format not recognized; treating as linker script
1645.4 /usr/bin/ld:/src/tensorrt_llm/cpp/tensorrt_llm/batch_manager/x86_64-linux-gnu/libtensorrt_llm_batch_manager_static.a:1: syntax error
1645.4 collect2: error: ld returned 1 exit status
1645.4 gmake[3]: *** [tensorrt_llm/CMakeFiles/tensorrt_llm.dir/build.make:714: tensorrt_llm/libtensorrt_llm.so] Error 1
1645.4 gmake[2]: *** [CMakeFiles/Makefile2:677: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/all] Error 2
1645.4 gmake[1]: *** [CMakeFiles/Makefile2:684: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/rule] Error 2
1645.4 gmake: *** [Makefile:179: tensorrt_llm] Error 2
1645.4 Traceback (most recent call last):
1645.4   File "/src/tensorrt_llm/scripts/build_wheel.py", line 248, in <module>
1645.4     main(**vars(args))
1645.4   File "/src/tensorrt_llm/scripts/build_wheel.py", line 152, in main
1645.4     build_run(
1645.4   File "/usr/lib/python3.10/subprocess.py", line 526, in run
1645.4     raise CalledProcessError(retcode, process.args,
1645.4 subprocess.CalledProcessError: Command 'cmake --build . --config Release --parallel 48 --target tensorrt_llm tensorrt_llm_static nvinfer_plugin_tensorrt_llm th_common ' returned non-zero exit status 2.
------
Dockerfile.multi:48
--------------------
  46 |
  47 |     ARG BUILD_WHEEL_ARGS="--clean --trt_root /usr/local/tensorrt"
  48 | >>> RUN python3 scripts/build_wheel.py ${BUILD_WHEEL_ARGS}
  49 |
  50 |     FROM devel as release
--------------------
ERROR: failed to solve: process "/bin/bash -c python3 scripts/build_wheel.py ${BUILD_WHEEL_ARGS}" did not complete successfully: exit code: 1
make: *** [Makefile:47: release_build] Error 1
make: Leaving directory '/home/ubuntu/TensorRT-LLM/docker'
root@ip-172-31-37-99:/home/ubuntu/TensorRT-LLM# ]
```

**Comment by byshiue** [comment]
This issue should be same to https://github.com/NVIDIA/TensorRT-LLM/issues/100, it may be helpful.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Please reopen it if needed.
