### ISSUE TITLE
AWQ quantization fails with cuda_ext import error

### ISSUE THREAD

**Issue by theophilegervet** [NVIDIA/TensorRT-LLM#403]
Quantizing with AWQ using `atq.quantize(model, atq.INT4_AWQ_CFG, calibrate_loop)` leads to this error
```
>>> from ammo.torch.quantization import cuda_ext
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/local/lib/python3.10/dist-packages/ammo/torch/quantization/cuda_ext.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

I've installed `ammo` with recommended instructions from https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/examples/quantization:
```
cuda_version=$(nvcc --version | grep 'release' | awk '{print $6}' | awk -F'[V.]' '{print $2$3}')
python_version=$(python3 --version 2>&1 | awk '{print $2}' | awk -F. '{print $1$2}')
wget https://developer.nvidia.com/downloads/assets/cuda/files/nvidia-ammo/nvidia_ammo-0.3.0.tar.gz
tar -xzf nvidia_ammo-0.3.0.tar.gz
pip install nvidia_ammo-0.3.0/nvidia_ammo-0.3.0+cu$cuda_version-cp$python_version-cp$python_version-linux_x86_64.whl
```

Environment:
```
$cuda_version 122
$python_version 310
torch.__version__ 2.1.0+cu121
```

This seems similar to [this issue](https://github.com/NVIDIA/TensorRT-LLM/issues/126), but installation with
```
pip install nvidia_ammo-0.3.0/nvidia_ammo-0.3.0-cp$python_version-cp$python_version-linux_x86_64.whl
```
as recommended there, gives
```
>>> from ammo.torch.quantization import cuda_ext
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'cuda_ext' from 'ammo.torch.quantization' (/usr/local/lib/python3.10/dist-packages/ammo/torch/quantization/__init__.py)
```

**Comment by RalphMao** [comment]
Hi @theophilegervet 

I just tested it and simply replacing `from ammo.torch.quantization import cuda_ext` with `from  ammo.torch.quantization.extensions import cuda_ext` will work

**Comment by theophilegervet** [comment]
Awesome, thanks!

**Comment by shwu-nyunai** [comment]
I'm on Cuda 12.3 and the expected .whl for ammo is `nvidia_ammo-0.3.0/nvidia_ammo-0.3.0+cu123-cp310-cp310-linux_x86_64.whl` which is not available in the downloaded zip. 

```shell
root@79b341fd0ce8:/workspace# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Sep__8_19:17:24_PDT_2023
Cuda compilation tools, release 12.3, V12.3.52
Build cuda_12.3.r12.3/compiler.33281558_0
root@79b341fd0ce8:/workspace# ls nvidia_ammo-0.3.0
LICENSE                                             nvidia_ammo-0.3.0+cpu-cp39-cp39-linux_x86_64.whl      nvidia_ammo-0.3.0+cu118-cp311-cp311-linux_x86_64.whl  nvidia_ammo-0.3.0-cp310-cp310-linux_x86_64.whl
README.md                                           nvidia_ammo-0.3.0+cu117-cp310-cp310-linux_x86_64.whl  nvidia_ammo-0.3.0+cu118-cp38-cp38-linux_x86_64.whl    nvidia_ammo-0.3.0-cp311-cp311-linux_x86_64.whl
docs                                                nvidia_ammo-0.3.0+cu117-cp311-cp311-linux_x86_64.whl  nvidia_ammo-0.3.0+cu118-cp39-cp39-linux_x86_64.whl    nvidia_ammo-0.3.0-cp38-cp38-linux_x86_64.whl
nvidia_ammo-0.3.0+cpu-cp310-cp310-linux_x86_64.whl  nvidia_ammo-0.3.0+cu117-cp38-cp38-linux_x86_64.whl    nvidia_ammo-0.3.0+cu121-cp310-cp310-linux_x86_64.whl  nvidia_ammo-0.3.0-cp39-cp39-linux_x86_64.whl
nvidia_ammo-0.3.0+cpu-cp311-cp311-linux_x86_64.whl  nvidia_ammo-0.3.0+cu117-cp39-cp39-linux_x86_64.whl    nvidia_ammo-0.3.0+cu121-cp38-cp38-linux_x86_64.whl
nvidia_ammo-0.3.0+cpu-cp38-cp38-linux_x86_64.whl    nvidia_ammo-0.3.0+cu118-cp310-cp310-linux_x86_64.whl  nvidia_ammo-0.3.0+cu122-cp310-cp310-linux_x86_64.whl
```
Can someone point me where to find the required file? I tried installing a lower version but it throws the error mentioned above. 

Changing the import statement also doesn't help

```shell
root@79b341fd0ce8:/workspace# python
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from  ammo.torch.quantization.extensions import cuda_ext
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'ammo.torch.quantization.extensions'
>>> 
```
