### ISSUE TITLE
 func load_from_gptq_llama  dimension  canot concat

### ISSUE THREAD

**Issue by foocker** [NVIDIA/TensorRT-LLM#405]
for   [codefuse34b-int4 model.](https://www.modelscope.cn/models/codefuse-ai/CodeFuse-CodeLlama-34B-4bits/summary)
```
[11/16/2023-03:54:02] [TRT-LLM] [I] Loading weights from groupwise GPTQ LLaMA safetensors...
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/llama/build.py", line 736, in <module>
    build(0, args)
  File "/code/tensorrt_llm/examples/llama/build.py", line 707, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/code/tensorrt_llm/examples/llama/build.py", line 545, in build_rank_engine
    load_func(tensorrt_llm_llama=tensorrt_llm_llama,
  File "/code/tensorrt_llm/examples/llama/weight.py", line 931, in load_from_gptq_llama
    qkv_part = torch.cat([q_part, k_part, v_part], dim=0)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 8192 but got size 1024 for tensor number 1 in the list.
```

buiid 

```
python build.py \
                --quant_ckpt_path ${dm} \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --use_weight_only \
                --weight_only_precision int4_gptq \
                --per_group \
                --world_size 1 \
                --tp_size 1 \
                --use_inflight_batching \
                --paged_kv_cache \
                --max_batch_size 1 \
                --max_input_len 2048 \
                --max_output_len 1024 \
                --group_size 64 \
                --output_dir trt_engines/int4-gptq/1-gpu
```

**Comment by byshiue** [comment]
TensorRT-LLM does not suuport models not quantized by AMMO.

**Comment by foocker** [comment]
> TensorRT-LLM does not suuport models not quantized by AMMO.

but qwen-gptq successed! [Qwen-7B-Chat-TensorRT-LLM](https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM).There's no contradiction here, right?

**Comment by byshiue** [comment]
I think there are some details to resolve to support, including weight shape, parameter renames and mapping. So, we only claim to support the model quantized by AMMO. For other models, we cannot guarantee that it works.

**Comment by foocker** [comment]
> I think there are some details to resolve to support, including weight shape, parameter renames and mapping. So, we only claim to support the model quantized by AMMO. For other models, we cannot guarantee that it works.

ok,thx. but what is AMMO. is there only paper？

**Comment by byshiue** [comment]
[Here](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/quantization) is the document.
