### ISSUE TITLE
Failed to build chatglm-6b hf format model to trt engines

### ISSUE THREAD

**Issue by Ajay-Wong** [NVIDIA/TensorRT-LLM#416]
I follow this https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/chatglm to build chatglm-6b hf format model to trt engines.

When i run below command:

python build.py --model_version 1 --world_size 2 --dtype float16 --max_batch_size 32 --max_input_len 1024 --max_output_len 1024 --max_beam_width 5 --use_gpt_attention_plugin float16 --use_gemm_plugin float16 --remove_input_padding --use_inflight_batching --use_weight_only --weight_only_precision int8 --paged_kv_cache --model_dir=/mnt/cephfs/workspace/speech/chatglm_6B/origin_hf_model/chatglm_6b --output_dir=./trt_engines/chatglm6b_tp2_inflight_w8a16

i get some errors:

<details><summary>Details</summary>
<p>

[11/17/2023-03:01:46] [TRT-LLM] [I] Build TensorRT engine chatglm-6b_float16_tp2_rank0.engine
[11/17/2023-03:01:46] [TRT] [E] 1: [network.cpp::setWeightsName::3858] Error Code 1: Internal Error (Error: Weights of same values but of different counts are used in the network!)
Traceback (most recent call last):
  File "/mnt/cephfs/workspace/speech/wangzhijian/TRTLLM/TensorRT-LLM/examples/chatglm/build.py", line 571, in <module>
    run_build()
  File "/mnt/cephfs/workspace/speech/wangzhijian/TRTLLM/TensorRT-LLM/examples/chatglm/build.py", line 563, in run_build
    build(0, args)
  File "/mnt/cephfs/workspace/speech/wangzhijian/TRTLLM/TensorRT-LLM/examples/chatglm/build.py", line 528, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/mnt/cephfs/workspace/speech/wangzhijian/TRTLLM/TensorRT-LLM/examples/chatglm/build.py", line 470, in build_rank_engine
    engine = builder.build_engine(network, builder_config)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/builder.py", line 48, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/builder.py", line 303, in build_engine
    raise RuntimeError(f'Failed to set weight: {name}')
RuntimeError: Failed to set weight: embedding.weight

</p>
</details> 

How can i fix this issue

**Comment by nv-guomingz** [comment]
Please share us your gpu details.

**Comment by Ajay-Wong** [comment]
> Please share us your gpu details.

A800, NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 12.2, ubuntu 22.04

**Comment by nv-guomingz** [comment]
I can reproduce this issue locally. We'll have a look this issue internally.
A quick war is to remove --world_size and set its value to 1.

**Comment by Ajay-Wong** [comment]
> I can reproduce this issue locally. We'll have a look this issue internally. A quick war is to remove --world_size and set its value to 1.

ok, thanks
I set --world_size to 1, it works.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Please reopen it if needed.
