### ISSUE TITLE
CMake Generate step failed.  Build files cannot be regenerated correctly.

### ISSUE THREAD

**Issue by yuvraj108c** [NVIDIA/TensorRT-LLM#429]
```bash
(tensorml) user@10324cdf-227b-465d-98af-cabfa0a5996c:~/TensorRT-LLM$ python3 ./scripts/build_wheel.py --trt_root /home/user/TensorRT-LLM/TensorRT-9.1.0.4
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: build in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (1.0.3)
Requirement already satisfied: torch in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (2.1.0)
Requirement already satisfied: transformers==4.31.0 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (4.31.0)
Requirement already satisfied: diffusers==0.15.0 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (0.15.0)
Requirement already satisfied: accelerate==0.20.3 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from -r requirements.txt (line 5)) (0.20.3)
Requirement already satisfied: colored in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from -r requirements.txt (line 6)) (2.2.3)
Requirement already satisfied: polygraphy in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from -r requirements.txt (line 7)) (0.49.0)
Requirement already satisfied: onnx>=1.12.0 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from -r requirements.txt (line 8)) (1.15.0)
Requirement already satisfied: mpi4py in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from -r requirements.txt (line 9)) (3.1.5)
Requirement already satisfied: tensorrt>=8.6.0 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from -r requirements.txt (line 10)) (9.1.0.post12.dev4)
Requirement already satisfied: numpy in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from -r requirements.txt (line 11)) (1.26.0)
Requirement already satisfied: cuda-python==12.2.0 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from -r requirements.txt (line 12)) (12.2.0)
Requirement already satisfied: sentencepiece>=0.1.99 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from -r requirements.txt (line 13)) (0.1.99)
Requirement already satisfied: wheel in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from -r requirements.txt (line 14)) (0.41.3)
Requirement already satisfied: lark in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from -r requirements.txt (line 15)) (1.1.8)
Requirement already satisfied: filelock in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (3.13.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.14.1 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (0.19.4)
Requirement already satisfied: packaging>=20.0 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (2023.10.3)
Requirement already satisfied: requests in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (2.31.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (0.13.3)
Requirement already satisfied: safetensors>=0.3.1 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (0.4.0)
Requirement already satisfied: tqdm>=4.27 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from transformers==4.31.0->-r requirements.txt (line 3)) (4.66.1)
Requirement already satisfied: Pillow in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from diffusers==0.15.0->-r requirements.txt (line 4)) (9.4.0)
Requirement already satisfied: importlib-metadata in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from diffusers==0.15.0->-r requirements.txt (line 4)) (6.8.0)
Requirement already satisfied: psutil in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from accelerate==0.20.3->-r requirements.txt (line 5)) (5.9.5)
Requirement already satisfied: cython in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from cuda-python==12.2.0->-r requirements.txt (line 12)) (3.0.5)
Requirement already satisfied: pyproject_hooks in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from build->-r requirements.txt (line 1)) (1.0.0)
Requirement already satisfied: typing-extensions in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from torch->-r requirements.txt (line 2)) (4.8.0)
Requirement already satisfied: sympy in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from torch->-r requirements.txt (line 2)) (1.12)
Requirement already satisfied: networkx in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from torch->-r requirements.txt (line 2)) (3.2.1)
Requirement already satisfied: jinja2 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from torch->-r requirements.txt (line 2)) (3.1.2)
Requirement already satisfied: fsspec in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from torch->-r requirements.txt (line 2)) (2023.10.0)
Requirement already satisfied: protobuf>=3.20.2 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from onnx>=1.12.0->-r requirements.txt (line 8)) (4.25.1)
Requirement already satisfied: tensorrt-libs==9.1.0.post12.dev4 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from tensorrt>=8.6.0->-r requirements.txt (line 10)) (9.1.0.post12.dev4)
Requirement already satisfied: tensorrt-bindings==9.1.0.post12.dev4 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from tensorrt>=8.6.0->-r requirements.txt (line 10)) (9.1.0.post12.dev4)
Requirement already satisfied: nvidia-cuda-runtime-cu12 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from tensorrt-libs==9.1.0.post12.dev4->tensorrt>=8.6.0->-r requirements.txt (line 10)) (12.3.101)
Requirement already satisfied: nvidia-cudnn-cu12 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from tensorrt-libs==9.1.0.post12.dev4->tensorrt>=8.6.0->-r requirements.txt (line 10)) (8.9.6.50)
Requirement already satisfied: nvidia-cublas-cu12 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from tensorrt-libs==9.1.0.post12.dev4->tensorrt>=8.6.0->-r requirements.txt (line 10)) (12.3.4.1)
Requirement already satisfied: zipp>=0.5 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from importlib-metadata->diffusers==0.15.0->-r requirements.txt (line 4)) (3.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from jinja2->torch->-r requirements.txt (line 2)) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from requests->transformers==4.31.0->-r requirements.txt (line 3)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from requests->transformers==4.31.0->-r requirements.txt (line 3)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from requests->transformers==4.31.0->-r requirements.txt (line 3)) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from requests->transformers==4.31.0->-r requirements.txt (line 3)) (2023.7.22)
Requirement already satisfied: mpmath>=0.19 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from sympy->torch->-r requirements.txt (line 2)) (1.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12 in /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages (from nvidia-cudnn-cu12->tensorrt-libs==9.1.0.post12.dev4->tensorrt>=8.6.0->-r requirements.txt (line 10)) (12.3.103)
-- The CXX compiler identification is GNU 9.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- NVTX is disabled
-- Importing batch manager
-- Building PyTorch
-- Building Google tests
-- Building benchmarks
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - /usr/local/cuda-12.2/bin/nvcc
-- CUDA compiler: /usr/local/cuda-12.2/bin/nvcc
-- GPU architectures: 70-real;80-real;86-real;89-real;90-real
-- The CUDA compiler identification is NVIDIA 12.2.140
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda-12.2/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Found CUDAToolkit: /usr/local/cuda-12.2/include (found version "12.2.140")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- ========================= Importing and creating target nvinfer ==========================
-- Looking for library nvinfer
-- Library that was found /home/user/TensorRT-LLM/TensorRT-9.1.0.4/targets/x86_64-linux-gnu/lib/libnvinfer.so
-- ==========================================================================================
-- ========================= Importing and creating target nvuffparser ==========================
-- Looking for library nvparsers
-- Library that was found nvparsers_LIB_PATH-NOTFOUND
-- ==========================================================================================
-- CUDAToolkit_VERSION 12.2 is greater or equal than 11.0, enable -DENABLE_BF16 flag
-- CUDAToolkit_VERSION 12.2 is greater or equal than 11.8, enable -DENABLE_FP8 flag
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-- COMMON_HEADER_DIRS: /home/user/TensorRT-LLM/cpp;/usr/local/cuda-12.2/include
-- TORCH_CUDA_ARCH_LIST: 7.0;8.0;8.6;8.9;9.0
-- Found Python3: /home/user/mambaforge/envs/tensorml/bin/python3.11 (found version "3.11.6") found components: Interpreter Development Development.Module Development.Embed
-- Found Python executable at /home/user/mambaforge/envs/tensorml/bin/python3.11
-- Found Python libraries at /home/user/mambaforge/envs/tensorml/lib
-- Found CUDA: /usr/local/cuda-12.2 (found version "12.2")
-- Found CUDAToolkit: /usr/local/cuda-12.2/include (found version "12.2.140")
-- Caffe2: CUDA detected: 12.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda-12.2/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-12.2
-- Caffe2: Header version is: 12.2
-- /usr/local/cuda-12.2/targets/x86_64-linux/lib/libnvrtc.so shorthash is 000ca627
-- USE_CUDNN is set to 0. Compiling without cuDNN support
-- USE_CUSPARSELT is set to 0. Compiling without cuSPARSELt support
-- Added CUDA NVCC flags for: -gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_89,code=sm_89;-gencode;arch=compute_90,code=sm_90
-- MKL_ARCH: None, set to ` intel64` by default
-- MKL_ROOT /home/user/mambaforge/envs/tensorml
-- MKL_LINK: None, set to ` dynamic` by default
-- MKL_INTERFACE_FULL: None, set to ` intel_ilp64` by default
-- MKL_THREADING: None, set to ` intel_thread` by default
-- MKL_MPI: None, set to ` intelmpi` by default
CMake Warning at /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  CMakeLists.txt:281 (find_package)


-- Found Torch: /home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages/torch/lib/libtorch.so
-- TORCH_CXX_FLAGS: -D_GLIBCXX_USE_CXX11_ABI=0
-- Building for TensorRT version: 9.1.0, library version: 9
-- Using MPI_CXX_INCLUDE_DIRS: /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi;/usr/lib/x86_64-linux-gnu/openmpi/include
-- Using MPI_CXX_LIBRARIES: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- USE_CXX11_ABI: False
-- The C compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Python: /home/user/mambaforge/envs/tensorml/bin/python3.11 (found version "3.11.6") found components: Interpreter
-- ========================= Importing and creating target nvonnxparser ==========================
-- Looking for library nvonnxparser
-- Library that was found /home/user/TensorRT-LLM/TensorRT-9.1.0.4/targets/x86_64-linux-gnu/lib/libnvonnxparser.so
-- ==========================================================================================
-- Configuring done (31.5s)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDNN_LIB
    linked by target "tensorrt_llm_static" in directory /home/user/TensorRT-LLM/cpp/tensorrt_llm
    linked by target "tensorrt_llm" in directory /home/user/TensorRT-LLM/cpp/tensorrt_llm
    linked by target "nvinfer_plugin_tensorrt_llm" in directory /home/user/TensorRT-LLM/cpp/tensorrt_llm/plugins
NCCL_LIB
    linked by target "tensorrt_llm_static" in directory /home/user/TensorRT-LLM/cpp/tensorrt_llm
    linked by target "tensorrt_llm" in directory /home/user/TensorRT-LLM/cpp/tensorrt_llm
    linked by target "runtime_src" in directory /home/user/TensorRT-LLM/cpp/tensorrt_llm/runtime
    linked by target "nvinfer_plugin_tensorrt_llm" in directory /home/user/TensorRT-LLM/cpp/tensorrt_llm/plugins

-- Generating done (0.2s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
Traceback (most recent call last):
  File "/home/user/TensorRT-LLM/./scripts/build_wheel.py", line 248, in <module>
    main(**vars(args))
  File "/home/user/TensorRT-LLM/./scripts/build_wheel.py", line 149, in main
    build_run(
  File "/home/user/mambaforge/envs/tensorml/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cmake -DCMAKE_BUILD_TYPE="Release" -DBUILD_PYT="ON"  -DTRT_LIB_DIR=/home/user/TensorRT-LLM/TensorRT-9.1.0.4/targets/x86_64-linux-gnu/lib -DTRT_INCLUDE_DIR=/home/user/TensorRT-LLM/TensorRT-9.1.0.4/include -S "/home/user/TensorRT-LLM/cpp"' returned non-zero exit status 1.
```

**Comment by byshiue** [comment]
Do you use the docker image we suggest?

**Comment by yuvraj108c** [comment]
Managed to build the wheel by following instructions on docker.multi, without using the docker image!
