### ISSUE TITLE
bug: chatglm2-6b does not support build with tensor parallel

### ISSUE THREAD

**Issue by NaNAGISaSA** [NVIDIA/TensorRT-LLM#430]
HEAD: v0.5.0
commit ffd5af342a817a2689d38e4af2cc59ded877e339 (HEAD, tag: v0.5.0)

build cmd:
```bash
python build.py --world_size 2 \
                --model_dir /workspace/volume/llm_models/chatglm/chatglm2-6b \
                --dtype float16 \
                --max_batch_size 2 \
                --max_input_len 2048 \
                --max_output_len 2048 \
                --use_gemm_plugin float16 \
                --use_gpt_attention_plugin float16 \
                --output_dir /workspace/volume/trt_models/chatglm2_6b/trt_engines/fp16/2-gpu/
```

error log:
```
[11/20/2023-02:26:18] [TRT-LLM] [I] Serially build TensorRT engines.
[11/20/2023-02:26:18] [TRT] [I] [MemUsageChange] Init CUDA: CPU +14, GPU +0, now: CPU 115, GPU 309 (MiB)
[11/20/2023-02:26:19] [TRT] [V] Trying to load shared library libnvinfer_builder_resource.so.9.1.0
[11/20/2023-02:26:19] [TRT] [V] Loaded shared library libnvinfer_builder_resource.so.9.1.0
[11/20/2023-02:26:19] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +482, GPU +80, now: CPU 733, GPU 389 (MiB)
[11/20/2023-02:26:19] [TRT] [V] CUDA lazy loading is enabled.
[11/20/2023-02:26:19] [TRT-LLM] [W] Invalid timing cache, using freshly created one
loading weights from hugging face model
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:08<00:00,  1.26s/it]
[11/20/2023-02:26:40] [TRT-LLM] [I] Loading weights from HF ChatGLM2...
Traceback (most recent call last):
  File "/workspace/TensorRT-LLM/examples/chatglm2-6b/build.py", line 395, in <module>
    build(0, args)
  File "/workspace/TensorRT-LLM/examples/chatglm2-6b/build.py", line 361, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/workspace/TensorRT-LLM/examples/chatglm2-6b/build.py", line 264, in build_rank_engine
    tensorrt_llm_ChatGLM2_6BModel = load_from_hf_chatglm2_6B(
  File "/workspace/TensorRT-LLM/examples/chatglm2-6b/weight.py", line 64, in load_from_hf_chatglm2_6B
    tensorrt_llm_model.lm_head.weight.value = hf_model.transformer.output_layer.weight.detach(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/parameter.py", line 66, in value
    assert v.shape == self._value.shape, \
AssertionError: ('The value updated is not the same shape as the original. ', 'Updated: (65024, 4096), original: (32512, 4096)')
```

It seems that `load_from_hf_chatglm2_6B` function does not use `tensor_parallel` param.

**Comment by byshiue** [comment]
Could you try the latest main branch?

**Comment by NaNAGISaSA** [comment]
@byshiue hi，I have tried on the latest main branch, commit: 6837c8141acd036b8884330f4eadb50e097163f7. The same error occurred.

**Comment by byshiue** [comment]
The commit you share is not the latest main branch. It should be here https://github.com/NVIDIA/TensorRT-LLM/tree/main and the commit is [6755a3f](https://github.com/NVIDIA/TensorRT-LLM/commit/6755a3f077bc39d51b74bbcb50403f54663cc8dc)

**Comment by NaNAGISaSA** [comment]
@byshiue hello, I have tested on the latest main branch, this bug is fixed. Close this issue.
