### ISSUE TITLE
How to use AWQ for llama 70B

### ISSUE THREAD

**Issue by HamidShojanazeri** [NVIDIA/TensorRT-LLM#440]
quantizing and building the llama 70b following the the [README](https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/examples/llama#awq), on 8xA100, when trying to run it with following command,

```
mpirun -n 8 --allow-run-as-root python3 run.py --max_output_len=50 --tokenizer_dir llama70b --engine_dir=llama70b/trt_engines/int4_AWQ/8-gpu

```

It runs into conflict with world_size has been set in the engine and one at the runtime.  Would appreciate your help how to correctly run it.

```
 TP size is 1, pp_size 1 world_size1
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/llama/run.py", line 279, in <module>
    generate(**vars(args))
  File "/code/tensorrt_llm/examples/llama/run.py", line 214, in generate
    model_config, tp_size, pp_size, dtype = read_config(config_path)
  File "/code/tensorrt_llm/examples/llama/run.py", line 54, in read_config
    assert world_size == tensorrt_llm.mpi_world_size(), \
AssertionError: Engine world size (1) != Runtime world size (8)
 TP size is 1, pp_size 1 world_size1
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/llama/run.py", line 279, in <module>
    generate(**vars(args))
  File "/code/tensorrt_llm/examples/llama/run.py", line 214, in generate
    model_config, tp_size, pp_size, dtype = read_config(config_path)
  File "/code/tensorrt_llm/examples/llama/run.py", line 54, in read_config
    assert world_size == tensorrt_llm.mpi_world_size(), \
AssertionError: Engine world size (1) != Runtime world size (8)
 TP size is 1, pp_size 1 world_size1
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/llama/run.py", line 279, in <module>
    generate(**vars(args))
  File "/code/tensorrt_llm/examples/llama/run.py", line 214, in generate
    model_config, tp_size, pp_size, dtype = read_config(config_path)
  File "/code/tensorrt_llm/examples/llama/run.py", line 54, in read_config
 TP size is 1, pp_size 1 world_size1
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/llama/run.py", line 279, in <module>
    assert world_size == tensorrt_llm.mpi_world_size(), \
AssertionError: Engine world size (1) != Runtime world size (8)
    generate(**vars(args))
  File "/code/tensorrt_llm/examples/llama/run.py", line 214, in generate
    model_config, tp_size, pp_size, dtype = read_config(config_path)
  File "/code/tensorrt_llm/examples/llama/run.py", line 54, in read_config
    assert world_size == tensorrt_llm.mpi_world_size(), \
AssertionError: Engine world size (1) != Runtime world size (8)
 TP size is 1, pp_size 1 world_size1
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/llama/run.py", line 279, in <module>
    generate(**vars(args))
  File "/code/tensorrt_llm/examples/llama/run.py", line 214, in generate
    model_config, tp_size, pp_size, dtype = read_config(config_path)
  File "/code/tensorrt_llm/examples/llama/run.py", line 54, in read_config
    assert world_size == tensorrt_llm.mpi_world_size(), \
AssertionError: Engine world size (1) != Runtime world size (8)
 TP size is 1, pp_size 1 world_size1
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/llama/run.py", line 279, in <module>
    generate(**vars(args))
  File "/code/tensorrt_llm/examples/llama/run.py", line 214, in generate
    model_config, tp_size, pp_size, dtype = read_config(config_path)
  File "/code/tensorrt_llm/examples/llama/run.py", line 54, in read_config
    assert world_size == tensorrt_llm.mpi_world_size(), \
AssertionError: Engine world size (1) != Runtime world size (8)
 TP size is 1, pp_size 1 world_size1
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/llama/run.py", line 279, in <module>
    generate(**vars(args))
  File "/code/tensorrt_llm/examples/llama/run.py", line 214, in generate
    model_config, tp_size, pp_size, dtype = read_config(config_path)
  File "/code/tensorrt_llm/examples/llama/run.py", line 54, in read_config
    assert world_size == tensorrt_llm.mpi_world_size(), \
AssertionError: Engine world size (1) != Runtime world size (8)
 TP size is 1, pp_size 1 world_size1
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/llama/run.py", line 279, in <module>
    generate(**vars(args))
  File "/code/tensorrt_llm/examples/llama/run.py", line 214, in generate
    model_config, tp_size, pp_size, dtype = read_config(config_path)
  File "/code/tensorrt_llm/examples/llama/run.py", line 54, in read_config
    assert world_size == tensorrt_llm.mpi_world_size(), \
AssertionError: Engine world size (1) != Runtime world size (8)
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[28800,1],0]
  Exit code:    1
  
  ```

**Comment by byshiue** [comment]
Can you share your scripts to build the engine?

**Comment by HamidShojanazeri** [comment]
@byshiue I was under this impression that should use the build script in example/llama as shown [here](https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/examples/llama#awq), should I have made changes to this?

**Comment by byshiue** [comment]
To build engine with tensor parallelism, you should add `--world_size 8 --tp_size 8` (an example for 8-way TP).

**Comment by jdemouth-nvidia** [comment]
I’m closing that issue. Feel free to reopen it if needed. Thanks.

**Comment by HamidShojanazeri** [comment]
> To build engine with tensor parallelism, you should add `--world_size 8 --tp_size 8` (an example for 8-way TP).

I have used the `--world_size 8 --tp_size 8` during the build as well, same issue.

**Comment by byshiue** [comment]
Please share your new build script and new log message.

**Comment by nv-guomingz** [comment]
do u still have further issue or question now? If not, we'll close it soon.
