### ISSUE TITLE
TypeError: SplitInfo.__init__() got an unexpected keyword argument 'shard_lengths'

### ISSUE THREAD

**Issue by yuvraj108c** [NVIDIA/TensorRT-LLM#443]
```bash
(venv) user@f1623c4b-0aaf-429f-a230-a524e2e5ff32:~/TensorRT-LLM/examples/bloom$ python summarize.py --test_trt_llm \
>                     --hf_model_location ./bloom/560M/ \
>                     --data_type fp16 \
>                     --engine_dir ./bloom/560M/trt_engines/fp16/1-gpu/
[11/20/2023-19:36:17] [TRT-LLM] [I] Load tokenizer takes: 0.3652012348175049 sec
Traceback (most recent call last):
  File "/home/user/TensorRT-LLM/examples/bloom/summarize.py", line 370, in <module>
    main(args)
  File "/home/user/TensorRT-LLM/examples/bloom/summarize.py", line 97, in main
    dataset_cnn = load_dataset("ccdv/cnn_dailymail",
  File "/home/user/mambaforge/envs/venv/lib/python3.10/site-packages/datasets/load.py", line 1656, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/user/mambaforge/envs/venv/lib/python3.10/site-packages/datasets/load.py", line 1465, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/home/user/mambaforge/envs/venv/lib/python3.10/site-packages/datasets/builder.py", line 1148, in __init__
    super().__init__(*args, **kwargs)
  File "/home/user/mambaforge/envs/venv/lib/python3.10/site-packages/datasets/builder.py", line 341, in __init__
    self.info = DatasetInfo.from_directory(self._cache_dir)
  File "/home/user/mambaforge/envs/venv/lib/python3.10/site-packages/datasets/info.py", line 267, in from_directory
    return cls.from_dict(dataset_info_dict)
  File "/home/user/mambaforge/envs/venv/lib/python3.10/site-packages/datasets/info.py", line 272, in from_dict
    return cls(**{k: v for k, v in dataset_info_dict.items() if k in field_names})
  File "<string>", line 20, in __init__
  File "/home/user/mambaforge/envs/venv/lib/python3.10/site-packages/datasets/info.py", line 150, in __post_init__
    self.splits = SplitDict.from_split_dict(self.splits)
  File "/home/user/mambaforge/envs/venv/lib/python3.10/site-packages/datasets/splits.py", line 551, in from_split_dict
    split_info = SplitInfo(**split_info)
TypeError: SplitInfo.__init__() got an unexpected keyword argument 'shard_lengths'
```

**Comment by yuvraj108c** [comment]
fixed by reinstalling datasets package
