### ISSUE TITLE
Error on docker file build

### ISSUE THREAD

**Issue by robosina** [NVIDIA/TensorRT-LLM#48]
Got the following error when building the docker file, I followed the instructions written in [here](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/installation.md):

```
7145.6 [ 97%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/weightOnlyBatchedGemv/weightOnlyBatchedGemvBs3Int4b.cu.o
7159.0 [ 97%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/weightOnlyBatchedGemv/weightOnlyBatchedGemvBs3Int8b.cu.o
7175.4 [ 97%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/weightOnlyBatchedGemv/weightOnlyBatchedGemvBs4Int4b.cu.o
7175.7 [ 98%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/weightOnlyBatchedGemv/weightOnlyBatchedGemvBs4Int8b.cu.o
7507.6 [ 98%] Built target kernels_src
7507.6 [ 98%] Linking CXX static library libtensorrt_llm_static.a
7523.5 [ 98%] Built target tensorrt_llm_static
7523.5 [100%] Linking CXX shared library libtensorrt_llm.so
7523.6 /usr/bin/ld:/src/tensorrt_llm/cpp/tensorrt_llm/batch_manager/x86_64-linux-gnu/libtensorrt_llm_batch_manager_static.a: file format not recognized; treating as linker script
7523.6 /usr/bin/ld:/src/tensorrt_llm/cpp/tensorrt_llm/batch_manager/x86_64-linux-gnu/libtensorrt_llm_batch_manager_static.a:1: syntax error
7523.7 collect2: error: ld returned 1 exit status
7523.7 gmake[3]: *** [tensorrt_llm/CMakeFiles/tensorrt_llm.dir/build.make:714: tensorrt_llm/libtensorrt_llm.so] Error 1
7523.7 gmake[2]: *** [CMakeFiles/Makefile2:677: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/all] Error 2
7523.7 gmake[1]: *** [CMakeFiles/Makefile2:684: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/rule] Error 2
7523.7 gmake: *** [Makefile:179: tensorrt_llm] Error 2
7523.7 Traceback (most recent call last):
7523.7   File "/src/tensorrt_llm/scripts/build_wheel.py", line 248, in <module>
7523.7     main(**vars(args))
7523.7   File "/src/tensorrt_llm/scripts/build_wheel.py", line 152, in main
7523.7     build_run(
7523.7   File "/usr/lib/python3.10/subprocess.py", line 526, in run
7523.7     raise CalledProcessError(retcode, process.args,
7523.7 subprocess.CalledProcessError: Command 'cmake --build . --config Release --parallel 8 --target tensorrt_llm tensorrt_llm_static nvinfer_plugin_tensorrt_llm th_common ' returned non-zero exit status 2.
------
Dockerfile.multi:48
--------------------
  46 |     
  47 |     ARG BUILD_WHEEL_ARGS="--clean --trt_root /usr/local/tensorrt"
  48 | >>> RUN python3 scripts/build_wheel.py ${BUILD_WHEEL_ARGS}
  49 |     
  50 |     FROM devel as release
--------------------
ERROR: failed to solve: process "/bin/bash -c python3 scripts/build_wheel.py ${BUILD_WHEEL_ARGS}" did not complete successfully: exit code: 1
make: *** [Makefile:47: release_build] Error 1
make: Leaving directory '/saeed/openai-whisper/TensorRT-LLM/docker'
```

**Comment by LeoCeasar** [comment]
May I ask how do u fix this issue? I
 have the same promblem

**Comment by robosina** [comment]
@LeoCeasar , did you fetch the LFS files?, I mean did you follow these steps correctly?:

```
apt-get update && apt-get -y install git git-lfs

git clone https://github.com/NVIDIA/TensorRT-LLM.git
cd TensorRT-LLM
git submodule update --init --recursive
git lfs install
git lfs pull
```

If you not please do it again and then try to build again.
