### ISSUE TITLE
Issue when summarizing gpt 

### ISSUE THREAD

**Issue by jinish1991** [NVIDIA/TensorRT-LLM#509]
Getting below error when trying to build for model summarization

code/tensorrt_llm/examples/gpt# python3 build.py --world_size 8 --n_layer 96 --n_head 96 --model_dir=./c-model/gpt2/fp16/8-gpu --remove_input_padding --use_gpt_attention_plugin --enable_context_fmha --use_gemm_plugin --max_batch_size 8 --max_input_len 924 --max_output_len 100 --output_dir trt_engine/gpt2/fp16/8-gpu/ --hidden_act gelu              [11/30/2023-07:47:20] [TRT-LLM] [I] Setting model configuration from ./c-model/gpt2/fp16/8-gpu.
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/gpt/build.py", line 624, in <module>
    run_build()
  File "/code/tensorrt_llm/examples/gpt/build.py", line 600, in run_build
    args = parse_arguments(args)
  File "/code/tensorrt_llm/examples/gpt/build.py", line 311, in parse_arguments
    n_embd, n_head, n_layer, n_positions, vocab_size, _, hidden_act, rotary_pct, bias, inter_size, multi_query_mode, dtype, prompt_num_tasks, prompt_max_vocab_size = parse_ft_config(
  File "/code/tensorrt_llm/examples/gpt/weight.py", line 62, in parse_ft_config
    n_embd = gpt_config.getint('gpt', 'n_embd')
  File "/usr/lib/python3.10/configparser.py", line 820, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
  File "/usr/lib/python3.10/configparser.py", line 810, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "/usr/lib/python3.10/configparser.py", line 805, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.10/configparser.py", line 783, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.10/configparser.py", line 1154, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'gpt'

**Comment by byshiue** [comment]
Do you use the latest main branch? And what's your script to convert/generate the c model?

**Comment by jinish1991** [comment]
Hi, 
I was able to get past this issue after completely rebuilding 

Thanks
