### ISSUE TITLE
Building T5 encoder could not find any supported formats consistent with input/output data types

### ISSUE THREAD

**Issue by shannonphu** [NVIDIA/TensorRT-LLM#520]
I was trying to setup the Flan-T5 example provided here on main branch: https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/enc_dec

I downloaded the flan-t5 weights using the provided 
```
git clone https://huggingface.co/google/flan-t5-small tmp/hf_models/flan-t5-small
``` 
and ran this
```
python build.py --model_type t5 \
                --weight_dir tmp/trt_models/t5-small/tp1 \
                -o tmp/trt_engines/t5-small/1-gpu \
                --engine_name t5-small \
                --remove_input_padding \
                --use_bert_attention_plugin \
                --use_gpt_attention_plugin \
                --use_gemm_plugin \
                --use_rmsnorm_plugin \
                --dtype float32 \
                --max_beam_width 1
```

When I try to build the engine I run into an error
```
[12/01/2023-00:54:34] [TRT-LLM] [I] Setting model configuration from tmp/trt_models/t5-small/tp1.
[12/01/2023-00:54:34] [TRT-LLM] [I] use_bert_attention_plugin set, without specifying a value. Using float32 automatically.
[12/01/2023-00:54:34] [TRT-LLM] [I] use_gpt_attention_plugin set, without specifying a value. Using float32 automatically.
[12/01/2023-00:54:34] [TRT-LLM] [I] use_gemm_plugin set, without specifying a value. Using float32 automatically.
[12/01/2023-00:54:34] [TRT-LLM] [I] use_rmsnorm_plugin set, without specifying a value. Using float32 automatically.
[12/01/2023-00:54:34] [TRT-LLM] [I] Serially build TensorRT engines.
[12/01/2023-00:54:35] [TRT] [I] [MemUsageChange] Init CUDA: CPU +12, GPU +0, now: CPU 111, GPU 186 (MiB)
[12/01/2023-00:54:39] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1809, GPU +316, now: CPU 2056, GPU 502 (MiB)
[12/01/2023-00:54:39] [TRT-LLM] [W] Invalid timing cache, using freshly created one
[12/01/2023-00:54:39] [TRT-LLM] [I] Loading weights from binary...
[12/01/2023-00:54:40] [TRT-LLM] [I] Weights loaded. Total time: 00:00:00
[12/01/2023-00:54:40] [TRT-LLM] [I] Remove Padding Enabled
[12/01/2023-00:54:40] [TRT-LLM] [I] Build TensorRT engine t5-small_float32_tp1_rank0.engine
[12/01/2023-00:54:40] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 2232, GPU 678 (MiB)
[12/01/2023-00:54:40] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +1, GPU +10, now: CPU 2233, GPU 688 (MiB)
[12/01/2023-00:54:40] [TRT] [I] Global timing cache in use. Profiling results in this builder pass will be stored.
[12/01/2023-00:54:40] [TRT] [E] 9: EncoderModel/encoder_layers/0/attention/PLUGIN_V2_BertAttention_0: could not find any supported formats consistent with input/output data types
[12/01/2023-00:54:40] [TRT] [E] 9: [pluginV2Builder.cpp::reportPluginError::24] Error Code 9: Internal Error (EncoderModel/encoder_layers/0/attention/PLUGIN_V2_BertAttention_0: could not find any supported formats consistent with input/output data types)
[12/01/2023-00:54:40] [TRT-LLM] [E] Engine building failed, please check the error log.
Traceback (most recent call last):
  File "/code/TensorRT-LLM/examples/enc_dec/build.py", line 515, in <module>
    run_build(component='encoder')
  File "/code/TensorRT-LLM/examples/enc_dec/build.py", line 507, in run_build
    build(0, args)
  File "/code/TensorRT-LLM/examples/enc_dec/build.py", line 467, in build
    assert engine is not None, f'Failed to build engine for rank {cur_rank}'
AssertionError: Failed to build engine for rank 0
```

**Comment by symphonylyh** [comment]
Hi @shannonphu , first, the [README](https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/enc_dec/README.md) shows that you need to do the "Convert and split weight" step between checkpoint downloading and engine building. Second, for `flan-t5` you should change the name accordingly in your build command. The one you used is for `t5`. I would recommend following the README more closely.

**Comment by shannonphu** [comment]
Yes I did that step "Convert and split weight", did not mention it here because that was successful. You're right I had an issue with the T5 vs FLAN-T5 path thanks for pointing that out.

**Comment by symphonylyh** [comment]
@shannonphu for Flan-T5 specifically, please apply this fix locally as it's related to results accuracy: https://github.com/NVIDIA/TensorRT-LLM/issues/474#issuecomment-1853500202. Release containing this fix is coming soon, but just in case of time-sensitive scenarios.
