### ISSUE TITLE
build.py for llama7b failed with v0.6.0

### ISSUE THREAD

**Issue by flexwang** [NVIDIA/TensorRT-LLM#533]
```
python build.py --model_dir /models/llama-2-7b-chat-hf/ \
                --dtype bfloat16 \
                --use_gpt_attention_plugin bfloat16 \
                --use_inflight_batching \
                --paged_kv_cache \
                --remove_input_padding \
                --use_gemm_plugin bfloat16 \
                --output_dir /models/trt_engines/llama-2-7b-chat-hf/1-gpu/
```

I got
```
Traceback (most recent call last):
  File "/app/tensorrt_llm/examples/llama/build.py", line 780, in <module>
    build(0, args)
  File "/app/tensorrt_llm/examples/llama/build.py", line 735, in build
    profiler.check_gpt_mem_usage(
  File "/app/tensorrt_llm/tensorrt_llm/builder.py", line 48, in decorated
    return f(*args, **kwargs)
  File "/app/tensorrt_llm/tensorrt_llm/profiler.py", line 311, in check_gpt_mem_usage
    _, _, total_mem = device_memory_info(torch.cuda.current_device())
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by IzzyPutterman** [comment]
I've had this happen when pynvml isn't installed.  I could be wrong, but I believe the issue comes from this line: https://github.com/NVIDIA/TensorRT-LLM/blob/v0.6.0/tensorrt_llm/profiler.py#L240, so both psutil and pynvml need to be available.

**Comment by byshiue** [comment]
Yes, this should be caused by installation of pynvml and psutil. Please try the latest `main` branch or `0.6.1`.

**Comment by flexwang** [comment]
@byshiue 0.6.1 also doesn't work.

**Comment by byshiue** [comment]
Have you rebuild the docker image? Besides, could you try on latest main branch? It looks the `requirement-dev.txt` is only added in docker file on latest main branch.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Please reopen it if needed.
