### ISSUE TITLE
V0.6.1 LLAMA convertion does not work for fine tune model

### ISSUE THREAD

**Issue by liyu-tan** [NVIDIA/TensorRT-LLM#561]
It was working before. But after I build with the V0.6.1
I run the conversion, and I had this error:
```
Traceback (most recent call last):
  File "/home/liyu.tan/trt_12_03/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/home/liyu.tan/uber-triton-workspace/src/tensorrtllm_backend/tensorrt_llm/examples/llama/build.py", line 726, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/home/liyu.tan/uber-triton-workspace/src/tensorrtllm_backend/tensorrt_llm/examples/llama/build.py", line 574, in build_rank_engine
    load_from_hf_llama(tensorrt_llm_llama,
  File "/home/liyu.tan/uber-triton-workspace/src/tensorrtllm_backend/tensorrt_llm/examples/llama/weight.py", line 243, in load_from_hf_llama
    tensorrt_llm_llama.vocab_embedding.weight.value = v
  File "/home/liyu.tan/trt_12_03/lib/python3.10/site-packages/tensorrt_llm/parameter.py", line 84, in value
    assert v.shape == self._value.shape, \
AssertionError: The value updated is not the same shape as the original. Updated: (32002, 4096), original: (32000, 4096)
```

**Comment by oleneyl** [comment]
In my case specifying vocab size by argument (in your case maybe `--vocab_size 32002`) solved that problem.

**Comment by liyu-tan** [comment]
Hm.. That worked for me! Thanks! But do we change anything recently? I was converting by a previous version, seems working without need to change anything

**Comment by oleneyl** [comment]
I think [this change](https://github.com/NVIDIA/TensorRT-LLM/pull/524/files#diff-258ea12cc3914f3a76eab633fe5e30d27883b2d023bcaefd806725d9d8841f3dL439-L443) corrected bug that not using `hf_config.vocab_size` since `arg.vocab_size` has default value(32k). Maybe built by previous version(0.5.0) without specified vocab size had not been utilized tokens with id larger than 32k.. I'm not confident about this guess, however only change in `build.py` related with vocab_size is that line.
