### ISSUE TITLE
Cannot convertion the llama2 model in v0.6.0

### ISSUE THREAD

**Issue by liyu-tan** [NVIDIA/TensorRT-LLM#572]
I got errors like this:
```
Traceback (most recent call last):
  File "/home/liyu.tan/uber-triton-workspace/src/tensorrtllm_backend/tensorrt_llm/examples/llama/build.py", line 776, in <module>
    mp.spawn(build, nprocs=args.world_size, args=(args, ))
  File "/home/liyu.tan/uber-triton-workspace/trt_12_05/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 246, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/home/liyu.tan/uber-triton-workspace/trt_12_05/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 202, in start_processes
    while not context.join():
  File "/home/liyu.tan/uber-triton-workspace/trt_12_05/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 163, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/liyu.tan/uber-triton-workspace/trt_12_05/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/home/liyu.tan/uber-triton-workspace/src/tensorrtllm_backend/tensorrt_llm/examples/llama/build.py", line 735, in build
    profiler.check_gpt_mem_usage(
  File "/home/liyu.tan/uber-triton-workspace/trt_12_05/lib/python3.10/site-packages/tensorrt_llm/builder.py", line 48, in decorated
    return f(*args, **kwargs)
  File "/home/liyu.tan/uber-triton-workspace/trt_12_05/lib/python3.10/site-packages/tensorrt_llm/profiler.py", line 311, in check_gpt_mem_usage
    _, _, total_mem = device_memory_info(torch.cuda.current_device())
TypeError: cannot unpack non-iterable NoneType object```

**Comment by flexwang** [comment]
I think you need to `pip install pynvml==14.1.0`

**Comment by byshiue** [comment]
Please take a try on latest main branch.

**Comment by flexwang** [comment]
@byshiue it shouldn't work since `pynvml` is not in the requirements.txt: https://github.com/triton-inference-server/tensorrtllm_backend/blob/171ed05830ff7e0a8057134f08802c7e3044b7b3/requirements.txt

**Comment by sc-gr** [comment]
The error happens because [this function](https://github.com/NVIDIA/TensorRT-LLM/blob/9b3e12dbc820a8b72bcd7d712a8c9a54facf97df/tensorrt_llm/profiler.py#L252C27-L254) returns None (because`pynvml` is not installed by default). This happens if you use `v0.6.0` and `v0.6.1` tags, but in the main branch this function has default values, even if `pynvml` is None: https://github.com/NVIDIA/TensorRT-LLM/blob/42af740db51d6f11442fd5509ef745a4c043ce51/tensorrt_llm/profiler.py#L150 

So the workaround is to either use `v0.6.1`/`v0.6.0` + install pynvml or use main branch (I haven't tested this myself though)

@byshiue is it recommended to use tag `v0.6.1` or `main` branch for TRT-LLM and triton backend for now?

**Comment by HuChundong** [comment]
> The error happens because [this function](https://github.com/NVIDIA/TensorRT-LLM/blob/9b3e12dbc820a8b72bcd7d712a8c9a54facf97df/tensorrt_llm/profiler.py#L252C27-L254) returns None (because`pynvml` is not installed by default). This happens if you use `v0.6.0` and `v0.6.1` tags, but in the main branch this function has default values, even if `pynvml` is None:
> 
> https://github.com/NVIDIA/TensorRT-LLM/blob/42af740db51d6f11442fd5509ef745a4c043ce51/tensorrt_llm/profiler.py#L150
> 
> So the workaround is to either use `v0.6.1`/`v0.6.0` + install pynvml or use main branch (I haven't tested this myself though)
> 
> @byshiue is it recommended to use tag `v0.6.1` or `main` branch for TRT-LLM and triton backend for now?

main branch could not build in windows.

**Comment by liyu-tan** [comment]
Got it. Will install pynvml instead.
```pip install pynvml==14.1.0```
this is not working for me. I use `pip install pynvml` instead
