### ISSUE TITLE
Python Benchmark Tensor Name Error When Adding "engine_dir" Option 

### ISSUE THREAD

**Issue by taozhang9527** [NVIDIA/TensorRT-LLM#574]
Knowing that C++ benchmark is recommended, but it would be nice to have the python script working as it is easier to use. It used to work fine with the following command:
`python benchmarks/python/benchmark.py --model llama_7b --mode plugin --batch_size "64" --input_output_len "512, 200" --engine_dir examples/llama/out/7b/fp16_1gpu`

The results look reasonable compared to [the official results](https://nvidia.github.io/TensorRT-LLM/performance.html). However, I am not sure if there was some code change recently or what, the latest code does not work any more with `--engine_dir examples/llama/out/7b/fp16_1gpu`, with tensor name mismatch error:
```
[12/05/2023-23:50:35] [TRT-LLM] [E] The following expected tensors are not found: {'past_key_value_16', 'present_key_value_31', 'present_key_value_10', 'present_key_value_5', 'past_key_value_24', 'present_key_value_14', 'present_key_valu
e_16', 'past_key_value_4', 'present_key_value_6', 'past_key_value_6', 'past_key_value_28', 'present_key_value_18', 'present_key_value_29', 'present_key_value_13', 'past_key_value_7', 'present_key_value_17', 'past_key_value_18', 'present_
key_value_23', 'past_key_value_3', 'past_key_value_10', 'past_key_value_30', 'present_key_value_15', 'past_key_value_22', 'past_key_value_25', 'past_key_value_15', 'present_key_value_1', 'present_key_value_22', 'past_key_value_11', 'past
_key_value_1', 'present_key_value_24', 'past_key_value_19', 'present_key_value_2', 'past_key_value_20', 'past_key_value_31', 'present_key_value_25', 'present_key_value_28', 'past_key_value_27', 'present_key_value_27', 'past_key_value_23'
, 'present_key_value_3', 'past_key_value_0', 'past_key_value_5', 'past_key_value_13', 'past_key_value_8', 'present_key_value_8', 'past_key_value_12', 'past_key_value_21', 'past_key_value_17', 'past_key_value_26', 'present_key_value_21',
'present_key_value_30', 'past_key_value_9', 'present_key_value_0', 'present_key_value_7', 'past_key_value_2', 'present_key_value_4', 'present_key_value_11', 'present_key_value_12', 'present_key_value_19', 'past_key_value_14', 'present_key_value_20', 'present_key_value_9', 'past_key_value_29', 'present_key_value_26'}
[12/05/2023-23:50:35] [TRT-LLM] [E] Those tensors in engine are not expected: {'kv_cache_block_pointers_28', 'kv_cache_block_pointers_9', 'kv_cache_block_pointers_22', 'kv_cache_block_pointers_1', 'kv_cache_block_pointers_15', 'kv_cache_block_pointers_5', 'kv_cache_block_pointers_25', 'kv_cache_block_pointers_17', 'kv_cache_block_pointers_4', 'kv_cache_block_pointers_0', 'kv_cache_block_pointers_26', 'kv_cache_block_pointers_2', 'kv_cache_block_pointers_16', 'kv_cache_block_pointers_6', 'kv_cache_block_pointers_13', 'kv_cache_block_pointers_12', 'kv_cache_block_pointers_3', 'kv_cache_block_pointers_10', 'kv_cache_block_pointers_23', 'kv_cache_block_pointers_11', 'kv_cache_block_pointers_14', 'kv_cache_block_pointers_19', 'kv_cache_block_pointers_31', 'kv_cache_block_pointers_8', 'kv_cache_block_pointers_20', 'kv_cache_block_pointers_29', 'kv_cache_block_pointers_7', 'kv_cache_block_pointers_21', 'kv_cache_block_pointers_24', 'kv_cache_block_pointers_18', 'kv_cache_block_pointers_27', 'kv_cache_block_pointers_30'}
[12/05/2023-23:50:35] [TRT-LLM] [E] Expected tensor names: ['input_ids', 'logits', 'last_token_ids', 'position_ids', 'cache_indirection', 'past_key_value_0', 'past_key_value_1', 'past_key_value_2', 'past_key_value_3', 'past_key_value_4', 'past_key_value_5', 'past_key_value_6', 'past_key_value_7', 'past_key_value_8', 'past_key_value_9', 'past_key_value_10', 'past_key_value_11', 'past_key_value_12', 'past_key_value_13', 'past_key_value_14', 'past_key_value_15', 'past_key_value_16', 'past_key_value_17', 'past_key_value_18', 'past_key_value_19', 'past_key_value_20', 'past_key_value_21', 'past_key_value_22', 'past_key_value_23', 'past_key_value_24', 'past_key_value_25', 'past_key_value_26', 'past_key_value_27', 'past_key_value_28', 'past_key_value_29', 'past_key_value_30', 'past_key_value_31', 'present_key_value_0', 'present_key_value_1', 'present_key_value_2', 'present_key_value_3', 'present_key_value_4', 'present_key_value_5', 'present_key_value_6', 'present_key_value_7', 'present_key_value_8', 'present_key_value_9', 'present_key_value_10', 'present_key_value_11', 'present_key_value_12', 'present_key_value_13', 'present_key_value_14', 'present_key_value_15', 'present_key_value_16', 'present_key_value_17', 'present_key_value_18', 'present_key_value_19', 'present_key_value_20', 'present_key_value_21', 'present_key_value_22', 'present_key_value_23', 'present_key_value_24', 'present_key_value_25', 'present_key_value_26', 'present_key_value_27', 'present_key_value_28', 'present_key_value_29', 'present_key_value_30', 'present_key_value_31', 'sequence_length', 'context_lengths', 'host_request_types', 'host_past_key_value_lengths', 'host_context_lengths']
[12/05/2023-23:50:35] [TRT-LLM] [E] Found tensor names: ['input_ids', 'position_ids', 'kv_cache_block_pointers_0', 'kv_cache_block_pointers_1', 'kv_cache_block_pointers_2', 'kv_cache_block_pointers_3', 'kv_cache_block_pointers_4', 'kv_cache_block_pointers_5', 'kv_cache_block_pointers_6', 'kv_cache_block_pointers_7', 'kv_cache_block_pointers_8', 'kv_cache_block_pointers_9', 'kv_cache_block_pointers_10', 'kv_cache_block_pointers_11', 'kv_cache_block_pointers_12', 'kv_cach
e_block_pointers_13', 'kv_cache_block_pointers_14', 'kv_cache_block_pointers_15', 'kv_cache_block_pointers_16', 'kv_cache_block_pointers_17', 'kv_cache_block_pointers_18', 'kv_cache_block_pointers_19', 'kv_cache_block_pointers_20', 'kv_c
ache_block_pointers_21', 'kv_cache_block_pointers_22', 'kv_cache_block_pointers_23', 'kv_cache_block_pointers_24', 'kv_cache_block_pointers_25', 'kv_cache_block_pointers_26', 'kv_cache_block_pointers_27', 'kv_cache_block_pointers_28', 'k
v_cache_block_pointers_29', 'kv_cache_block_pointers_30', 'kv_cache_block_pointers_31', 'sequence_length', 'host_request_types', 'host_past_key_value_lengths', 'context_lengths', 'host_context_lengths', 'last_token_ids', 'cache_indirecti
on', 'logits']
Traceback (most recent call last):
  File "/code/tensorrt_llm/benchmarks/python/benchmark.py", line 322, in <module>
    main(args)
  File "/code/tensorrt_llm/benchmarks/python/benchmark.py", line 219, in main
    benchmarker = GPTBenchmark(
  File "/code/tensorrt_llm/benchmarks/python/gpt_benchmark.py", line 173, in __init__
    self.decoder = tensorrt_llm.runtime.GenerationSession(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 430, in __init__
    raise RuntimeError(
RuntimeError: Tensor names in engine are not the same as expected, to use this GenerationSession, you need to use GPTLMHeadModel.prepare_inputs to create TRT Network inputs.
```
Without defining engine file, it (`python benchmarks/python/benchmark.py --model llama_7b --mode plugin --batch_size "64" --input_output_len "512, 200"`) works fine.

**Comment by byshiue** [comment]
When you run on latest code, have you rebuild the engine based on the latest code?

**Comment by taozhang9527** [comment]
Yes, I rebuilt the docker image but I didn't rebuild the engine. Do I have to re-build the engine?

**Comment by byshiue** [comment]
Yes. You should rebuild the engine.

**Comment by taozhang9527** [comment]
Rebuilding the engine resolved the issue. 
Does this mean that we have to rebuild the engine every time we pull the latest updates? What is the best practice here? Building the engine for 70b is time-consuming. Any parallel option I can add into the build command for speeding it up?

**Comment by byshiue** [comment]
It is recommanded to rebuild the engine when you update the codes. Different I/O, workspace, parameters would lead to error. Also, we may upgrade the tensorrt version in newer branch, and an engine bulit on old trt version cannot be run on newer trt version. 

For engine building time, please share your scripts to build engine.

**Comment by taozhang9527** [comment]
` python examples/llama/build.py --model_dir ./Llama-2-70b-chat-hf --quant_ckpt_path ./Llama-2-70b-chat-hf_gptq/llama-70b-4bit-gs128.safetensors  --dtype float16 --remove_input_padding --use_gpt_attention_plugin float16              --enable_context_fmha  --use_gemm_plugin float16  --use_weight_only  --weight_only_precision int4_gptq --per_group                 --enable_context_fmha   --world_size 4  --tp_size 4  --output_dir ./examples/llama/out/70b/gptq_4gpu`

I don't know if there is 1 GPU or 4GPUs participating in the building process.

**Comment by byshiue** [comment]
How many time are taken for engine building?

**Comment by taozhang9527** [comment]
It took ~ 45mins for 4 H100 GPUs build.

**Comment by byshiue** [comment]
You could try adding `--parallel_build`.

**Comment by taozhang9527** [comment]
Verified with the latest` 0.7.1` release and `23.11-trtllm-python-py3` triton image. Parallel build works with the GPU number equals to TP settings. For example, if TP=2, even I have 8 GPUs, it will use 2 GPUs instead of 8 for the building process. The building process in the latest release seems much faster. 
I think we can close the ticket. No further question.

**Comment by YanfeiDai** [comment]
Hi, I met the same issue. The error code was like RuntimeError: Tensor names in engine are not the same as expected, to use this GenerationSession, you need to use PretrainedModel.prepare_inputs to create TRT Network inputs.
    self.decoder = tensorrt_llm.runtime.GenerationSession(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 861, in __init__
    raise RuntimeError(
RuntimeError: Tensor names in engine are not the same as expected, to use this GenerationSession, you need to use PretrainedModel.prepare_inputs to create TRT Network inputs. My version is as belowsNVIDIA-SMI 555.42.06              Driver Version: 555.42.06      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        Off |   00000000:21:00.0 Off |                  Off |
| 30%   37C    P0             76W /  480W |       1MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 4090        Off |   00000000:22:00.0 Off |                  Off |
| 30%   40C    P0             78W /  450W |       1MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA GeForce RTX 4090        Off |   00000000:41:00.0 Off |                  Off |
| 30%   34C    P0             78W /  480W |       1MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA GeForce RTX 4090        Off |   00000000:42:00.0 Off |                  Off |
| 30%   35C    P0             74W /  480W |       1MiB /  24564MiB |      2%      Default |
|                                         |                        |                  N/A   and my tensorrt is the lastest version. Appreciate if you could help me !
