### ISSUE TITLE
Error LLaMAForCausalLM/layers/0/attention/PLUGIN_V2_GPTAttention_0:

### ISSUE THREAD

**Issue by moseshu** [NVIDIA/TensorRT-LLM#582]
```
python build.py --model_dir Mistral-7B-Instruct-v0.1 \
                --dtype bfloat16 \
                --use_gpt_attention_plugin bfloat16 \
                --use_inflight_batching \
                --paged_kv_cache \
                --remove_input_padding \
                --use_gemm_plugin bfloat16 \
                --output_dir saved/1-gpu/
```
I got this error. 
the main branch tensorRT-LLM ,it does not support "use_inflight_batching"?
```
LLaMAForCausalLM/layers/0/attention/PLUGIN_V2_GPTAttention_0: could not find any supported formats consistent with input/output data types
[12/06/2023-05:15:03] [TRT] [E] 9: [pluginV2Builder.cpp::reportPluginError::24] Error Code 9: Internal Error (LLaMAForCausalLM/layers/0/attention/PLUGIN_V2_GPTAttention_0: could not find any supported formats consistent with input/output data types)
[12/06/2023-05:15:03] [TRT-LLM] [E] Engine building failed, please check the error log.
[12/06/2023-05:15:03] [TRT-LLM] [I] Config saved to saved/1-gpu/config.json.
Traceback (most recent call last):
  File "/root/workspace/llama/build.py", line 839, in <module>
    build(0, args)
  File "/root/workspace/llama/build.py", line 785, in build
    assert engine is not None, f'Failed to build engine for rank {cur_rank}'
AssertionError: Failed to build engine for rank 0
```

**Comment by byshiue** [comment]
Can you share the branch you use? If you don't use the latest main branch, please take a try.

**Comment by moseshu** [comment]
thanks. it's wrong with branch. I change it to the v0.7.1 or v0.6.1. it works well
