### ISSUE TITLE
Expected Output For Run.py Script Of 0.6.1 Release

### ISSUE THREAD

**Issue by taozhang9527** [NVIDIA/TensorRT-LLM#636]
run.py script used to be under each example folder in 0.5 release. In the latest 0.6.1 release, the script seems to be consolidated and put under the example folder. When I use the script to test 70b Llama model with the following command:
` python examples/run.py --max_output_len=50 --tokenizer_dir Llama-2-70b-chat-hf --engine_dir examples/llama/out/70b/gptq_1gpu/`,

I got the following output:
```
Input [Text 0]: "<s> Born in north-east France, Soyer trained as a"
Output [Text 0 Beam 0]: "lllllllll111111111111111111111111111111111111111111111"
```
The output text is not decoded, and seems not make sense. Could you check if that is expected?

**Comment by QiJune** [comment]
Could you please share your build command? How many GPUs are you using?

**Comment by taozhang9527** [comment]
` python examples/llama/build.py --model_dir ./Llama-2-70b-chat-hf --quant_ckpt_path ./Llama-2-70b-chat-hf_gptq/llama-70b-4bit-gs128.safetensors  --dtype float16 --remove_input_padding --use_gpt_attention_plugin float16              --enable_context_fmha  --use_gemm_plugin float16  --use_weight_only  --weight_only_precision int4_gptq --per_group                 --enable_context_fmha  --output_dir ./examples/llama/out/70b/gptq_1gpu `

Both 1 GPU and 4 GPUs gave the same "11111.." result.

**Comment by QiJune** [comment]
@Tracin  Could you please take a look?  Also cc @RalphMao

**Comment by Tracin** [comment]
I think it is nothing to do with inference, GPTQ algorithm fails on this specific model. I can reproduce the bad accuracy on Llama-2-7b-chat-hf but normal accuracy on Llama-7b-hf. How about try INT4-AWQ

**Comment by taozhang9527** [comment]
For Llama-2-7b-chat-hf AWQ, single GPU scenario gave me reasonable output, but 4 GPU case gave me the following error:

```
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/run.py", line 376, in <module>
    main(args)
  File "/code/tensorrt_llm/examples/run.py", line 266, in main
    model_name = read_model_name(args.engine_dir)
  File "/code/tensorrt_llm/examples/utils.py", line 54, in read_model_name
    engine_version = tensorrt_llm.builder.get_engine_version(engine_dir)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/builder.py", line 515, in get_engine_version
    with open(config_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'examples/llama/out/7b/awq_4gpu/config.json'
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/run.py", line 376, in <module>
    main(args)
  File "/code/tensorrt_llm/examples/run.py", line 266, in main
    model_name = read_model_name(args.engine_dir)
  File "/code/tensorrt_llm/examples/utils.py", line 54, in read_model_name
    engine_version = tensorrt_llm.builder.get_engine_version(engine_dir)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/builder.py", line 515, in get_engine_version
    with open(config_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'examples/llama/out/7b/awq_4gpu/config.json'
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/run.py", line 376, in <module>
    main(args)
  File "/code/tensorrt_llm/examples/run.py", line 266, in main
    model_name = read_model_name(args.engine_dir)
  File "/code/tensorrt_llm/examples/utils.py", line 54, in read_model_name
    engine_version = tensorrt_llm.builder.get_engine_version(engine_dir)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/builder.py", line 515, in get_engine_version
    with open(config_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'examples/llama/out/7b/awq_4gpu/config.json'
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/run.py", line 376, in <module>
    main(args)
  File "/code/tensorrt_llm/examples/run.py", line 266, in main
    model_name = read_model_name(args.engine_dir)
  File "/code/tensorrt_llm/examples/utils.py", line 54, in read_model_name
    engine_version = tensorrt_llm.builder.get_engine_version(engine_dir)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/builder.py", line 515, in get_engine_version
    with open(config_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'examples/llama/out/7b/awq_4gpu/config.json'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[52910,1],2]
  Exit code:    1
--------------------------------------------------------------------------
```
Command:
`mpirun -n 4 --allow-run-as-root python examples/run.py --max_output_len=50 --tokenizer_dir Llama-2-7b-chat-hf --engine_dir examples/llama/out/7b/awq_4gpu/`

**Comment by Tracin** [comment]
Did you give the correct `--engine_dir` path? Please check.

**Comment by taozhang9527** [comment]
Yes, the -`-engine_dir` path is correct.

**Comment by Tracin** [comment]
> Yes, the -`-engine_dir` path is correct.

Sorry, still can not reproduce the error. The error means no `config.json` under that folder, it is very unlikely to be lack of that file if the `engine_dir` is correct.
May be have another try with v0.7.0?
