### ISSUE TITLE
TypeError: Expected numpy.ndarray or torch.Tensor, got <class 'NoneType'>

### ISSUE THREAD

**Issue by Kevinddddddd** [NVIDIA/TensorRT-LLM#653]
I want to build a baichuan2 engine and encounter the following errors:
`
Traceback (most recent call last):
  File "/tensorrtllm_backend/tensorrt_llm/examples/baichuan/build.py", line 579, in <module>
    build(0, args)
  File "/tensorrtllm_backend/tensorrt_llm/examples/baichuan/build.py", line 548, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/tensorrtllm_backend/tensorrt_llm/examples/baichuan/build.py", line 434, in build_rank_engine
    load_from_binary(tensorrt_llm_baichuan,
  File "/tensorrtllm_backend/tensorrt_llm/examples/baichuan/weight.py", line 357, in load_from_binary
    set_smoothquant_scale_factors(
  File "/tensorrtllm_backend/tensorrt_llm/examples/baichuan/weight.py", line 272, in set_smoothquant_scale_factors
    module.per_channel_scale.value = t
  File "/app/tensorrt_llm/tensorrt_llm/parameter.py", line 83, in value
    v = self._regularize_value(v)
  File "/app/tensorrt_llm/tensorrt_llm/parameter.py", line 98, in _regularize_value
    raise TypeError(
TypeError: Expected numpy.ndarray or torch.Tensor, got <class 'NoneType'>
`

First, I build the docker image using tag v0.6.1:
`
git clone https://github.com/triton-inference-server/tensorrtllm_backend.git
cd tensorrtllm_backend
git lfs install
git submodule update --init --recursive
DOCKER_BUILDKIT=1 docker build -t triton_trt_llm -f dockerfile/Dockerfile.trt_llm_backend .
`

Second, I convert the HF model:
`
python hf_baichuan_convert.py --o /tensorrtllm_backend/output_model/bin_model \
        -i /tensorrtllm_backend/baichuan2-chat-mt-v2 \
        -p 32 \
        -sq 0.8 \
        -t fp16
`

Third, I buil the engine:
`
python build.py --world_size 1 \
                --bin_model_dir /tensorrtllm_backend/output_model/bin_model/1-gpu \
                --model_version v2_7b \
                --dtype float16 \
                --max_batch_size 128 \
                --max_input_len 128 \
                --max_output_len 128 \
                --use_gpt_attention_plugin float16 \
                --use_gemm_plugin float16 \
                --output_dir /tensorrtllm_backend/tensorrt_llm/output_model \
                --remove_input_padding \
                --use_inflight_batching \
                --paged_kv_cache \
                --use_smooth_quant
`

**Comment by Tracin** [comment]
Please add `--per_token --per_channel` for smoothquant when building.

**Comment by Kevinddddddd** [comment]
> Please add `--per_token --per_channel` for smoothquant when building.

Thanks.
