### ISSUE TITLE
Triton server test with tensorrtllm as backend HTTP end point doesn't support models with decoupled transaction policy

### ISSUE THREAD

**Issue by SDcodehub** [NVIDIA/TensorRT-LLM#677]
building model with tensorrt-llm with following command

`
python3 examples/llama/build.py \
    --model_dir meta-llama/Llama-2-7b-chat-hf \
    --dtype float16 \
    --use_gpt_attention_plugin float16 \
    --use_gemm_plugin float16 \
    --remove_input_padding \
    --use_inflight_batching \
    --paged_kv_cache \
    --output_dir examples/llama/out
`

running following commands to build the config files
`
```
python3 tools/fill_template.py --in_place \
      all_models/inflight_batcher_llm/tensorrt_llm/config.pbtxt \
      decoupled_mode:true,engine_dir:/all_models/inflight_batcher_llm/tensorrt_llm/1,\
max_tokens_in_paged_kv_cache:,batch_scheduler_policy:guaranteed_completion,kv_cache_free_gpu_mem_fraction:0.2,\
max_num_sequences:4
 
python tools/fill_template.py --in_place \
    all_models/inflight_batcher_llm/preprocessing/config.pbtxt \
    tokenizer_type:llama,tokenizer_dir:meta-llama/Llama-2-7b-chat-hf
 
python tools/fill_template.py --in_place \
    all_models/inflight_batcher_llm/postprocessing/config.pbtxt \
    tokenizer_type:llama,tokenizer_dir:meta-llama/Llama-2-7b-chat-hf
```
`

made some changes to test.sh script to accomodate the llama model and built model
getting following error
`
```
++ curl -s -w '%{http_code}' localhost:8000/v2/health/ready
+ code=200
+ set -e
+ '[' 200 == 200 ']'
+ return
+ '[' 0 '!=' 0 ']'
+ set -e
+ python3 /tensorrtllm_backend/tools/inflight_batcher_llm/identity_test.py --max_input_len=500 --dataset=/tensorrtllm_backend/ci/L0_backend_trtllm/simple_data.json --tokenizer_dir=/data/data/models/Llama-2-7b-chat-hf/
Tokens per word: 1.496
[INFO] Warm up for benchmarking.
Traceback (most recent call last):
File "/tensorrtllm_backend/tools/inflight_batcher_llm/identity_test.py", line 236, in <module>
test_performance(client, input_start_ids, input_lens, output_lens, FLAGS)
File "/tensorrtllm_backend/tools/inflight_batcher_llm/identity_test.py", line 45, in test_performance
client.infer(model_name, inputs, request_id=str(i))
File "/usr/local/lib/python3.10/dist-packages/tritonclient/http/_client.py", line 1468, in infer
_raise_if_error(response)
File "/usr/local/lib/python3.10/dist-packages/tritonclient/http/_utils.py", line 69, in _raise_if_error
raise error
tritonclient.utils.InferenceServerException: [400] HTTP end point doesn't support models with decoupled transaction policy
```
`

what does this means , how can I resolve this?

where can I read bout decoupled model and info related to it and other options

**Comment by byshiue** [comment]
decoupled mode is not supported on HTTP, please the triton document https://github.com/triton-inference-server/server/blob/main/docs/user_guide/decoupled_models.md#running-inference-on-decoupled-models.
