### ISSUE TITLE
Try to build Trt-llm engine on other models (Aside from currently supported models)

### ISSUE THREAD

**Issue by THU-mjx** [NVIDIA/TensorRT-LLM#684]
Our team are trying to implement end-to-end deployment on a newly reported model.
We added a new tensor "lfa_idx" and deleted "position_ids". We used the trt-llm-0.5.0-release to successfully build our engine, but found some errors while testing it. Do you know where I can add or change the "Expected tensor names"?
```
[12/18/2023-00:29:32] [TRT-LLM] [E] Expected tensor names: ['input_ids', 'logits', 'last_token_ids', 'position_ids', 'cache_indirection', 'past_key_value_0', 'past_key_value_1', 'past_key_value_2', 'past_key_value_3', 'past_key_value_4', 'past_key_value_5', 'past_key_value_6', 'past_key_value_7', 'past_key_value_8', 'past_key_value_9', 'past_key_value_10', 'past_key_value_11', 'past_key_value_12', 'past_key_value_13', 'past_key_value_14', 'past_key_value_15', 'past_key_value_16', 'past_key_value_17', 'past_key_value_18', 'past_key_value_19', 'past_key_value_20', 'past_key_value_21', 'past_key_value_22', 'past_key_value_23', 'present_key_value_0', 'present_key_value_1', 'present_key_value_2', 'present_key_value_3', 'present_key_value_4', 'present_key_value_5', 'present_key_value_6', 'present_key_value_7', 'present_key_value_8', 'present_key_value_9', 'present_key_value_10', 'present_key_value_11', 'present_key_value_12', 'present_key_value_13', 'present_key_value_14', 'present_key_value_15', 'present_key_value_16', 'present_key_value_17', 'present_key_value_18', 'present_key_value_19', 'present_key_value_20', 'present_key_value_21', 'present_key_value_22', 'present_key_value_23', 'sequence_length', 'context_lengths', 'host_request_types', 'host_past_key_value_lengths']
[12/18/2023-00:29:32] [TRT-LLM] [E] Found tensor names: ['input_ids', 'lfa_idx', 'past_key_value_0', 'past_key_value_1', 'past_key_value_2', 'past_key_value_3', 'past_key_value_4', 'past_key_value_5', 'past_key_value_6', 'past_key_value_7', 'past_key_value_8', 'past_key_value_9', 'past_key_value_10', 'past_key_value_11', 'past_key_value_12', 'past_key_value_13', 'past_key_value_14', 'past_key_value_15', 'past_key_value_16', 'past_key_value_17', 'past_key_value_18', 'past_key_value_19', 'past_key_value_20', 'past_key_value_21', 'past_key_value_22', 'past_key_value_23', 'sequence_length', 'host_request_types', 'host_past_key_value_lengths', 'context_lengths', 'last_token_ids', 'cache_indirection', 'present_key_value_0', 'present_key_value_1', 'present_key_value_2', 'present_key_value_3', 'present_key_value_4', 'present_key_value_5', 'present_key_value_6', 'present_key_value_7', 'present_key_value_8', 'present_key_value_9', 'present_key_value_10', 'present_key_value_11', 'present_key_value_12', 'present_key_value_13', 'present_key_value_14', 'present_key_value_15', 'present_key_value_16', 'present_key_value_17', 'present_key_value_18', 'present_key_value_19', 'present_key_value_20', 'present_key_value_21', 'present_key_value_22', 'present_key_value_23', 'logits']
Traceback (most recent call last):
  File "/temp_data/TensorRT-LLM/examples/yuan/run.py", line 269, in <module>
    generate(**vars(args))
  File "/temp_data/TensorRT-LLM/examples/yuan/run.py", line 233, in generate
    decoder = tensorrt_llm.runtime.GenerationSession(model_config,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 430, in __init__
    raise RuntimeError(
RuntimeError: Tensor names in engine are not the same as expected, to use this GenerationSession, you need to use GPTLMHeadModel.prepare_inputs to create TRT Network inputs.
```

**Comment by byshiue** [comment]
The error is throwed here https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/runtime/generation.py#L606-L619, and you could add your input above the codes like other inputs.

**Comment by Hukongtao** [comment]
> The error is throwed here https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/runtime/generation.py#L606-L619, and you could add your input above the codes like other inputs.

Hi， I build the engine with --enable_debug_output. But when I run my engine, it would throw this error if I didn't set --debug_mode. Do you know why?

**Comment by byshiue** [comment]
> > The error is throwed here https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/runtime/generation.py#L606-L619, and you could add your input above the codes like other inputs.
> 
> Hi， I build the engine with --enable_debug_output. But when I run my engine, it would throw this error if I didn't set --debug_mode. Do you know why?

If you enable the `--enable_debug_output`, TRT-LLM will add many output automatically, and hence you need to setup the buffers of these output tensors. `--debug_mode` will setup these output tensors automatically.
