### ISSUE TITLE
Error when building Mixtral-7b-instruct weight-only engine with LORA

### ISSUE THREAD

**Issue by ZihanLiao** [NVIDIA/TensorRT-LLM#697]
When building mixtral gpt model with LORA, I met the following error. Seems like a misuse of tensor.transpose(). I've build successfully mixtral gpt without LORA .

Building script

```
python build.py --model_dir ./Mistral-7B-Instruct-v0.1 \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --load_by_shard \
                --paged_kv_cache \
                --max_input_len 32256 \
                --use_weight_only \
                --use_lora_plugin float16 \
                --hf_lora_dir ./mistral_7b_finetune-human-results-85k-prompt-v2-epochs5 \
                --output_dir ./Mistral-7B-Instruct-v0.1/trt_engines/weight_only_lora_finetune-human-results-85k-prompt-v2-epochs5/1-gpu
```

Error

```
root@cc5127988eed:/code/tensorrt_llm/examples/llama# sh build_int8_lora.sh 
[12/19/2023-06:09:51] [TRT-LLM] [W] Found pynvml==11.4.1. Please use pynvml>=11.5.0 to get accurate memory usage
You are using a model of type mistral to instantiate a model of type llama. This is not supported for all configurations of models and can yield errors.
[12/19/2023-06:09:52] [TRT-LLM] [I] Serially build TensorRT engines.
[12/19/2023-06:09:52] [TRT] [I] [MemUsageChange] Init CUDA: CPU +1, GPU +0, now: CPU 125, GPU 1048 (MiB)
[12/19/2023-06:09:54] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1974, GPU +350, now: CPU 2235, GPU 1398 (MiB)
[12/19/2023-06:09:54] [TRT-LLM] [W] Invalid timing cache, using freshly created one
[12/19/2023-06:09:54] [TRT-LLM] [I] [MemUsage] Rank 0 Engine build starts - Allocated Memory: Host 2.7129 (GiB) Device 2.2151 (GiB)
[12/19/2023-06:10:06] [TRT-LLM] [I] Loading HF LLaMA ... from ./Mistral-7B-Instruct-v0.1
[12/19/2023-06:10:06] [TRT-LLM] [I] Loading weights from HF LLaMA...
<class 'torch.Tensor'>
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/llama/build.py", line 839, in <module>
    build(0, args)
  File "/code/tensorrt_llm/examples/llama/build.py", line 783, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/code/tensorrt_llm/examples/llama/build.py", line 631, in build_rank_engine
    load_from_hf_checkpoint(tensorrt_llm_llama,
  File "/code/tensorrt_llm/examples/llama/weight.py", line 523, in load_from_hf_checkpoint
    param = split_v.transpose()
TypeError: transpose() received an invalid combination of arguments - got (), but expected one of:
 * (int dim0, int dim1)
 * (name dim0, name dim1)
```

Env version: tensorrt_llm/0.6.1

**Comment by manarshehadeh** [comment]
@ZihanLiao did you figure out the issue here? running into issues as well building a Mixtral engine with Lora.
