### ISSUE TITLE
AWQ quantisation using NVIDIA AMMO toolkit, invalid file name:

### ISSUE THREAD

**Issue by SDcodehub** [NVIDIA/TensorRT-LLM#709]
following https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama

using - `python ./examples/llama/quantize.py --model_dir /mnt/Llama-2-7b-chat-hf/ --dtype float16 --qformat int4_awq --export_path /code/quantized_int4-awq/ --calib_size 32`

running in docker container, used make file to create and run the container

```
root@BD-MUM-NLPGPU1-release:/code/tensorrt_llm# python ./examples/llama/quantize.py --model_dir /mnt/Llama-2-7b-chat-hf/ --dtype float16 --qformat int4_awq --export_path /code/quantized_int4-awq/ --calib_size 32
[NeMo W 2023-12-20 11:55:38 nemo_logging:349] /usr/local/lib/python3.10/dist-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

WARNING: Logging before flag parsing goes to stderr.
W1220 11:55:40.234147 139977810834048 modeling.py:706] The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00, 1.01s/it]
Loading calibration dataset
[NeMo W 2023-12-20 11:55:47 nemo_logging:349] /usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:2411: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
warnings.warn(

Replaced 675 modules to quantized modules
Caching activation statistics for awq_lite...
Searching awq_lite parameters...
[NeMo W 2023-12-20 11:56:07 nemo_logging:349] /usr/local/lib/python3.10/dist-packages/ammo/torch/quantization/nn/modules/tensor_quantizer.py:153: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
self.register_buffer("_pre_quant_scale", torch.tensor(value))

Loading extension ammo_cuda_ext...
Loading extension ammo_cuda_ext_fp8...
[NeMo W 2023-12-20 11:56:07 nemo_logging:349] /usr/local/lib/python3.10/dist-packages/ammo/torch/quantization/nn/modules/tensor_quantizer.py:155: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
value = torch.tensor(value, device=self._pre_quant_scale.device)

[NeMo W 2023-12-20 11:56:07 nemo_logging:349] /usr/local/lib/python3.10/dist-packages/ammo/torch/quantization/nn/modules/tensor_quantizer.py:153: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
self.register_buffer("_pre_quant_scale", torch.tensor(value))

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /code/tensorrt_llm/./examples/llama/quantize.py:135 in <module> │
│ │
│ 132 │
│ 133 │
│ 134 if __name__ == "__main__": │
│ ❱ 135 │ main() │
│ 136 │
│ │
│ /code/tensorrt_llm/./examples/llama/quantize.py:128 in main │

│ │

│ 125 │ │

│ 126 │ calib_dataloader = get_calib_dataloader(tokenizer=tokenizer, │

│ 127 │ │ │ │ │ │ │ │ │ │ │ calib_size=args.calib_size) │

│ ❱ 128 │ model = quantize_and_export(model, │

│ 129 │ │ │ │ │ │ │ │ qformat=args.qformat, │

│ 130 │ │ │ │ │ │ │ │ calib_dataloader=calib_dataloader, │

│ 131 │ │ │ │ │ │ │ │ export_path=args.export_path) │

│ │

│ /usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/quantized/ammo.py:86 in │

│ quantize_and_export │

│ │

│ 83 │ if export_path: │

│ 84 │ │ with torch.inference_mode(): │

│ 85 │ │ │ if qformat == "int4_awq": │

│ ❱ 86 │ │ │ │ torch.save(model.state_dict(), export_path) │

│ 87 │ │ │ else: │

│ 88 │ │ │ │ export_model_config( │

│ 89 │ │ │ │ │ model, │

│ │

│ /usr/local/lib/python3.10/dist-packages/torch/serialization.py:620 in save │

│ │

│ 617 │ _check_save_filelike(f) │

│ 618 │ │

│ 619 │ if _use_new_zipfile_serialization: │

│ ❱ 620 │ │ with _open_zipfile_writer(f) as opened_zipfile: │

│ 621 │ │ │ _save(obj, opened_zipfile, pickle_module, pickle_protocol, _disable_byteorde │

│ 622 │ │ │ return │

│ 623 │ else: │

│ │

│ /usr/local/lib/python3.10/dist-packages/torch/serialization.py:494 in _open_zipfile_writer │

│ │

│ 491 │ │ container = _open_zipfile_writer_file │

│ 492 │ else: │

│ 493 │ │ container = _open_zipfile_writer_buffer │

│ ❱ 494 │ return container(name_or_buffer) │

│ 495 │

│ 496 │

│ 497 def _is_compressed_file(f) -> bool: │

│ │

│ /usr/local/lib/python3.10/dist-packages/torch/serialization.py:465 in __init__ │

│ │

│ 462 │ │ │ self.file_stream = io.FileIO(self.name, mode='w') │

│ 463 │ │ │ super().__init__(torch._C.PyTorchFileWriter(self.file_stream)) │

│ 464 │ │ else: │

│ ❱ 465 │ │ │ super().__init__(torch._C.PyTorchFileWriter(self.name)) │

│ 466 │ │

│ 467 │ def __exit__(self, *args) -> None: │

│ 468 │ │ self.file_like.write_end_of_file() │

╰──────────────────────────────────────────────────────────────────────────────────────────────────╯

RuntimeError: [enforce fail at [inline_container.cc:462](http://inline_container.cc:462/)] . invalid file name: /code/quantized_int4-awq/
https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama
```

**Comment by sagarsdesai** [comment]
ran with original command `./quantized_int4-awq` (was avoiding due to space issue, wanted to be written to attached volume).

it is successful, however it has created a file of ~12GB.

now trying to create engine out of it.

Error quantised 

```
/code/tensorrt_llm# python examples/llama/build.py --model_dir /mnt/Llama-2-7b-chat-hf/ \
--quant_ckpt_path ./quantized_int4-awq \
--dtype float16 \
--remove_input_padding \
--use_gpt_attention_plugin float16 \
--enable_context_fmha \
--use_gemm_plugin float16 \
--use_weight_only \
--weight_only_precision int4_awq \
--per_group \
--output_dir model_outputs/int4_AWQ/1-gpu/
[12/20/2023-12:20:02] [TRT-LLM] [I] Serially build TensorRT engines.
[12/20/2023-12:20:02] [TRT] [I] [MemUsageChange] Init CUDA: CPU +14, GPU +0, now: CPU 133, GPU 273 (MiB)
[12/20/2023-12:20:03] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1800, GPU +312, now: CPU 2068, GPU 585 (MiB)
[12/20/2023-12:20:03] [TRT-LLM] [W] Invalid timing cache, using freshly created one
[12/20/2023-12:20:10] [TRT-LLM] [I] Loading weights from groupwise AWQ LLaMA safetensors...
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /code/tensorrt_llm/examples/llama/build.py:718 in <module> │
│ │
│ 715 │ else: │
│ 716 │ │ args.parallel_build = False │
│ 717 │ │ [logger.info](http://logger.info/)('Serially build TensorRT engines.') │
│ ❱ 718 │ │ build(0, args) │
│ 719 │ │
│ 720 │ tok = time.time() │
│ 721 │ t = time.strftime('%H:%M:%S', time.gmtime(tok - tik)) │
│ │
│ /code/tensorrt_llm/examples/llama/build.py:689 in build │
│ │
│ 686 │ │ │ opt_level=args.builder_opt) │
│ 687 │ │ engine_name = get_engine_name(MODEL_NAME, args.dtype, args.tp_size, │
│ 688 │ │ │ │ │ │ │ │ │ args.pp_size, cur_rank) │
│ ❱ 689 │ │ engine = build_rank_engine(builder, builder_config, engine_name, │
│ 690 │ │ │ │ │ │ │ │ cur_rank, args) │
│ 691 │ │ assert engine is not None, f'Failed to build engine for rank {cur_rank}' │
│ 692 │
│ │
│ /code/tensorrt_llm/examples/llama/build.py:543 in build_rank_engine │
│ │
│ 540 │ │ │ │ │ │ │ │ │ │ quant_scales=quant_scales) │
│ 541 │ if args.per_group: │
│ 542 │ │ load_func = load_from_awq_llama if args.weight_only_precision == 'int4_awq' else │
│ ❱ 543 │ │ load_func(tensorrt_llm_llama=tensorrt_llm_llama, │
│ 544 │ │ │ │ quant_ckpt_path=args.quant_ckpt_path, │
│ 545 │ │ │ │ mapping=mapping, │
│ 546 │ │ │ │ dtype=args.dtype) │
│ │
│ /code/tensorrt_llm/examples/llama/weight.py:1063 in load_from_awq_llama │
│ │
│ 1060 │ │ awq_llama = torch.load(quant_ckpt_path, │
│ 1061 │ │ │ │ │ │ │ map_location=torch.device('cpu')) │
│ 1062 │ else: │
│ ❱ 1063 │ │ assert False, "Quantized checkpoint format not supported!" │
│ 1064 │ │
│ 1065 │ group_size = awq_llama["model.layers.0.self_attn.o_proj.weight"].numel( │
│ 1066 │ ) // awq_llama[ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError: Quantized checkpoint format not supported!
```

**Comment by sagarsdesai** [comment]
fixed above issue, `./quantized_int4-awq.pt`

is expected

**Comment by sagarsdesai** [comment]
with that fix new error comes up `KeyError: 'lm_head.weight_quantizer._amax'`

```
python examples/llama/build.py --model_dir /mnt/Llama-2-7b-chat-hf/ --quant_ckpt_path ./quantized_int4-awq.pt
--dtype float16 --remove_input_padding --use_gpt_attention_plugin float16 --enable_context_fmha --use_gemm_plugin
float16 --use_weight_only --weight_only_precision int4_awq --per_group --output_dir model_outputs/int4_AWQ/1-gpu/
[12/20/2023-13:51:43] [TRT-LLM] [I] Serially build TensorRT engines.
[12/20/2023-13:51:44] [TRT] [I] [MemUsageChange] Init CUDA: CPU +14, GPU +0, now: CPU 133, GPU 273 (MiB)
[12/20/2023-13:51:45] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1800, GPU +312, now: CPU 2068, GPU 585 (MiB)
[12/20/2023-13:51:45] [TRT-LLM] [W] Invalid timing cache, using freshly created one
[12/20/2023-13:51:52] [TRT-LLM] [I] Loading weights from groupwise AWQ LLaMA safetensors...
[12/20/2023-13:51:56] [TRT-LLM] [I] Process weights in layer: 0
[12/20/2023-13:51:58] [TRT-LLM] [I] Process weights in layer: 1
[12/20/2023-13:52:00] [TRT-LLM] [I] Process weights in layer: 2
[12/20/2023-13:52:02] [TRT-LLM] [I] Process weights in layer: 3
[12/20/2023-13:52:03] [TRT-LLM] [I] Process weights in layer: 4
[12/20/2023-13:52:05] [TRT-LLM] [I] Process weights in layer: 5
[12/20/2023-13:52:07] [TRT-LLM] [I] Process weights in layer: 6
[12/20/2023-13:52:09] [TRT-LLM] [I] Process weights in layer: 7
[12/20/2023-13:52:11] [TRT-LLM] [I] Process weights in layer: 8
[12/20/2023-13:52:12] [TRT-LLM] [I] Process weights in layer: 9
[12/20/2023-13:52:14] [TRT-LLM] [I] Process weights in layer: 10
[12/20/2023-13:52:16] [TRT-LLM] [I] Process weights in layer: 11
[12/20/2023-13:52:18] [TRT-LLM] [I] Process weights in layer: 12
[12/20/2023-13:52:19] [TRT-LLM] [I] Process weights in layer: 13
[12/20/2023-13:52:21] [TRT-LLM] [I] Process weights in layer: 14
[12/20/2023-13:52:23] [TRT-LLM] [I] Process weights in layer: 15
[12/20/2023-13:52:25] [TRT-LLM] [I] Process weights in layer: 16
[12/20/2023-13:52:27] [TRT-LLM] [I] Process weights in layer: 17
[12/20/2023-13:52:28] [TRT-LLM] [I] Process weights in layer: 18
[12/20/2023-13:52:30] [TRT-LLM] [I] Process weights in layer: 19
[12/20/2023-13:52:32] [TRT-LLM] [I] Process weights in layer: 20
[12/20/2023-13:52:34] [TRT-LLM] [I] Process weights in layer: 21
[12/20/2023-13:52:36] [TRT-LLM] [I] Process weights in layer: 22
[12/20/2023-13:52:37] [TRT-LLM] [I] Process weights in layer: 23
[12/20/2023-13:52:39] [TRT-LLM] [I] Process weights in layer: 24
[12/20/2023-13:52:41] [TRT-LLM] [I] Process weights in layer: 25
[12/20/2023-13:52:43] [TRT-LLM] [I] Process weights in layer: 26
[12/20/2023-13:52:45] [TRT-LLM] [I] Process weights in layer: 27
[12/20/2023-13:52:47] [TRT-LLM] [I] Process weights in layer: 28
[12/20/2023-13:52:48] [TRT-LLM] [I] Process weights in layer: 29
[12/20/2023-13:52:50] [TRT-LLM] [I] Process weights in layer: 30
[12/20/2023-13:52:52] [TRT-LLM] [I] Process weights in layer: 31
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮

│ /code/tensorrt_llm/examples/llama/build.py:718 in <module> │

│ │

│ 715 │ else: │

│ 716 │ │ args.parallel_build = False │

│ 717 │ │ [logger.info](http://logger.info/)('Serially build TensorRT engines.') │

│ ❱ 718 │ │ build(0, args) │

│ 719 │ │

│ 720 │ tok = time.time() │

│ 721 │ t = time.strftime('%H:%M:%S', time.gmtime(tok - tik)) │

│ │

│ /code/tensorrt_llm/examples/llama/build.py:689 in build │

│ │

│ 686 │ │ │ opt_level=args.builder_opt) │

│ 687 │ │ engine_name = get_engine_name(MODEL_NAME, args.dtype, args.tp_size, │

│ 688 │ │ │ │ │ │ │ │ │ args.pp_size, cur_rank) │

│ ❱ 689 │ │ engine = build_rank_engine(builder, builder_config, engine_name, │

│ 690 │ │ │ │ │ │ │ │ cur_rank, args) │

│ 691 │ │ assert engine is not None, f'Failed to build engine for rank {cur_rank}' │

│ 692 │

│ │

│ /code/tensorrt_llm/examples/llama/build.py:543 in build_rank_engine │

│ │

│ 540 │ │ │ │ │ │ │ │ │ │ quant_scales=quant_scales) │

│ 541 │ if args.per_group: │

│ 542 │ │ load_func = load_from_awq_llama if args.weight_only_precision == 'int4_awq' else │

│ ❱ 543 │ │ load_func(tensorrt_llm_llama=tensorrt_llm_llama, │

│ 544 │ │ │ │ quant_ckpt_path=args.quant_ckpt_path, │

│ 545 │ │ │ │ mapping=mapping, │

│ 546 │ │ │ │ dtype=args.dtype) │

│ │

│ /code/tensorrt_llm/examples/llama/weight.py:1272 in load_from_awq_llama │

│ │

│ 1269 │ │ mPrefix = "lm_head" │

│ 1270 │ │ mOp = tensorrt_llm_llama.lm_head │

│ 1271 │ │ if mapping.is_last_pp_rank(): │

│ ❱ 1272 │ │ │ process_and_assign_weight(awq_llama, mPrefix, mOp, 1) │

│ 1273 │ │

│ 1274 │ tok = time.time() │

│ 1275 │ t = time.strftime('%H:%M:%S', time.gmtime(tok - tik)) │

│ │

│ /code/tensorrt_llm/examples/llama/weight.py:1098 in process_and_assign_weight │

│ │

│ 1095 │ │ [k, n] = weight.shape │

│ 1096 │ │ weight = weight.split(weight.shape[tp_dim] // mapping.tp_size, │

│ 1097 │ │ │ │ │ │ │ dim=tp_dim)[mapping.tp_rank] │

│ ❱ 1098 │ │ amax = awq_llama[mPrefix + ".weight_quantizer._amax"].reshape( │

│ 1099 │ │ │ (n, int(k / group_size))).T.contiguous() │

│ 1100 │ │ amax = amax.split(amax.shape[tp_dim] // mapping.tp_size, │

│ 1101 │ │ │ │ │ │ dim=tp_dim)[mapping.tp_rank] │

╰──────────────────────────────────────────────────────────────────────────────────────────────────╯

KeyError: 'lm_head.weight_quantizer._amax'
```

**Comment by Tracin** [comment]
@SDcodehub Hi, Which AMMO version did you use? Could you try with AMMO of 0.5.0 and TRT-LLM 0.7.0?

**Comment by sagarsdesai** [comment]
- using tensorrtllm 0.5.0
- installing Processing ./nvidia_ammo-0.3.0/nvidia_ammo-0.3.0+cu122-cp310-cp310-linux_x86_64.whl
- pip installed requirements.txt for llama model
- 13B model

`python examples/llama/quantize.py --model_dir ../../data/data/models/Llama-2-13b-chat-hf                 --dtype float16                 --qformat int4_awq                 --export_path ./Llama-2-13b-quantized_int4-awq                 --calib_size 32`

creates `Llama-2-13b-quantized_int4-awq` file

```
/code/tensorrt_llm# python examples/llama/build.py --model_dir ../../data/data/models/Llama-2-13b-chat-hf/ \
                --quant_ckpt_path ./Llama-2-13b-quantized_int4-awq/llama_tp1_rank0.npz \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --use_weight_only \
                --weight_only_precision int4_awq \
                --per_group \
                --output_dir /model_outputs_llama13b/Llama-2-13b-quantized_int4-awq/
```

tried `--quant_ckpt_path ./Llama-2-13b-quantized_int4-awq`, `--quant_ckpt_path ./Llama-2-13b-quantized_int4-awq.pt`

```
[01/04/2024-10:14:25] [TRT-LLM] [I] Serially build TensorRT engines.
[01/04/2024-10:14:25] [TRT] [I] [MemUsageChange] Init CUDA: CPU +14, GPU +0, now: CPU 129, GPU 273 (MiB)
[01/04/2024-10:14:26] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1798, GPU +312, now: CPU 2063, GPU 585 (MiB)
[01/04/2024-10:14:26] [TRT-LLM] [W] Invalid timing cache, using freshly created one
[01/04/2024-10:14:40] [TRT-LLM] [I] Loading weights from groupwise AWQ LLaMA safetensors...
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/llama/build.py", line 718, in <module>
    build(0, args)
  File "/code/tensorrt_llm/examples/llama/build.py", line 689, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/code/tensorrt_llm/examples/llama/build.py", line 543, in build_rank_engine
    load_func(tensorrt_llm_llama=tensorrt_llm_llama,
  File "/code/tensorrt_llm/examples/llama/weight.py", line 1063, in load_from_awq_llama
    assert False, "Quantized checkpoint format not supported!"
AssertionError: Quantized checkpoint format not supported!
```

**Comment by Tracin** [comment]
Please update AMMO version please. `pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com nvidia-ammo~=0.5.0`

**Comment by jonny2027** [comment]
@Tracin I am still getting the same issue. I have tried to install ammo 0.5.0 and it fails to install. On downloading and inspecting the package it is nothing more than a placeholder. Does ammo not exist for windows?

**Comment by Tracin** [comment]
> @Tracin I am still getting the same issue. I have tried to install ammo 0.5.0 and it fails to install. On downloading and inspecting the package it is nothing more than a placeholder. Does ammo not exist for windows?

Can you open a new issue for this please?
