### ISSUE TITLE
Assertion failed when building engine for Llama2-7b with INT8 KV Cache and per-channel weight-only quantization

### ISSUE THREAD

**Issue by bhavika** [NVIDIA/TensorRT-LLM#729]
I'm using the latest `main` branch of TensorRT-LLM. [Hash](https://github.com/NVIDIA/TensorRT-LLM/commit/a75618df24e97ecf92b8899ca3c229c4b8097dda)

Building a Docker image for Triton using https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/dockerfile/Dockerfile.trt_llm_backend. 

Following the examples in [this section](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama#int8-kv-cache), I tried building an engine for Llama 2 7B using these steps: 

1. Built the INT8 KV cache: 

```
python3 hf_llama_convert.py -i /data/Llama2-7b-hf/Llama2-7b-hf -o /app/engines/Llama2-7b-hf/int8_kv_cache/ --calibrate-kv-cache -t fp16
``` 

2. Build the TensorRT-LLM engine with: 

```
python build.py --model_dir /data/Llama2-7b-hf/Llama2-7b-hf --dtype float16 --parallel_build --use_inflight_batching --remove_input_padding --use_gpt_attention_plugin float16 --enable_context_fmha --use_gemm_plugin float16 --output_dir /app/engines/Llama2-7b-hf/trt_engines/engine6/ --world_size 8 --tp_size 8 --pp_size 1 --use_weight_only --bin_model_dir "/app/engines/Llama2-7b-hf/int8_kv_cache/1-gpu/" --int8_kv_cache --use_weight_only
``` 

This leads to the following error: 

```
[12/23/2023-03:13:58] [TRT-LLM] [I] Loading weights from HF LLaMA...
Traceback (most recent call last):
  File "/app/tensorrt_llm/examples/llama/build.py", line 902, in <module>
    mp.spawn(build, nprocs=args.world_size, args=(args, ))
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 246, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 202, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 163, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/app/tensorrt_llm/examples/llama/build.py", line 850, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/app/tensorrt_llm/examples/llama/build.py", line 690, in build_rank_engine
    load_from_hf_llama(tensorrt_llm_llama,
  File "/app/tensorrt_llm/examples/llama/weight.py", line 389, in load_from_hf_llama
    torch.ops.fastertransformer.symmetric_quantize_last_axis_of_batched_matrix(
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 692, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: [TensorRT-LLM][ERROR] Assertion failed: The number of rows must be a multiple of 64 but the number of rows is 1376. (/app/tensorrt_llm/cpp/tensorrt_llm/kernels/cutlass_kernels/cutlass_preprocessors.cpp:501)
1       0x7fb55f3aaa36 tensorrt_llm::common::throwRuntimeError(char const*, int, std::string const&) + 102
2       0x7fb55f41960f tensorrt_llm::kernels::cutlass_kernels::interleave_column_major_tensor(signed char*, signed char const*, std::vector<unsigned long, std::allocator<unsigned long> > const&, tensorrt_llm::kernels::cutlass_kernels::QuantType, tensorrt_llm::kernels::cutlass_kernels::LayoutDetails) + 735
3       0x7fb55f419ab7 tensorrt_llm::kernels::cutlass_kernels::preprocess_weights_for_mixed_gemm(signed char*, signed char const*, std::vector<unsigned long, std::allocator<unsigned long> > const&, tensorrt_llm::kernels::cutlass_kernels::QuantType) + 327
4       0x7fb55f420621 void tensorrt_llm::kernels::cutlass_kernels::symmetric_quantize<__half, __half>(signed char*, signed char*, __half*, __half const*, std::vector<unsigned long, std::allocator<unsigned long> > const&, tensorrt_llm::kernels::cutlass_kernels::QuantType) + 1505
5       0x7fb55f3e4fad torch_ext::symmetric_quantize_helper(at::Tensor, c10::ScalarType, bool) + 2141
6       0x7fb55f3e51c6 torch_ext::symmetric_quantize_last_axis_of_batched_matrix(at::Tensor, c10::ScalarType) + 70
7       0x7fb55f3ea5dd c10::impl::make_boxed_from_unboxed_functor<c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<std::vector<at::Tensor, std::allocator<at::Tensor> > (*)(at::Tensor, c10::ScalarType), std::vector<at::Tensor, std::allocator<at::Tensor> >, c10::guts::typelist::typelist<at::Tensor, c10::ScalarType> >, true>::call(c10::OperatorKernel*, c10::OperatorHandle const&, c10::DispatchKeySet, std::vector<c10::IValue, std::allocator<c10::IValue> >*) + 141
8       0x7fb7d232c362 c10::Dispatcher::callBoxed(c10::OperatorHandle const&, std::vector<c10::IValue, std::allocator<c10::IValue> >*) const + 562
9       0x7fb7d20c38c3 torch::jit::invokeOperatorFromPython(std::vector<std::shared_ptr<torch::jit::Operator>, std::allocator<std::shared_ptr<torch::jit::Operator> > > const&, pybind11::args, pybind11::kwargs const&, c10::optional<c10::DispatchKey>) + 1155
10      0x7fb7d20c41b8 torch::jit::_get_operation_for_overload_or_packet(std::vector<std::shared_ptr<torch::jit::Operator>, std::allocator<std::shared_ptr<torch::jit::Operator> > > const&, c10::Symbol, pybind11::args, pybind11::kwargs const&, bool, c10::optional<c10::DispatchKey>) + 1448
11      0x7fb7d1fa81a0 /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_python.so(+0x8021a0) [0x7fb7d1fa81a0]
```

I've attached the full logs here as well. 
[trtllm_issue_logs.log](https://github.com/NVIDIA/TensorRT-LLM/files/13757861/trtllm_issue_logs.log)

I'm using an NVIDIA A100.

**Comment by juney-nvidia** [comment]
@bhavika 
Thanks for reporting this.
I just assigned this to my colleague @Tracin who is focusing on quantization support in TensorRT-LLM. 

Also there are ongoing efforts to refine the quantization workflow of TensorRT-LLM, we will sync together to figure out how to address the issue reported here. 

Thanks
June

**Comment by Tracin** [comment]
@bhavika Hi, I think this makes sense because inter_dim of LLAMA after TP is 11008 / 8 = 1376, which can not be divided by 64, it is a requirement of weight-only quantization. Please try reduce the TP size.

**Comment by bhavika** [comment]
> @bhavika Hi, I think this makes sense because inter_dim of LLAMA after TP is 11008 / 8 = 1376, which can not be divided by 64, it is a requirement of weight-only quantization. Please try reduce the TP size.

Thanks @Tracin! That suggestion was helpful. Just in case someone comes looking, I basically changed `tp_size` to `4`  and `pp_size` to `2` for the engine to build successfully.
