### ISSUE TITLE
Convert model to FP8 error

### ISSUE THREAD

**Issue by warlock135** [NVIDIA/TensorRT-LLM#734]
I tried to convert a fine-tuned LLama7b model to fp8.
The model is on the link below:
https://huggingface.co/togethercomputer/LLaMA-2-7B-32K

The convert command:
`examples/llama/quantize.py --model_dir /mnt/models/llama2-7b-32k-hf --dtype float16 --qformat fp8 --export_path /mnt/models/llama2-7b-32k-fp8 --calib_size 512`

which results an error: "TypeError: Object of type Tensor is not JSON serializable"
Here is the full running log:

> [12/25/2023-03:24:09] [TRT-LLM] [W] Found pynvml==11.4.1. Please use pynvml>=11.5.0 to get accurate memory usage
> [NeMo W 2023-12-25 03:24:24 nemo_logging:349] /usr/local/lib/python3.10/dist-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
>       warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
> 
> >>>> Flash Attention installed
> >>>> Flash RoPE installed
> WARNING: Logging before flag parsing goes to stderr.
> W1225 03:24:25.657692 139858700212032 modeling.py:706] The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
> Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 2/2 [00:09<00:00,  4.86s/it]
> Loading calibration dataset
> [NeMo W 2023-12-25 03:24:40 nemo_logging:349] /usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:2436: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
>       warnings.warn(
> 
> Replaced 675 modules to quantized modules
> torch.distributed not initialized, assuming single world_size.
> torch.distributed not initialized, assuming single world_size.
> torch.distributed not initialized, assuming single world_size.
> torch.distributed not initialized, assuming single world_size.
> torch.distributed not initialized, assuming single world_size.
> torch.distributed not initialized, assuming single world_size.
> torch.distributed not initialized, assuming single world_size.
> Cannot export model to the model_config. The AMMO optimized model state_dict (including the quantization factors) is saved to /mnt/models/llama2-7b-32k-fp8/ammo_model.0.pth using torch.save for further inspection.
> Detailed export error: Object of type Tensor is not JSON serializable
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/dist-packages/ammo/torch/export/model_config_export.py", line 183, in export_model_config
>     json.dump(model_config_dict, f)
>   File "/usr/lib/python3.10/json/__init__.py", line 179, in dump
>     for chunk in iterable:
>   File "/usr/lib/python3.10/json/encoder.py", line 431, in _iterencode
>     yield from _iterencode_dict(o, _current_indent_level)
>   File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
>     yield from chunks
>   File "/usr/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
>     yield from chunks
>   File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
>     yield from chunks
>   File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
>     yield from chunks
>   File "/usr/lib/python3.10/json/encoder.py", line 438, in _iterencode
>     o = _default(o)
>   File "/usr/lib/python3.10/json/encoder.py", line 179, in default
>     raise TypeError(f'Object of type {o.__class__.__name__} '
> TypeError: Object of type Tensor is not JSON serializable

**Comment by Tracin** [comment]
@RalphMao Assign to Huizi since it broke in AMMO.

**Comment by hello-11** [comment]
@warlock135 Do you still have the problem? If not, we will close it soon.
