### ISSUE TITLE
Unable to install via pip

### ISSUE THREAD

**Issue by diogogonnelli** [NVIDIA/TensorRT-LLM#777]
when installing via pip with the following code (using windows, not using docker):

pip install tensorrt_llm --extra-index-url https://pypi.nvidia.com --extra-index-url https://download.pytorch.org/whl/cu121

I get the following errors:

```
Collecting tensorrt_llm
  Downloading tensorrt-llm-0.7.1.tar.gz (6.9 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "C:\Users\RI_2\AppData\Roaming\Python\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\RI_2\AppData\Roaming\Python\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\RI_2\AppData\Roaming\Python\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\RI_2\AppData\Local\Temp\pip-build-env-0vf7hyl9\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\RI_2\AppData\Local\Temp\pip-build-env-0vf7hyl9\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\RI_2\AppData\Local\Temp\pip-build-env-0vf7hyl9\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\RI_2\AppData\Local\Temp\pip-build-env-0vf7hyl9\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 90, in <module>
      RuntimeError: Bad params
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

I have already reinstalled setuptools and the error continues.

**Comment by juney-nvidia** [comment]
@tp5uiuc  can you help take a look at this Windows installation issue when you have time?

June

**Comment by neory9771** [comment]
Same issue on Linux

**Comment by Shixiaowei02** [comment]
> Same issue on Linux

@khsibr Please provide the detailed error message and ensure that you are running the Python 3.10 and CUDA 12.x, thanks!

**Comment by tp5uiuc** [comment]
Hi @diogogonnelli, installation of `tensorrt_llm` with the provided command works for me, but downloads the wheel for `tensorrt_llm==0.7.0` (and not 0.7.1) because we haven't hosted a wheel for windows 0.7.1 yet (see logs, it initially errors out the same way as you, but proceeds to discard the 0.7.1 tarfile and installs the old wheel). Functionally, on windows, both 0.7.0 and 0.7.1 are identical, so please feel free to use 0.7.0. (Edit : realized later that I was using pip `21.2.4` which has this fallback behavior, if using latest pip `23.3.2`, my installation command also errors out).

For now, as a workaround, please try pinning the version to 0.7.0 instead
`pip install tensorrt_llm==0.7.0 --extra-index-url https://pypi.nvidia.com/ --extra-index-url https://download.pytorch.org/whl/cu121`

We will fix this by providing the 0.7.1 wheel sometime soon. Thanks!

Logs
```
python3 -m pip install tensorrt_llm --extra-index-url https://pypi.nvidia.com/ --extra-index-url https://download.pytorch.org/whl/cu121
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com/, https://pypi.nvidia.com/, https://download.pytorch.org/whl/cu121
Collecting tensorrt_llm
  Downloading tensorrt-llm-0.7.1.tar.gz (6.9 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\python3.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tejaswinp\\AppData\\Local\\Temp\\pip-install-n0__idlf\\tensorrt-llm_6cc89a136844458ab1f2501d4873c22a\\setup.py'"'"'; __file__='"'"'C:\\Users\\tejaswinp\\AppData\\Local\\Temp\\pip-install-n0__idlf\\tensorrt-llm_6cc89a136844458ab1f2501d4873c22a\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\tejaswinp\AppData\Local\Temp\pip-pip-egg-info-jxlfv0ii'
         cwd: C:\Users\tejaswinp\AppData\Local\Temp\pip-install-n0__idlf\tensorrt-llm_6cc89a136844458ab1f2501d4873c22a\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\tejaswinp\AppData\Local\Temp\pip-install-n0__idlf\tensorrt-llm_6cc89a136844458ab1f2501d4873c22a\setup.py", line 90, in <module>
        raise RuntimeError("Bad params")
    RuntimeError: Bad params
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/0a/fa/489752fa8576bf06142cb225b0da93fc9550786c0ed027113d48de97123c/tensorrt-llm-0.7.1.tar.gz#sha256=10275e2585484f138b43576acddba42ebee073fbb1665fe0954032e421e26e08 (from https://pypi.org/simple/tensorrt-llm/) (requires-python:>=3.7, <4). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading https://pypi.nvidia.com/tensorrt-llm/tensorrt_llm-0.7.0-cp310-cp310-win_amd64.whl (443.7 MB)
     |████████████████████████████████| 443.7 MB 6.8 MB/s
Requirement already satisfied: polygraphy in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tensorrt_llm) (0.49.0)
Requirement already satisfied: cuda-python==12.2.0 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tensorrt_llm) (12.2.0)
Requirement already satisfied: torchtext==0.16.0+cpu in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tensorrt_llm) (0.16.0+cpu)
Requirement already satisfied: tokenizers==0.13.3 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tensorrt_llm) (0.13.3)
Requirement already satisfied: accelerate==0.20.3 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tensorrt_llm) (0.20.3)
Requirement already satisfied: mpi4py in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tensorrt_llm) (3.1.5)
Requirement already satisfied: onnx>=1.12.0 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tensorrt_llm) (1.15.0)
Requirement already satisfied: tensorrt==9.2.0.post12.dev5 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tensorrt_llm) (9.2.0.post12.dev5)
Requirement already satisfied: pywin32 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tensorrt_llm) (306)
Requirement already satisfied: numpy in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tensorrt_llm) (1.26.2)
Requirement already satisfied: torchdata==0.7.0 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tensorrt_llm) (0.7.0)
Requirement already satisfied: torchvision==0.16.0+cu121 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tensorrt_llm) (0.16.0+cu121)
Requirement already satisfied: colored in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tensorrt_llm) (2.2.3)
Requirement already satisfied: sentencepiece>=0.1.99 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tensorrt_llm) (0.1.99)
Requirement already satisfied: torch==2.1.0+cu121 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tensorrt_llm) (2.1.0+cu121)
Requirement already satisfied: transformers==4.33.1 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tensorrt_llm) (4.33.1)
Requirement already satisfied: build in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tensorrt_llm) (1.0.3)
Requirement already satisfied: diffusers==0.15.0 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tensorrt_llm) (0.15.0)
Requirement already satisfied: wheel in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tensorrt_llm) (0.42.0)
Requirement already satisfied: psutil in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from accelerate==0.20.3->tensorrt_llm) (5.9.6)
Requirement already satisfied: packaging>=20.0 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from accelerate==0.20.3->tensorrt_llm) (23.2)
Requirement already satisfied: pyyaml in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from accelerate==0.20.3->tensorrt_llm) (6.0.1)
Requirement already satisfied: cython in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from cuda-python==12.2.0->tensorrt_llm) (3.0.6)
Requirement already satisfied: requests in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from diffusers==0.15.0->tensorrt_llm) (2.31.0)
Requirement already satisfied: regex!=2019.12.17 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from diffusers==0.15.0->tensorrt_llm) (2023.10.3)
Requirement already satisfied: huggingface-hub>=0.13.2 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from diffusers==0.15.0->tensorrt_llm) (0.19.4)
Requirement already satisfied: filelock in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from diffusers==0.15.0->tensorrt_llm) (3.13.1)
Requirement already satisfied: Pillow in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from diffusers==0.15.0->tensorrt_llm) (10.1.0)
Requirement already satisfied: importlib-metadata in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from diffusers==0.15.0->tensorrt_llm) (7.0.0)
Requirement already satisfied: tensorrt-libs==9.2.0.post12.dev5 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tensorrt==9.2.0.post12.dev5->tensorrt_llm) (9.2.0.post12.dev5)
Requirement already satisfied: tensorrt-bindings==9.2.0.post12.dev5 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tensorrt==9.2.0.post12.dev5->tensorrt_llm) (9.2.0.post12.dev5)
Requirement already satisfied: nvidia-cudnn-cu12 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tensorrt-libs==9.2.0.post12.dev5->tensorrt==9.2.0.post12.dev5->tensorrt_llm) (8.9.7.29)
Requirement already satisfied: nvidia-cublas-cu12 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tensorrt-libs==9.2.0.post12.dev5->tensorrt==9.2.0.post12.dev5->tensorrt_llm) (12.3.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tensorrt-libs==9.2.0.post12.dev5->tensorrt==9.2.0.post12.dev5->tensorrt_llm) (12.3.101)
Requirement already satisfied: typing-extensions in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from torch==2.1.0+cu121->tensorrt_llm) (4.8.0)
Requirement already satisfied: fsspec in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from torch==2.1.0+cu121->tensorrt_llm) (2023.10.0)
Requirement already satisfied: jinja2 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from torch==2.1.0+cu121->tensorrt_llm) (3.1.2)
Requirement already satisfied: networkx in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from torch==2.1.0+cu121->tensorrt_llm) (3.2.1)
Requirement already satisfied: sympy in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from torch==2.1.0+cu121->tensorrt_llm) (1.12)
Requirement already satisfied: urllib3>=1.25 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from torchdata==0.7.0->tensorrt_llm) (2.1.0)
Requirement already satisfied: tqdm in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from torchtext==0.16.0+cpu->tensorrt_llm) (4.66.1)
Requirement already satisfied: safetensors>=0.3.1 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from transformers==4.33.1->tensorrt_llm) (0.4.1)
Requirement already satisfied: protobuf>=3.20.2 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from onnx>=1.12.0->tensorrt_llm) (4.25.1)
Requirement already satisfied: colorama in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from tqdm->torchtext==0.16.0+cpu->tensorrt_llm) (0.4.6)
Requirement already satisfied: tomli>=1.1.0 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from build->tensorrt_llm) (2.0.1)
Requirement already satisfied: pyproject_hooks in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from build->tensorrt_llm) (1.0.0)
Requirement already satisfied: zipp>=0.5 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from importlib-metadata->diffusers==0.15.0->tensorrt_llm) (3.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from jinja2->torch==2.1.0+cu121->tensorrt_llm) (2.1.3)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from nvidia-cudnn-cu12->tensorrt-libs==9.2.0.post12.dev5->tensorrt==9.2.0.post12.dev5->tensorrt_llm) (12.3.103)
Requirement already satisfied: idna<4,>=2.5 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from requests->diffusers==0.15.0->tensorrt_llm) (3.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from requests->diffusers==0.15.0->tensorrt_llm) (3.3.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from requests->diffusers==0.15.0->tensorrt_llm) (2023.11.17)
Requirement already satisfied: mpmath>=0.19 in c:\users\tejaswinp\.pyenv\pyenv-win\versions\3.10.2\lib\site-packages (from sympy->torch==2.1.0+cu121->tensorrt_llm) (1.3.0)
Installing collected packages: tensorrt-llm
Successfully installed tensorrt-llm-0.7.0
```

**Comment by jeongsoopark** [comment]
also unable to install via pip but a bit different output log 
used pip 23.3.2 on WSL2

```
pip install tensorrt_llm==0.7.0 --extra-index-url https://pypi.nvidia.com --extra-index-url https://download.pytorch.org/whl/cu121
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com, https://download.pytorch.org/whl/cu121
Collecting tensorrt_llm==0.7.0
  Downloading tensorrt-llm-0.7.0.tar.gz (6.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-qmm9h0y3/tensorrt-llm_3cfc5883efb4495a86d8f00683a90514/setup.py", line 90, in <module>
          raise RuntimeError("Bad params")
      RuntimeError: Bad params
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by tp5uiuc** [comment]
Hi @diogogonnelli : Can you try the command now : we released the `0.7.1` wheel as of yesterday. Thanks! (I will mark this as completed, but of course, feel free to re-open the issue in case things don't work as expected).

@jeongsoopark : I don't think we have validated `tensorrt-llm` on WSL, feel free to open another issue and we can continue the discussion there.

**Comment by park12sj** [comment]
@tp5uiuc 
Hello. I think there's still the same issue in version 0.7.1. Please tell me how to do it.
It's a linux environment, python=3.10, cuda>12.x
```
root@personal-sangjune-trt-llm-0:/workspace/storage/cephfs-personal/git/pai/paip-TensorRT-LLM# uname -a
Linux personal-sangjune-trt-llm-0 5.15.117-1.20230620.el7.x86_64 #1 SMP Tue Jun 20 12:08:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

root@personal-sangjune-trt-llm-0:/workspace/storage/cephfs-personal/git/pai/paip-TensorRT-LLM# python --version
Python 3.10.12

root@personal-sangjune-trt-llm-0:/workspace/storage/cephfs-personal/git/pai/paip-TensorRT-LLM# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:17:15_PST_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0
```
```
root@personal-sangjune-trt-llm-0:/workspace/storage/cephfs-personal/git/pai/paip-TensorRT-LLM/examples/multimodal# pip3 install tensorrt_llm==0.7.1 -U --pre --extra-index-url https://pypi.nvidia.com
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /tensorrt-llm/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /tensorrt-llm/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /tensorrt-llm/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /tensorrt-llm/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /tensorrt-llm/
Collecting tensorrt_llm==0.7.1
  Using cached tensorrt-llm-0.7.1.tar.gz (6.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-d31a6i67/tensorrt-llm_0ddce389e5ce4d52849b6d347af6df64/setup.py", line 90, in <module>
          raise RuntimeError("Bad params")
      RuntimeError: Bad params
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by tp5uiuc** [comment]
@Shixiaowei02 : Can you double check/confirm if there's an issue on the `linux` side? thanks

**Comment by park12sj** [comment]
@tp5uiuc 

If I run whl build from main branch to below command, I think the same error occurs when installing nvidia-ammo. Can it be related?
I tried inside the container after image build for build as described in the guide.
`python3 ./scripts/build_wheel.py --clean  --trt_root /usr/local/tensorrt`
```
Collecting nvidia-ammo~=0.5.0 (from -r requirements.txt (line 18))
  Downloading nvidia-ammo-0.5.1.tar.gz (6.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-cwksnwhn/nvidia-ammo_375eeb4e0f7248fea8e87aaffc9f0eec/setup.py", line 90, in <module>
          raise RuntimeError("Bad params")
      RuntimeError: Bad params
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

```

**Comment by rajeevbaalwan** [comment]
Hi @tp5uiuc thanks for the solution.
I'm still getting error when installing 

```
root@cda267ebcb37:/# pip3 install tensorrt_llm==0.7.1 -U --pre --extra-index-url https://pypi.nvidia.com
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
Collecting tensorrt_llm==0.7.1
  Using cached tensorrt-llm-0.7.1.tar.gz (6.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-70ji5ttq/tensorrt-llm/setup.py'"'"'; __file__='"'"'/tmp/pip-install-70ji5ttq/tensorrt-llm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-70ji5ttq/tensorrt-llm/pip-egg-info
         cwd: /tmp/pip-install-70ji5ttq/tensorrt-llm/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-70ji5ttq/tensorrt-llm/setup.py", line 90, in <module>
        raise RuntimeError("Bad params")
    RuntimeError: Bad params
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
I have tried both 0.7.0 and 0.7.1

**Comment by Shixiaowei02** [comment]
Could you run the instruction and upload the debug log? Thank you! @rajeevbaalwan 
`pip3 install tensorrt_llm==0.7.1 -U --pre --extra-index-url https://pypi.nvidia.com --log=debug.txt`

**Comment by AvisP** [comment]
I am getting the following error message when doing a `pip install tensorrt_llm --extra-index-url https://pypi.nvidia.com --extra-index-url https://download.pytorch.org/whl/cu121` on Windows

```
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
Collecting tensorrt_llm==0.7.1
  Using cached tensorrt-llm-0.7.1.tar.gz (6.9 kB)
  Installing build dependencies ... done
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
PS C:\Users\avpaul\Downloads> pip3 install tensorrt_llm==0.7.1 -U --pre --extra-index-url https://pypi.nvidia.com --log=debug.txt
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
Collecting tensorrt_llm==0.7.1
  Using cached tensorrt-llm-0.7.1.tar.gz (6.9 kB)
  Installing build dependencies ... done
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
PS C:\Users\avpaul\Downloads> pip install tensorrt_llm --extra-index-url https://pypi.nvidia.com --extra-index-url https://download.pytorch.org/whl/cu121
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com, https://download.pytorch.org/whl/cu121
Collecting tensorrt_llm
  Using cached tensorrt-llm-0.7.1.tar.gz (6.9 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "C:\Users\avpaul\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\avpaul\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\avpaul\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\avpaul\AppData\Local\Temp\pip-build-env-7t1ywyxa\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\avpaul\AppData\Local\Temp\pip-build-env-7t1ywyxa\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\avpaul\AppData\Local\Temp\pip-build-env-7t1ywyxa\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\avpaul\AppData\Local\Temp\pip-build-env-7t1ywyxa\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 90, in <module>
      RuntimeError: Bad params
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

**Comment by sam-india-007** [comment]
same here :/, Windows

**Comment by tp5uiuc** [comment]
@AvisP Looks like your `python` version is 3.11. We only test/provide wheels for `python3.10` on `pypi.nvidia.com` (documented [here](https://github.com/NVIDIA/TensorRT-LLM/tree/main/windows#python)). If you want to build a wheel for `python` 3.11, please follow the instructions listed [here](https://github.com/NVIDIA/TensorRT-LLM/tree/main/windows#building-from-source) (and this is untested from our side on windows). Thanks!

@sam-india-007 Can you also provide the `python` version you are using?

**Comment by sam-india-007** [comment]
Hi @tp5uiuc I was using Python 3.12, will report if 3.10 returns any error

**Comment by AvisP** [comment]
Installed properly with python 3.10.11 Thanks!

**Comment by tp5uiuc** [comment]
Closing this issue
