### ISSUE TITLE
Getting error while running run.py from whisper examples

### ISSUE THREAD

**Issue by sasikr2** [NVIDIA/TensorRT-LLM#788]
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/whisper/run.py", line 336, in <module>
    model = WhisperTRTLLM(args.engine_dir, args.debug, args.assets_dir)
  File "/code/tensorrt_llm/examples/whisper/run.py", line 218, in __init__
    self.decoder = WhisperDecoding(engine_dir,
  File "/code/tensorrt_llm/examples/whisper/run.py", line 121, in __init__
    self.decoder_generation_session = self.get_session(
  File "/code/tensorrt_llm/examples/whisper/run.py", line 153, in get_session
    decoder_generation_session = tensorrt_llm.runtime.GenerationSession(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 457, in __init__
    self.runtime = _Runtime(engine_buffer, mapping)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 150, in __init__
    self.__prepare(mapping, engine_buffer)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 170, in __prepare
    address = CUASSERT(cudart.cudaMalloc(self.engine.device_memory_size))[0]
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 99, in CUASSERT
    raise RuntimeError(
RuntimeError: CUDA ERROR: 2, error code reference: https://nvidia.github.io/cuda-python/module/cudart.html#cuda.cudart.cudaError_t
Exception ignored in: <function _Runtime.__del__ at 0x7fb94d845360>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 266, in __del__
    cudart.cudaFree(self.address)  # FIXME: cudaFree is None??
AttributeError: '_Runtime' object has no attribute 'address'

**Comment by jdemouth-nvidia** [comment]
Hi. Could you share the command line to reproduce the issue, please? As well as tell us more about your environment, please? Thanks a lot.

**Comment by sasikr2** [comment]
First I created model.engine by running command 
python3 build.py --output_dir whisper_large_v2_bm5 --model_name large-v2  --max_batch_size 16 --max_beam_width 5 --use_gpt_attention_plugin --use_gemm_plugin --use_layernorm_plugin  --use_bert_attention_plugin
after this I simply run python3 run.py

Env: Running on A100 card (40GB)

**Comment by nv-guomingz** [comment]
would u please try our latest code base to see if the issue still exists?

And do u still have further issue or question now? If not, we'll close it soon.
