### ISSUE TITLE
KeyError when building a Falcon-7B TRT-LLM engine with FP8 Post Training Quantization

### ISSUE THREAD

**Issue by kelkarn** [NVIDIA/TensorRT-LLM#796]
**Environment**

1. Machine: NVIDIA A100 GPU (80GB GPU memory)
2. TRT-LLM version: release/0.5.0 (I am using the 23.10-trtllm-python-py3 container)
3. AMMO lib version: `nvidia_ammo-0.3.0.tar.gz`
4. architecture (`uname -m`): x86_64
5. Driver and CUDA versions: `NVIDIA-SMI 515.48.07    Driver Version: 515.48.07    CUDA Version: 11.7`
6. OS version: `Ubuntu 20.04.6 LTS`

**Expected Behavior**

I expect the `tensorrt_llm/examples/falcon/build.py` script to generate a TRT-LLM engine file for my Falcon-7B model (with FP8 PTQ) successfully.

**Actual Behavior**

I get an error like below:

```
[01/03/2024-00:13:55] [TRT-LLM] [I] Serially build TensorRT engines.
[01/03/2024-00:13:55] [TRT] [I] [MemUsageChange] Init CUDA: CPU +15, GPU +0, now: CPU 117, GPU 418 (MiB)
[01/03/2024-00:13:57] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1974, GPU +350, now: CPU 2227, GPU 768 (MiB)
[01/03/2024-00:13:57] [TRT-LLM] [W] Invalid timing cache, using freshly created one
[01/03/2024-00:13:59] [TRT-LLM] [I] Loading scaling factors from ./quantized_fp8/falcon_tp1_rank0.npz
Traceback (most recent call last):
  File "/azureuser/tensorrtllm_backend/tensorrt_llm/examples/falcon/build.py", line 567, in <module>
    build(0, args)
  File "/azureuser/tensorrtllm_backend/tensorrt_llm/examples/falcon/build.py", line 537, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/azureuser/tensorrtllm_backend/tensorrt_llm/examples/falcon/build.py", line 412, in build_rank_engine
    quant_scales = get_scaling_factors(args.quantized_fp8_model_path,
  File "/azureuser/tensorrtllm_backend/tensorrt_llm/examples/falcon/weight.py", line 499, in get_scaling_factors
    weight_dict[f'_np:layers:{layer}:attention:qkv:q:activation_scaling_factor'].item(),
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py", line 260, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: '_np:layers:0:attention:qkv:q:activation_scaling_factor is not a file in the archive'
```

**Reproduction Steps**

I am basically following the documentation [here](https://github.com/NVIDIA/TensorRT-LLM/blob/ffd5af342a817a2689d38e4af2cc59ded877e339/examples/falcon/README.md#fp8-post-training-quantization) word-for-word (except instead of a `180b` model, I use a Falcon `7b` model).

1. Generate FP8 model weights:
```
root@nishant-a100-test2:/azureuser/tensorrtllm_backend/tensorrt_llm/examples/falcon# python quantize.py --model_dir /azureuser/falcon/7b --dtype float16 --qformat fp8 --export_path quantized_fp8 --calib_size 16
```
This successfully generates the `quantized_fp8/falcon_tp1.json` and `quantized_fp8/falcon_tp1_rank0.npz` files. It does generate a few warnings along the way, like so (not sure if these are relevant to the issue):

```
[NeMo W 2024-01-03 00:11:04 nemo_logging:349] /usr/local/lib/python3.10/dist-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
      warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
    
Using pad_token, but it is not set yet.
[01/03/2024-00:11:05] 
WARNING: You are currently loading Falcon using legacy code contained in the model repository. Falcon has now been fully ported into the Hugging Face transformers library. For the most up-to-date and high-performance version of the Falcon model code, please update to the latest version of transformers and then load the model without the trust_remote_code=True argument.

Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.65s/it]
Loading calibration dataset
Downloading data: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 313M/313M [00:10<00:00, 30.4MB/s]
Downloading data: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 304M/304M [00:11<00:00, 27.1MB/s]
Downloading data: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 155M/155M [00:04<00:00, 35.2MB/s]
Downloading data: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 34.7M/34.7M [00:01<00:00, 32.1MB/s]
Downloading data: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30.0M/30.0M [00:00<00:00, 54.1MB/s]
Generating train split: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 287113/287113 [00:02<00:00, 113317.15 examples/s]
Generating validation split: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13368/13368 [00:00<00:00, 114631.69 examples/s]
Generating test split: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11490/11490 [00:00<00:00, 102988.08 examples/s]
[NeMo W 2024-01-03 00:11:47 nemo_logging:349] /usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:2411: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
      warnings.warn(
    
Replaced 3 modules to quantized modules
torch.distributed not initialized, assuming single world_size.
torch.distributed not initialized, assuming single world_size.
torch.distributed not initialized, assuming single world_size.
torch.distributed not initialized, assuming single world_size.
torch.distributed not initialized, assuming single world_size.
torch.distributed not initialized, assuming single world_size.
```

2. Attempt to generate TRT-LLM engine file using above FP8 scaling factors
```
root@nishant-a100-test2:/azureuser/tensorrtllm_backend/tensorrt_llm/examples/falcon# python build.py --model_dir /azureuser/falcon/7b --quantized_fp8_model_path ./quantized_fp8/falcon_tp1_rank0.npz --dtype float16 --enable_context_fmha --use_gpt_attention_plugin float16 --output_dir /azureuser/falcon/7b/trt_engines/fp8/1-gpu/                 --remove_input_padding --enable_fp8 --fp8_kv_cache --strongly_typed
```
This above step fails with the above shown error stack trace.

**Comment by kelkarn** [comment]
It seems there's nothing for 'layer 0' w.r.t. scaling factors in the `.npz` file that is created for the FP8 quantization:

```
>>> import numpy as np
>>> x = np.load('quantized_fp8/falcon_tp1_rank0.npz')
>>> type(x)
<class 'numpy.lib.npyio.NpzFile'>
>>> sf = [p for p in x.keys() if 'scaling_factor' in p]
>>> sf
['_np:lm_head:activation_scaling_factor', '_np:lm_head:weights_scaling_factor']
```
Only scaling factors I can see are for a layer called `_np:lm_head`, nothing for `_np:layers:0`.

**Comment by kelkarn** [comment]
When I try removing the ` --quantized_fp8_model_path ./quantized_fp8/falcon_tp1_rank0.npz` to force it to use the dummy scales automatically, I get this error:

```
[01/03/2024-01:02:19] [TRT] [E] 9: [standardEngineBuilder.cpp::buildEngine::2207] Error Code 9: Internal Error (Networks with FP8 precision require hardware with FP8 support.)
[01/03/2024-01:02:19] [TRT-LLM] [E] Engine building failed, please check the error log.
[01/03/2024-01:02:19] [TRT-LLM] [I] Config saved to /azureuser/falcon/7b/trt_engines/fp8/1-gpu/config.json.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /azureuser/tensorrtllm_backend/tensorrt_llm/examples/falcon/build.py:567 in <module>             │
│                                                                                                  │
│   564 │   else:                                                                                  │
│   565 │   │   args.parallel_build = False                                                        │
│   566 │   │   logger.info('Serially build TensorRT engines.')                                    │
│ ❱ 567 │   │   build(0, args)                                                                     │
│   568 │                                                                                          │
│   569 │   tok = time.time()                                                                      │
│   570 │   t = time.strftime('%H:%M:%S', time.gmtime(tok - tik))                                  │
│                                                                                                  │
│ /azureuser/tensorrtllm_backend/tensorrt_llm/examples/falcon/build.py:539 in build                │
│                                                                                                  │
│   536 │   │   │   │   │   │   │   │   │     args.pp_size, cur_rank)                              │
│   537 │   │   engine = build_rank_engine(builder, builder_config, engine_name,                   │
│   538 │   │   │   │   │   │   │   │      cur_rank, args)                                         │
│ ❱ 539 │   │   assert engine is not None, \                                                       │
│   540 │   │   │   f'Failed to build engine for rank {cur_rank}'                                  │
│   541 │   │                                                                                      │
│   542 │   │   if cur_rank == 0:                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError: Failed to build engine for rank 0
```

What does it mean here that I need hardware with FP8 support? My understanding was FP8 models can be created on A100 GPUs, is that not the case?

**Comment by Tracin** [comment]
Hi I will try to reproduce the error you met. However you do have to build FP8 engine with FP8 hardware support since FP8 kernel will be benchmarked during building.

**Comment by Tracin** [comment]
Hi, I think you used a old version of AMMO i.e. 0.3.0, please try with newer one `pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com nvidia-ammo~=0.5.0`. I verified that it works.
