### ISSUE TITLE
aww-int4  quantize  chatglm3-6b model  set tp_size=4 ,got some error

### ISSUE THREAD

**Issue by white-wolf-tech** [NVIDIA/TensorRT-LLM#811]
```
awq_weight_path=quantize_model/chatglm3-awq-4bit-trt/chatglm3_6b_4bit_gs128_awq.pt
python build.py \
    --model_dir=$hf_model_path \
    --quant_ckpt_path=$awq_weight_path \
    --output_dir $engine_dir \
    --world_size 4 \
    --tp_size 4 \
    --use_weight_only \
    --weight_only_precision=int4_awq \
    --per_group
```
error info:

[01/04/2024-07:52:32] [TRT-LLM] [I] ========================================= Build Arguments ==========================================
[01/04/2024-07:52:32] [TRT-LLM] [I]  - model_name..............................: chatglm3_6b_base
[01/04/2024-07:52:32] [TRT-LLM] [I]  - gpus_per_node...........................: 8
[01/04/2024-07:52:32] [TRT-LLM] [I]  - world_size..............................: 4
[01/04/2024-07:52:32] [TRT-LLM] [I]  - tp_size.................................: 4
[01/04/2024-07:52:32] [TRT-LLM] [I]  - pp_size.................................: 1
[01/04/2024-07:52:32] [TRT-LLM] [I]  - model_dir...............................: /models/tcl_finetune/chatglm3
[01/04/2024-07:52:32] [TRT-LLM] [I]  - quant_ckpt_path.........................: quantize_model/chatglm3-awq-4bit-trt/chatglm3_6b_4bit_gs128_awq.pt
[01/04/2024-07:52:32] [TRT-LLM] [I]  - quantized_fp8_model_path................: None
[01/04/2024-07:52:32] [TRT-LLM] [I]  - output_dir..............................: trt_engines/fp16/4-gpu
[01/04/2024-07:52:32] [TRT-LLM] [I]  - dtype...................................: float16
[01/04/2024-07:52:32] [TRT-LLM] [I]  - logits_dtype............................: float32
[01/04/2024-07:52:32] [TRT-LLM] [I]  - strongly_typed..........................: False
[01/04/2024-07:52:32] [TRT-LLM] [I]  - timing_cache............................: model.cache
[01/04/2024-07:52:32] [TRT-LLM] [I]  - profiling_verbosity.....................: layer_names_only
[01/04/2024-07:52:32] [TRT-LLM] [I]  - log_level...............................: info
[01/04/2024-07:52:32] [TRT-LLM] [I]  - builder_opt.............................: None
[01/04/2024-07:52:32] [TRT-LLM] [I]  - parallel_build..........................: False
[01/04/2024-07:52:32] [TRT-LLM] [I]  - enable_debug_output.....................: False
[01/04/2024-07:52:32] [TRT-LLM] [I]  - visualize...............................: False
[01/04/2024-07:52:32] [TRT-LLM] [I]  - random_seed.............................: None
[01/04/2024-07:52:32] [TRT-LLM] [I]  - max_batch_size..........................: 8
[01/04/2024-07:52:32] [TRT-LLM] [I]  - max_input_len...........................: 1024
[01/04/2024-07:52:32] [TRT-LLM] [I]  - max_output_len..........................: 1024
[01/04/2024-07:52:32] [TRT-LLM] [I]  - max_beam_width..........................: 1
[01/04/2024-07:52:32] [TRT-LLM] [I]  - max_num_tokens..........................: 4294967296
[01/04/2024-07:52:32] [TRT-LLM] [I]  - use_gpt_attention_plugin................: float16
[01/04/2024-07:52:32] [TRT-LLM] [I]  - use_gemm_plugin.........................: float16
[01/04/2024-07:52:32] [TRT-LLM] [I]  - use_layernorm_plugin....................: float16
[01/04/2024-07:52:32] [TRT-LLM] [I]  - use_rmsnorm_plugin......................: float16
[01/04/2024-07:52:32] [TRT-LLM] [I]  - enable_context_fmha.....................: False
[01/04/2024-07:52:32] [TRT-LLM] [I]  - enable_context_fmha_fp32_acc............: False
[01/04/2024-07:52:32] [TRT-LLM] [I]  - multi_block_mode........................: False
[01/04/2024-07:52:32] [TRT-LLM] [I]  - gather_all_token_logits.................: False
[01/04/2024-07:52:32] [TRT-LLM] [I]  - use_custom_all_reduce...................: False
[01/04/2024-07:52:32] [TRT-LLM] [I]  - remove_input_padding....................: False
[01/04/2024-07:52:32] [TRT-LLM] [I]  - paged_kv_cache..........................: False
[01/04/2024-07:52:32] [TRT-LLM] [I]  - tokens_per_block........................: 128
[01/04/2024-07:52:32] [TRT-LLM] [I]  - use_inflight_batching...................: False
[01/04/2024-07:52:32] [TRT-LLM] [I]  - use_weight_only.........................: True
[01/04/2024-07:52:32] [TRT-LLM] [I]  - weight_only_precision...................: int4_awq
[01/04/2024-07:52:32] [TRT-LLM] [I]  - disable_weight_only_quant_plugin........: False
[01/04/2024-07:52:32] [TRT-LLM] [I]  - use_smooth_quant........................: False
[01/04/2024-07:52:32] [TRT-LLM] [I]  - per_token...............................: False
[01/04/2024-07:52:32] [TRT-LLM] [I]  - per_channel.............................: False
[01/04/2024-07:52:32] [TRT-LLM] [I]  - per_group...............................: True
[01/04/2024-07:52:32] [TRT-LLM] [I]  - group_size..............................: 128
[01/04/2024-07:52:32] [TRT-LLM] [I]  - int8_kv_cache...........................: False
[01/04/2024-07:52:32] [TRT-LLM] [I]  - enable_fp8..............................: False
[01/04/2024-07:52:32] [TRT-LLM] [I]  - fp8_kv_cache............................: False
[01/04/2024-07:52:32] [TRT-LLM] [I]  - apply_query_key_layer_scaling...........: False
[01/04/2024-07:52:32] [TRT-LLM] [I]  - apply_residual_connection_post_layernorm: False
[01/04/2024-07:52:32] [TRT-LLM] [I]  - ffn_hidden_size.........................: 13696
[01/04/2024-07:52:32] [TRT-LLM] [I]  - hidden_act..............................: swiglu
[01/04/2024-07:52:32] [TRT-LLM] [I]  - hidden_size.............................: 4096
[01/04/2024-07:52:32] [TRT-LLM] [I]  - linear_bias.............................: False
[01/04/2024-07:52:32] [TRT-LLM] [I]  - max_seq_length..........................: 2048
[01/04/2024-07:52:32] [TRT-LLM] [I]  - multi_query_mode........................: False
[01/04/2024-07:52:32] [TRT-LLM] [I]  - norm_epsilon............................: 1e-05
[01/04/2024-07:52:32] [TRT-LLM] [I]  - num_heads...............................: 32
[01/04/2024-07:52:32] [TRT-LLM] [I]  - num_kv_heads............................: 2
[01/04/2024-07:52:32] [TRT-LLM] [I]  - num_layers..............................: 28
[01/04/2024-07:52:32] [TRT-LLM] [I]  - qkv_bias................................: True
[01/04/2024-07:52:32] [TRT-LLM] [I]  - rmsnorm.................................: True
[01/04/2024-07:52:32] [TRT-LLM] [I]  - rotary_embedding_scaling................: 1.0
[01/04/2024-07:52:32] [TRT-LLM] [I]  - use_cache...............................: True
[01/04/2024-07:52:32] [TRT-LLM] [I]  - vocab_size..............................: 65024
[01/04/2024-07:52:32] [TRT-LLM] [I]  - quant_mode..............................: 33
[01/04/2024-07:52:32] [TRT-LLM] [I] ====================================================================================================
[01/04/2024-07:52:32] [TRT-LLM] [I] Serially build TensorRT engines.
[01/04/2024-07:52:32] [TRT] [I] [MemUsageChange] Init CUDA: CPU +13, GPU +0, now: CPU 111, GPU 238 (MiB)
[01/04/2024-07:52:34] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1799, GPU +312, now: CPU 2046, GPU 550 (MiB)
[01/04/2024-07:52:34] [TRT-LLM] [I] [MemUsage] Rank 0 Engine build starts - Allocated Memory: Host 2.4801 (GiB) Device 0.5378 (GiB)
[01/04/2024-07:52:34] [TRT-LLM] [I] Loading weights from groupwise AWQ checkpoint
[01/04/2024-07:52:40] [TRT-LLM] [W] Parameter was initialized as DataType.HALF but set to float16
[01/04/2024-07:52:40] [TRT-LLM] [W] Parameter was initialized as DataType.HALF but set to float16
[01/04/2024-07:52:40] [TRT-LLM] [W] Parameter was initialized as DataType.HALF but set to float16
[01/04/2024-07:52:40] [TRT-LLM] [W] Parameter was initialized as DataType.HALF but set to float16
[01/04/2024-07:52:40] [TRT-LLM] [W] Parameter was initialized as DataType.HALF but set to float16
[01/04/2024-07:52:40] [TRT-LLM] [W] Parameter was initialized as DataType.HALF but set to float16
Traceback (most recent call last):
  File "/api/example/tensorrt_llm/chatglm/build.py", line 908, in <module>
    run_build()
  File "/api/example/tensorrt_llm/chatglm/build.py", line 900, in run_build
    build(0, args)
  File "/api/example/tensorrt_llm/chatglm/build.py", line 840, in build
    engine = build_rank_engine(
  File "/api/example/tensorrt_llm/chatglm/build.py", line 664, in build_rank_engine
    load_func(
  File "/api/example/tensorrt_llm/chatglm/weight.py", line 609, in load_from_awq
    process_and_assign_weight(op, name, 1)
  File "/api/example/tensorrt_llm/chatglm/weight.py", line 572, in process_and_assign_weight
    op.weight.value = AWQ_quantize_pack_preprocess(weight, scale)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/parameter.py", line 112, in value
    assert v.shape == self._shape, \
AssertionError: The value updated is not the same shape as the original. Updated: (4096, 288), original: (4096, 320)

**Comment by wili-65535** [comment]
Thank you for finding this error!
Now **INT4-AWQ + TP>1** is not supported for ChatGLM series models, though either **INT4-AWQ** or **TP>1** is supported.
We are evaluating to add this feature combination.

**Comment by nv-guomingz** [comment]
hi do u still have further issue or question now? If not, we'll close it soon.
