### ISSUE TITLE
Encountered an error while using Python benchmark.

### ISSUE THREAD

**Issue by ghost** [NVIDIA/TensorRT-LLM#818]
## Environment

CPU architecture: x86_64
GPU name: L40S
GPU memory size: 46068MiB
TensorRT-LLM tag: v0.7.0
TensorRT: 9.1.0.post12.dev4
CUDA: V12.1.105
Container used: self build
NVIDIA driver version: 535.129.03
OS: ubuntu 20.04.6

## Reproduction Steps
Build a llama-7b model using the following command:
```shell
python examples/llama/build.py \
    --log_level=info \
    --model_dir=${MODEL_DIR} \
    --dtype=float16 \
    --use_gpt_attention_plugin=float16 \
    --use_gemm_plugin=float16 \
    --enable_context_fmha \
    --world_size=1 \
    --tp_size=1 \
    --pp_size=1 \
    --max_batch_size=2 \
    --max_input_len=2048 \
    --max_output_len=1024 \
    --remove_input_padding \
    --paged_kv_cache \
    --output_dir=${OUT_DIR}
```

After above execution, I successfully obtained an engine model. Then I tested the performance of the model using the following command:
```shell
python benchmarks/benchmark.py \
    --input_output_len="2048,512" \
    --engine_dir="${MODEL_DIR}" \
    --batch_size="2" \
    --mode="plugin"
```
Then the following error occurred:
```txt
/opt/pyenv/versions/3.10.12/lib/python3.10/site-packages/tensorrt_llm/runtime/generation.py:862: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. (Triggered internally at ../aten/src/ATen/NestedTensorImpl.cpp:178.)
  torch.nested.nested_tensor(split_ids_list,
[01/05/2024-03:20:20] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:20] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:20] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:20] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:20] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:20] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:20] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:20] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:20] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:20] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:20] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:20] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:20] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:20] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:20] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:20] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:20] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:20] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:20] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::resolveSlots::2898] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::resolveSlots::2898, condition: allInputDimensionsSpecified(routine) )
[01/05/2024-03:20:21] [TRT] [E] 3: [executionContext.cpp::resolveSlots::2898] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::resolveSlots::2898, condition: allInputDimensionsSpecified(routine) )
Traceback (most recent call last):
  File "/app/scripts/benchmarks/benchmark.py", line 280, in main
    benchmarker.run(inputs, config)
  File "/app/scripts/benchmarks/gpt_benchmark.py", line 121, in run
    self.decoder.decode_batch(inputs[0],
  File "/opt/pyenv/versions/3.10.12/lib/python3.10/site-packages/tensorrt_llm/runtime/generation.py", line 2157, in decode_batch
    return self.decode(input_ids,
  File "/opt/pyenv/versions/3.10.12/lib/python3.10/site-packages/tensorrt_llm/runtime/generation.py", line 705, in wrapper
    ret = func(self, *args, **kwargs)
  File "/opt/pyenv/versions/3.10.12/lib/python3.10/site-packages/tensorrt_llm/runtime/generation.py", line 2273, in decode
    return self.decode_regular(
  File "/opt/pyenv/versions/3.10.12/lib/python3.10/site-packages/tensorrt_llm/runtime/generation.py", line 2006, in decode_regular
    should_stop, next_step_tensors, tasks, context_lengths, host_context_lengths, attention_mask, logits, encoder_input_lengths = self.handle_per_step(
  File "/opt/pyenv/versions/3.10.12/lib/python3.10/site-packages/tensorrt_llm/runtime/generation.py", line 1741, in handle_per_step
    raise RuntimeError('Executing TRT engine failed!')
RuntimeError: Executing TRT engine failed!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/scripts/benchmarks/benchmark.py", line 331, in <module>
    main(args)
  File "/app/scripts/benchmarks/benchmark.py", line 304, in main
    print("Found exception during benchmarking", e.with_traceback())
TypeError: BaseException.with_traceback() takes exactly one argument (0 given)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/pyenv/versions/3.10.12/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/pyenv/versions/3.10.12/lib/python3.10/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/opt/pyenv/versions/3.10.12/lib/python3.10/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[27883,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

## Additional Notes

I was able to successfully execute it using the tag of v0.5.0.
```[tasklist]
### Tasks
```

**Comment by nv-guomingz** [comment]
would u please try our latest code base to see if the issue still exists?

And do u still have further issue or question now? If not, we'll close it soon.
