### ISSUE TITLE
Build failed with dummy weights for chatglm3_6b

### ISSUE THREAD

**Issue by Isar-ss** [NVIDIA/TensorRT-LLM#821]
I can build chatglm3_6b model with real weights. But I failed  to use dummy weights to build chatglm3_6b model. The error message shows that it still need model checkpoint.
Build command:
`python3 build.py --model_name chatglm3_6b --world_size 8  --output_dir chatglm3_6b_engine/fp16_3 --tp_size 8`

error message:
`[01/05/2024-05:46:16] [TRT-LLM] [I] ========================================= Build Arguments =========================
[01/05/2024-05:46:16] [TRT-LLM] [I]  - model_name....................: chatglm3_6b
[01/05/2024-05:46:16] [TRT-LLM] [I]  - world_size....................: 8
[01/05/2024-05:46:16] [TRT-LLM] [I]  - tp_size.......................: 8
[01/05/2024-05:46:16] [TRT-LLM] [I]  - pp_size.......................: 1
[01/05/2024-05:46:16] [TRT-LLM] [I]  - model_dir.....................: chatglm3_6b
[01/05/2024-05:46:16] [TRT-LLM] [I]  - quant_ckpt_path...............: awq/
[01/05/2024-05:46:16] [TRT-LLM] [I]  - dtype.........................: float16
[01/05/2024-05:46:16] [TRT-LLM] [I]  - logits_dtype..................: float32
[01/05/2024-05:46:16] [TRT-LLM] [I]  - timing_cache..................: model.cache
[01/05/2024-05:46:16] [TRT-LLM] [I]  - log_level.....................: info
[01/05/2024-05:46:16] [TRT-LLM] [I]  - max_batch_size................: 128
[01/05/2024-05:46:16] [TRT-LLM] [I]  - max_input_len.................: 1024
[01/05/2024-05:46:16] [TRT-LLM] [I]  - max_output_len................: 1024
[01/05/2024-05:46:16] [TRT-LLM] [I]  - max_beam_width................: 1
[01/05/2024-05:46:16] [TRT-LLM] [I]  - use_gpt_attention_plugin......: float16
[01/05/2024-05:46:16] [TRT-LLM] [I]  - use_gemm_plugin...............: float16
[01/05/2024-05:46:16] [TRT-LLM] [I]  - use_layernorm_plugin..........: float16
[01/05/2024-05:46:16] [TRT-LLM] [I]  - use_rmsnorm_plugin............: float16
[01/05/2024-05:46:16] [TRT-LLM] [I]  - gather_all_token_logits.......: False
[01/05/2024-05:46:16] [TRT-LLM] [I]  - parallel_build................: False
[01/05/2024-05:46:16] [TRT-LLM] [I]  - enable_context_fmha...........: False
[01/05/2024-05:46:16] [TRT-LLM] [I]  - enable_context_fmha_fp32_acc..: False
[01/05/2024-05:46:16] [TRT-LLM] [I]  - multi_block_mode..............: False
[01/05/2024-05:46:16] [TRT-LLM] [I]  - visualize.....................: False
[01/05/2024-05:46:16] [TRT-LLM] [I]  - enable_debug_output...........: False
[01/05/2024-05:46:16] [TRT-LLM] [I]  - gpus_per_node.................: 8
[01/05/2024-05:46:16] [TRT-LLM] [I]  - builder_opt...................: None
[01/05/2024-05:46:16] [TRT-LLM] [I]  - output_dir....................: chatglm3_6b_engine/fp16_3
[01/05/2024-05:46:16] [TRT-LLM] [I]  - strongly_typed................: False
[01/05/2024-05:46:16] [TRT-LLM] [I]  - remove_input_padding..........: False
[01/05/2024-05:46:16] [TRT-LLM] [I]  - paged_kv_cache................: False
[01/05/2024-05:46:16] [TRT-LLM] [I]  - use_inflight_batching.........: False
[01/05/2024-05:46:16] [TRT-LLM] [I]  - use_smooth_quant..............: False
[01/05/2024-05:46:16] [TRT-LLM] [I]  - use_weight_only...............: False
[01/05/2024-05:46:16] [TRT-LLM] [I]  - weight_only_precision.........: int8
[01/05/2024-05:46:16] [TRT-LLM] [I]  - per_channel...................: False
[01/05/2024-05:46:16] [TRT-LLM] [I]  - per_token.....................: False
[01/05/2024-05:46:16] [TRT-LLM] [I]  - per_group.....................: False
[01/05/2024-05:46:16] [TRT-LLM] [I]  - group_size....................: 128
[01/05/2024-05:46:16] [TRT-LLM] [I]  - int8_kv_cache.................: False
[01/05/2024-05:46:16] [TRT-LLM] [I]  - random_seed...................: None
[01/05/2024-05:46:16] [TRT-LLM] [I]  - tokens_per_block..............: 128
[01/05/2024-05:46:16] [TRT-LLM] [I]  - enable_fp8....................: False
[01/05/2024-05:46:16] [TRT-LLM] [I]  - fp8_kv_cache..................: False
[01/05/2024-05:46:16] [TRT-LLM] [I]  - max_num_tokens................: None
[01/05/2024-05:46:16] [TRT-LLM] [I]  - use_custom_all_reduce.........: False
[01/05/2024-05:46:16] [TRT-LLM] [I]  - apply_query_key_layer_scaling.: False
[01/05/2024-05:46:16] [TRT-LLM] [I]  - apply_residual_connection_post_layernorm: False
[01/05/2024-05:46:16] [TRT-LLM] [I]  - ffn_hidden_size...............: 13696
[01/05/2024-05:46:16] [TRT-LLM] [I]  - hidden_act....................: swiglu
[01/05/2024-05:46:16] [TRT-LLM] [I]  - hidden_size...................: 4096
[01/05/2024-05:46:16] [TRT-LLM] [I]  - linear_bias...................: False
[01/05/2024-05:46:16] [TRT-LLM] [I]  - max_seq_length................: 2048
[01/05/2024-05:46:16] [TRT-LLM] [I]  - multi_query_mode..............: False
[01/05/2024-05:46:16] [TRT-LLM] [I]  - norm_epsilon..................: 1e-05
[01/05/2024-05:46:16] [TRT-LLM] [I]  - num_heads.....................: 32
[01/05/2024-05:46:16] [TRT-LLM] [I]  - num_kv_heads..................: 2
[01/05/2024-05:46:16] [TRT-LLM] [I]  - num_layers....................: 28
[01/05/2024-05:46:16] [TRT-LLM] [I]  - qkv_bias......................: True
[01/05/2024-05:46:16] [TRT-LLM] [I]  - rmsnorm.......................: True
[01/05/2024-05:46:16] [TRT-LLM] [I]  - rotary_embedding_scaling......: 1.0
[01/05/2024-05:46:16] [TRT-LLM] [I]  - use_cache.....................: True
[01/05/2024-05:46:16] [TRT-LLM] [I]  - vocab_size....................: 65024
[01/05/2024-05:46:16] [TRT-LLM] [I]  - quant_mode....................: 0
[01/05/2024-05:46:16] [TRT-LLM] [I] ===================================================================================
[01/05/2024-05:46:16] [TRT-LLM] [I] Serially build TensorRT engines.
[01/05/2024-05:46:16] [TRT] [I] [MemUsageChange] Init CUDA: CPU +13, GPU +0, now: CPU 111, GPU 427 (Mi
[01/05/2024-05:46:19] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1974, GPU +350, now77 (MiB)
[01/05/2024-05:46:21] [TRT-LLM] [I] Loading weights from HF
Loading checkpoint shards:   0%|                                                                 | 0/7
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 488, in load_sta
    return torch.load(checkpoint_file, map_location=map_location)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'chatglm3_6b/pytorch_model-00001-of-00007.bin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/dz0114090/TensorRT-LLM/examples/chatglm/build.py", line 787, in <module>
    run_build()
  File "/mnt/data/dz0114090/TensorRT-LLM/examples/chatglm/build.py", line 779, in run_build
    build(0, args)
  File "/mnt/data/dz0114090/TensorRT-LLM/examples/chatglm/build.py", line 719, in build
    engine = build_rank_engine(
  File "/mnt/data/dz0114090/TensorRT-LLM/examples/chatglm/build.py", line 576, in build_rank_engine
    trtllm_model = load_from_hf(
  File "/mnt/data/dz0114090/TensorRT-LLM/examples/chatglm/weight.py", line 110, in load_from_hf
    hf_model = transformers.AutoModel.from_pretrained(hf_model_dir,
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 558, i
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3175, in from_pr
    ) = cls._load_pretrained_model(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3548, in _load_p
    state_dict = load_state_dict(shard_file)
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 491, in load_sta
    with open(checkpoint_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'chatglm3_6b/pytorch_model-00001-of-00007.bin'`

**Comment by nv-guomingz** [comment]
Hi @Isar-ss we've supported chatglm3 several months ago. Please have a try the latest code base and please feel free to reopen this ticket if needed.
