### ISSUE TITLE
run the engine failed in debug mode

### ISSUE THREAD

**Issue by MIrandaStock** [NVIDIA/TensorRT-LLM#838]
**step1:mark the output tensor**
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/45962405/5b00de56-89c6-4956-9253-69bd84c52d82)

**step2:enable_debug_output**
```
python3 build.py \
    --dtype float16 \
    --bin_model_dir $save_dir/sq0.5/smooth/1-gpu \
    --use_smooth_quant \
    --output_dir $output_dir \
    --per_token \
    --per_channel \
    --enable_debug_output \
    --use_gpt_attention_plugin float16 \

python3 ./../run.py --max_output_len 128 \
    --max_kv_cache_length 128 \
    --max_input_length 128 \
    --debug_mode \
    --engine_dir $output_dir \
    --tokenizer_dir $tokenizer_dir \
    --input_text "1+1等于几"
```

I debug the engine of bloom-1b model followed by the methined steps and created engines successfully, but got this errors during inference:
```
[01/08/2024-10:55:50] [TRT] [E] 3: [executionContext.cpp::enqueueV3::2629] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::enqueueV3::2629, condition: mContext.profileObliviousBindings.at(profileObliviousIndex) || getPtrOrNull(mOutputAllocators, profileObliviousIndex) )
Traceback (most recent call last):
  File "./../run.py", line 349, in <module>
    main(args)
  File "./../run.py", line 293, in main
    outputs = runner.generate(batch_input_ids,
  File "/root/jfs-hdfs/user/yujie01.meng/projects/trt-llm/tensorrt_llm/runtime/model_runner.py", line 384, in generate
    outputs = self.session.decode(
  File "/root/jfs-hdfs/user/yujie01.meng/projects/trt-llm/tensorrt_llm/runtime/generation.py", line 641, in wrapper
    ret = func(self, *args, **kwargs)
  File "/root/jfs-hdfs/user/yujie01.meng/projects/trt-llm/tensorrt_llm/runtime/generation.py", line 2216, in decode
    return self.decode_regular(
  File "/root/jfs-hdfs/user/yujie01.meng/projects/trt-llm/tensorrt_llm/runtime/generation.py", line 1951, in decode_regular
    should_stop, next_step_buffer, tasks, context_lengths, host_context_lengths, attention_mask, logits, encoder_input_lengths = self.handle_per_step(
  File "/root/jfs-hdfs/user/yujie01.meng/projects/trt-llm/tensorrt_llm/runtime/generation.py", line 1714, in handle_per_step
    raise RuntimeError('Executing TRT engine failed!')
RuntimeError: Executing TRT engine failed!
```

Please tell me how to solve this problem?

**Comment by MIrandaStock** [comment]
I found the problem here
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/45962405/40eb0d33-e118-4382-bad4-b6cfd24b3555)

**Comment by WeiboXu** [comment]
I met the same issue.

**Comment by poweiw** [comment]
Hello @MIrandaStock ! Is this issue still relevant?
