### ISSUE TITLE
Building chatglm2-6b on single node multi gpus failed.

### ISSUE THREAD

**Issue by shaunxiong** [NVIDIA/TensorRT-LLM#84]
I run the file `tensorrt_llm/examples/chatglm2-6b/build.py` using the following commad to build chatglm2-6b model from huggface format to tensorrt-llm format. :

  ```bash

python3 build.py --model_dir=./pyTorchModel \
                 --dtype float16 \
                 --use_gpt_attention_plugin float16 \
                 --use_gemm_plugin float16 \
                 --parallel_build \
                 --world_size 4 \
                 --gpus_per_node 4

  ```

But I met the following error:

  ```bash

[10/24/2023-05:37:18] [TRT-LLM] [W] Parallelly build TensorRT engines. Please make sure that all of the 4 GPUs are totally free.
[10/24/2023-05:37:21] [TRT] [I] [MemUsageChange] Init CUDA: CPU +2, GPU +0, now: CPU 119, GPU 310 (MiB)
[10/24/2023-05:37:21] [TRT] [V] Trying to load shared library libnvinfer_builder_resource.so.9.1.0
[10/24/2023-05:37:21] [TRT] [V] Loaded shared library libnvinfer_builder_resource.so.9.1.0
[10/24/2023-05:37:21] [TRT] [I] [MemUsageChange] Init CUDA: CPU +14, GPU +0, now: CPU 114, GPU 310 (MiB)
[10/24/2023-05:37:21] [TRT] [I] [MemUsageChange] Init CUDA: CPU +2, GPU +0, now: CPU 119, GPU 310 (MiB)
[10/24/2023-05:37:21] [TRT] [I] [MemUsageChange] Init CUDA: CPU +2, GPU +0, now: CPU 119, GPU 310 (MiB)
[10/24/2023-05:37:21] [TRT] [V] Trying to load shared library libnvinfer_builder_resource.so.9.1.0
[10/24/2023-05:37:21] [TRT] [V] Loaded shared library libnvinfer_builder_resource.so.9.1.0
[10/24/2023-05:37:21] [TRT] [V] Trying to load shared library libnvinfer_builder_resource.so.9.1.0
[10/24/2023-05:37:21] [TRT] [V] Loaded shared library libnvinfer_builder_resource.so.9.1.0
[10/24/2023-05:37:21] [TRT] [V] Trying to load shared library libnvinfer_builder_resource.so.9.1.0
[10/24/2023-05:37:21] [TRT] [V] Loaded shared library libnvinfer_builder_resource.so.9.1.0
[10/24/2023-05:37:22] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +483, GPU +80, now: CPU 737, GPU 390 (MiB)
[10/24/2023-05:37:22] [TRT] [V] CUDA lazy loading is enabled.
[10/24/2023-05:37:22] [TRT-LLM] [W] Invalid timing cache, using freshly created one
[10/24/2023-05:37:22] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +482, GPU +80, now: CPU 736, GPU 390 (MiB)
[10/24/2023-05:37:22] [TRT] [V] CUDA lazy loading is enabled.
[10/24/2023-05:37:22] [TRT-LLM] [W] Invalid timing cache, using freshly created one
[10/24/2023-05:37:22] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +483, GPU +80, now: CPU 737, GPU 390 (MiB)
[10/24/2023-05:37:22] [TRT] [V] CUDA lazy loading is enabled.
[10/24/2023-05:37:22] [TRT-LLM] [W] Invalid timing cache, using freshly created one
[10/24/2023-05:37:22] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +482, GPU +80, now: CPU 732, GPU 390 (MiB)
[10/24/2023-05:37:22] [TRT] [V] CUDA lazy loading is enabled.
[10/24/2023-05:37:22] [TRT-LLM] [W] Invalid timing cache, using freshly created one
loading weights from hugging face model
loading weights from hugging face model
loading weights from hugging face model
loading weights from hugging face model
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:14<00:00,  2.14s/it]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:16<00:00,  2.42s/it]
[10/24/2023-05:37:55] [TRT-LLM] [I] Loading weights from HF ChatGLM2...
[10/24/2023-05:37:55] [TRT-LLM] [I] Loading weights from HF ChatGLM2...
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:17<00:00,  2.50s/it]
[10/24/2023-05:37:55] [TRT-LLM] [I] Loading weights from HF ChatGLM2...
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:17<00:00,  2.51s/it]
[10/24/2023-05:37:55] [TRT-LLM] [I] Loading weights from HF ChatGLM2...
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/chatglm2-6b/build.py", line 391, in <module>
    mp.spawn(build, nprocs=args.world_size, args=(args, ))
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/code/tensorrt_llm/examples/chatglm2-6b/build.py", line 361, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/code/tensorrt_llm/examples/chatglm2-6b/build.py", line 264, in build_rank_engine
    tensorrt_llm_ChatGLM2_6BModel = load_from_hf_chatglm2_6B(
  File "/code/tensorrt_llm/examples/chatglm2-6b/weight.py", line 64, in load_from_hf_chatglm2_6B
    tensorrt_llm_model.lm_head.weight.value = hf_model.transformer.output_layer.weight.detach(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/parameter.py", line 66, in value
    assert v.shape == self._value.shape, \
AssertionError: ('The value updated is not the same shape as the original. ', 'Updated: (65024, 4096), original: (16256, 4096)')


  ```
When `--world_size=1` , it runs well, but failed on multi gpus.

**Comment by byshiue** [comment]
> ```shell
> python3 build.py --model_dir=./pyTorchModel \
>                --dtype float16 \
>                --use_gpt_attention_plugin float16 \
>                --use_gemm_plugin float16 \
>                --parallel_build \
>                --world_size 4 \
>                --gpus_per_node 4
> ```

@shaunxiong TensorRT-LLM does not support chatglm2 with model parallelism now although there are related args in the `build.py`. Sorry for confusion.
