### ISSUE TITLE
tensorrt_llm installation issue 

### ISSUE THREAD

**Issue by venergiac-bh** [NVIDIA/TensorRT-LLM#867]
CUDA 12.3

```
!apt-get update && apt-get -y install openmpi-bin libopenmpi-dev
# Install the latest version of TensorRT-LLM
#!pip3 install tensorrt_llm --no-cache-dir --extra-index-url https://pypi.nvidia.com
!pip3 install tensorrt_llm --no-cache --extra-index-url https://pypi.nvidia.com --extra-index-url https://download.pytorch.org/whl/cu121 --trusted-host pypi.nvidia.com --trusted-host download.pytorch.org
```

I got

```
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease                 
Hit:3 http://archive.ubuntu.com/ubuntu focal-backports InRelease               
Hit:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease
Hit:5 http://security.ubuntu.com/ubuntu focal-security InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libopenmpi-dev is already the newest version (4.0.3-0ubuntu1).
openmpi-bin is already the newest version (4.0.3-0ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com/, https://download.pytorch.org/whl/cu121
Collecting tensorrt_llm
  Downloading tensorrt-llm-0.7.1.tar.gz (6.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-d5f67wfx/tensorrt-llm_52e127aadfc34ddd816ee04efe6dad38/setup.py", line 90, in <module>
          raise RuntimeError("Bad params")
      RuntimeError: Bad params
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Shixiaowei02** [comment]
Please ensure that you are using Python 3.10 because TensorRT-LLM requires it currently, thanks!
