### ISSUE TITLE
TypeError: LLaMAForCausalLM.__init__() got an unexpected keyword argument 'enable_pos_shift'

### ISSUE THREAD

**Issue by realhaik** [NVIDIA/TensorRT-LLM#874]
Hey guys,

What is this jaw dropping nightmare that you put me thru? 

PS C:\AI\TensorRT\TensorRT-LLM\examples\llama> python build.py --meta_ckpt_dir C:/AI/LLaMA2_Docker_FileSystem/codellama/CodeLlama-7b-Instruct/ --dtype float16 --remove_input_padding --use_gpt_attention_plugin float16 --use_gemm_plugin float16 --enable_context_fmha --output_dir codellama_7b --rotary_base 1000000 --vocab_size 32016
[01/13/2024-02:22:31] [TRT-LLM] [I] Serially build TensorRT engines.
[01/13/2024-02:22:33] [TRT] [I] [MemUsageChange] Init CUDA: CPU +2497, GPU +0, now: CPU 24169, GPU 2473 (MiB)
[01/13/2024-02:22:35] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +2734, GPU +314, now: CPU 27170, GPU 2787 (MiB)
[01/13/2024-02:22:35] [TRT] [W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
[01/13/2024-02:22:35] [TRT-LLM] [W] Invalid timing cache, using freshly created one
[01/13/2024-02:22:35] [TRT-LLM] [I] [MemUsage] Rank 0 Engine build starts - Allocated Memory: Host 6.9300 (GiB) Device 1.5781 (GiB)
Traceback (most recent call last):
  File "C:\AI\TensorRT\TensorRT-LLM\examples\llama\build.py", line 983, in <module>
    build(0, args)
  File "C:\AI\TensorRT\TensorRT-LLM\examples\llama\build.py", line 927, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "C:\AI\TensorRT\TensorRT-LLM\examples\llama\build.py", line 670, in build_rank_engine
    tensorrt_llm_llama = tensorrt_llm.models.LLaMAForCausalLM(
TypeError: LLaMAForCausalLM.__init__() got an unexpected keyword argument 'enable_pos_shift'
PS C:\AI\TensorRT\TensorRT-LLM\examples\llama>

**Comment by byshiue** [comment]
Could you check that you can find the parameter here https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/models/llama/model.py#L357? You might not install the latest TRT LLM version successfully.

**Comment by 0xMatthew** [comment]
i'm also having the same issue. can we not use 0.7.1 on Windows? do we have to use 0.6.1 instead?

i'm getting the same error as @realhaik when using tensorrt_llm 0.7.1:
`TypeError: LLaMAForCausalLM.__init__() got an unexpected keyword argument 'enable_pos_shift'`

when i use pip to downgrade to tensorrt_llm 0.6.1 and run build.py again, i get a different error:
`ImportError: cannot import name 'MoeConfig' from 'tensorrt_llm.layers'`

command that i'm running both times:
`python build.py --model_dir "C:\Users\<username>\Desktop\NVIDIA\Llama-2-7b-hf" --dtype float16 --remove_input_padding --use_gpt_attention_plugin float16 --enable_context_fmha --use_gemm_plugin float16 --use_weight_only --output_dir "E:\LLAMA_13B\NVIDIA\TRT_engine\"`

**Comment by 0xMatthew** [comment]
i figured out what my issue was. this fix works for Windows.

1.) ensure that you installed the pip package tensorrt_llm 0.6.1 on windows:
`pip install tensorrt_llm==0.6.1 --extra-index-url https://pypi.nvidia.com` 

a.) verify that you indeed have tensorrt_llm 0.6.1 installed using `pip show tensorrt_llm`. your output should be something like the following:
`Name: tensorrt-llm
Version: 0.6.1`

2.) you also need to use the 0.6.1 release of this repo found here: https://github.com/NVIDIA/TensorRT-LLM/releases/tag/v0.6.1
^^ download the .zip of the repo, extract it to your local device. navigate into the top-level folder, then try to run `build.py` in the repo's `\examples\llama` folder.

**Comment by nv-guomingz** [comment]
please feel free to reopen this ticket if needed.
