### ISSUE TITLE
Missing config file for T5

### ISSUE THREAD

**Issue by kimihailv** [NVIDIA/TensorRT-LLM#887]
I am trying to build the flan-t5-xxl's engine for BLIP2. But this error encountered:

```python
[01/15/2024-15:03:31] [TRT-LLM] [I] Setting model configuration from tmp/hf_models/flan-t5-xxl.
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/multimodal/../enc_dec/build.py", line 568, in <module>
    run_build(component='encoder')
  File "/code/tensorrt_llm/examples/multimodal/../enc_dec/build.py", line 542, in run_build
    args = parse_arguments(component)
  File "/code/tensorrt_llm/examples/multimodal/../enc_dec/build.py", line 273, in parse_arguments
    args = parse_config(
  File "/code/tensorrt_llm/examples/multimodal/../enc_dec/build.py", line 48, in parse_config
    assert ini_file.exists(), f"Missing config file {ini_file}"
AssertionError: Missing config file tmp/hf_models/flan-t5-xxl/config.ini
```

**Comment by symphonylyh** [comment]
Hi @kimihailv , from the [README](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/multimodal#blip--t5), you should first run the `t5/convert.py` script and then use `--weight_dir tmp/hf_models/${MODEL_NAME}/tp1` for your build call. 
`tmp/hf_models/${MODEL_NAME}/` is the original HuggingFace weights, and `tmp/hf_models/${MODEL_NAME}/tp1` is the TRT-LLM weight format.

I believe this can fix this. I'll close the issue for now, and feel free to re-open!
