### ISSUE TITLE
Failed to launch Triton for Llama

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/TensorRT-LLM#89]
What does this mean?

ERROR: Failed to create instance: unexpected error when creating modelInstanceState: TrtGptModelInflightBatching requires GPT attention plugin with packed input and paged KV cache.
E1024 07:33:56.907690 74602 model_lifecycle.cc:622] failed to load 'tensorrt_llm' version 1: Internal: unexpected error when creating modelInstanceState: TrtGptModelInflightBatching requires GPT attention plugin with packed input and paged KV cache.

```
[TensorRT-LLM][INFO] Initializing MPI with thread mode 1
I1024 07:33:39.624732 74602 python_be.cc:2115] TRITONBACKEND_ModelInstanceInitialize: postprocessing_0_0 (CPU device 0)
I1024 07:33:39.624917 74602 python_be.cc:2115] TRITONBACKEND_ModelInstanceInitialize: preprocessing_0_0 (CPU device 0)
I1024 07:33:40.100045 74602 model_lifecycle.cc:819] successfully loaded 'postprocessing'
I1024 07:33:41.456487 74602 model_lifecycle.cc:819] successfully loaded 'preprocessing'
[TensorRT-LLM][INFO] MPI size: 1, rank: 0
[TensorRT-LLM][INFO] TRTGptModel maxNumSequences: 16
[TensorRT-LLM][INFO] TRTGptModel maxBatchSize: 8
[TensorRT-LLM][INFO] TRTGptModel enableTrtOverlap: 1
[TensorRT-LLM][INFO] Loaded engine size: 12856 MiB
[TensorRT-LLM][INFO] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 13201, GPU 13175 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] Init cuDNN: CPU +1, GPU +10, now: CPU 13202, GPU 13185 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +12852, now: CPU 0, GPU 12852 (MiB)
E1024 07:33:56.907623 74602 backend_model.cc:553] ERROR: Failed to create instance: unexpected error when creating modelInstanceState: TrtGptModelInflightBatching requires GPT attention plugin with packed input and paged KV cache.
E1024 07:33:56.907690 74602 model_lifecycle.cc:622] failed to load 'tensorrt_llm' version 1: Internal: unexpected error when creating modelInstanceState: TrtGptModelInflightBatching requires GPT attention plugin with packed input and paged KV cache.
I1024 07:33:56.907712 74602 model_lifecycle.cc:757] failed to load 'tensorrt_llm'
E1024 07:33:56.907796 74602 model_repository_manager.cc:563] Invalid argument: ensemble 'ensemble' depends on 'tensorrt_llm' which has no loaded version. Model 'tensorrt_llm' loading failed with error: version 1 is at UNAVAILABLE state: Internal: unexpected error when creating modelInstanceState: TrtGptModelInflightBatching requires GPT attention plugin with packed input and paged KV cache.;
I1024 07:33:56.907861 74602 server.cc:604]
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I1024 07:33:56.908035 74602 server.cc:631]
+-------------+-----------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Backend     | Path                                                            | Config                                                                                                                                                                                             |
+-------------+-----------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| pytorch     | /opt/tritonserver/backends/pytorch/libtriton_pytorch.so         | {}                                                                                                                                                                                                 |
| tensorrtllm | /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so | {"cmdline":{"auto-complete-config":"false","backend-directory":"/opt/tritonserver/backends","min-compute-capability":"6.000000","default-max-batch-size":"4"}}                                     |
| python      | /opt/tritonserver/backends/python/libtriton_python.so           | {"cmdline":{"auto-complete-config":"false","backend-directory":"/opt/tritonserver/backends","min-compute-capability":"6.000000","shm-region-prefix-name":"prefix0_","default-max-batch-size":"4"}} |
+-------------+-----------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by jdemouth-nvidia** [comment]
Can you add the commands to reproduce the issue, please? 

Based on that message:

```
ERROR: Failed to create instance: unexpected error when creating modelInstanceState: TrtGptModelInflightBatching requires GPT attention plugin with packed input and paged KV cache.
```

I guess you built an engine without **GPT attention plugin with packed input and paged KV cache** but you are trying to use in-flight batching in Triton.

**Comment by sleepwalker2017** [comment]
> Can you add the commands to reproduce the issue, please?
> 
> Based on that message:
> 
> ```
> ERROR: Failed to create instance: unexpected error when creating modelInstanceState: TrtGptModelInflightBatching requires GPT attention plugin with packed input and paged KV cache.
> ```
> 
> I guess you built an engine without **GPT attention plugin with packed input and paged KV cache** but you are trying to use in-flight batching in Triton.

So I need to turn off inflight batching  or I need to rebuild the model, right?

**Comment by sleepwalker2017** [comment]
> Can you add the commands to reproduce the issue, please?
> 
> Based on that message:
> 
> ```
> ERROR: Failed to create instance: unexpected error when creating modelInstanceState: TrtGptModelInflightBatching requires GPT attention plugin with packed input and paged KV cache.
> ```
> 
> I guess you built an engine without **GPT attention plugin with packed input and paged KV cache** but you are trying to use in-flight batching in Triton.

Hello, I turn off the inflight batching and the server is started. 

Then I want to find a client example file and I turn to the `tensorrtllm_backend/tools/inflight_batcher_llm/end_to_end_test.py` file.

But it needs a dataset file, Is there any example for it? I think it need specific format.

**Comment by sleepwalker2017** [comment]
Can I use this to send request? I did this but it complains 
```
tritonclient.utils.InferenceServerException: [StatusCode.UNIMPLEMENTED] ModelInfer RPC doesn't support models with decoupled transaction policy
```

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/26128514/1a2704ee-e631-47a4-bff9-598ee9d523b2)

**Comment by jdemouth-nvidia** [comment]
We have a colleague who wrote a blog post on deploying with TensorRT-LLM : https://developer.nvidia.com/blog/optimizing-inference-on-llms-with-tensorrt-llm-now-publicly-available/

It shows how to send requests.

**Comment by sleepwalker2017** [comment]
> We have a colleague who wrote a blog post on deploying with TensorRT-LLM : https://developer.nvidia.com/blog/optimizing-inference-on-llms-with-tensorrt-llm-now-publicly-available/
> 
> It shows how to send requests.

Hi, I tried that and get similar error.
```
python send.py
Traceback (most recent call last):
  File "/data/weilong.yu/trt-llm/tensorrtllm_backend/inflight_batcher_llm/client/send.py", line 23, in <module>
    result = client.infer("ensemble", inputs)
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/http/_client.py", line 1468, in infer
    _raise_if_error(response)
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/http/_utils.py", line 69, in _raise_if_error
    raise error
tritonclient.utils.InferenceServerException: [400] HTTP end point doesn't support models with decoupled transaction policy
```

Here is the log after triton server starts:

```
I1025 02:47:40.479663 80876 server.cc:674]
+----------------+---------+--------+
| Model          | Version | Status |
+----------------+---------+--------+
| ensemble       | 1       | READY  |
| postprocessing | 1       | READY  |
| preprocessing  | 1       | READY  |
| tensorrt_llm   | 1       | READY  |
+----------------+---------+--------+

I1025 02:47:40.717556 80876 metrics.cc:810] Collecting metrics for GPU 0: NVIDIA A30
I1025 02:47:40.717579 80876 metrics.cc:810] Collecting metrics for GPU 1: NVIDIA A30
I1025 02:47:40.718082 80876 metrics.cc:703] Collecting CPU metrics
I1025 02:47:40.718233 80876 tritonserver.cc:2435]
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                                                        |
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                                                       |
| server_version                   | 2.37.0                                                                                                                                                                       |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data  |
|                                  | parameters statistics trace logging                                                                                                                                          |
| model_repository_path[0]         | ./triton_model_repo/                                                                                                                                                         |
| model_control_mode               | MODE_NONE                                                                                                                                                                    |
| strict_model_config              | 1                                                                                                                                                                            |
| rate_limit                       | OFF                                                                                                                                                                          |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                    |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                                                                     |
| cuda_memory_pool_byte_size{1}    | 67108864                                                                                                                                                                     |
| min_supported_compute_capability | 6.0                                                                                                                                                                          |
| strict_readiness                 | 1                                                                                                                                                                            |
| exit_timeout                     | 30                                                                                                                                                                           |
| cache_enabled                    | 0                                                                                                                                                                            |
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

I1025 02:47:40.719477 80876 grpc_server.cc:2451] Started GRPCInferenceService at 0.0.0.0:8001
I1025 02:47:40.719724 80876 http_server.cc:3558] Started HTTPService at 0.0.0.0:8000
I1025 02:47:41.198820 80876 http_server.cc:187] Started Metrics Service at 0.0.0.0:8002
```

The code is here : https://developer.nvidia.com/blog/optimizing-inference-on-llms-with-tensorrt-llm-now-publicly-available/#:~:text=all_models/inflight_batcher_llm-,Sending%20requests,-To%20send%20requests

**Comment by uppalutkarsh** [comment]
If you intent to use decoupled mode (streaming) for model serving, please use `<ip>:8001` (or `localhost:8001`) as endpoint (grpc) instead of `8000` port number (http).

https://github.com/triton-inference-server/tensorrtllm_backend/blob/release/0.5.0/all_models/inflight_batcher_llm/tensorrt_llm/config.pbtxt#L32

**Comment by sleepwalker2017** [comment]
> If you intent to use decoupled mode (streaming) for model serving, please use `<ip>:8001` (or `localhost:8001`) as endpoint (grpc) instead of `8000` port number (http).
> 
> https://github.com/triton-inference-server/tensorrtllm_backend/blob/release/0.5.0/all_models/inflight_batcher_llm/tensorrt_llm/config.pbtxt#L32

Thank you for the reply. 

You mean streaming is supported only in GRPC mode?

From the log, 8081 is a GRPC port. I can't send request to this port using the current client file.  Do you have an example?

Or, how can I disable the decouple mode? I don't know how to use non-streaming mode.

**Comment by byshiue** [comment]
Please try set here https://github.com/triton-inference-server/tensorrtllm_backend/blob/release/0.5.0/all_models/inflight_batcher_llm/tensorrt_llm/config.pbtxt#L32 to `False`.

**Comment by sleepwalker2017** [comment]
> Please try set here https://github.com/triton-inference-server/tensorrtllm_backend/blob/release/0.5.0/all_models/inflight_batcher_llm/tensorrt_llm/config.pbtxt#L32 to `False`.

Thank you! It works!

How can I print the text output?

In this way, I can't see the text.
```python
result = client.infer("ensemble", inputs)
print(result)
```
<img width="1716" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/26128514/227b9d8c-2c4b-4876-9e72-b9e398323aa3">

**Comment by sleepwalker2017** [comment]
> Please try set here https://github.com/triton-inference-server/tensorrtllm_backend/blob/release/0.5.0/all_models/inflight_batcher_llm/tensorrt_llm/config.pbtxt#L32 to `False`.

And another question, only GRPC supports streaming output? Is that the fact?

**Comment by uppalutkarsh** [comment]
> You mean streaming is supported only in GRPC mode?

To use streaming the default endpoint is 8001 (not 8081)

**Comment by sleepwalker2017** [comment]
> > You mean streaming is supported only in GRPC mode?
> 
> To use streaming the default endpoint is 8001 (not 8081)

```
I1025 08:16:46.669373 85102 grpc_server.cc:2451] Started GRPCInferenceService at 0.0.0.0:8001
I1025 08:16:46.669634 85102 http_server.cc:3558] Started HTTPService at 0.0.0.0:8000
I1025 08:16:46.762788 85102 http_server.cc:187] Started Metrics Service at 0.0.0.0:8002
```

Yes, it's 8001, that's a typo. 
The log shows 8001 is grpc port. I only see an example for http client.

**Comment by uppalutkarsh** [comment]
You can use [this](https://github.com/triton-inference-server/tensorrtllm_backend/blob/release/0.5.0/tools/inflight_batcher_llm/end_to_end_streaming_client.py) script for streaming mode.

**Comment by sleepwalker2017** [comment]
> You can use [this](https://github.com/triton-inference-server/tensorrtllm_backend/blob/release/0.5.0/tools/inflight_batcher_llm/end_to_end_streaming_client.py) script for streaming mode.

Thank you! I see that. And to print result, I can use this
```python
text = result.as_numpy('text_output')
print(text)
```

**Comment by sleepwalker2017** [comment]
> You can use [this](https://github.com/triton-inference-server/tensorrtllm_backend/blob/release/0.5.0/tools/inflight_batcher_llm/end_to_end_streaming_client.py) script for streaming mode.

Hi, how can I set top_k and top_p in the client?

I modify the code here, but it complains that `unexpected inference input 'runtime_top_p' for model 'ensemble'`
```python
def test(triton_client, prompt):
    model_name = "ensemble"

    input0 = [[prompt]]
    input0_data = np.array(input0).astype(object)
    output0_len = np.ones_like(input0).astype(np.uint32) * FLAGS.output_len
    bad_words_list = np.array([[""]], dtype=object)
    stop_words_list = np.array([[""]], dtype=object)
    streaming = [[FLAGS.streaming]]
    streaming_data = np.array(streaming, dtype=bool)
    top_k = np.array([[3]], dtype=np.uint32)
    top_p = np.array([[0]], dtype=np.float32)

    inputs = [
        utils.prepare_tensor("text_input", input0_data, FLAGS.protocol),
        utils.prepare_tensor("max_tokens", output0_len, FLAGS.protocol),
        utils.prepare_tensor("bad_words", bad_words_list, FLAGS.protocol),
        utils.prepare_tensor("stop_words", stop_words_list, FLAGS.protocol),
        utils.prepare_tensor("stream", streaming_data, FLAGS.protocol),
        utils.prepare_tensor("runtime_top_k", top_k, FLAGS.protocol),
        utils.prepare_tensor("runtime_top_p", top_p, FLAGS.protocol),
    ]
```

**Comment by byshiue** [comment]
Close this bug because the issue is resolved. Feel free to ask here if you still have question/issue, we will reopen the issue.

**Comment by Boom199801** [comment]
ERROR: Failed to create instance: unexpected error when creating modelInstanceState: maxTokensInPagedKvCache must be large enough to process at least 1 sequence to completion (i.e. must be larger than beam_width * tokensPerBlock * maxBlocksPerSeq)
E1220 03:14:46.995583 24196 model_lifecycle.cc:621] failed to load 'tensorrt_llm' version 1: Internal: unexpected error when creating modelInstanceState: maxTokensInPagedKvCache must be large enough to process at least 1 sequence to completion (i.e. must be larger than beam_width * tokensPerBlock * maxBlocksPerSeq)
I1220 03:14:46.995632 24196 model_lifecycle.cc:756] failed to load 'tensorrt_llm'          Hello, I encountered the same problem as you and tried the following methods, but did not find a solution. May I ask how the boss operated it

**Comment by sleepwalker2017** [comment]
> ERROR: Failed to create instance: unexpected error when creating modelInstanceState: maxTokensInPagedKvCache must be large enough to process at least 1 sequence to completion (i.e. must be larger than beam_width * tokensPerBlock * maxBlocksPerSeq) E1220 03:14:46.995583 24196 model_lifecycle.cc:621] failed to load 'tensorrt_llm' version 1: Internal: unexpected error when creating modelInstanceState: maxTokensInPagedKvCache must be large enough to process at least 1 sequence to completion (i.e. must be larger than beam_width * tokensPerBlock * maxBlocksPerSeq) I1220 03:14:46.995632 24196 model_lifecycle.cc:756] failed to load 'tensorrt_llm' Hello, I encountered the same problem as you and tried the following methods, but did not find a solution. May I ask how the boss operated it

I think the triton server error message makes it hard to locate the problem.
