### ISSUE TITLE
Tensor shape mismatch when doing smoothquant for Yi-34B

### ISSUE THREAD

**Issue by xikaluo** [NVIDIA/TensorRT-LLM#895]
Hello, I just tried to use code in TensorRT-LLM/blob/main/examples/llama to do smoothquant for Yi-34B model, but I met tensor shape mismatch in building engine on 4 GPU.

The command I use to do smoothquant is :
```
python3 hf_llama_convert.py \
    --in-file ./models/yi \
    --out-dir ./engines/yi/sq05 \
    --smoothquant 0.5 \
    --tensor-parallelism 1 \
    --storage-type fp16 \
    --processes 1
```
After convert, I got many bin file in output_dir, which seems OK.

The command used to build engine is:
```
python build.py \
    --bin_model_dir ./engines/yi/sq05/1-gpu \
    --output_dir ./engines/yi/fp16/4-gpu \
    --max_input_len 8192 \
    --max_output_len 512 \
    --max_batch_size 1 \
    --max_beam_width 1 \
    --dtype float16 \
    --use_gpt_attention_plugin float16 \
    --remove_input_padding \
    --enable_context_fmha_fp32 \
    --use_gemm_plugin float16 \
    --world_size 4 \
    --pp_size 4 \
    --use_smooth_quant \
    --per_channel \
    --per_token
```

The error msg is:
```
Traceback (most recent call last):
  File "/data/projects/tensorRT-LLM-test/build_engine/llama/build.py", line 983, in <module>
    build(0, args)
  File "/data/projects/tensorRT-LLM-test/build_engine/llama/build.py", line 927, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/data/projects/tensorRT-LLM-test/build_engine/llama/build.py", line 777, in build_rank_engine
    load_from_binary(tensorrt_llm_llama,
  File "/data/miniconda3/envs/TensorRT-LLM-cu122-cpp/lib/python3.10/site-packages/tensorrt_llm/models/llama/weight.py", line 1019, in load_from_binary
    t = fromfile(
  File "/data//miniconda3/envs/TensorRT-LLM-cu122-cpp/lib/python3.10/site-packages/tensorrt_llm/models/llama/weight.py", line 901, in fromfile
    t = t.reshape(shape)
ValueError: cannot reshape array of size 66060288 into shape (7168,8960)
```
And I found that this error occured in loading file ./engines/yi/sq05/1-gpu/model.layers.0.attention.query_key_value.weight.int8.col.0.bin
In addition, do smoothquant in TP=4 or TP=1 would both got this error

**Comment by byshiue** [comment]
Please follow the `bug_report.yml` template to share the infomation of your issue, thanks.

**Comment by xikaluo** [comment]
> I found that this error occured in loading file ./engines/yi/sq05/1-gpu/model.layers.0.attention.query_key_value.weight.int8.col.0.bin
> In addition, do smoothquant in TP=4 or TP=1 would both got this error

Create a new issue with the template here: https://github.com/NVIDIA/TensorRT-LLM/issues/899
