### ISSUE TITLE
build from source fail

### ISSUE THREAD

**Issue by park12sj** [NVIDIA/TensorRT-LLM#914]
### System Info

- cpu 
```
root@personal-sangjune-trt-llm-0:/workspace/storage/cephfs-personal/git/pai/paip-TensorRT-LLM# lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  40
  On-line CPU(s) list:   0-39
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Xeon(R) Silver 4210 CPU @ 2.20GHz
    CPU family:          6
    Model:               85
    Thread(s) per core:  2
    Core(s) per socket:  10
    Socket(s):           2
    Stepping:            7
    BogoMIPS:            4400.00
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_
                         1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdsee
                         d adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
Virtualization features: 
  Virtualization:        VT-x
Caches (sum of all):     
  L1d:                   640 KiB (20 instances)
  L1i:                   640 KiB (20 instances)
  L2:                    20 MiB (20 instances)
  L3:                    27.5 MiB (2 instances)
NUMA:                    
  NUMA node(s):          2
  NUMA node0 CPU(s):     0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38
  NUMA node1 CPU(s):     1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39
Vulnerabilities:         
  Itlb multihit:         KVM: Mitigation: VMX disabled
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Vulnerable
  Retbleed:              Vulnerable
  Spec store bypass:     Vulnerable
  Spectre v1:            Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
  Spectre v2:            Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Vulnerable
  Srbds:                 Not affected
  Tsx async abort:       Vulnerable
```
- gpu
```
root@personal-sangjune-trt-llm-0:/workspace/storage/cephfs-personal/git/pai/paip-TensorRT-LLM# nvidia-smi
Fri Jan 19 01:43:33 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:3B:00.0 Off |                    0 |
| N/A   34C    P8              14W /  70W |      2MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla T4                       Off | 00000000:D8:00.0 Off |                    0 |
| N/A   37C    P8              14W /  70W |      2MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```
- commit : c89653021e66ca78c55f02b366f404455bc12e8d

### Who can help?

@byshiue 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. build image for building whl https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/build_from_source.md#on-systems-without-gnu-make
2. create container and whl build https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/build_from_source.md#build-tensorrt-llm

### Expected behavior

Build Success

### actual behavior

1. error occuered when pip install nvidia-ammo
```
Collecting nvidia-ammo~=0.5.0 (from -r requirements.txt (line 18))
  Downloading nvidia-ammo-0.5.1.tar.gz (6.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-cwksnwhn/nvidia-ammo_375eeb4e0f7248fea8e87aaffc9f0eec/setup.py", line 90, in <module>
          raise RuntimeError("Bad params")
      RuntimeError: Bad params
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```
2. if ignore installing nvidia-ammo, build is fail
```
[ 93%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/decoderMaskedMultiheadAttention/decoderMaskedMultiheadAttention64_half.cu.o
[ 93%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/decoderMaskedMultiheadAttention/decoderMaskedMultiheadAttention80_bf16.cu.o
[ 93%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/decoderMaskedMultiheadAttention/decoderMaskedMultiheadAttention80_float.cu.o
[ 93%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/decoderMaskedMultiheadAttention/decoderMaskedMultiheadAttention80_half.cu.o
[ 93%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/decoderMaskedMultiheadAttention/decoderMaskedMultiheadAttention96_bf16.cu.o
[ 93%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/decoderMaskedMultiheadAttention/decoderMaskedMultiheadAttention96_float.cu.o
[ 93%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/decoderMaskedMultiheadAttention/decoderMaskedMultiheadAttention96_half.cu.o
nvcc error   : 'ptxas' died due to signal 9 (Kill signal)
gmake[3]: *** [tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/build.make:8149: tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/decoderMaskedMultiheadAttention/decoderMaskedMultiheadAttention144_half.cu.o] Error 9
gmake[3]: *** Waiting for unfinished jobs....
nvcc error   : 'ptxas' died due to signal 9 (Kill signal)
gmake[3]: *** [tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/build.make:8164: tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/decoderMaskedMultiheadAttention/decoderMaskedMultiheadAttention160_bf16.cu.o] Error 9
gmake[2]: *** [CMakeFiles/Makefile2:865: tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:790: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/rule] Error 2
gmake: *** [Makefile:192: tensorrt_llm] Error 2
Traceback (most recent call last):
  File "/workspace/storage/cephfs-personal/git/pai/paip-TensorRT-LLM/./scripts/build_wheel.py", line 306, in <module>
    main(**vars(args))
  File "/workspace/storage/cephfs-personal/git/pai/paip-TensorRT-LLM/./scripts/build_wheel.py", line 164, in main
    build_run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cmake --build . --config Release --parallel 40 --target tensorrt_llm tensorrt_llm_static nvinfer_plugin_tensorrt_llm th_common bindings ' returned non-zero exit status 2.
```

### additional notes

I don't know if it's related, but the error that occurs when pip install version 0.7.1 is the same as the error that occurs in the nvidia-ammo install during build.

https://github.com/NVIDIA/TensorRT-LLM/issues/777#issuecomment-1895562944

**Comment by Tlntin** [comment]
cpu memory? 64GB may need when compile.

**Comment by park12sj** [comment]
@Tlntin 

Oh, it's 50GB... I'll go over 64GB and try again.
I wonder if you have any opinions about the nvidia-ammo installation error.

**Comment by Tlntin** [comment]
> I wonder if you have any opinions about the nvidia-ammo installation error.

what's your python version? nvidia-ammo only support python 3.10.

**Comment by park12sj** [comment]
@Tlntin 

I am using 3.10 version.
```
root@personal-sangjune-trt-llm-0:/workspace/storage/cephfs-personal/git/pai/paip-TensorRT-LLM# python --version
Python 3.10.12
```

I'm trying to do a whl build in the container for build according to the guide
https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/build_from_source.md#on-systems-without-gnu-make

**Comment by Tlntin** [comment]
oh, maybe other error, i will watch nvidia ammo setup.py source code after a moment.

**Comment by Tlntin** [comment]
maybe you can try install nvidia-ammo with this command
```bash
pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com nvidia-ammo~=0.5.0
```
when you install nvidia-ammo,
the torch, tensorrt-llm, mpi4py must have installed.

**Comment by park12sj** [comment]
Thank you for the guidance.

By the way, nvidia-ammo is a requirement for tensorrt-llm, when installing nvidia-ammo, if tensorrt-llm is required to be installed, is there no dependency between each other?
https://github.com/NVIDIA/TensorRT-LLM/blob/c89653021e66ca78c55f02b366f404455bc12e8d/requirements.txt#L18

**Comment by Tlntin** [comment]
> Thank you for the guidance.
> 
> By the way, nvidia-ammo is a requirement for tensorrt-llm, when installing nvidia-ammo, if tensorrt-llm is required to be installed, is there no dependency between each other?
> 
> https://github.com/NVIDIA/TensorRT-LLM/blob/c89653021e66ca78c55f02b366f404455bc12e8d/requirements.txt#L18

This may be a bug, in the previous 0.7.0/0.6.0/0.5.0 versions, tensorrt-llm was installed first, and then nvidia-ammo. I haven't tried the compilation of 0.7.1 though, so I can't be sure yet.

**Comment by park12sj** [comment]
Thank you for your answer. I'll close the issue.
