### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers_modules' on build LLM()

### ISSUE THREAD

**Issue by xesdiny** [NVIDIA/TensorRT-LLM#919]
### System Info

-CPU architecture x86_64
-GPU name NVIDA V100
-GPU memory size 32G*8
-TensorRT-LLM branch main[c896530]

### Who can help?

 @ncomly-nvidia

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Use tensorllm AsyncLLMEngine loading builded engine.
Used weight: llama 7b 
Used engine: weight int8 +kv_cahe  TP=2.
I have switched to main[c896530] and re-completed the installation package building according to this [guide](https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/build_from_source.md#link-with-the-tensorrt-llm-c-runtime).

Next my command show

```script
...
adding 'tensorrt_llm-0.7.1.dist-info/zip-safe'
adding 'tensorrt_llm-0.7.1.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Successfully built tensorrt_llm-0.7.1-cp310-cp310-linux_x86_64.whl

$ pip uninstall tensorrt_llm
$ pip install build/tensorrt_llm-0.7.1-cp310-cp310-linux_x86_64.whl
....
Installing collected packages: tensorrt-llm
Successfully installed tensorrt-llm-0.7.1

$ python 
>>> from transformers import AutoTokenizer
>>> from tensorrt_llm import LLM, ModelConfig
>>> trt_model= "[llama7b_builded_engined_path]"
>>> config = ModelConfig(model_dir=llama_model_path)
>>> tokenizer= AutoTokenizer.from_pretrained(trt_model+"/tokenzier",trust_remote_code=True)
>>> config = ModelConfig(model_dir=trt_model)
### set TP& weight only+kv_cache
>>> config.parallel_config.tp_size=2
>>>config.quant_config.init_from_description(
...                        quantize_weights=True,
...                                        quantize_activations=False,
...                       use_int8_kv_cache=True)
>>> llm = LLM(config,tokenizer)

>>>async for output in llm.generate_async(<prompt>, streaming=True):
    print(output)
```

### Expected behavior

print sampling text

### actual behavior

```python
>>> llm = LLM(config,tokenizer)
[1705672763.733962] [dev-aigc-20:48570:f]        vfs_fuse.c:281  UCX  ERROR inotify_add_watch(/tmp) failed: No space left on device
[1705672763.733963] [dev-aigc-20:48569:f]        vfs_fuse.c:281  UCX  ERROR inotify_add_watch(/tmp) failed: No space left on device
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/hlapi/llm.py", line 172, in __init__
    self._build_model()
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/hlapi/llm.py", line 323, in _build_model
    return build_sync()
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/hlapi/llm.py", line 277, in build_sync
    res.append(future.result())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
ModuleNotFoundError: No module named 'transformers_modules'
```

### additional notes

Ymm.

**Comment by Superjomn** [comment]
Are you referring to [this guide](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/high-level-api#asynchronous-generation) for the high-level-api?

I found a mistake in the code you provided:

To use the async generate in your code:
```
>>>async for output in llm.generate_async(<prompt>, streaming=True):
    print(output)
```

You should pass `async_mode=True` in LLM's constructor like `llm = LLM(config, tokenizer, async_mode=True)`.

And just so you know, currently, only the LLaMA model is supported, when input other models, the behavior will be unknown,

If you still get errors, please offer the docker image, and I will reproduce it.

**Comment by xesdiny** [comment]
> Are you referring to [this guide](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/high-level-api#asynchronous-generation) for the high-level-api?
> 
> I found a mistake in the code you provided:
> 
> To use the async generate in your code:
> 
> ```
> >>>async for output in llm.generate_async(<prompt>, streaming=True):
>     print(output)
> ```
> 
> You should pass `async_mode=True` in LLM's constructor like `llm = LLM(config, tokenizer, async_mode=True)`.
> 
> And just so you know, currently, only the LLaMA model is supported, when input other models, the behavior will be unknown,
> 
> If you still get errors, please offer the docker image, and I will reproduce it.

Yeah, I understood through guide.md that the sampling method I used should be wrong `generate_async` ->`generate`.
But the error message I reported above should be `llm = LLM(config,tokenizer)`.
So I use the `trt_model` path after builded is completed for `LLM().build_sync()`
It should be that in `def _node_build_task(...)` multi-gpu does not print the error log normally.
I tried to set `config.parallel_config.tp_size=1` and found the error message as
```script
>>> llm = LLM(config,tokenizer)
Loading Model: [1/2]    Load HF model to memory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/hlapi/llm.py", line 172, in __init__
    self._build_model()
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/hlapi/llm.py", line 323, in _build_model
    return build_sync()
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/hlapi/llm.py", line 283, in build_sync
    self.runtime_context = model_loader()
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/hlapi/llm.py", line 610, in __call__
    step()
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/hlapi/llm.py", line 733, in _build_model_from_hf
    self.model = model2struct[model_arch].from_hugging_face(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/model.py", line 648, in from_hugging_face
    tllm_llama._quantize(hf_model_dir, dtype, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/model.py", line 704, in _quantize
    assert ammo_qformat is not None
AssertionError
```
，
when ser config to 
```python
config.quant_config.init_from_description(
                       quantize_weights=False,
					   quantize_activations=False,
                      use_int8_kv_cache=False)
```
At this time, the log result is normal.

```
>>> llm = LLM(config,tokenizer)
Loading Model: [1/2]    Load HF model to memory
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.26s/it]
Time: 11.570s
Loading Model: [2/2]    Build TRT-LLM engine
Time: 35.991s
Loading model done.
Total latency: 47.561s
```

Therefore, there seems to be a problem with the process of quantized construction online. It can only support `int4_awq` & `fp8` and cannot implement `weight-only` or `smoothquant`.
in model/llama/model.py line 684:
```
...
def _quantize(self, hf_model_dir, dtype, **kwargs):
     quantized_temp_dir = tempfile.TemporaryDirectory("llama-quantized")
      quantized_checkpoint_path = kwargs.get("quantization_cache_dir",
                                             quantized_temp_dir.name)
      quantize_lm_head = kwargs.get("quantize_lm_head", False)
      quant_mode = self.quant_mode
      ammo_qformat = None
      calib_size = None
      if quant_mode.has_fp8_qdq() or quant_mode.has_fp8_kv_cache():
          ammo_qformat = 'fp8'
          calib_size = 512
      # TODO: how to distinguish from quant_mode about int4_awq or int4_gptq?
      elif quant_mode.is_int4_weight_only_per_group():
          ammo_qformat = 'int4_awq'
          calib_size = 32
      assert ammo_qformat is not None
```

**Comment by Superjomn** [comment]
> >>> config.parallel_config.tp_size=2

Oh, find another issue, currently, the TP is only supported for `LLM.generate()`, not `LLM.generate_async()`, the later one will soon be released.

The main branch is updated eagerly, you can refer to [test_llm.py](https://github.com/NVIDIA/TensorRT-LLM/blob/main/tests/hlapi/test_llm.py) for the tested cases, they are all tested on LLaMA model.

For quantization, [this example](https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/high-level-api/llm_examples.py#L68) is a preview, other cases might not be supported yet.

**Comment by xesdiny** [comment]
> > > > > config.parallel_config.tp_size=2
> 
> Oh, find another issue, currently, the TP is only supported for `LLM.generate()`, not `LLM.generate_async()`, the later one will soon be released.
> 
> The main branch is updated eagerly, you can refer to [test_llm.py](https://github.com/NVIDIA/TensorRT-LLM/blob/main/tests/hlapi/test_llm.py) for the tested cases, they are all tested on LLaMA model.
> 
> For quantization, [this example](https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/high-level-api/llm_examples.py#L68) is a preview, other cases might not be supported yet.

[Good job]. I have used `ModelRunner` based on `weight-only` & `TP >1` in the previous [#891](https://github.com/NVIDIA/TensorRT-LLM/commit/c89653021e66ca78c55f02b366f404455bc12e8d) Completed the target requirements. Thank you very much for your support. And currently I want to try to implement the `inflight_batching` mode based on `tllm.GptManager` in `AsyncLLMEngine`.
Another question I want to ask is, are there any blocks in `C++ runntime` for multi-card synchronous communication?

**Comment by litaotju** [comment]
@Superjomn  @xesdiny  the LLM class are still in early stage, thus yes many quantization were not supported in the Jan release (only had fp8 and awq in that time) We will add more quantization in the 0.9 release.
