### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by whk6688** [NVIDIA/TensorRT-LLM#922]
run command:
python build.py --hf_model_dir /home/wanghaikuan/.cache/huggingface/hub/models--Qwen--Qwen-7B-Chat/snapshots/8d24619bab456ea5abe2823c1d05fc5edec19174/ \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --use_gemm_plugin float16 \
                --use_weight_only \
                --weight_only_precision int4 \
                --output_dir ./tmp/Qwen/7B/trt_engines/int4_weight_only/1-gpu/ > t2.log

error as following:

[01/20/2024-16:09:15] [TRT-LLM] [I] Loading weights from HF QWen...
Converting...:  93%|████████████████████████▏ | 241/259 [02:02<00:09,  1.97it/s]
Traceback (most recent call last):
  File "/home/wanghaikuan/code/tt/TensorRT-LLM/examples/qwen/build.py", line 677, in <module>
    build(0, args)
  File "/home/wanghaikuan/code/tt/TensorRT-LLM/examples/qwen/build.py", line 647, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/home/wanghaikuan/code/tt/TensorRT-LLM/examples/qwen/build.py", line 504, in build_rank_engine
    load_from_hf_qwen(tensorrt_llm_qwen,
  File "/home/wanghaikuan/code/tt/TensorRT-LLM/examples/qwen/weight.py", line 432, in load_from_hf_qwen
    v = torch_to_numpy(v.to(torch_dtype).detach().cpu())
NotImplementedError: Cannot copy out of meta tensor; no data!

NOTE:  my platform is orin 32G

**Comment by byshiue** [comment]
Please refine your issue by following the issue template.
