### ISSUE TITLE
error: libtensorrt_llm_batch_manager_static.a: file format not recting as linker script

### ISSUE THREAD

**Issue by WangxuP** [NVIDIA/TensorRT-LLM#94]
When I was compiling the current project, the following error occurred: 
```
110.5 [ 98%] Built target layers_src
120.1 [ 98%] Built target common_src
121.8 [ 98%] Built target runtime_src
1434.0 [ 98%] Built target kernels_src
1434.0 [ 98%] Linking CXX static library libtensorrt_llm_static.a
1444.0 [ 98%] Built target tensorrt_llm_static
1444.0 [100%] Linking CXX shared library libtensorrt_llm.so
1444.1 /usr/bin/ld:/src/tensorrt_llm/cpp/tensorrt_llm/batch_manager/x86_64-linux-gnu/libtensorrt_llm_batch_manager_static.a: file format not recting as linker script
1444.1 /usr/bin/ld:/src/tensorrt_llm/cpp/tensorrt_llm/batch_manager/x86_64-linux-gnu/libtensorrt_llm_batch_manager_static.a:1: syntax error
1444.1 collect2: error: ld returned 1 exit status
1444.1 gmake[3]: *** [tensorrt_llm/CMakeFiles/tensorrt_llm.dir/build.make:714: tensorrt_llm/libtensorrt_llm.so] Error 1
1444.1 gmake[2]: *** [CMakeFiles/Makefile2:677: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/all] Error 2
1444.1 gmake[1]: *** [CMakeFiles/Makefile2:684: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/rule] Error 2
1444.1 gmake: *** [Makefile:179: tensorrt_llm] Error 2
1444.1 Traceback (most recent call last):
1444.1   File "/src/tensorrt_llm/scripts/build_wheel.py", line 248, in <module>
1444.1     main(**vars(args))
1444.1   File "/src/tensorrt_llm/scripts/build_wheel.py", line 152, in main
1444.1     build_run(
1444.1   File "/usr/lib/python3.10/subprocess.py", line 526, in run
1444.1     raise CalledProcessError(retcode, process.args,
1444.1 subprocess.CalledProcessError: Command 'cmake --build . --config Release --parallel 112 --target tensorrt_llm tensorrt_llm_static nvinferrrt_llm th_common ' returned non-zero exit status 2.
------
Dockerfile.multi:49
--------------------
  47 |
  48 |     ARG BUILD_WHEEL_ARGS="--clean --trt_root /usr/local/tensorrt"
  49 | >>> RUN python3 scripts/build_wheel.py ${BUILD_WHEEL_ARGS}
  50 |
  51 |     FROM devel as release
--------------------
ERROR: failed to solve: process "/bin/bash -c python3 scripts/build_wheel.py ${BUILD_WHEEL_ARGS}" did not complete successfully: exit code: 1

```

**Comment by byshiue** [comment]
Your issue may be same to this issue https://github.com/NVIDIA/TensorRT-LLM/issues/71. 

Do you install `git-lfs`?

**Comment by WangxuP** [comment]
> Your issue may be same to this issue #71.
> 
> Do you install `git-lfs`?

Perhaps I really didn't install git lfs
