### ISSUE TITLE
error happen when run the first step to convert model

### ISSUE THREAD

**Issue by whk6688** [NVIDIA/TensorRT-LLM#944]
### System Info

model qwen-chat-7b/qwen-chat-7b-int/qwen1_8B

### Who can help?

@n

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

run following script:

nohup python build.py --hf_model_dir /home/wanghaikuan/.cache/huggingface/hub/models--Qwen--Qwen-7B-Chat/snapshots/62ee27f810e7f59905ee1dac4ccc86d593dd57f4/ \
                --dtype bfloat16   \
                --remove_input_padding \
                --use_gpt_attention_plugin bfloat16  \
                --enable_context_fmha \
                --use_gemm_plugin bfloat16  \
                --output_dir ./tmp/Qwen/18b/trt_engines/fp16/1-gpu/ > t5.log 2>&1 &

### Expected behavior

convert to model successfully

### actual behavior

[01/23/2024-21:08:32] [TRT] [W] Unused Input: position_ids
[01/23/2024-21:08:32] [TRT] [W] [RemoveDeadLayers] Input Tensor position_ids is unused or used only at compile-time, but is not being removed.
[01/23/2024-21:08:32] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 6058, GPU 12149 (MiB)
[01/23/2024-21:08:32] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +2, GPU +0, now: CPU 6060, GPU 12149 (MiB)
[01/23/2024-21:08:32] [TRT] [I] Global timing cache in use. Profiling results in this builder pass will be stored.
[01/23/2024-21:08:39] [TRT] [E] 9: Skipping tactic 0x0000000000000004 due to exception cudaEventElapsedTime
[01/23/2024-21:08:40] [TRT] [E] 9: Skipping tactic 0x0000000000000006 due to exception cudaEventElapsedTime
[01/23/2024-21:08:40] [TRT] [E] 9: Skipping tactic 0x0000000000000007 due to exception cudaEventElapsedTime
[01/23/2024-21:08:41] [TRT] [E] 9: Skipping tactic 0x0000000000000008 due to exception cudaEventElapsedTime
[01/23/2024-21:08:41] [TRT] [E] 9: Skipping tactic 0x0000000000000009 due to exception cudaEventElapsedTime
[01/23/2024-21:08:42] [TRT] [E] 9: Skipping tactic 0x000000000000001c due to exception cudaEventElapsedTime
[01/23/2024-21:08:48] [TRT] [E] 9: Skipping tactic 0x0000000000000000 due to exception cudaEventElapsedTime
[01/23/2024-21:08:48] [TRT] [E] 9: Skipping tactic 0x0000000000000001 due to exception cudaEventElapsedTime
[01/23/2024-21:08:49] [TRT] [E] 9: Skipping tactic 0x0000000000000004 due to exception cudaEventElapsedTime
[01/23/2024-21:08:50] [TRT] [E] 9: Skipping tactic 0x0000000000000007 due to exception cudaEventElapsedTime
[01/23/2024-21:08:51] [TRT] [E] 9: Skipping tactic 0x0000000000000009 due to exception cudaEventElapsedTime
[01/23/2024-21:08:52] [TRT] [E] 9: Skipping tactic 0x000000000000001c due to exception cudaEventElapsedTime
[01/23/2024-21:08:58] [TRT] [E] 9: Skipping tactic 0x0000000000000000 due to exception cudaEventElapsedTime
[01/23/2024-21:08:58] [TRT] [E] 10: Could not find any implementation for node {ForeignNode[QWenForCausalLM/layers/1/ln_1/CONSTANT_1 + QWenForCausalLM/layers/1/ln_1/SHUFFLE_0...QWenForCausalLM/layers/1/ln_1/ELEMENTWISE_PROD_0]}.
[01/23/2024-21:08:58] [TRT] [E] 10: [optimizer.cpp::computeCosts::4048] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[QWenForCausalLM/layers/1/ln_1/CONSTANT_1 + QWenForCausalLM/layers/1/ln_1/SHUFFLE_0...QWenForCausalLM/layers/1/ln_1/ELEMENTWISE_PROD_0]}.)
[01/23/2024-21:08:58] [TRT-LLM] [E] Engine building failed, please check the error log.
[01/23/2024-21:08:58] [TRT-LLM] [I] Config saved to ./tmp/Qwen/18b/trt_engines/fp16/1-gpu/config.json.
Traceback (most recent call last):
  File "/home/wanghaikuan/code/tt/TensorRT-LLM/examples/qwen/build.py", line 673, in <module>
    build(0, args)
  File "/home/wanghaikuan/code/tt/TensorRT-LLM/examples/qwen/build.py", line 645, in build
    assert engine is not None, f'Failed to build engine for rank {cur_rank}'
AssertionError: Failed to build engine for rank 0

### additional notes

None

**Comment by jershi425** [comment]
Thanks you @whk6688 for the feedback. May I ask which model are you running exactly, the `Qwen-7B-Chat` or `Qwen-1_8B-Chat`? If it is the 1.8B one, what is your build command exactly?

**Comment by whk6688** [comment]
qwen-chat-7b/qwen-chat-7b-int/qwen1_8B  means,  no matter which one, the error is same.

**Comment by nv-guomingz** [comment]
would u please try our latest code base to see if the issue still exists?

And do u still have further issue or question now? If not, we'll close it soon.
