### ISSUE TITLE
smooth quant fail on llama model

### ISSUE THREAD

**Issue by forrestjgq** [NVIDIA/TensorRT-LLM#952]
**Environment**

If applicable, please include the following:

CPU architecture x86_64
CPU/Host memory size: big enough

GPU properties
GPU name 3090x2
GPU memory size 24G
Clock frequencies used: not sure

**Libraries**
TensorRT-LLM branch or tag : `main`
TensorRT-LLM commit: `c89653021e66ca78c55f02b366f404455bc12e8d`
Versions of TensorRT, AMMO, CUDA, cuBLAS,: `build container using script provided by TRTLLM and its backend`
Container used: `based on nvcr.io/nvidia/tritonserver:23.12-py3 and build mannually as backend says`
NVIDIA driver version: `535.104.05`
OS: `Ubuntu 22.04`

**Reproduction Steps**

1. build llama model using command:
```
CUDA_VISIBLE_DEVICES=1,2 python -u /app/tensorrt_llm/examples/llama/hf_llama_convert.py -i <llama-13b-model> -o <tmp-file-path> -sq 0.4 --tensor-parallelism 1 --storage-type fp16

python -u /app/tensorrt_llm/examples/llama/build.py --use_lookup_plugin --dtype float16 --output_dir <engine dir> --max_batch_size 8 --max_input_len 2048 --max_output_len 32 --world_size 1 --tp_size 1 --pp_size 1 --remove_input_padding --use_gpt_attention_plugin float16 --use_gemm_plugin float16 --enable_context_fmha --use_inflight_batching --paged_kv_cache --bin_model_dir <tmp-file-path>/1-gpu --use_smooth_quant --per_token --per_channel
```

**Expected Behavior**

model could be built without error

**Actual Behavior**
 error happens:

```
Traceback (most recent call last):
  File "/app/tensorrt_llm/examples/llama/build.py", line 1059, in <module>
    build(0, args)
  File "/app/tensorrt_llm/examples/llama/build.py", line 1003, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/app/tensorrt_llm/examples/llama/build.py", line 907, in build_rank_engine
    tensorrt_llm_llama(*inputs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/module.py", line 40, in __call__
    output = self.forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/model.py", line 466, in forward
    hidden_states = super().forward(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/model.py", line 310, in forward
    hidden_states = layer(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/module.py", line 40, in __call__
    output = self.forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/model.py", line 153, in forward
    attention_output = self.attention(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/module.py", line 40, in __call__
    output = self.forward(*args, **kwargs)
TypeError: SmoothQuantAttention.forward() got an unexpected keyword argument 'medusa_packed_mask'
cmd execute failed: 256
```

**Comment by byshiue** [comment]
Please follow the issue template to file issue, thank you for cooperation.

**Comment by forrestjgq** [comment]
> Please follow the issue template to file issue, thank you for cooperation.

@byshiue updated

**Comment by forrestjgq** [comment]
The latest main branch has solved this issue

Thanks
