### ISSUE TITLE
CodeLlama-7B int4-awq get error of The value updated is not the same shape as the original. Updated: (32064, 4096), original: (32016, 4096)

### ISSUE THREAD

**Issue by activezhao** [NVIDIA/TensorRT-LLM#955]
I use the command for int4-awq with CodeLlama-7B.
```
python tensorrt_llm/examples/quantization/quantize.py --model_dir /data/META-CodeLlama-7b-hf/ \
                --dtype float16 \
                --qformat int4_awq \
                --export_path /data/trt_llama_7b_quantized_int4-awq \
                --calib_size 32
```

And I get the files like this:
```
trt_llama_7b_quantized_int4-awq/
├── llama_tp1.json
└── llama_tp1_rank0.npz
```

Next, I build the model with command below and get errors:
```
root@7728b95eabcd:/data/tensorrt_llm/examples/llama# python build.py --model_dir /data/META-CodeLlama-7b-hf/ \                --quant_ckpt_path /data/trt_llama_7b_quantized_int4-awq/llama_tp1_rank0.npz \                --dtype float16 \                --remove_input_padding \                --use_gpt_attention_plugin float16 \
                --paged_kv_cache \
                --use_inflight_batching \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --vocab_size 32064  \
                --rotary_base 1000000  \
                --use_weight_only \
                --weight_only_precision int4_awq \
                --per_group \
                --output_dir /data/llama_7B_trt_engines_int4_AWQ/1-gpu/
[01/25/2024-01:36:11] [TRT-LLM] [I] Serially build TensorRT engines.
[01/25/2024-01:36:11] [TRT] [I] [MemUsageChange] Init CUDA: CPU +13, GPU +0, now: CPU 133, GPU 228 (MiB)
[01/25/2024-01:36:13] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1799, GPU +312, now: CPU 2068, GPU 540 (MiB)
[01/25/2024-01:36:13] [TRT-LLM] [W] Invalid timing cache, using freshly created one
[01/25/2024-01:36:13] [TRT-LLM] [I] [MemUsage] Rank 0 Engine build starts - Allocated Memory: Host 2.5261 (GiB) Device 0.0000 (GiB)
[01/25/2024-01:36:13] [TRT-LLM] [I] Loading weights from groupwise AWQ LLaMA checkpoint...
Traceback (most recent call last):
  File "/data/tensorrt_llm/examples/llama/build.py", line 1051, in <module>
    build(0, args)
  File "/data/tensorrt_llm/examples/llama/build.py", line 995, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/data/tensorrt_llm/examples/llama/build.py", line 873, in build_rank_engine
    tensorrt_llm_llama = get_model_object(args,
  File "/data/tensorrt_llm/examples/llama/build.py", line 745, in get_model_object
    load_from_awq_llama(tensorrt_llm_llama=tensorrt_llm_llama,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/weight.py", line 1522, in load_from_awq_llama
    tensorrt_llm_llama.vocab_embedding.weight.value = v.to(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/parameter.py", line 113, in value
    assert v.shape == self._shape, \
AssertionError: The value updated is not the same shape as the original. Updated: (32064, 4096), original: (32016, 4096)
```

CodeLlama-7b-hf/config.json, the vocab_size is 32016
```
{
  "architectures": [
    "LlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 16384,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "rope_theta": 1000000,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.32.0.dev0",
  "use_cache": true,
  "vocab_size": 32016
}
```

But trt_llama_7b_quantized_int4-awq/llama_tp1.json, the vocab_size is 32064.
```
{"version": 0.4, "quantization": "int4_awq", "awq_block_size": 128, "dtype": "float16", "vocab_size": 32064, "rank": 0, "tensor_parallel": 1, "vocab_embedding": {"weight": "_np:vocab_embedding:weight"}, "positional_embedding": null, "layers": [{"decoder_type": "llama", "input_layernorm": {"weight": "_np:layers:0:input_layernorm:weight", "bias": null, "layernorm_type": "rms", "eps": 1e-05}, "mlp_layernorm": null
```

The vocab_size is different, so how to solve this problem?

Thanks.

**Comment by byshiue** [comment]
Please follow the issue template to file issue, thank you for cooperation.

**Comment by activezhao** [comment]
> Please follow the issue template to file issue, thank you for cooperation.

@byshiue OK, I have created a new issue with issue template.
https://github.com/NVIDIA/TensorRT-LLM/issues/962
