### ISSUE TITLE
AssertionError: Failed to build engine for rank 0

### ISSUE THREAD

**Issue by whk6688** [NVIDIA/TensorRT-LLM#978]
### System Info

CUDA12.2

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

python build.py --hf_model_dir /home/wanghaikuan/.cache/huggingface/hub/models--Qwen--Qwen-7B-Chat-Int4/snapshots/5a9a1ed9203a3d4ccc62f24fbb9b7e3948ce8ec1/                 --dtype bfloat16                   --remove_input_padding                 --use_gpt_attention_plugin bfloat16                  --enable_context_fmha
   --use_gemm_plugin bfloat16                  --output_dir ./tmp/Qwen/18b/trt_engines/fp16/1-gpu/ 

### Expected behavior

Get onnx model

### actual behavior

[01/25/2024-22:20:51] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +1, GPU +8, now: CPU 17286, GPU 29162 (MiB)
[01/25/2024-22:20:51] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +1, GPU +12, now: CPU 17287, GPU 29174 (MiB)
[01/25/2024-22:20:51] [TRT] [I] Global timing cache in use. Profiling results in this builder pass will be stored.
[01/25/2024-22:20:51] [TRT] [E] 9: Skipping tactic 0x0000000000000000 due to exception Assertion engine failed.
[01/25/2024-22:20:53] [TRT] [E] 9: Skipping tactic 0x0000000000000001 due to exception cudaEventElapsedTime
[01/25/2024-22:20:55] [TRT] [E] 9: Skipping tactic 0x0000000000000004 due to exception cudaEventElapsedTime
[01/25/2024-22:20:55] [TRT] [E] 9: Skipping tactic 0x0000000000000005 due to exception cudaEventElapsedTime
[01/25/2024-22:20:55] [TRT] [E] 9: Skipping tactic 0x0000000000000006 due to exception cudaEventElapsedTime
[01/25/2024-22:20:56] [TRT] [E] 9: Skipping tactic 0x0000000000000007 due to exception cudaEventElapsedTime
[01/25/2024-22:20:57] [TRT] [E] 9: Skipping tactic 0x0000000000000009 due to exception cudaEventElapsedTime
[01/25/2024-22:20:57] [TRT] [E] 9: Skipping tactic 0x000000000000001c due to exception cudaEventElapsedTime
[01/25/2024-22:21:01] [TRT] [E] 9: Skipping tactic 0x0000000000000000 due to exception cudaEventElapsedTime
[01/25/2024-22:21:01] [TRT] [E] 10: Could not find any implementation for node {ForeignNode[QWenForCausalLM/layers/0/ln_2/CONSTANT_1 + QWenForCausalLM/layers/0/ln_2/SHUFFLE_0...QWenForCausalLM/layers/0/ln_2/ELEMENTWISE_PROD_0]}.
[01/25/2024-22:21:01] [TRT] [E] 10: [optimizer.cpp::computeCosts::4048] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[QWenForCausalLM/layers/0/ln_2/CONSTANT_1 + QWenForCausalLM/layers/0/ln_2/SHUFFLE_0...QWenForCausalLM/layers/0/ln_2/ELEMENTWISE_PROD_0]}.)
[01/25/2024-22:21:01] [TRT-LLM] [E] Engine building failed, please check the error log.
[01/25/2024-22:21:01] [TRT-LLM] [I] Config saved to ./tmp/Qwen/18b/trt_engines/fp16/1-gpu/config.json.
Traceback (most recent call last):
  File "/home/wanghaikuan/code/tt/TensorRT-LLM/examples/qwen/build.py", line 673, in <module>
    build(0, args)
  File "/home/wanghaikuan/code/tt/TensorRT-LLM/examples/qwen/build.py", line 645, in build
    assert engine is not None, f'Failed to build engine for rank {cur_rank}'
AssertionError: Failed to build engine for rank 0

### additional notes

None

**Comment by byshiue** [comment]
Duplicated to issue https://github.com/NVIDIA/TensorRT-LLM/issues/931, close this one.
