### ISSUE TITLE
when I run summarize.py, to_bettertransformer does not support baichuan model

### ISSUE THREAD

**Issue by shaowenchen** [NVIDIA/TensorRT-LLM#982]
### System Info

```bash
python examples/summarize.py --test_hf \
                    --hf_model_dir ./models/Baichuan2-7B-Chat \
                    --data_type fp16 \
                    --engine_dir ./models/Baichuan2-7B-Chat/trt_engines/fp16/1-gpu/
[01/26/2024-23:01:21] [TRT-LLM] [W] Found pynvml==11.4.1. Please use pynvml>=11.5.0 to get accurate memory usage
[01/26/2024-23:01:21] [TRT-LLM] [I] Load tokenizer takes: 0.05020022392272949 sec
/usr/local/lib/python3.10/dist-packages/datasets/load.py:1429: FutureWarning: The repository for ccdv/cnn_dailymail contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/ccdv/cnn_dailymail
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
  warnings.warn(
[01/26/2024-23:01:26] Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.

Traceback (most recent call last):
  File "/app/tensorrt_llm/examples/summarize.py", line 579, in <module>
    main(args)
  File "/app/tensorrt_llm/examples/summarize.py", line 140, in main
    model.to_bettertransformer()
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3772, in to_bettertransformer
    return BetterTransformer.transform(self)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/optimum/bettertransformer/transformation.py", line 234, in transform
    raise NotImplementedError(
NotImplementedError: The model type baichuan is not yet supported to be used with BetterTransformer. Feel free to open an issue at https://github.com/huggingface/optimum/issues if you would like this model type to be supported. Currently supported models are: dict_keys(['albert', 'bark', 'bart', 'bert', 'bert-generation', 'blenderbot', 'bloom', 'camembert', 'blip-2', 'clip', 'codegen', 'data2vec-text', 'deit', 'distilbert', 'electra', 'ernie', 'fsmt', 'gpt2', 'gptj', 'gpt_neo', 'gpt_neox', 'hubert', 'layoutlm', 'm2m_100', 'marian', 'markuplm', 'mbart', 'opt', 'pegasus', 'rembert', 'prophetnet', 'roberta', 'roc_bert', 'roformer', 'splinter', 'tapas', 't5', 'vilt', 'vit', 'vit_mae', 'vit_msn', 'wav2vec2', 'xlm-roberta', 'yolos']).
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

You can reproduce this error by running python examples/summarize.py to baichuan model

### Expected behavior

examples/summarize.py can Ignore the BetterTransformer error

### actual behavior

examples/summarize.py  terminates automatically when the model doesn't support BetterTransformer

### additional notes

none

**Comment by shaowenchen** [comment]
sorry, I used the old version, the new version has been processed
